### ISSUE TITLE
tomcrypt_macros.h asm error

### ISSUE THREAD

**Issue by SimpleX91** [Legrandin/pycryptodome#1]
GCC says incorrect restriction in *src/libtom/tomcrypt_macros.h:275:4*
```C
asm ("rorl %2,%0"
```

**Comment by Legrandin** [comment]
Thanks for reporting this.
Do you possibly mean "impossible constraint"?
I thought all assembly imported from those old headers was removed, but it could be it is not.
In general, this issue should be solvable by defining the LTC_NO_ASM macro.
