### ISSUE TITLE
Equations on page 37 (43/82) of v.3.4.7 PDF hard to see

### ISSUE THREAD

**Issue by hoang408** [Legrandin/pycryptodome#100]
The equations on page 37 (43/82) of the v.3.4.7 PDF are hard to see. I had to find the corresponding page online to know what it was. Attached is what it looks like. Please see if there is a way to fix it.
![equations on p37](https://user-images.githubusercontent.com/22355177/31327698-bdd06294-ac85-11e7-9c39-e3c6dc9bd8ca.png)

**Comment by Legrandin** [comment]
Please see the HTML version here: https://www.pycryptodome.org/en/latest/src/public_key/elgamal.html . The PDF version is not really supported right now.
