### ISSUE TITLE
Consider releasing "manylinux" wheels 

### ISSUE THREAD

**Issue by macropin** [Legrandin/pycryptodome#101]
Please consider releasing "manylinux" wheels to ease the builddeps installation burden. This has already been successfully done by other packages including psycopg2.

Ref: https://github.com/psycopg/psycopg2/issues/425

**Comment by naamancampbell** [comment]
Releasing "manylinux" wheels will also allow [Zappa](https://github.com/Miserlou/Zappa) users to replace `pycrypto` in AWS Lambda apps.
https://blog.zappa.io/posts/zappa-adds-support-for-manylinux-wheels

**Comment by Legrandin** [comment]
Support "manylinux" is in place. It will become available in the upcoming new release.
