### ISSUE TITLE
PKCS1_v1_5.new(key).sign() is broken and do nothing

### ISSUE THREAD

**Issue by cepreu2github** [Legrandin/pycryptodome#102]
## Steps to reproduce:
Run `sh test.sh` in PyCryptodome_bug folder.

## Actual result:
`The signature is valid.` in console output.

## Expected result:
`The signature is not valid.`

## Additional problems:
It is even worse. Try to write `PKCS1_v1_5.new(key).verify(h, b"sdfdsf")` in 16 line of `pycryptodome_test.py`. You still got message "...is valid."

## Notes about importance:
Official docs recommends to use `pkcs1_15` class to RSA sign/verify. And it works fine as expected:
https://www.pycryptodome.org/en/latest/src/signature/pkcs1_v1_5.html

But web is full of outdated recipes with PKCS1_v1_5 class to sign/verify. And silently do nothing it is worst thing, because it breaks security for any user, who used those outdated manuals to write their digital signature check. Example of manuals:
https://stackoverflow.com/questions/6350031/how-to-verify-in-pycrypto-signature-created-by-openssl
https://gist.github.com/lkdocs/6519372
https://legrandin.github.io/pycryptodome/Doc/3.0/Crypto.Signature.PKCS1_v1_5-module.html

There is legion of them...

## My environment
Python 3.4.5 (default, Sep 12 2017, 14:09:02) 
[GCC 5.4.0] on linux
Linux calculate 4.9.51-calculate #1 SMP PREEMPT Wed Sep 20 09:11:30 UTC 2017 x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux

[PyCryptodome_bug.zip](https://github.com/Legrandin/pycryptodome/files/1373909/PyCryptodome_bug.zip)

**Comment by Legrandin** [comment]
Thanks. I am looking at it.

**Comment by Legrandin** [comment]
I see two issues.

=== 1
In the shell script you do this:

    openssl rsa -in private_good.pem -outform PEM -pubout -out public_good.pem

Then in `pycryptodome_test.py`, you verify the signature created by the "evil" private key using `public_good.pem`. However, the latter is in the reality the "evil" public key, so it is normal that verification succeeds.

=== 2
The right way to verify signatures generated with the `PKCS1_v1_5` module is to check the boolean value returned by `verify()`, which is the way inherited from PyCrypto:

https://www.dlitz.net/software/pycrypto/api/current/Crypto.Cipher.PKCS1_v1_5-module.html

The new module `pkcs1_15` was introduced to allow an invalid signature to lead to an exception, as shown here:

https://www.pycryptodome.org/en/latest/src/signature/pkcs1_v1_5.html

The PyCryptodome documentation you link is very old and incorrect. I will actually take it down ASAP.
