### ISSUE TITLE
Install fails while running build_ext on python 3.7 & pip 9(?)

### ISSUE THREAD

**Issue by TJNK** [Legrandin/pycryptodome#104]
Command 
"c:\users\[usr]\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\[usr]\\AppData\\Local\\Temp\\pip-build-ftuug689\\pycryptodome\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\[usr]\AppData\Local\Temp\pip-n08qqlyr-record\install-record.txt --single-version-externally-managed --compile"
 failed with error code 1 in C:\Users\[usr]\AppData\Local\Temp\pip-build-ftuug689\pycryptodome\   

...[running code]...
running build_ext

  ----------------------------------------
  Failed building wheel for pycryptodome
  Running setup.py clean for pycryptodome
Failed to build pycryptodome
....[logging]...

**Comment by Legrandin** [comment]
Python3.7 just came out as alpha very recently, so there are no wheels pre-built for it in pypi; that is something I was thinking to do one of these days.

To fix the error above you would need to install Microsoft Visual Studio 2015, which is not exactly a pleasant process, as described here: https://www.pycryptodome.org/en/latest/src/installation.html#windows-from-sources-python-3-5-and-newer .

**Comment by wwqgtxx** [comment]
the Python3.7 was released, would the py37 wheels add to pypi.org?

**Comment by Legrandin** [comment]
That will be possible only after Appveyor adds Python 3.7 (they only have [up to 3.6 right now](https://www.appveyor.com/docs/build-environment/#python)).

**Comment by Legrandin** [comment]
And apparently Python 3.7 will be added [next week](https://github.com/appveyor/ci/issues/2475).

**Comment by ParZaib** [comment]
i still have this problem

**Comment by Legrandin** [comment]
Fixed in v3.6.5
