### ISSUE TITLE
Python3.6 issues

### ISSUE THREAD

**Issue by kcgthb** [Legrandin/pycryptodome#105]
Hi!

I have two issues with `pycryptodomex` 3.4.7 that I think are related to Python 2/3 compatibility. The module was installed with:
```
$ pip3.6 install --user pycryptodomex
```
```
$ pip3.6 show pycryptodomex
Name: pycryptodomex
Version: 3.4.7
Summary: Cryptographic library for Python
Home-page: http://www.pycryptodome.org
Author: Helder Eijs
Author-email: helderijs@gmail.com
License: UNKNOWN
Location: /home/kilian/.local/lib/python3.6/site-packages
Requires:
```

## Issue importing *
```
$ python3.6
Python 3.6.2 (default, Sep 26 2017, 00:02:18) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cryptodome import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kilian/.local/lib/python3.6/site-packages/Cryptodome/Cipher/__init__.py", line 7, in <module>
    from Cryptodome.Cipher._mode_ctr import _create_ctr_cipher
  File "/home/kilian/.local/lib/python3.6/site-packages/Cryptodome/Cipher/_mode_ctr.py", line 35, in <module>
    from Cryptodome.Util.number import long_to_bytes
  File "/home/kilian/.local/lib/python3.6/site-packages/Cryptodome/Util/number.py", line 387
    s = pack('>I', n & 0xffffffffL) + s
                                 ^
SyntaxError: invalid syntax
```
I understand that the `0xffffffffL` is not valid in Python 3.x anymore, so I'm a bit surprised to see this error.

## Selftest doesn't work
```
$ python3.6 -m Cryptodome.SelfTest
Traceback (most recent call last):
  File "/runpy.py", line 183, in _run_module_as_main
  File "/runpy.py", line 142, in _get_module_details
  File "/runpy.py", line 109, in _get_module_details
  File "/home/kilian/.local/lib/python3.6/site-packages/Cryptodome/SelfTest/__init__.py", line 35, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```
Again, `StringIO` seem to be gone in Python3, and replaced by the `io`  module, that provides `io.StringIO `.

Could you please advise on those issues? Thanks!

**Comment by Legrandin** [comment]
Thanks for reporting.
Which OS is that exactly?
Doing all of that in Fedora 26 (w/ Python 3.6.1) seem to work fine.

**Comment by kcgthb** [comment]
This is a Synology NAS running DSM 6.1, and using Python 3.6 from [Entware-ng](https://github.com/Entware-ng/Entware-ng)

**Comment by ouija** [comment]
Have a similar error occurring with another script that uses pycryptodome on a QNAP NAS using Python 3.6.2 via Entware-ng as well...

**Comment by Varbin** [comment]
On Ubuntu 17.10 it works w/ Python 3.6.3. Is it possible to import lib2to3 on your machines?

**Comment by jsetton** [comment]
I believe this issue is related to software distributions that only provide bytecode pyc in their Python packages, such as Entware. There is a [known issue](https://www.bugs.python.org/issue31143) in which 2to3 can only work with the fixes source files, preventing setuptools from properly running 2to3 during the package build.

Assuming lib2to3 is install properly on your device, the workaround is to copy the source files from the relevant official Python source tarball:

`cp Python-3.7.0/Lib/lib2to3/fixes/*.py /opt/lib/python3.7/lib2to3/fixes`

And then, either reinstall the package or run the following command to fixes the files:

`2to3 -wWn --no-diffs /opt/lib/python3.7/site-packages/Cryptodome`

**Comment by Legrandin** [comment]
Closing this as it is a platform issue. Thanks @jsetton for investigating it!
In the meanwhile, we also got rid of 2to3 a few versions ago.
