### ISSUE TITLE
Support custom counters for CTR mode

### ISSUE THREAD

**Issue by mon** [Legrandin/pycryptodome#107]
I'm replicating crypto from an application that uses a custom counter (big endian, but incrementing the second-last u32 instead of the last). As such, I relied on the generic counter support used in the original PyCrypto.

It would be excellent if this has native support, vs encrypting the blocks myself.

**Comment by Legrandin** [comment]
I think you can use the existing `Crypto.Util.Counter` to create a custom counter for the CTR mode:

https://www.pycryptodome.org/en/latest/src/util/util.html#crypto-util-counter-module

Specifically, you need to pass the appropriate 4 fixed bytes as the `suffix` parameter.
