### ISSUE TITLE
Reduced round cipher encryption

### ISSUE THREAD

**Issue by agamemnonc** [Legrandin/pycryptodome#110]
Is there a way of performing reduced round encryption using a given cipher (e.g. DES or AES)?

**Comment by Legrandin** [comment]
Yes, but not from python. You need to modify the C source code and rebuild.

**Comment by agamemnonc** [comment]
Thanks for the ultra-fast response! 

I think I have identified which part of the source code I need to modify, but I am not sure though how I should rebuild? Initially, I installed the package using pip under a conda env.

**Comment by Legrandin** [comment]
From the source code tree with the modification (and assuming you have compiler installed):

    python setup.py build

And then to install (you might want to do this in a virtualenv):

    python setup.py install

**Comment by agamemnonc** [comment]
Many thanks for the help. 

I am closing this issue.
