### ISSUE TITLE
NIST certification for Pycrytodome?

### ISSUE THREAD

**Issue by sriluvan** [Legrandin/pycryptodome#111]
Our compliance organization asked if we are using NIST approved crypography libraries. I don't see pycryptodome is in the NIST approved list - https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search

 for example IBM JCE is certified by NIST 

1993 | IBM® Corporation | IBM® Java JCE FIPS 140-2   Cryptographic Module | Software | 08/27/2013   05/29/2015   03/15/2016
-- | -- | -- | -- | --

but couldn't find any python cryptography library in the list.  

Would pycryptodome open source community consider getting NIST certification? 

Thank you

**Comment by Legrandin** [comment]
Not really: FIPS 140-2 certification costs a lot of time and several thousand dollars.
