### ISSUE TITLE
Cannot load native module 'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by lujunpeng** [Legrandin/pycryptodome#118]
win10 python3.63

`from Crypto.Cipher import AES`

Why is this problem?

Traceback (most recent call last):
  File "d:\python\test\test.py", line 7, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\lujunpenng\AppData\Local\Programs\Python\Python36\lib\site-packages\Crypto\Cipher\__init__.py", line 3, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\lujunpenng\AppData\Local\Programs\Python\Python36\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Userslujunpenng\AppData\Local\Programs\Python\Python36\lib\site-packages\Crypto\Util\_raw_api.py", line 189, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

**Comment by Legrandin** [comment]
How did you install PyCryptodome in Windows?

**Comment by lujunpeng** [comment]
pip install pycryptodome

**Comment by Legrandin** [comment]
OK, thanks. What is you version of Windows? And is it 32 or 64 bits?

**Comment by lujunpeng** [comment]
64bit

**Comment by Legrandin** [comment]
Which version exactly?

**Comment by lujunpeng** [comment]
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by frispete** [comment]
You still missed to mention the exact windows version...

**Comment by lujunpeng** [comment]
win 10 64bit  version:1706

**Comment by salmanakj** [comment]
raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

am got this error .....what i do for clear this error ?? am using linux nixos and python version is 3.6

**Comment by Varbin** [comment]
@salmanakj Please share your code and the full traceback (= the *full* error message). 

It might help us if you show the versions of Pycryptodome(x) and cffi. You can do it with:

`pip show pycryptodome` respectively `pip show pycryptodomex` and for cffi with `pip show cffi`. It will show nothing if the packages has not been installed.

**Comment by Legrandin** [comment]
The latest version (3.4.8) puts some more information in the exception string.

@salmanakj @lujunpeng it would be great if you could try again.

**Comment by ethen8181** [comment]
Hi team, I'm getting a similar error: 

```python
from Crypto.Cipher import AES

raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-35m-x86_64-linux-gnu.so'
```

And when I do a ls under the Cipher folder i get normal results:
```bash
/Crypto/Cipher$ ls
AES.py                                     _raw_aesni.cpython-36m-x86_64-linux-gnu.so
ARC2.py                                    _raw_aesni.py
_ARC4.cpython-36m-x86_64-linux-gnu.so      _raw_aes.py
_ARC4.py                                   _raw_arc2.cpython-36m-x86_64-linux-gnu.so
ARC4.py                                    _raw_arc2.py
Blowfish.py                                _raw_blowfish.cpython-36m-x86_64-linux-gnu.so
CAST.py                                    _raw_blowfish.py
_chacha20.cpython-36m-x86_64-linux-gnu.so  _raw_cast.cpython-36m-x86_64-linux-gnu.so
_chacha20.py                               _raw_cast.py
ChaCha20.py                                _raw_cbc.cpython-36m-x86_64-linux-gnu.so
DES3.py                                    _raw_cbc.py
DES.py                                     _raw_cfb.cpython-36m-x86_64-linux-gnu.so
__init__.py                                _raw_cfb.py
_mode_cbc.py                               _raw_ctr.cpython-36m-x86_64-linux-gnu.so
_mode_ccm.py                               _raw_ctr.py
_mode_cfb.py                               _raw_des3.cpython-36m-x86_64-linux-gnu.so
_mode_ctr.py                               _raw_des3.py
_mode_eax.py                               _raw_des.cpython-36m-x86_64-linux-gnu.so
_mode_ecb.py                               _raw_des.py
_mode_gcm.py                               _raw_ecb.cpython-36m-x86_64-linux-gnu.so
_mode_ocb.py                               _raw_ecb.py
_mode_ofb.py                               _raw_ocb.cpython-36m-x86_64-linux-gnu.so
_mode_openpgp.py                           _raw_ocb.py
_mode_siv.py                               _raw_ofb.cpython-36m-x86_64-linux-gnu.so
PKCS1_OAEP.py                              _raw_ofb.py
PKCS1_v1_5.py                              _Salsa20.cpython-36m-x86_64-linux-gnu.so
__pycache__                                _Salsa20.py
_raw_aes.cpython-36m-x86_64-linux-gnu.so   Salsa20.py
```

However, when i do a `ls` on the `.so` file it shows the file does not exist. Some guidance is much appreciated. Thank you!

```bash
/Crypto/Cipher$ ls _raw_ecb.cpython-35m-x86_64-linux-gnu.so
ls: cannot access '/_raw_ecb.cpython-35m-x86_64-linux-gnu.so': No such file or directory
```
