### ISSUE TITLE
Is the pycryptodome thread-safe?

### ISSUE THREAD

**Issue by user0007** [Legrandin/pycryptodome#12]
Hello,

I'm wondering if I can use pycryptodome in a web environment (multithread) to generate RSA keys and decrypt messages:

    key = RSA.generate(2048)
    public_key = key.publickey().exportKey(format)
    private_key = key.exportKey(format)
    ...
    priv_key = RSA.importKey(private_key)
    priv_key.decrypt(encrypted_message)

Are `RSA.generate` and `RSA.importKey` thread safe?

Thank you.

**Comment by Legrandin** [comment]
Yes, no global variables are used in either the Python or the C part so they are thread-safe.

**Comment by user0007** [comment]
Thank you for the answer.
