### ISSUE TITLE
ECDH ETA

### ISSUE THREAD

**Issue by GoobyCorp** [Legrandin/pycryptodome#120]
I've seen a lot of ECDH implementations and most of them are horrible, is there an ETA on ECDH being implemented? I would do it myself but I'm terrible at working with other peoples' code and keeping the formatting consistent.

**Comment by elichai** [comment]
Waiting for it too :+1: 
(even independent DH and then we could create ECC keys and then use the DH)

**Comment by eribean** [comment]
Waiting for it three!, is this just back burnered?

**Comment by Legrandin** [comment]
ECDH is implemented in v3.19 (https://www.pycryptodome.org/src/protocol/dh).
