### ISSUE TITLE
PKCS#1 v1.5 support

### ISSUE THREAD

**Issue by user0007** [Legrandin/pycryptodome#13]
The library implements PKCS#1 OAEP, but the common standard is PKCS#1 v1.5 (eg. in openssl). Is there a chance to decrypt/encrypt messages in PKCS#1 v1.5? Eg: I can't decrypt messages which are encrypted by openssl:

    openssl rsautl -sign -in hello.txt -inkey id_rsa -out out.sig

    PKCS1_OAEP.new(id_rsa).decrypt(open('hello.txt', "rb").read())
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/local/lib/python2.7/site-packages/Cryptodome/Cipher/PKCS1_OAEP.py", line 227, in decrypt
        raise ValueError("Incorrect decryption.")
    ValueError: Incorrect decryption.

**Comment by Legrandin** [comment]
PKCS#1 v1.5 is implemented in the [`Crypto.Cipher.PKCS1_v1_5`](http://legrandin.github.io/pycryptodome/Doc/3.4/Crypto.Cipher.PKCS1_v1_5-module.html) module.
For example:

    from Crypto.Cipher import PKCS1_v1_5
    from Crypto.PublicKey import RSA
    from Crypto import Random

    key = RSA.import_key(open('privkey.der').read())
    sentinel = Random.get_random_bytes(16)

    cipher = PKCS1_v1_5.new(key)
    message = cipher.decrypt(ciphertext, sentinel)

Where `sentinel` is returned if the decryption is incorrect.

**Comment by user0007** [comment]
Ooo, I couldn't find it :-) Thanks!
