### ISSUE TITLE
CTR mode does not accept callable counters anymore

### ISSUE THREAD

**Issue by Varbin** [Legrandin/pycryptodome#138]
PyCrypto was conform to PEP-272 (block cipher API) so it did accept a callable argument for counter attribute. While being slow (overhead for a call) custom counter classes could be used.

How to convert legacy code to the new behaviour?

**Comment by Legrandin** [comment]
The `counter` parameter for CTR mode is deprecated but still accepted, with the caveat that it must be generated with [`Crypto.Util.Counter.new`](https://www.pycryptodome.org/en/latest/src/util/util.html#module-Crypto.Util.Counter).
