### ISSUE TITLE
pycryptome 3.5.0 fails to build when installed via pip 

### ISSUE THREAD

**Issue by Melvin-Ross-Bose** [Legrandin/pycryptodome#142]
Environment:
Mac OS 10.12.6 Sierra
Virtualenv  15.1.0
Python 3.6.4 

**Steps Taken:** 
_pip install pycryptodome_  
 This tries to install the current latest version, 3.5.0
**Result:** 
Package fails to install. What I believe to be the  pertinent output is below, but I've also attached a file.
[Output.txt](https://github.com/Legrandin/pycryptodome/files/1791139/Output.txt)

 clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wno-error -DHAVE_X86INTRIN_H -DPY_LITTLE_ENDIAN -DLTC_NO_ASM -DHAVE_UINT128 -DHAVE_CPUID_H -Isrc/ -I/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/multiply_64.c -o build/temp.macosx-10.12-x86_64-3.6/src/multiply_64.o -msse2
    src/multiply_64.c:57:10: error: conflicting types for 'addmul128'
    uint64_t addmul128(uint64_t * RESTRICT t, const uint64_t * RESTRICT a, uint64_t b0, uint64_t b1, size_t words)
             ^
    src/multiply.h:62:8: note: previous declaration is here
    size_t addmul128(uint64_t * RESTRICT t, const uint64_t * RESTRICT a, uint64_t b0, uint64_t b1, size_t words)
           ^
    1 error generated.
    error: command 'clang' failed with exit status 1

**Workaround :** 
Revert to the previous version via
_pip install pycryptodome==3.4.11_

**Comment by boneyard93501** [comment]
ditto

**Comment by ezdac** [comment]
I get the same, running on Mac OS 10.12.6 Sierra as well.

**Comment by thorstenhirsch** [comment]
It's not a warning. It's an error, the build fails.
Same problem here.

**Comment by Legrandin** [comment]
A patch kindly offered by @drewbanin is on master. I will make a dot release later today.

**Comment by Legrandin** [comment]
Fixed in v3.5.1.

**Comment by smtakeda** [comment]
Thank you for a quick fix!
