### ISSUE TITLE
Documentation falsely says AES.new function ignores IV parameter

### ISSUE THREAD

**Issue by mikez302** [Legrandin/pycryptodome#15]
The [documentation for the Crypto.Cipher.AES module](https://legrandin.github.io/pycryptodome/Doc/3.3.1/Crypto.Cipher.AES-module.html) says that the `IV` parameter is ignored by the `AES.new` function for `MODE_ECB` and `MODE_CTR`. That sounds very believable, since that is how PyCrypto behaves.

PyCryptodome behaves differently. If I try running `AES.new(b"\x00"*16, AES.MODE_ECB, b"\x00"*16)`, I get a TypeError that says `IV is not meaningful for the ECB mode`. For `AES.new(b"\x00"*16, AES.MODE_CTR, b"\x00"*16)`, it says `Too many arguments for this mode`.

I think the documentation should be updated to reflect this. I am trying to port a project from PyCrypto to PyCryptodome, and some things broke because the IV is not being silently ignored for ECB mode like it used to be. I tried to fix it myself, but I have been unable to figure out where in this repo (or elsewhere) that part of the documentation is.

**Comment by Legrandin** [comment]
Thanks, the API docs on the site were indeed out of date.

In the most [recent ones](http://legrandin.github.io/pycryptodome/Doc/3.4/Crypto.Cipher.AES-module.html), the `iv` parameter is defined only for a set of modes, ECB not being one of them.
