### ISSUE TITLE
Have some nice example files in a fork

### ISSUE THREAD

**Issue by SolarDon** [Legrandin/pycryptodome#152]
Hi,

I have some nice examples along with a README.txt and a Test.bat
https://github.com/SolarDon/pycryptodome/tree/master/Examples

I would like to add them to pycryptodome but I don't seem to have push access to the directory

**Comment by Legrandin** [comment]
I appreciate the effort, but there is no intention for now to add scripts to the project.
You can certainly create a separate project and use pycryptodome from there.
