### ISSUE TITLE
Different result than in java

### ISSUE THREAD

**Issue by futi16** [Legrandin/pycryptodome#153]
I have a java code that do AES encryption and now i want to make it work in python, but the problem is in python i get last 22 character wrong or missing in base64, which is 16 bytes, here is python code: 

```python
import base64
from Crypto.Cipher import AES
from Crypto import Random

raw='channel=chd;pm=sp100;up=ma;u=;p=15.8.9.13;device=qwefghgf;me=1521979714702;r=put'.encoe('utf-8')
key = bytes.fromhex("a941cc8a3fbb849a01fc9b7a2966a576")
iv = b'IqtY8jgALtjZNLM5'
cipher = AES.new( key, AES.MODE_CBC, iv )
print (base64.b64encode( cipher.encrypt( raw ) ).decode('utf-8') )```


here is what i get in java: 
OtUa70BShww2GgJt5aJT0hQnRPg0aoaE88m5Qk5hriDSjnxUAcJry7rClNehBWdkymg9Uyy5n-gw1Le6PgfP8NOk_N9FBnUj-nLl6iX-UjtxOK-a4SVxyrQB92jIi6Mb
and in python:
OtUa70BShww2GgJt5aJT0hQnRPg0aoaE88m5Qk5hriDSjnxUAcJry7rClNehBWdkymg9Uyy5n-gw1Le6PgfP8NOk_N9FBnUj-nLl6iX-Ujs=

Until '-Uj' everything is good. If you need i can post and java code.

**Comment by Varbin** [comment]
@futi16 To encrypt a (byte)string in a block mode (ECB, CBC) it must be a multiple of blocksize length - a common way to do is padding, which i assume Java does automatically.
Your raw data is 80 bytes long, the blocksize is 16.

PyCryptodome does not - it normally raises an error. It seems you are still using the old PyCrypto (which does not raise the error). To solve it, add padding. Commonly PKCS7 is used. To add padding with *PyCryptodome* see [here](https://www.pycryptodome.org/en/latest/src/util/util.html).

**Comment by futi16** [comment]
That worked. I did get error if the 'raw' was different than (len(raw)%16=0), if i had len(raw)=96, than i would't need padding?

**Comment by Varbin** [comment]
@futi16 Yes. But I would use padding in any case ("it won't hurt") as - I think - Java does this by default, so unpadding will always succeed.
