### ISSUE TITLE
Issue using KDF to get a Derived Key

### ISSUE THREAD

**Issue by gakar06** [Legrandin/pycryptodome#156]
I'm trying to re-create PowerShell's PasswordDeriveBytes method in python using pycryptodome's KDF module.

The main thing I can't get passed right now is getting the correct DerivedKey result in Python that I get from PowerShell.

PARAMETERS:

```
password = '1234567890'
salt = '0987654321'
length = 16
iterations = 2
```

SAMPLE POWERSHELL CODE:

```
$AsciiEncoder = New-Object System.Text.ASCIIEncoding;
$DerivedPass = New-Object System.Security.Cryptography.PasswordDeriveBytes('1234567890', $AsciiEncoder.GetBytes('0987654321'), "SHA1", 2);
[Byte[]] $KeyBytes = $DerivedPass.GetBytes(16);
-join($KeyBytes | ForEach { $_.ToString("X2")});
```

RESULT:

```
C937511EBDBE12C7A0FCC8D6CB42BEDC
```

*NOTE: The PowerShell code above is amended from https://github.com/PowerShellMafia/PowerSploit/blob/master/ScriptModification/Out-EncryptedScript.ps1. I am trying to re-implement the functionality in the Python code below.

PYTHON CODE:

```
from Crypto.Protocol import KDF
from Crypto.Hash import SHA1

def password_derive_key(password, salt, length, count):
    return KDF.PBKDF2(password, salt, length, count)

def main():
    derivedKey = password_derive_key('1234567890', '0987654321', 16, 2)
    print derivedKey.encode('hex')

if __name__ == "__main__":
    main()
```

RESULT:

```
5a3f103f5dc4558f8dca5d5b145ed0b4
```

The only thing that I can think of us that the ".GetBytes" method of PasswordDeriveBytes is generating a different result than what pycryptodome's KDF module.

Any help would be greatly appreciated.

**Comment by gakar06** [comment]
I still didn't get the same answer.

PARAMETERS

```
password = '1234567890'
salt = '0987654321'
length = 16
count = 2
hashAlgo = SHA1
```

PYTHON CODE:

```
derivedKey = password_derive_key(password, salt[:8], length, count, hashAlgo)
print 'TEST_1: {0}'.format(derivedKey.encode('hex'))

derivedKey = password_derive_key(password, salt[2:], length, count, hashAlgo)
print 'TEST_2: {0}'.format(derivedKey.encode('hex'))

derivedKey = password_derive_key(password, '87654321', length, count, hashAlgo)
print 'TEST_3: {0}'.format(derivedKey.encode('hex'))
```

ANSWER:

```
TEST_1: fe690b8e54eabcc4907dfc019734cffe
TEST_2: 054e55121f39a81e4c010a988474b2d9
TEST_3: 054e55121f39a81e4c010a988474b2d9
```

**Comment by Legrandin** [comment]
Closing, since this is not an issue of this project.

**Comment by gakar06** [comment]
Eijs,

Have you ever come across RC6 in malware? I have a sample that I am
analyzing that has a payload encrypted with RC6. It appears to pass a
4-byte initial key into the function. I have been unsuccessful in
re-creating the RC6 function in Python. Have you had any experience here?

Thanks,

Chris

**Comment by frispete** [comment]
Hi Chris, 

while I don't have anything to help you with your question, I'm pretty sure, that Helder is Helder's ;-) forename, and Eijs his surname. In my experience, only Bavarians and Chinese people turn this around...

**Comment by gakar06** [comment]
Thanks! Sometimes it is hard to tell. I didn't see RC6 in pycryptodome
which is why I was asking.
