### ISSUE TITLE
Example of saving encrypted string to database 

### ISSUE THREAD

**Issue by jqn** [Legrandin/pycryptodome#157]
I've looked everywhere and I can't seem to find a single example of encrypting a string and saving it to a database. Has anyone try this before?

**Comment by frispete** [comment]
Hi @jqn, 

cryptography is storage device agnostic in general.

Please start with a basic example: https://pycryptodome.readthedocs.io/en/latest/src/cipher/cipher.html but remember, the devil is in the details (encryption mode, key management), so get your feet wet, and formulate more specific questions.

This is hardly an issue of PyCryptodome.

**Comment by frispete** [comment]
Well, the universe always depends on the observers standpoint... 

That's just a pretty concise way to write a couple of binary objects with a fixed size to a file.

What's important for you is `cipher.nonce, tag, ciphertext` and the **secret** `key` in this context.
How to handle the database I/O is so specific to the database, ORM, etc, that this is way off topic here.

**Comment by jqn** [comment]
haha, ok thanks for your wisdom @frispete and my the force be with you. cheers!
