### ISSUE TITLE
Encrypt data with RSA example, does not work (Ciphertext with incorrect length)

### ISSUE THREAD

**Issue by DarkShroom** [Legrandin/pycryptodome#158]
actually it does not seem to return the data to unencrypt (when it reads the file, all them variables, they are empty), and i don't seem to be the only one?

i think this shows that:
https://stackoverflow.com/questions/46132222/pycryptodome-official-example-unclear?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

i have modified the example removing list comprehension, it works!

https://gist.github.com/DarkShroom/2e2eb0acea3ee15bf1a3691d86a35244

the code is a bit untidy though, but it still loads from the file and works

I am running python 2.7, surely this needs sorting? (just chuck my less pythonic version there?)

**Comment by frispete** [comment]
The stackoverflow issue, you're referencing here, was fixed 2 month ago with commit 6d72e37.

The 3 code snippets for generating the RSA keys, encrypt and decrypt runs fine here using PyCryptodome  3.6.1 with Python 2.7 and Python 3. For further investigation, post the exact traceback from the original examples here, please, including version numbers.
