### ISSUE TITLE
Add Twofish Cipher

### ISSUE THREAD

**Issue by crass** [Legrandin/pycryptodome#159]
Twofish would be a very useful addition to cryptodome as Twofish is used commonly as an alternative to Rijndael (AES).  Specifically, I'd like to support Twofish in python-libkeepass using only cryptodome.

For those looking to implement Twofish, here are some references:
* [mcrypt](https://github.com/CEPBEP/mcrypt) (C, LGPL)
* [cryptopp](https://www.cryptopp.com/wiki/Twofish) (C++, Public Domain)
* [botan](https://botan.randombit.net/) (C++, BSD)
* [cryptoplus](https://github.com/doegox/python-cryptoplus) (Python, MIT)

**Comment by Legrandin** [comment]
Sorry, no plans to implement Twofish.
