### ISSUE TITLE
ChaCha20 should be rfc7539 compliant (96bit nonce)

### ISSUE THREAD

**Issue by crass** [Legrandin/pycryptodome#160]
The current Chacha20 implementation uses the old recommended nonce size of 64bits.  [RFC7539](https://tools.ietf.org/html/rfc7539#section-2.3) specifies a 96bit nonce for added security.  Perhaps the nonce size could be specified to allow the user to choose between 64bit and 96bit nonces.  Basically the change is the block counter goes from 64bits to 32bits and the 32bits are added to the nonce.

**Comment by Legrandin** [comment]
This is currently supported on master.

**Comment by crass** [comment]
Thanks! I just did some basic decrypt tests and everything looks good! I think there's a minor error in 72321bbb.  The documentation was modified to suggest that the encrypt example was using RFC7539.  However, the code does not provide a nonce parameter to the `new` function, so a random 8-byte nonce will be used, which is not RFC7539 compliant. I think specifying a nonce parameter is the only correction needed.  Thanks again!
