### ISSUE TITLE
AES-CTR Node.js 16bytes nonce vs. Cryptodome 15bytes nonce compatibility 

### ISSUE THREAD

**Issue by Pro7ech** [Legrandin/pycryptodome#165]
Hello, I just wanted to point out that in Cryptodome the maximum length of the nonce for aes-ctr is set to 15bytes , while in Node.js the minimum length for the nonce is 16 bytes. This small issue prevented me using Cryptodome.

**Comment by Legrandin** [comment]
Reopening as a reminder to improve the documentation on this.

**Comment by Pro7ech** [comment]
I agree, this is also how it is presented everywhere. However the way AES-256-CTR is implemented in node.js is by using a 16byte nonce, and then incrementing on top of this nonce.

**Comment by Legrandin** [comment]
Terminology and how CTR works are explained in greater detail now:

https://www.pycryptodome.org/en/latest/src/cipher/classic.html#ctr-mode

**Comment by jcorbettfrank** [comment]
I just wanted to say that this also prevented me from using Cryptodome. I can't get into specifics, but I'm using two other libraries in C and C++ that use 16 byte nonces. While I could work around this, I'm going to use another python library that supports 16 byte nonces out of the box. I respect your design decision, just wanted to let you know.

**Comment by Varbin** [comment]
@jcorbettfrank Shouldn't you be able to set the second half with initial_value (first 8 bytes=nonce, second one =initial_value)?

**Comment by jcorbettfrank** [comment]
@Varbin Yea, you're completely right, duh. Sorry for the false alarm.
