### ISSUE TITLE
Blowfish doesn't support 72 byte key

### ISSUE THREAD

**Issue by VisualStudio-zz** [Legrandin/pycryptodome#166]
The bcrypt implementation of Blowfish supports 72 byte keys, I don't know if this is a valid issue but it lowers the versatility of this library.

**Comment by Varbin** [comment]
According to the [Blowfish specs](https://www.schneier.com/academic/blowfish/) the maximum key size for it is 56 bytes.

I'm not sure, but is it possible that bcrypt uses a modified Blowfish algorithm?

**Comment by Legrandin** [comment]
Yes, it uses Blowfish with a customized key scheduling ([EksBlowfishSetup](https://en.wikipedia.org/wiki/Bcrypt#Expensive_key_setup)), which indeed takes up to 72 bytes as input password.

I close this because arguably the algorithm is not Blowfish anymore.
