### ISSUE TITLE
Docs "Generic state diagram for a AEAD cipher mode" needs extra state transitions

### ISSUE THREAD

**Issue by cmcqueen** [Legrandin/pycryptodome#168]
See the diagram "Generic state diagram for a AEAD cipher mode" at [Modern modes of operation for symmetric block ciphers](http://pycryptodome.readthedocs.io/en/latest/src/cipher/modern.html#modern-modes-of-operation-for-symmetric-block-ciphers). It needs a `verify()` path from the "Hashing" to "Decryption completed" states. It needs a `digest()` path from the "Hashing" to "Encryption completed" states. That is for the case of running AES-GCM in authentication-only mode.

**Comment by Legrandin** [comment]
Thanks. This is fixed now.
