### ISSUE TITLE
Decrypt with OpenSSH key with passphrase

### ISSUE THREAD

**Issue by drohm** [Legrandin/pycryptodome#17]
I'm trying to use my pub/private OpenSSH keys that has a passphrase and can't seem to get it to work.  Does the RsaKey class not support OpenSSH keys with passphrases?  I can get another OpenSSH key that doesn't have a passphrase to work correctly.

I'm getting this error:

`
  File "C:\code\security.py", line 56, in _decrypt
    private_key = RSA.import_key(open(self.private_key).read(), passphrase=self.passphrase)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 736, in import_key
    (der, marker, enc_flag) = PEM.decode(tostr(extern_key), passphrase)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\Cryptodome\IO\PEM.py", line 171, in decode
    data = unpad(objdec.decrypt(data), objdec.block_size)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\Cryptodome\Util\Padding.py", line 94, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
`

**Comment by Varbin** [comment]
The [documentation](https://legrandin.github.io/pycryptodome/Doc/3.3.1/Crypto.PublicKey.RSA-module.html#importKey) says that only PEM-formated key can be decoded with Pycrypto(dome) but OpenSSH uses its own key format.

**Comment by drohm** [comment]
Thanks.  I got around by just using the library to generate new keys (PEM format).  I was hoping I could use our existing OpenSSH keys (that we use for git and github) with this, but I could only get keys without passphrases to work.  Just curious, are you looking to add support for OpenSSH down the road?

**Comment by drohm** [comment]
@Legrandin I'm using the instructions on github for generating the key

> ssh-keygen -t rsa -b 2048 -C 'pycryptodome'

The first three lines of the private key:
`
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,30A5CB7A122643096E2FF0B93D1DB65C
`

**Comment by Varbin** [comment]
While I think it is possible to generate encrypted PEM-encoded keyfiles, it is not the default and it only works with OpenSSH >(=?) 6.5. On default OpenSSH uses its own key format for encrypted private keys.

**Comment by Legrandin** [comment]
Converted into a feature request https://github.com/Legrandin/pycryptodome/issues/275
