### ISSUE TITLE
it not work in windows with python3.5(x64)

### ISSUE THREAD

**Issue by linzhi** [Legrandin/pycryptodome#174]
I install pycryptodome 3.6.1 in pycharm

from Crypto.Cipher import AES

But ImportError: No module named 'Crypto'

**Comment by sspring** [comment]
well,just rename the folder name `crypto` to `Crypto` in %python_install_dir%/Lib/site-packages directory.It works for me.

**Comment by datta90** [comment]
download miniconda 
https://files.pythonhosted.org/packages/0f/5d/a429a53eacae3e13143248c3868c76985bcd0d75858bd4c25b574e51bd4d/pycryptodome-3.6.3-cp36-cp36m-win_amd64.whl
https://repo.continuum.io/miniconda/Miniconda3-4.3.31-Windows-x86_64.exe
then try to install it worked for me

Please note remove your old python or remove the python dir from  PATH variable in windows
![capture1](https://user-images.githubusercontent.com/10784012/42377629-a90f2e26-8141-11e8-9639-59ddba9f2741.PNG)

**Comment by datta90** [comment]
![capture2](https://user-images.githubusercontent.com/10784012/42378088-a215da28-8143-11e8-88a3-5b46533b25a2.PNG)
