### ISSUE TITLE
License.rst inconsistent with setup.py license

### ISSUE THREAD

**Issue by RacingTadpole** [Legrandin/pycryptodome#176]
[setup.py](https://github.com/Legrandin/pycryptodome/blob/master/setup.py#L708) states the license is simply "BSD".

However the license.rst file mentions a mix of public domain, BSD, patents and Apache 2 licenses.

I suggest setup.py be updated to reflect this, as automated license-checking tools often only check setup.py.

**Comment by Legrandin** [comment]
Fixed with 3367e21d7204c2f3cb68303b7cb0d60c8bf0ed28
