### ISSUE TITLE
Missing macOS and Windows wheels for Python 3.7

### ISSUE THREAD

**Issue by BoboTiG** [Legrandin/pycryptodome#177]
Hello,

Do you know when wheels for Python 3.7 on macOS and Windows will be available?

**Comment by Legrandin** [comment]
I can do that as soon as AppVeyor has added 3.7 to their images, [which should happen next week](https://github.com/appveyor/ci/issues/2475).

**Comment by BoboTiG** [comment]
Excellent :+1:

**Comment by Legrandin** [comment]
Python 3.7 wheels now available for Linux, Windows and Mac.

**Comment by Legrandin** [comment]
Reopening, as `2to3` in Python 3.7 is now messing up end-of-lines and preventing 3.7 wheels from being built in appveyor (they did get built for a few hours though).

**Comment by Legrandin** [comment]
This is indeed a bug in `2to3`: https://bugs.python.org/issue34108 .

**Comment by BoboTiG** [comment]
It will be OK with Python 3.7.1 then :)

**Comment by Legrandin** [comment]
Fixed in v3.6.5
