### ISSUE TITLE
Use of dict.has_key breaking python 3 compatability

### ISSUE THREAD

**Issue by arnimarj** [Legrandin/pycryptodome#182]
Hi,

I ran into an issue whilst running Python 2.7 in py3k compatibility mode (the `-3` flag). It reported the use of `dict.has_key()`. Looking over the source code, it seems that there are 3 uses of `has_key`, each of which may break Python 3  compatability:

https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/SelfTest/Cipher/common.py#L412
https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Random/random.py#L120
https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Cipher/__init__.py#L61

**Comment by frispete** [comment]
...which isn't an issue, because PyCryptodome converts the code during installation:

https://github.com/Legrandin/pycryptodome/blob/master/setup.py#L113

Cheers,
Pete

**Comment by arnimarj** [comment]
That explains what I am seeing. Thank you and sorry for the misunderstanding.
