### ISSUE TITLE
PyCryptodomeX does not install using PIP under Microsoft Windows

### ISSUE THREAD

**Issue by tomrow** [Legrandin/pycryptodome#183]
I think there may be a problem with the 3.6.3 build of this software for Win32
```
>>> import Cryptodome
Traceback (most recent call last):
  File "<pyshell#38>", line 1, in <module>
    import Cryptodome
ModuleNotFoundError: No module named 'Cryptodome'
>>> 
```
Its files were installed by PIP into the following directories:
```
c:\python36-32\lib\site-packages\cryptodome\
c:\python36-32\lib\site-packages\pycryptodomex-3.6.3.dist-info\
```

**Comment by Varbin** [comment]
@tomrow Which version of Windows do you have? The exact pip version might be important, too (`pip --version`), some versions of pip resulted installation failures? While I doubt the exact Python version is important, what what exakt Python version do you have?

Out of couriosity: Does `import cryptodome` (lowercase) work?

**Comment by Legrandin** [comment]
Closing for lack of further feedback...
