### ISSUE TITLE
Error 126 when running selftest

### ISSUE THREAD

**Issue by jairoxyz** [Legrandin/pycryptodome#184]
Hi,

I have built the Crypto package following https://www.pycryptodome.org/en/latest/src/installation.html#windows-from-sources-python-2-x-python-3-2 using this environment:
- Windows Server 2008 R2 new VM installation
- Python 2.7.13 x86
- pip 10.0.1
- VC++ for Python 2.7

Setup script and build process complete without error. When running selftest with:
python -m Crypto.SelfTest

this error message is produced:
Skipping GMP tests ([Error 126] The specified module could not be found) ............

Is that normal behavior due to GMP libs not installed on Windows? 

Thanks!

**Comment by Legrandin** [comment]
Yes, that is expected behavior on Windows (GMP is only supported on Unix system).
It is not actually an error.
If self-test gives you an OK at the end you are good to go.
