### ISSUE TITLE
Error loading native modules

### ISSUE THREAD

**Issue by jairoxyz** [Legrandin/pycryptodome#185]
Thanks to your swift answer to https://github.com/Legrandin/pycryptodome/issues/184 . 

Now, I know this might be the wrong place to ask but I don't know where else. As described I have built cryptodome for win python x86 version 2.7.13, which is exactly the same version my Kodi install, but I keep running into the same error when I try to use Cyrpto or Cryptodome as a package in Kodi, no matter if I put it into Kodi system python site-packages or inside the custom addon/module I have made. It always breaks when trying to load the dynamic C libraries:

`
Kodi17\system\python\lib\site-packages\Crypto\Util\_raw_api.py", line 258, in load_pycryptodome_raw_lib
raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.pyd': [Error 126] The specified module could not be found
`
I debugged the library paths and all seems to be correct, but whatever I try it gives me the same error.

Appreciate any help or hint.

**Comment by Legrandin** [comment]
A `.pyd` file is really just a `.DLL` file renamed. Often, this is due to missing non-obvious binary dependency, which you can find for instance with [depwalker](http://www.dependencywalker.com).

It sounds like you are building it on a separate Windows machine and then trasferring manually to you Windows Kodi install. Is that hte case? Are you sure they are both 64- or both 32-bits?

**Comment by jairoxyz** [comment]
Hi again, yes, I solved it by installing the VC++ 2008 Redistributable as I could see in dependencywalker that MSVCR90 was not found. Also important for Kodi 17 is to build it for x86 platform but you'll see a clear error message if building for x64. Kodi 18 will be different/easier as they will package Pycryptodomex into the installers. Thanks for your help and excellent work ;)

**Comment by Legrandin** [comment]
Awesome... I can close this issue then...
