### ISSUE TITLE
AES.MODE_EAX decrypt is not-matching/incompatibility to Java EAXBlockCipher 

### ISSUE THREAD

**Issue by kashirin-alex** [Legrandin/pycryptodome#190]
There is an open issue with BouncyCastle, You can follow-up for the details at https://github.com/didisoft/bc-java/issues/1

Are there known facts on this?

Thanks

**Comment by Legrandin** [comment]
Can you please provide the output of the various `System.out.println` statements in `get_aes_token()` for on sample run?

**Comment by kashirin-alex** [comment]
Attached is the output.log for the following output.,
https://github.com/thither/Thither.Direct-client-libraries/blob/master/java/libthither/src/main/java/direct/thither/lib/api/fms/FmsClient.java#L96

[output.log](https://github.com/Legrandin/pycryptodome/files/2244560/output.log)

the Python side result is 
--------------------------------------------------------------------------------
rndBytes|1533028053|1234567812345678|8|rndBytes�®¬±
--------------------------------------------------------------------------------
cm5kQnl0ZXN8MTUzMzAyODA1M3wxMjM0NTY3ODEyMzQ1Njc4fDh8cm5kQnl0ZXPGrqyxAgOOkA==
--------------------------------------------------------------------------------

**Comment by Legrandin** [comment]
On the Java side (encryption), the `crp` variable contains the ciphertext concatenated to the 8-byte MAC tag (the same returned by `c.getMac()`), not just the ciphertext alone as intended.

At the Python side (decryption), validation will therefore fail for two reasons:

1. the plaintext contains 8 extra bytes
2. the expected MAC tag is 16 bytes and not 8

It's not clear to me which side can be modified, but it might be helpful to know that with PyCryptodome you can change the expected MAC tag length with the parameter `mac_len` when calling `AES.new()`.
For example:

    cipher = AES.new(key, AES.MODE_EAX, mac_len=8)

**Comment by kashirin-alex** [comment]
In hope that info can be useful,
with Addition data Parameters (AEADParameters), the MAC-len is set able.
https://github.com/thither/Thither.Direct-client-libraries/blob/master/java/libthither/src/main/java/direct/thither/lib/api/fms/FmsClient.java#L120

here are the outputs with a16 bit MAC,
PY:
> --------------------------------------------------------------------------------
> c;,dZK´��1533069717|1234567812345678|8|rndBytes,-7
> --------------------------------------------------------------------------------
> cm5kQnl0ZXN8MTUzMzA2OTcxN3wxMjM0NTY3ODEyMzQ1Njc4fDh8cm5kQnl0ZXMsLTcNEWM7LGRaAUuYtN3Y
> --------------------------------------------------------------------------------
> Traceback (most recent call last):
>  
>   File "/opt/pypy2/site-packages/Cryptodome/Cipher/_mode_eax.py", line 293, in verify
>     raise ValueError("MAC check failed")
> ValueError: MAC check failed
> 

JAVA:
[output.log](https://github.com/Legrandin/pycryptodome/files/2247037/output.log)

By removing the additional bytes (16 in this case), The tag and The data does verify
`plaintext = cipher.decrypt(base64.b64decode(ciphered)[:-16])`

probably be the solution, for long term is to keep the original computed data and to tag the "token" with a type of encrypt used, While at this point I'll be cutting of the submitted encrypted-data(crp) on the java side.

Thanks
