### ISSUE TITLE
Any roadmaps to support decryption by public key like bouncy castle in java?

### ISSUE THREAD

**Issue by SuperMarioX** [Legrandin/pycryptodome#194]
FYI~

**Comment by Legrandin** [comment]
Which algorithm are you interested in exactly?
RSA OAEP and PKCS#1v1.5 are already supported.

**Comment by SuperMarioX** [comment]
Bouncycastle Java version supports encrypting a string with private key and decrypting it with public key.
And in my project, unfortunately I am using this way to do encryption and decryption with padding   RSA/ECB/OAEPWithSHA-256AndMGF1Padding. But I don't find any clue to decrypt a string by public key with this specific padding in pycryptodome.

Any codes or suggestions to help me get out of this situation? That will be very thankful.

**Comment by SuperMarioX** [comment]
@Legrandin Would you please help me?

**Comment by Legrandin** [comment]
I have not tried directly, but I am using the assumptions described [here](https://stackoverflow.com/questions/32161720/breaking-down-rsa-ecb-oaepwithsha-256andmgf1padding).

```python
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Hash import SHA256

# We assume RSA key has been loaded already in recipient_public_key

cipher_rsa = PKCS1_OAEP.new(recipient_public_key, hashAlgo=SHA256)
ciphertext = cipher_rsa.encrypt(clear_data)
```

**Comment by SuperMarioX** [comment]
Thanks for the comments. However decrypting by PUBLIC KEY is still my problem. I tried many crypto lib sbut no ones would help. @Legrandin

**Comment by Legrandin** [comment]
Decryption can only be done with the private key. Public keys can only be used for encryption (or signature verification).

**Comment by lizhaode** [comment]
@Legrandin 
Hi, why public key only can be used for encrypt? in Java, public key also can be used for decrypt

**Comment by frispete** [comment]
Because that's the way, asymmetric cryptography works. 

Maybe you're looking for symmetric crypto? If you can use the public key for everything, why would you need a private key anymore?

**Comment by lizhaode** [comment]
@frispete 
thx, I search some article, it's really as you say.
But, I also has a confuse. If A send message with RSA pub key encrypted to B, B decrypted message with private key. Then B send some message encrypted with private key to A, how can A to decrypt message?
many thanks

**Comment by frispete** [comment]
Guess, you're looking for a Diffie-Hellman key exchange. See 3rd box on the right in https://en.wikipedia.org/wiki/Public-key_cryptography for an overview...
