### ISSUE TITLE
Add XOR.py to Cipher directory

### ISSUE THREAD

**Issue by voytecPL** [Legrandin/pycryptodome#201]
Is there any reason XOR.py is missing from Cipher directory?
It does exist in original PyCrypto project under:
https://github.com/dlitz/pycrypto/blob/master/lib/Crypto/Cipher/XOR.py

**Comment by Legrandin** [comment]
It has been removed because it is dangerous to call it a cipher.

If you need that functionality, I would recommend to look at the [Cipher.Util.strxor](https://www.pycryptodome.org/en/latest/src/util/util.html#crypto-util-strxor-module) module, which does basically the same.

**Comment by voytecPL** [comment]
Thank you for your response.
For backward compatibility I'd like to see it there but I understand your view on this one.
I have worked around this by using some others xor tools.
Thanks
