### ISSUE TITLE
Minimum key size in Blowfish doesn't match the specification

### ISSUE THREAD

**Issue by cspiegel** [Legrandin/pycryptodome#203]
According to https://www.schneier.com/academic/blowfish/, the Blowfish key size ranges from 32 to 448 bits.  However, the minimum key size accepted by PyCryptodome is 40 bits.

**Comment by Legrandin** [comment]
Fixed in master ith 93912230f3c39e09f4038cb17e301468687c6538.

**Comment by Legrandin** [comment]
Released in v3.8.1
