### ISSUE TITLE
Unable to install pycryptodome on Onion Omega 2+ (580MHz MIPS-based Linux Platform)

### ISSUE THREAD

**Issue by cluster10537** [Legrandin/pycryptodome#205]
I am trying to install pycryptodome on onion omega 2+ as pycryptodome is a dependency for Firebase python wrapper REST API Pyrebase. I have been getting this error.
```
root@Omega-872F:~# pip3 install pycryptodome
Collecting pycryptodome
  Downloading https://files.pythonhosted.org/packages/94/7f/33b748dd22ea889fcb1a6c6f1f30ad1e5a70066cd7615dbce7d9a6392106/pycryptodome-3.6.6.tar.gz (7.1MB)
    100% |████████████████████████████████| 7.1MB 191kB/s 
Building wheels for collected packages: pycryptodome
  Running setup.py bdist_wheel for pycryptodome ... error
  Failed building wheel for pycryptodome
  Running setup.py clean for pycryptodome
Failed to build pycryptodome
Installing collected packages: pycryptodome
  Running setup.py install for pycryptodome ... error
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hv5rkah9/pycryptodome/setup.py';
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" 
install --record /tmp/pip-record-xdclwsl8/install-record.txt --single-version-externally-managed --compile" 
failed with error code 1 in /tmp/pip-install-hv5rkah9/pycryptodome/
```
This is the list of pip packages installed on onion omega 2+ with their respective versions
```
root@Omega-872F:~# pip3 list
Package                  Version
------------------------ -------
gcloud                   0.17.0 
googleapis-common-protos 1.5.3  
httplib2                 0.11.3 
jws                      0.1.3  
oauth2client             3.0.0  
pip                      18.0   
protobuf                 3.6.1  
pyasn1                   0.4.4  
pyasn1-modules           0.2.2  
python-jwt               2.0.1  
requests                 2.11.1 
rsa                      3.4.2  
setuptools               40.2.0 
six                      1.11.0 
wheel                    0.31.1 
```
This is some information about onion omega 2+
**Operating system** - OpenWrt
**System on chip used** - MediaTek MT7688
**CPU** - 580 MHz 32-bit computing Single-core MIPS 24KEc
**Memory** - 64 MB (128 MB for Omega2 Plus)
**Storage** - 16 MB (32 MB and a Micro SDHC slot for Omega2 Plus)
**Graphics** - No graphic
**Power** - 0.6 Watts

More about onion omega 2+ can be found here https://docs.onion.io/omega2-docs/

**Comment by frispete** [comment]
You're missing a compiler, I guess.

Proabably, you need to setup a cross compilation infrastructure in order to produce binary packages for your target.

**Comment by cluster10537** [comment]
Could you please guide me through the process of cross compilation.

**Comment by cluster10537** [comment]
Is there any guide or documentation to cross-compile pycryptodome?? Please share if any. I am willing to try it and install pycryptodome on onion omega 2+.

**Comment by Legrandin** [comment]
Typically, it is sufficient to set the `CC` environment variable with the name of the C cross-compiler (e.g. with `export CC=arm-none-eabi-gcc`) and then build.

**Comment by cluster10537** [comment]
I am not so familiar with the complete process of cross compilation. Could you please provide me a step-by-step procedure or a complete guide. Thank you!!

**Comment by Legrandin** [comment]
Sorry, I don't have a step-by-step procedure.
