### ISSUE TITLE
Bandit considers pycryptodome a high vulnerability

### ISSUE THREAD

**Issue by robertlagrant** [Legrandin/pycryptodome#206]
Having just built a project that hasn't been built in a while, I found that bandit is now flagging the use of pycryptodome as a high vulnerability, which breaks our build. Here's the commit: https://github.com/PyCQA/bandit/commit/1c716beb1f7e687df24f2f17dc9b4c34180b1ab8

I haven't managed to find any commentary on this online, and thought this'd be a good place to start. Is there a useful defense of pycryptodome that can get this decision reversed? Is bandit wrong?

**Comment by Legrandin** [comment]
This was flagged to the bandit team here (https://github.com/PyCQA/bandit/issues/319).

Their position is that PyCryptodome includes old algorithms that are weak by today's standards (say SHA1 or single DES) and users may be tempted to use them.

I think it would be better if bandit just blacklisted the algorithms they don't like (say, `Crypto.Cipher.DES`) as opposed to the the whole library.

**Comment by Legrandin** [comment]
It is also bizarre that by the same argument `cryptography` would be unsafe too,
since it allows users to freely use SHA1, CAST5, MD5, SEED, RC4, IDEA, the ECB cipher mode, etc.

**Comment by robertlagrant** [comment]
Fully agree with the above.

**Comment by frispete** [comment]
@Legrandin you might give them a list of weak crypto methods, they should care about.

**Comment by Legrandin** [comment]
Fixed by the bandit team https://github.com/PyCQA/bandit/issues/319
