### ISSUE TITLE
Pycryptodome must return bytearrays instead of bytes

### ISSUE THREAD

**Issue by interlocuteur** [Legrandin/pycryptodome#208]
My program use a lot of:
```
x = AES.encrypt( x)
XOR( const, x) # modify in-place
```

With pyCrypto, I had to do:
`x= bytearray( AES.encrypt( bytes( x))
`
Thanks to pyCryptoDome accepting bytearrays, the code may be reduced to:
`x= bytearray( AES.encrypt( x)`

An improvement to AES.encrypt would be to return a bytearray instead of bytes[].
That would eliminate casting (it requires memory allocation and garbage collection). The code would be reduces to:
`x= AES.encrypt( x)`

Another improvement would be to enable "in-place" encryption. For example:
`AES.encrypt( x, in-place=True)`

The trend with recent versions of Python is to reduce memory allocation and garbage collection. That's why we now have socket.recvinto() or unpack_from( format, buffer, offset). They reduce memory allocation, garbage collection and slicing operations. That improve performance.
So, the ultimate improvement would be:
`AES.encrypt( buf1, offset, buf2 offset) # encrypt without slicing`
and it's reduced form:
`AES.encrypt( buf, offset) # encrypt without slicing, in-place`

Thanks for taking care of pyCrypto

**Comment by Legrandin** [comment]
Thanks for sharing the idea: I was thinking along similar lines too a while ago.

A better API might be one where an optional keyword (like `output`) can be used to indicate where to put the result **instead** of returning it as new `bytes`. You can then pass an existing `memoryview` or a `bytearray` (assuming it is sufficiently large) as the desired destination. So for instance:

    buffer_out = bytearray(out_len)
    ...
    rv = cipher.encrypt(plaintext, output=buffer_out)
    assert(rv == None)

And if you want to do some in-place encryption:

    cipher.encrypt(buffer, output=buffer)

Finally, I don't think it is so clean to have explicit offsets: you might as well create a `memoryview` at the right location in memory. That involves no inefficient copying.

**Comment by Legrandin** [comment]
This improvement is now in place: methods like `encrypt` accept a new parameter called `output`, as describing in the previous comment.
