### ISSUE TITLE
Problem in the Docs Example

### ISSUE THREAD

**Issue by mlbk0** [Legrandin/pycryptodome#21]
```
>>> from Crypto.Math import Number
```
gives me the error

```
ImportError: cannot import name 'Number'
```

Any pointers? (For example the import is featured in the example shown in http://legrandin.github.io/pycryptodome/Doc/3.3.1/Crypto.PublicKey.ElGamal-module.html)

**Comment by battyc** [comment]
I just looked through and it seems like that code is very out dated.  That SHA class was deprecated in python 2.6 along with many of the functions it relied on.   I'll look into piecing together a legitimate example to replace it tomorrow.

**Comment by mlbk0** [comment]
Thanks for looking into this. I ended up using the old Crypto library, which did what I needed for my purposes, but it would of course be nice if this works in the current CryptoDome version.

**Comment by Legrandin** [comment]
Thanks for reporting anyway, it was a typo (it should have been `Numbers` not `Number`). Fixed in master.
