### ISSUE TITLE
pip install and ModuleNotFoundError: No module named 'Crypto.Protocol.KDF'

### ISSUE THREAD

**Issue by lclevy** [Legrandin/pycryptodome#235]
Hi,
I'm under win10 and with Python 3.6.7
I installed using pip, then launched my script that worked perfectly with PyCrypto 3.6.1 and Python 3.3
https://github.com/lclevy/unarcrypto
I had ModuleNotFoundError: No module named 'Crypto.Protocol.KDF'
I uninstalled using pip
and installed using easy_install
No error anymore.
This issue is already discussed here: 
https://stackoverflow.com/questions/43994590/how-do-i-get-around-the-no-module-named-crypto-error-after-doing-pip-inst

Thanks for you work!

**Comment by Legrandin** [comment]
If you can reproduce this error, can you please check `sys.path` and verify that indeed it includes the right `site-packages` directory (and that a folder named `Crypto` exists there)?

I typically see that behavior when I activate a virtualenv, but still launch the `python` interpreter from the installation directory (say `C:\Python36`).  In other words, I forget that Windows always searches for the file to execute in the current directory first, and only after that parse the `PATH` environment variable (which virtualenv modifies, with the directories where modules are installed).

Beside that, I don't have a Win10 install at hand right now to try to reproduce this error. I'll look around.

**Comment by lclevy** [comment]
If I remember correctly, KDF.py where missing when installing with pip.
with easy install, KDF.py is here:
C:\Users\laurent\AppData\Local\Programs\Python\Python36\Lib\site-packages\pycryptodome-3.7.0-py3.6-win-amd64.egg\Crypto\Protocol
I did not use virtualenv.

C:\Users\laurent>python -c "import sys; print(sys.path)"
['', 'C:\\Users\\laurent\\AppData\\Local\\Programs\\Python\\Python36\\python36.zip', 'C:\\Users\\laurent\\AppData\\Local\\Programs\\Python\\Python36\\DLLs', 'C:\\Users\\laurent\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\Users\\laurent\\AppData\\Local\\Programs\\Python\\Python36', 'C:\\Users\\laurent\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages', 'C:\\Users\\laurent\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pycryptodome-3.7.0-py3.6-win-amd64.egg']

**Comment by Legrandin** [comment]
Can you please try the solution described in the FAQ (https://www.pycryptodome.org/en/latest/src/faq.html#why-do-i-get-the-error-no-module-named-crypto-on-windows), and reopen if it doesn't work.
