### ISSUE TITLE
importError can't find name in Crypto.Util.py3compat

### ISSUE THREAD

**Issue by xiewenlong1202** [Legrandin/pycryptodome#237]
I installed pycryptodome 3.6.6 in MacOS, and run it with python 3.7.0

It is used as a submodule in another module, and when run I got error:
File "/Users/xie/Src/venv/lib/python3.7/site-packages/steembase/memo.py", line 8, in <module>
    from Crypto.Cipher import AES
  File "/Users/xie/Src/venv/lib/python3.7/site-packages/Crypto/Cipher/__init__.py", line 28, in <module>
    from Crypto.Cipher._mode_cbc import _create_cbc_cipher
  File "/Users/xie/Src/venv/lib/python3.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 37, in <module>
    from Crypto.Util.py3compat import _copy_bytes
ImportError: cannot import name '_copy_bytes' from 'Crypto.Util.py3compat' (/Users/xie/Src/venv/lib/python3.7/site-packages/Crypto/Util/py3compat.py)

I have read the py3compat.py. It seems that you have changed the function name in the file recently and did not update the function name of all references even it is in you own project.

so the error happened. I recommend to change the function name back.
for example change b() to bytes() which is so used in other file of the project.

**Comment by Legrandin** [comment]
The function `_copy_bytes` is present in `Crypto.Util.py3compat` for both pycryptodome tagged v3.6.6 and on the current `master` branch.

**Comment by frispete** [comment]
In other words, your installation is broken.
