### ISSUE TITLE
AES-CMAC incorrect result

### ISSUE THREAD

**Issue by windsurfer1122** [Legrandin/pycryptodome#238]
Tried to verify a message with AES-CMAC.
Used module [cryptography](https://cryptography.io/en/latest/hazmat/primitives/mac/cmac/) before and wanted to switch to [pycryptodome](https://www.pycryptodome.org/en/latest/src/hash/cmac.html).
But results do not match.

Do I miss something here or is this an issue with pycryptodome?

```
Data length in bytes: 128
Data: b'7f504b4780000001000000c000000008000000c00000000e000000000f1bbeb00000000000000180000000000f1bbcd05550393030302d4243555339383132335f30302d554e434841525445443244534b4d5032000000000000000000000000daf49a4bd188b5c794bda67f32af1331be6ad3aa1ee556fabfdbf8b6b45cbc13'
Expected SHA-1: b'676c8812462b36d09e5594ef3e0b26551d7f76bd'
Expected AES-CMAC: b'12701ce27476d6c23f76104ca42fedbc'

>>>>> Test A with cryptography 2.3.1
SHA-1: b'676c8812462b36d09e5594ef3e0b26551d7f76bd' = Correct
AES-CMAC: b'12701ce27476d6c23f76104ca42fedbc' = Correct

>>>>> Test B with pycryptodomex 3.7.0
SHA-1: b'676c8812462b36d09e5594ef3e0b26551d7f76bd' = Correct
AES-CMAC: b'e9429f1f589ec53efce0832a7f6603fc' = Wrong!!!
```

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
### ^^^ see https://www.python.org/dev/peps/pep-0263/

### Python 2 workarounds:
## a) prevent interpreting print(a,b) as a tuple plus support print(a, file=sys.stderr)
from __future__ import print_function
## b) interpret all literals as unicode
from __future__ import unicode_literals
## c) support bytes()
from builtins import bytes

import sys
import binascii

### Test A with cryptography
import cryptography.hazmat.backends
import cryptography.hazmat.primitives.hashes
import cryptography.hazmat.primitives.cmac
import cryptography.hazmat.primitives.ciphers.algorithms

### Test B with pycryptodomex
import Cryptodome.Hash
import Cryptodome.Cipher.AES


Data = bytes.fromhex("7f504b4780000001000000c000000008000000c00000000e000000000f1bbeb00000000000000180000000000f1bbcd05550393030302d4243555339383132335f30302d554e434841525445443244534b4d5032000000000000000000000000daf49a4bd188b5c794bda67f32af1331be6ad3aa1ee556fabfdbf8b6b45cbc13")
Key = bytes.fromhex("2e7b71d7c9c9a14ea3221f188828b8f8")
Expected_SHA1 = bytes.fromhex("676c8812462b36d09e5594ef3e0b26551d7f76bd")
Expected_CMAC = bytes.fromhex("12701ce27476d6c23f76104ca42fedbc")

print ("Data length in bytes:", len(Data))
print ("Data:", binascii.hexlify(Data))
print ("Expected SHA-1:", binascii.hexlify(Expected_SHA1))
print ("Expected AES-CMAC:", binascii.hexlify(Expected_CMAC))
print()


### Test A with cryptography
### https://cryptography.io/en/latest/hazmat/primitives/mac/cmac/
print(">>>>> Test A with cryptography", cryptography.__version__)
Hash_SHA1_A = cryptography.hazmat.primitives.hashes.Hash(cryptography.hazmat.primitives.hashes.SHA1(), backend=cryptography.hazmat.backends.default_backend())
Hash_SHA1_A.update(Data)
Hash_SHA1_A_Digest = Hash_SHA1_A.copy().finalize()
print ("SHA-1:", binascii.hexlify(Hash_SHA1_A_Digest), "=", "Correct" if Hash_SHA1_A_Digest == Expected_SHA1 else "Wrong!!!")

Hash_CMAC_A = cryptography.hazmat.primitives.cmac.CMAC(cryptography.hazmat.primitives.ciphers.algorithms.AES(Key), backend=cryptography.hazmat.backends.default_backend())
Hash_CMAC_A.update(Data)
Hash_CMAC_A_Digest = Hash_CMAC_A.copy().finalize()
print ("AES-CMAC:", binascii.hexlify(Hash_CMAC_A_Digest), "=", "Correct" if Hash_CMAC_A_Digest == Expected_CMAC else "Wrong!!!")
print()


### Test B with PyCryptodome
### https://www.pycryptodome.org/en/latest/src/hash/cmac.html
print(">>>>> Test B with pycryptodomex", Cryptodome.__version__)
Hash_SHA1_B = Cryptodome.Hash.SHA1.new()
Hash_SHA1_B.update(Data)
Hash_SHA1_B_Digest = Hash_SHA1_B.copy().digest()
print ("SHA-1:", binascii.hexlify(Hash_SHA1_B_Digest), "=", "Correct" if Hash_SHA1_B_Digest == Expected_SHA1 else "Wrong!!!")

Hash_CMAC_B = Cryptodome.Hash.CMAC.new(Key, ciphermod=Cryptodome.Cipher.AES)
Hash_CMAC_B.update(Data)
Hash_CMAC_B_Digest = Hash_CMAC_B.copy().digest()
print ("AES-CMAC:", binascii.hexlify(Hash_CMAC_B_Digest), "=", "Correct" if Hash_CMAC_B_Digest == Expected_CMAC else "Wrong!!!")
print()
```

**Comment by Legrandin** [comment]
Yes, there is a bug, fixed in dfb0b5840e2da8d6eaf1cfacdef01c9544e7a8c9.

It only affects the `copy` method (which is seldom used, and not needed in your case), so you can replace already:

    Hash_CMAC_B_Digest = Hash_CMAC_B.copy().digest()

with:

    Hash_CMAC_B_Digest = Hash_CMAC_B.digest()

to get the correct response.

**Comment by windsurfer1122** [comment]
Great.

One task left for me:
Check that all hashes can be updated, although .digest() was already called before.
As in my project I use .copy() as I am calculating hashes of different offsets and sizes, that overlap most of the time.
Example: First 128 bytes are the header followed by the CMAC, then much more data and at the end a CMAC of all data before (including previous CMACs).
Therefore I start a hash at offset 0, take an in-between digest after 128 bytes, update hash further and take a final digest at the end.

**Comment by windsurfer1122** [comment]
Just tested. When I use .digest(), then I cannot further update the hash, the next .digest() will return the same result, although the hash was updated was further bytes.
Is that behaviour related to the same bug()?

**Comment by Legrandin** [comment]
The `update()` method of CMAC should really be throwing an exception when called after `digest()` or `verify()`. This will be fixed in the upcoming release, together with the problem affecting `copy()` of CMAC. Put differently, in the current version it is not possible to do what you describe (update a little, compute digest, add more data, compute the new digest and so on - out of curiosity, is that how some existing protocol works?).

**Comment by frispete** [comment]
I also considered a similar strategy already, when dealing with huge amounts of data, where transmission is expensive, interleaving the data with hashes would allow early detection/recover.

How hard will be fixing this issue by allowing repeated digest()s from updated data?
Does it come with a significant cost apart from testing?

**Comment by Legrandin** [comment]
It is actually quite easy, and already possible for BLAKE2 for instance.
When creating the hash, one passes the flag `update_after_digest=True` to `new()`.

At that point, it becomes possible to interleave `update()` and `digest()`, with the digest value being correctly updated and without needing to create a copy.

**Comment by windsurfer1122** [comment]
> The update() method of CMAC should really be throwing an exception when called after digest() or verify(). This will be fixed in the upcoming release, ...

So, I will need .copy().digest() for CMAC in 3.7.1, while I can just use .digest() multiple times with the other hashes?
Or can CMAC be made consistent to the other hashes?

> ... - out of curiosity, is that how some existing protocol works?).

No, it's not.
It's just some packed data inside a file that contains multiple different hashes for different offsets and sizes.
My python script allows to compute multiple hashes for different offsets and sizes, but only reads/streams the file once.
I use a single hash per start offset to have a lean solution for all wanted sizes. This avoids bloating up the code to handle much more hashes for each offset/size combination and also reduces CPU load as less hashes are updated.

**Comment by Legrandin** [comment]
> So, I have to use .copy().digest() for CMAC in 3.7.1, while I can just use .digest() multiple times

Starting from v3.7.1, you can create a CMAC like this (setting `update_after_digest` to True):

    key = b'0' * 16
    cmac = CMAC.new(key, ciphermod=Cryptodome.Cipher.AES, update_after_digest=True)

And then incrementally update its state:

    cmac.update(b'First piece')
    print(cmac.hexdigest())
    >>> 3815e818f0157ae1e6d6f1bb5970b20d
    cmac.update(b'Second piece')
    >>> 106ee1c1bcab19a2b32b71f70af646fb

The snippet you provided when opening the issue will work as well.

> Or can CMAC be made consistent to the other hashes?

CMAC is now consistent with BLAKE2 and SHA3. Because of backward compatibility, not all hashes can make to behave in the same exact way.
