### ISSUE TITLE
Build fails on Solaris 11.4 (now using gcc)

### ISSUE THREAD

**Issue by dhiltonp** [Legrandin/pycryptodome#244]
Pycryptodome build fails on Solaris 11.4. They changed the compiler from Studio to gcc.

`pip-3.5 search pycryptodome` reports it's trying to install 3.7.2.
`cc --version` reports gcc 7.3.0.
Tested on [Oracle's provided VM](https://www.oracle.com/technetwork/server-storage/solaris11/downloads/vm-templates-2245495.html).

pkg search compiler only shows GCC C compilers as being available.

```
    # pip-3.5 install pycryptodome
..................
    building 'Crypto.PublicKey._fastmath' extension
..................
    cc -DNDEBUG -O -m64 -xO4 -xchip=generic -Ui386 -U__i386 -xregs=no%frameptr -xc99=all -mt -xc99=all -D_XOPEN_SOURCE=600 -D__EXTESIONS__=1 -D_XPG6 -KPIC -DPIC -preserve_argvalues=complete -xO5 -xtarget=opteron -xarch=sse2 -xcache=generic -DPYCRYPTO_LITTLE_ENDIN -DLTC_NO_ASM -Isrc/ -I/usr/include/python3.5m -c src/MD2.c -o build/temp.solaris-2.11-i86pc.64bit-3.5/src/MD2.o
    cc: error: unrecognized command line option ‘-mt’; did you mean ‘-t’?
    cc: error: unrecognized command line option ‘-KPIC’; did you mean ‘-fPIC’?
    cc: error: unrecognized command line option ‘-preserve_argvalues=complete’
    error: command 'cc' failed with exit status 1
   
    ----------------------------------------
Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vpu4q7ga/pycryptodome/setup.py';exec(compil(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p9ima6cj-recrd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vpu4q7ga/pycryptodoe/
```

**Comment by dhiltonp** [comment]
It looks like gcc packages were introduced in 11.2, I'm not sure but suspect they became default in 11.3.

**Comment by dhiltonp** [comment]
I see the same issues when I grabbed from source and did `setup.py install`.

compiler.compiler shows the compiler is gcc, and has these parameters that are failing.

It looks like these issues may be coming from distutils.ccompiler?

Compiler type shows up as 'unix'

**Comment by Legrandin** [comment]
This is indeed a `distutils` problem and can't be fixed by the library.
