### ISSUE TITLE
Why labeled as Beta?

### ISSUE THREAD

**Issue by danizen** [Legrandin/pycryptodome#247]
My employer is looking to move from CPython 3.5 on the developer desktops to CPython 3.6.   Some developers have MacOS, and some have Windows 10.   Long ago, I built PyCrypto into a binary windows wheel for CPython 3.5, but it was not easy.

So, of course, it seems like the right thing to do is to move to pycryptodome, especially as I am the primary user through an internal module that handles some secrets.

I am curious to understand therefore, because my employer is a federal agency, why pycryptodome is still labeled as Beta, and whether there are any areas I should be concerned with?

I use PBKDF2 and AES256, and I think some HMAC algorithms - SHA1 and SHA256, and that's all.

**Comment by Legrandin** [comment]
Moved to "Production/Stable" in version 3.8.0, it has mostly labeled as Beta until this point just because I didn't put too much value on the meaning of that classifier.

**Comment by danizen** [comment]
Thanks, even places that take classification generally quite seriously find
out that strong ontologies and value sets are not always used -
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6380228/
