### ISSUE TITLE
Is it possible to continue a SHA-1 calculation from the resulting digest?

### ISSUE THREAD

**Issue by windsurfer1122** [Legrandin/pycryptodome#248]
This is more a knowledge question that may lead to a usage question or a fetaure request:
There are files that have a SHA-1 digest stored at the end for all previous data. Now I want to calculate the SHA-1 of the complete file.
To avoid loading all data again (multiple GiBs) I wondered if it would be possible - in general - to take the existing SHA-1 digest and update it with the bytes of the file tail and receive the correct SHA-1?
Available are the SHA-1 digest itlsef and the number of bytes that lead to that digest. Would this allow to reproduce the state of the original SHA-1 calculation?

Below is a small Python code to show how the files look like:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
### ^^^ see https://www.python.org/dev/peps/pep-0263/

### Python 2 workarounds:
## a) prevent interpreting print(a,b) as a tuple plus support print(a, file=sys.stderr)
from __future__ import print_function
## b) interpret all literals as unicode
from __future__ import unicode_literals
## c) support bytes()
from builtins import bytes

import sys
import binascii

### Check pycryptodome/x version for CMAC error
### https://github.com/Legrandin/pycryptodome/issues/238
import Cryptodome.Hash
import Cryptodome.Cipher.AES

### Data
Data1 = bytes.fromhex("\
0e 6d 4f 6b cb d8 9c b8 16 1a 03 5d 47 a6 5b 45\
13 3e ae 07 51 b1 74 a9 40 17 32 30 fb 59 ae 19\
f8 c0 c2 a4 9b 4c ff 76 b9 7f ae da 5a a5 3f 51\
c6 6a 38 bc e3 53 08 d2 ed be 9a f0 bb 61 69 fd\
ef fe 1a fd 0e 77 5c b9 6e ce d3 ae 7d 3d eb 91\
34 06 74 f2 ba f6 90 5c 47 de 95 2c 87 74 c5 2a\
fa 1d 44 db 58 35 7f f3 93 77 d6 d2 f9 e9 9e 31\
28 f0 b8 47 77 0a f2 c8 dc 80 0b 2e 52 56 f7 28")
### Trailing SHA-1 of data
Data2 = bytes.fromhex("828da64d0263272e7fa9f0ab6de36f816b132ef3")

Expected_SHA1 = bytes.fromhex("aa320d5bc4cc9ee292455417d064bc4ba60af22b")

print ("Data length in bytes:", len(Data1), "+", len(Data2), "=", len(Data1)+len(Data2))
print ("Data1:", binascii.hexlify(Data1))
print ("Data2:", binascii.hexlify(Data2))
print ("Expected SHA-1 for Data1+Data2:", binascii.hexlify(Expected_SHA1))
print()

### SHA-1
Hash_SHA1 = Cryptodome.Hash.SHA1.new()
Hash_SHA1.update(Data1)
Hash_SHA1_Digest = Hash_SHA1.copy().digest()
print ("SHA-1 Data1:", binascii.hexlify(Hash_SHA1_Digest), "=", "Correct" if Hash_SHA1_Digest == Data2 else "Wrong!!!")
### QUESTION: can Data2 be used here and then just continue with updating? To avoid loading all data again.
Hash_SHA1.update(Data2)
Hash_SHA1_Digest = Hash_SHA1.copy().digest()
print ("SHA-1 Data1+Data2:", binascii.hexlify(Hash_SHA1_Digest), "=", "Correct" if Hash_SHA1_Digest == Expected_SHA1 else "Wrong!!!")
```

**Comment by Legrandin** [comment]
You describe a [length extension attack](https://en.wikipedia.org/wiki/Length_extension_attack), which SHA-1 is vulnerable too - though not directly in the form you need.

The old digest + data length allows you to compute a new hash of the concatenation of:
* the old data (w/o old hash)
* a fixed, short padding (dependent on the data length only)
* any arbitrary data you may want to append (e.g. the old digest)

So yes, it is theoretically possible, but not without introducing the fixed padding.

**Comment by windsurfer1122** [comment]
The old data is already always padded to a mulitple of 16/0x10 (maybe even 32/0x20). Would this already avoid that extra padding? Or does it depend on more or other factors?
Could a custom subclass of [Crypto.SHA1.SHA1_Hash](https://www.pycryptodome.org/en/latest/src/hash/sha1.html) provide this functionality?
Unfortunately I'm not experienced in coding cryptographic functions, I just use them.

**Comment by Legrandin** [comment]
The padding varies in length between 65 bytes and 128 bytes, depending of the amount of actual data you hashed. This can't be done in pure Python: it requires some change to the SHA1 C extension too.

**Comment by windsurfer1122** [comment]
Sorry, have to ask how to install that "lea-sha1" version of the pycryptodome**x** module via pip (on Windows)? Or do I have to do it manually? Links as answers would be suffcient.

**Comment by windsurfer1122** [comment]
Enhanced the pad function to make it work with bytes() and Python 2 on Debian:
`
#!/usr/bin/env python
# -*- coding: utf-8 -*-
### ^^^ see https://www.python.org/dev/peps/pep-0263/

### Python 2 workarounds:
## a) prevent interpreting print(a,b) as a tuple plus support print(a, file=sys.stderr)
from __future__ import print_function
## b) interpret all literals as unicode
from __future__ import unicode_literals
## c) support bytes()
from builtins import bytes

...

def sha1_lea_paddding(length):
    zero_byte = bytes.fromhex("00")
    ## Add 0x80 byte as first byte for padding
    padding = bytearray.fromhex("80")
    ## Calculate remaining bytes in 64 bytes block
    bytes_left = 64 - ((length+1) % 64)
    ## Restart a new block, if there is no space left for the 64 bit counter (=8 bytes)
    if (bytes_left < 8):
        padding.extend(zero_byte * bytes_left)
        bytes_left = 64
    ## Pad the block with 0x00 while leaving enough space for the 64 bit counter (=8 bytes) at the end
    if (bytes_left > 8):
        padding.extend(zero_byte * (bytes_left - 8))
    ## Add the 64 bit counter (=8 bytes) with the original length in bits at the end
    padding.extend(Cryptodome.Util.number.long_to_bytes((length * 8), 8))
    ## Python 3 only: padding.extend((length * 8).to_bytes(8, 'big'))

    return bytes(padding)

...
`
