### ISSUE TITLE
CTR-Mode incompatible to bouncycastle?

### ISSUE THREAD

**Issue by mchlnix** [Legrandin/pycryptodome#249]
I'm trying to interface with a Python-Server using `pycryptodome`. But encrypting plaintext in Java using `Cipher.getInstance("AES/CTR/NoPadding", "BC");` and trying to decrypt it in Python fails.

Also decrypting the same plaintext (16 0s) with the same key (16 0s) and counter value (16 0s) yields different results.

Are they using different nonces?

**Comment by Legrandin** [comment]
Can you show a sample of how you do CTR encryption in Java and in Python?
I also recommend to review this [piece of documentation](https://www.pycryptodome.org/en/latest/src/cipher/classic.html#ctr-mode) for the CTR mode of operation in PyCryptodome.

**Comment by mchlnix** [comment]
It must have something to do with the nonces, I think.

**Comment by mchlnix** [comment]
package com.company;

    import javax.crypto.Cipher;
    import javax.crypto.spec.IvParameterSpec;
    import javax.crypto.spec.SecretKeySpec;
    import java.security.Security;
    import java.util.Arrays;

    public class Main {

        public static void main(String[] args) throws Exception {
            Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());

            Cipher cipher = Cipher.getInstance("AES/CTR/NoPadding", "BC");

            SecretKeySpec keySpec = new SecretKeySpec(new byte[16], "AES");
            IvParameterSpec ivSpec = new IvParameterSpec(new byte[16]);

            cipher.init(Cipher.ENCRYPT_MODE, keySpec, ivSpec);

            System.out.println(Arrays.toString(cipher.doFinal(new byte[16])));
        }
    }

`[102, -23, 75, -44, -17, -118, 44, 59, -120, 76, -6, 89, -54, 52, 43, 46]`

**Comment by mchlnix** [comment]
from Cryptodome.Cipher import AES
    ctr = AES.new(bytes(16), AES.MODE_CTR, nonce=bytes(8))
    ctr.encrypt(bytes(16))

or

    from Cryptodome.Cipher import AES
    ctr = Counter.new(nbits=64, initial_value=0, prefix=bytes(8))
    ctr = AES.new(bytes(16), AES.MODE_CTR, nonce=bytes(8))
    ctr.encrypt(bytes(16))

`b'f\xe9K\xd4\xef\x8a,;\x88L\xfaY\xca4+.'` which is the same as above

I didn't set a `nonce` or an `initial_value` before, so I guess it was chosen at random? Or is something other than `0` chosen?

Either way, it works now. It might only be the default values. I can imagine you implemented something along the lines of non-repeating IVs, which BC might not have.

**Comment by Legrandin** [comment]
Closing. Added an entry for this in the FAQ.
