### ISSUE TITLE
install module in qpython for android

### ISSUE THREAD

**Issue by vlrizkidz** [Legrandin/pycryptodome#25]
is possibe install pycryptodome in python android ?
i got error not suport AES IN

**Comment by Legrandin** [comment]
Can you please paste the full console error you see?

**Comment by Legrandin** [comment]
Closing due to lack of feedback.

**Comment by Melab** [comment]
Reopening. I encountered an error when trying to run `pip.main(["install", "--no-dependencies", "pycryptodone])` in QPython3 on Android Pie. Is this project native code?

**Comment by Varbin** [comment]
@Melab Yes, this module uses C extensions. QPython does not have a compiler bundled which would be required to install Pycryptodome.
