### ISSUE TITLE
Module Crypto,Hash.SHA256 has no attribute hashFactory

### ISSUE THREAD

**Issue by ThePlasmaRailgun** [Legrandin/pycryptodome#256]
I'm attempting to use PyCryptoDome as a drop-in replacement for PyCrypto, but I'm running into the error: `AttributeError: module 'Crypto.Hash.SHA256' has no attribute 'hashFactory'`

**Comment by Legrandin** [comment]
It seems that `hashFactory` is not defined in the last release of PyCrypto (see https://github.com/dlitz/pycrypto), maybe it was in some earlier version?

I close this, because we only strive to offer backward compatibility with the latest update to PyCrypto.
