### ISSUE TITLE
TypeError: Object type <class 'str'> cannot be passed to C code

### ISSUE THREAD

**Issue by hikenshi** [Legrandin/pycryptodome#259]
Hello,
i got this error when using python 3.5
this is the code:
`from Crypto.Cipher import AES

key = '0123456789abcdef'
IV = 16 * '\x00'           # Initialization vector: discussed later
mode = AES.MODE_CBC
encryptor = AES.new(key, mode, IV=IV)

text = 'j' * 64 + 'i' * 128
ciphertext = encryptor.encrypt(text)`

This code run good on python 2.7

But python 3.5 it raise error: "TypeError: Object type <class 'str'> cannot be passed to C code"

I was change : key = '0123456789abcdef'  to key = b'0123456789abcdef'  or key = key.encode('utf-8') but that error still raise.
i also changed : text = 'j' * 64 + 'i' * 128 to text = ('j' * 64 + 'i' * 128).encode('utf-8') but still error.

Can anyone help?
Thanks

**Comment by Varbin** [comment]
Did you miss to encode the IV?

Full example:
```python
#!/usr/local/env python3
from Crypto.Cipher import AES

key = b'0123456789abcdef'
IV = 16 * b'\x00'  # needs to be encoded, too!
mode = AES.MODE_CBC
encryptor = AES.new(key, mode, IV=IV)

text = b'j' * 64 + b'i' * 128
ciphertext = encryptor.encrypt(text)

print(ciphertext)
```
Outputs for Python 3.6:
```
b'\x0f<\xe8\xef\x06\x8fc^\x929p\xfcY\xda\x1c,\x9b)\x1cE\xbf\xb6\xd4\xcfrz\xdd\xb4e\xc21\xc4\xae@\xc8A\nc\xef\xf3J5_~\x1bg-\xc4o6b[\xcafnP\xe0\xd6\x8e\xfa;D\xcf67\x8c\xd2\x863sB\ri\x0b\xf8\x828q\xd0\xf6U\xf7\x98F\xedG\xca\xf4\xd5\x12Y\xf2{\xd8Ni\x94t3\x00"\xe5\x7f\xc2\x94\xfaH\xe7{\xcc\xc7\x84\xa2\xb9#*\x83\xc0\xc0\x1c\xdd\xcf/\x90\x7f\x8b\xd7\x92K\xf3(\x9ec(\'\x9c\xb1\xc4\xb9\x83\xac\xeb\xf4\xdeb\x82\xdc\xd0&\x05\x1e#C\x8dZ}`\x983<\xbc\x15\xbby\xf3ln\x0baB&\xf0\x05\x97\xb4\xdes\xd9\x8a\xb7\x0e\xb8\xc0\x17\xda\n\xc5\xe1\xb0q \xa9'
```

**Comment by hikenshi** [comment]
Thank you,
It's work now :).

**Comment by saurabhrajiwade** [comment]
Python has package named pycryptodome which causes this error.just uninstall the package

sudo pip3 uninstall pycryptodome
