### ISSUE TITLE
Possible to encrypt data files i.e. .zip, .pdf, etc.?

### ISSUE THREAD

**Issue by Nobody912** [Legrandin/pycryptodome#260]
I've been using PyCryptodome for some time and I absolutely love how easy it is to use. Recently I have been trying to make a small CLI encryption utility based off PyCryptodome, but I ran into an issue encrypting files. 

tl;dr I can encrypt strings, but not files. How can I encrypt files?

**Comment by Legrandin** [comment]
You can read the input file in memory as a byte string and encrypt that, then write it back into the output file.
