### ISSUE TITLE
Import PEM with multiple headers

### ISSUE THREAD

**Issue by steinroe** [Legrandin/pycryptodome#261]
Hi,

I am trying to import a pem string with 

`key = RSA.import_key(pem, secret)`

and it throws 

```
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    key = RSA.import_key(pem, secret)
  File "C:\Users\D064914\AppData\Local\Continuum\anaconda3\lib\site-packages\Crypto\PublicKey\RSA.py", line 733, in import_key
    (der, marker, enc_flag) = PEM.decode(tostr(extern_key), passphrase)
  File "C:\Users\D064914\AppData\Local\Continuum\anaconda3\lib\site-packages\Crypto\IO\PEM.py", line 127, in decode
    raise ValueError("Not a valid PEM post boundary")
ValueError: Not a valid PEM post boundary
```

My PEM looks like the following when I print it with
`print(repr(pem))`

`'-----BEGIN ENCRYPTED PRIVATE KEY-----\nMIIE6zAdBMtIcwBrY+Xe+GHT\n-----END ENCRYPTED PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIIEKzC3ODGesF\n-----END CERTIFICATE-----\n'`

I deleted parts of the key as well as the certificate.

My first guess was that the newline characters cause problems, but this is not the case.

Best
Philipp

**Comment by Legrandin** [comment]
Your input contains not only a key, but also a certificate.
You should remove the latter by deleting everything starting at `-----BEGIN CERTIFICATE-----`.
