### ISSUE TITLE
Installing pycryptodome(x) in Raspbian Stretch no longer works

### ISSUE THREAD

**Issue by diogomsantos** [Legrandin/pycryptodome#264]
Running Raspbian Stretch, which is Debian Stretch compiled for armhf, and this no longer works:
`pip install --user pycryptodomex`

Returns this error:
```
  Could not find a version that satisfies the requirement pycryptodomex (from versions: )
No matching distribution found for pycryptodomex
```

This was working fine like 1 month ago at least. Installing pycryptodome returns the same error. Installing with pip3 works, but I need the python 2.7 version.

**Comment by LaGrop** [comment]
Is there a solution to the issue yet?

**Comment by LaGrop** [comment]
> Running Raspbian Stretch, which is Debian Stretch compiled for armhf, and this no longer works:
> `pip install --user pycryptodomex`
> 
> Returns this error:
> 
> ```
>   Could not find a version that satisfies the requirement pycryptodomex (from versions: )
> No matching distribution found for pycryptodomex
> ```
> This was working fine like 1 month ago at least. Installing pycryptodome returns the same error. Installing with pip3 works, but I need the python 2.7 version.

Is there a solution for this issue yet?

**Comment by Legrandin** [comment]
Can you please provide more details with:

    pip install --user -v pycryptodomex

I have tried that on Stretch with Python 2.7 and it completes successfully.

**Comment by Legrandin** [comment]
@diogomsantos Could you please confirm this is still a problem for you?

**Comment by diogomsantos** [comment]
Sorry for the late response, it still does not work for me. Here is the verbose output:
http://paste.debian.net/1074268/
It works with the following command:
`pip install --user https://github.com/Legrandin/pycryptodome/archive/v3.7.3x.tar.gz`

**Comment by Legrandin** [comment]
Your pi can only connect to piwheels.org and not to pypi:

    Could not fetch URL https://pypi.python.org/simple/pycryptodomex/: connection error: ("bad handshake: SysCallError(104, 'ECONNRESET')",) - skipping

However, piwheels.org only contains wheels for Python 3, so pip gives up for Python 2.
If you could somehow determine why your pi can't reach pypi and fix it, you would have solved the problem (which seems a generic one, not specific to pycryptodome).
