### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.pyd'

### ISSUE THREAD

**Issue by leileigong** [Legrandin/pycryptodome#268]
After exported by py2exe , execute it will output error message:
OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.pyd'

File "Crypto\PublicKey\RSA.pyo", line 38, in <module>
  File "Crypto\IO\PKCS8.pyo", line 44, in <module>
  File "Crypto\IO\_PBES.pyo", line 43, in <module>
  File "Crypto\Hash\MD5.pyo", line 47, in <module>
  File "Crypto\Util\_raw_api.pyo", line 299, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.pyd': cannot load library 'E:\TestTool\dist\ClientWin.exe\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'E:\\TestTool\\dist\\ClientWin.exe\\Crypto\\Util\\..\\Hash\\_MD5.pyd'

**Comment by Legrandin** [comment]
py2exe is fully untested, so it may well be it does not work. Could you use [pyinstaller](https://www.pyinstaller.org/) instead?

**Comment by leileigong** [comment]
yeah, i try pyinstaller, it works fine on pyinstaller.
Could you test and support py2exe?

**Comment by frispete** [comment]
> Could you test and support py2exe?

@leileigong Obviously, py2exe cannot locate all dependant modules. 

If you're really interested in py2exe support, you might be able to figure out, what Pyinstaller does, and implement that for py2exe as well. This is, how Open Source works after all.

**Comment by Legrandin** [comment]
Closing this, because adding support for py2exe should probably be done by logging a request at the py2exe project, not here. py2exe seems to be much less actively maintained than pyinstaller though, so using the latter remains the general recommendation anyway.
