### ISSUE TITLE
Questions about how to fill

### ISSUE THREAD

**Issue by zjcnew** [Legrandin/pycryptodome#269]
Why does Crypto.Util.Padding.pad and Crypto.Util.Padding.unpad not support zero padding?   and Why does Crypto.Cipher not support No padding for RSA?

**Comment by Legrandin** [comment]
> Why does Crypto.Util.Padding.pad and Crypto.Util.Padding.unpad not support zero padding?

Because you need a way for the receiver to know how long the padding is, and that requires sending that information.

> and Why does Crypto.Cipher not support No padding for RSA?

Because it is not secure.
