### ISSUE TITLE
EccKey object has no attribute 'desc'

### ISSUE THREAD

**Issue by sabersauce** [Legrandin/pycryptodome#272]
There may be a bug in lib/Crypto/PublicKey/ECC.py, Line 471
EccKey object has no attribute 'desc'
does it mean self._curve.desc?

**Comment by Legrandin** [comment]
Thanks. This is fixed on master with 12f008b2542edd6d48db997271b2b77b21726489.

**Comment by Legrandin** [comment]
Released in v3.8.1
