### ISSUE TITLE
Object type <type 'unicode'> cannot be passed to C code on python2.7 

### ISSUE THREAD

**Issue by leileigong** [Legrandin/pycryptodome#279]
I upgrade my Crypto2.6.1 to Pycryptodome 3.8.
but when i run it, i got an error `Object type <type 'unicode'> cannot be passed to C code`  while call `SHA256.new(u'000000')`
.

but on Crypto2.6.1,`SHA256.new` still can accept unicode string. 
Does this compatibility have been broken on Pycryptodome?

**Comment by Varbin** [comment]
Yes, this is intended because the implicit conversion between unicode to Python 2 strings (=raw bytes)  can be problematic.

If you want to convert between bytes/unicode explicitly call `u'000000'.encode('utf-8')` (replace `utf-8` with whatever encoding you want to use).

**Comment by leileigong** [comment]
yeah, i got it.
Thanks!
