### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GammaC0de** [Legrandin/pycryptodome#280]
Hi,
Is this piece of code (notice that `e` is 0 / unknown) is possible with pycryptodome?
With pycrypto is runs fine..
Is there any alternative?

```python
rsa = Crypto.PublicKey.RSA.construct((p*q, 0L, d, p, q))
decrypted = rsa.key._decrypt(encrypted)
```

**Comment by Legrandin** [comment]
That sounds like a bug in pycrypto. The public exponent (`e`) cannot be 0 - and for good reasons....
