### ISSUE TITLE
Get_random_bytes

### ISSUE THREAD

**Issue by Wintreist** [Legrandin/pycryptodome#283]
Hi, today I met with the library pycryptodome. And today I faced a problem. Function random.get_random_bytes generates bad bytes which do not allow to encrypt / decrypt data correctly. Now I will attach the generated bytes
b'(v)\x19\xae\xd6\xfe\x92\x1c(j)\x8b\x17\x9d\xb6\x01(#)\xf7(!)'
b'({$q)\x9d(AP)\xc5\(nI)\xb1\xae(*)\xa9(H)\xa6(l)'
the fact that badly generated I have highlighted in brackets

**Comment by Varbin** [comment]
Were is the problem? If you mean that 'printable' (alphabetical, numerical, punctuation...) are not good for encryption: They are, as they represent a byte like every other character in your generated strings.

**Comment by Wintreist** [comment]
I agree with you, but after encryption -> decryption I need to somehow decode the resulting bytes into Unicode, however utf-8, 16, 32 does not cope with this.

> Where is the problem? If you mean that 'printable' (alphabetical, numerical, punctuation...) are not good for encryption: They are, as they represent a byte like every other character in your generated strings.

**Comment by Varbin** [comment]
@Wintreist Do you mind sharing your code? As I've used the library before, I know encryption and decryption does work.

**Comment by Wintreist** [comment]
@Varbin Yes, of course, it's just a test, but it doesn't work either. At first I thought the AES encryption was to blame, until I looked at what get_random_bytes generates
`from Cryptodome.Cipher import AES
from Cryptodome import Random

text = b'Hello, World'
AESkey = Random.urandom(16)
print(AESkey)


def encrypt(message, key):
    chiper = AES.new(key,AES.MODE_EAX)
    crypt = chiper.encrypt(message)
    return crypt

def decrypt(message, key):
    chiper = AES.new(key,AES.MODE_EAX)
    print(message)
    decrypt = chiper.decrypt(message)
    print(decrypt)
    decrypt = decrypt.decode('utf-8')
    print(decrypt)


#cryptmess = encrypt(text, AESkey)
#decrypt(cryptmess, AESkey)`

**Comment by Varbin** [comment]
EAX mode needs a nonce (or was it an IV?). As you don't supply one, a random one is generated on each instantiation of the AES class i.e. multiple calls of encrypt(..., ...) with the same message and key should lead to different output.
For decryption, the same nonce is required, or the decrypted text is not readable.

**Comment by Wintreist** [comment]
Thanks, I will try

**Comment by Wintreist** [comment]
Thanks, I did it
