### ISSUE TITLE
PKCS1_v1_5 and pkcs1_15 got different result

### ISSUE THREAD

**Issue by atlantis414** [Legrandin/pycryptodome#284]
ubuntu 16.04 x64 
pycryptodome 3.7.2
`
import base64

from Crypto.Hash import SHA, SHA1, MD5
from Crypto.PublicKey import RSA
from Crypto.Signature import pkcs1_15, PKCS1_v1_5

'https://www.pycryptodome.org/en/latest/index.html'

PrivateKey = '''MIICXAIBAAKBgQCt7neb4kMvhZ8SjeMptfJliD7dChNddpow7i3DJ9KMQ6iFMYez
mbrpJqJLZhXWlMj+Tf0fVhTnEB6636N/RPsjB1vUvXUwl6bAxsIai6vqZNBVJQPT
ihDOgP46zuJMHf4+o0Yrbobut7WSfFdZvkV+peiojlSBoNS0I4mmrUEHOQIDAQAB
AoGAGrQ4LPjKM+uiBqk+LVNAChKnBCzd2EWzWrvWztW4X8yrfPejzBFYPx+tX0In
LDDfwxuaN0tyHh+9eBeJ9KpUnEUu7WHNizi6nq7eM9iR3qB75/9fQpPIodP7r2CO
iq0Tj1QgwypEJiRWmfRorc5JU8OUugxcYhmrQ/JPQgCXLXkCQQDC42BPAGxxYWZx
fynmtlkkMLaZn0ytTnS09OjYvpR+Q6VKOiykL66RasIE5ddCBrDsifQsgnSWdo4H
Fd6XGsALAkEA5HjL7yuefO5n+66k9Z5SJYoVOb3uo+Pxxf5YauvqnrSIkFsjgLp3
CqSeN8VPoIxMqGm0gdDebc/vufXImWbMSwJAW8ZTfiCG8MWbRmtJwhmw1LgT5Tf9
FcfScby7QgZNS0BzwAaxKwhBPr11bHUH71HTUzCLycINQSXHMFL+JU41jQJBAJtU
NPHp6dpuC2vlFGmYtain9D5JjtEFy/4cKeinc99qRd4+2ChQnVYzDQ5FqxkvyX5G
P15yroZh9E2teDAy33kCQADrSg3Zyuhfh2UFKbmKXdZiLm2t4g1mVumqZFTdLze8
YmOgxjhI72+pldu1v6ttQu4lvKurD7E2xbnenUZsLMA='''

PublicKey = '''MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCt7neb4kMvhZ8SjeMptfJliD7d
ChNddpow7i3DJ9KMQ6iFMYezmbrpJqJLZhXWlMj+Tf0fVhTnEB6636N/RPsjB1vU
vXUwl6bAxsIai6vqZNBVJQPTihDOgP46zuJMHf4+o0Yrbobut7WSfFdZvkV+peio
jlSBoNS0I4mmrUEHOQIDAQAB'''

def RSA_Sign(message, privatekey):
    privatekey = base64.b64decode(privatekey)
    # rsakey = RSA.importKey(open('master-privatekey.pem').read())
    rsakey = RSA.importKey(privatekey)
    signer = PKCS1_v1_5.new(rsakey)
    hash = SHA1.new(message.encode('utf-8'))
    signature = base64.b64encode(signer.sign(hash))
    return signature

def RSA_Verify(message, publickey, signature):
    publickey = base64.b64decode(PublicKey)
    # rsakey = RSA.importKey(open('master-publickey.pem', 'r').read())
    rsakey = RSA.importKey(publickey)
    hash = SHA1.new(message.encode('utf-8'))
    verifier = PKCS1_v1_5.new(rsakey)
    ret = verifier.verify(hash, base64.b64decode(signature))
    return ret

if __name__ == '__main__':
    message = 'To be signed'
    signature = RSA_Sign(message, PrivateKey)
    print(signature)
    ret = RSA_Verify(message, PublicKey, signature)
    print(ret)
`

Use PKCS1_v1_5 to get results true
Use Pkcs1_15 to get results None
Can't these two classes be replaced with each other?

**Comment by minibear0523** [comment]
I came across the same problem that is `pycrypto.Signature.PKCS1_V1_5` result is different from `pycryptodome.Signature.pkcs1_15` result. Did you get the reason? @atlantis414

**Comment by Legrandin** [comment]
@minibear0523 Can you please post an example that reproduces this behaviour?

**Comment by minibear0523** [comment]
> @minibear0523 Can you please post an example that reproduces this behaviour?

```python
import base64
import logging
from Crypto.Hash import MD5
from Crypto.PublicKey import RSA
from Crypto.Signature import pkcs1_15
from Crypto.Signature import PKCS1_v1_5

class RsaUtil(object):
    public_key, private_key = None, None
    password = '123456'

    def __init__(self):
        self.import_public_key()
        # self.import_private_key()

    def create_sign(self, encrypt_str):
        """
        私钥加签
        :return:
        """
        hash_obj = MD5.new(encrypt_str.encode())
        # 改用PKCS1_v1_5
        return base64.b64encode(PKCS1_v1_5.new(self.private_key).sign(hash_obj))

    def verify_sign(self, encrypt_str, signature):
        """
        公钥验签
        :param encrypt_str:
        :param signature:
        :return:
        """
        b_encrypt_str = encrypt_str.encode()
        # print(f'byte encrypt str {b_encrypt_str}')
        hash_obj = MD5.new(b_encrypt_str)
        decode_sign = base64.b64decode(signature)
        # print(f'decode sign {decode_sign}')

        try:
            # 改用PKCS1_v1_5
            PKCS1_v1_5.new(self.public_key).verify(hash_obj, decode_sign)
######### FOLLOWING CODE RESULT THROW AN ERROR #########
            pkcs1_15.new(self.public_key).verify(hash_obj, decode_sign)
        except (ValueError, TypeError) as e:
            print(f'signature invalid, error {e}')
            return False
        return True

    @staticmethod
    def encrypt_str(params):
        """
        参数拼接
        :param params:
        :return:
        """
        params_list = []
        for k, v in params.items():
            params_list.append(f'{k}\'{v}')
        return '^'.join(params_list)

    def import_public_key(self):
        """
        导入公钥
        :return:
        """
        # 导入平台公钥
        self.public_key = self.import_key('my_rsa_public_platform.pem')

    def import_private_key(self):
        """
        导入私钥
        :return:
        """
        self.private_key = self.import_key('my_private_rsa_key.pem', self.password)

    @staticmethod
    def import_key(file_path, passphrase=None):
        """
        导入key
        :return:
        """
        return RSA.import_key(open(file_path).read(), passphrase=passphrase)

    def create_rsa_key(self):
        """
        生成密钥对
        :return:
        """
        key = RSA.generate(2048)
        encrypt_key = key.exportKey(passphrase=self.password, pkcs=8, protection='scryptAndAES128-CBC')
        with open('my_private_rsa_key.pem', 'wb') as f:
            f.write(encrypt_key)

        with open('my_rsa_public.pem', 'wb') as f:
            f.write(key.publickey().exportKey())


if __name__ == '__main__':
    rsa_util = RsaUtil()
    params = {
        'name': '张三',
        'sex': '男',
        'score': 86
    }
    encrypt_str = rsa_util.encrypt_str(params)
    print(f'encrypt_str {encrypt_str}')
    # 平台签名示例签名结果
    signature = 'E2s8Ma7l7JMK1t4ClitZxY/1sZO2WIVw+qsPppumMV4aCqgHYoXv8gGSockMfcPt03w0FWZPot4J79iOL1f3LgJ+etEV8hUZfMl+MkGsL2Sy5nP9olQYBKxH2mZjUNBfIIktGRwwscASJhW+3AcIKXcPynBqPJDPkgQgfw91uqvkSq0aGeUj4Jji4MRYZR7e2w3ztxyFAVJvRNa3wILjDECUfZo6aUx29ndqndKUX+mdgLyLSGCbv+Iz06ScYenCfjfscMcc8jWRT2aRvyuGhXd4tlStErCSai9TGxXwq5G02l1H4ubOtbr19ii0aOfYE2ua6V0ovl5JQy4o8wCHAA=='

    is_passed = rsa_util.verify_sign(encrypt_str, signature)
    print(f'is passed {is_passed}')
```
The public key is:
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzBIK71iLhfauIPG7ebZc
i86gjhQ9NtzZPTmQYn0MCz905Al2XHndQOy45fkIVA9aRo/fvDmOhYmG/9wN3hRI
DTsFvRdIOKG7A7fVYF00TUZtuszDk3MwvM2dFsf+9giQOAR2S83KeRHREyb6vIRD
eGDqMX1AJfpN5rYuzEZeqZrnig9BawFQ1pbuDtOK5u0gWz6hXZSt9vBHc7BaieDe
Nkh/GxW86fvcdPmpZTvAZAqE75K7u85+KEmKnJVm2UMxrtQYqO0utItUPAsesULm
93Q4PPFCW9Mfex8HlvvnU13NhOW1SkKa1ktkiQQUTdf7Rhor80tccg5F75Guk4Yf
2wIDAQAB
-----END PUBLIC KEY-----
```

I write this code for interact with another existing system which is written in Java, and the `signature` in main func and `public key` are provided by their developers, but `pycrypto` and `pycryptodome` got different result.

Thanks a lot.

**Comment by Arrow-Li** [comment]
I got the same problem, `PKCS1_v1_5.new(rsa_key).verify` is pass but `pkcs1_15.new(rsa_key).verify` raise a ValueError
