### ISSUE TITLE
the block size of MD2 must be 16 according to rfc 1319

### ISSUE THREAD

**Issue by jllin3029** [Legrandin/pycryptodome#285]
The block size of MD2 must be 16 according to rfc 1319, not 64.
Need modify block_size from 64 to 16 in MD2.py.

**Comment by jllin3029** [comment]
The error log is shown below:
>>> from Crypto.Hash import MD2, HMAC
>>> from Crypto.Cipher import AES
>>> pin_code=b'ASD129'
>>> random_number = b'ABCDEFGHIJKLMNOP'
>>> h = HMAC.new(pin_code, random_number+pin_code, MD2)
>>> security_key = h.digest()
>>> from Cryptodome.Hash import MD2, HMAC
>>> from Cryptodome.Cipher import AES
>>> h = HMAC.new(pin_code, random_number+pin_code, MD2)
>>> security_key2 = h.digest()
>>> print(security_key)
b'a\xcf|\xad2\x16\xe7W_?\xe7\xec\x0c<\xd0\x03' # right result from pycrypto
>>> print(security_key2)
b'E0\xe0\xb2HX\xa0G\xa6\xf4\x17\xce\xca{\xbcT' # wrong result from Pycryptodome

**Comment by Legrandin** [comment]
Fixed with e99deccdf9acc369e600c61b18fa5ee5010ab1a2
