### ISSUE TITLE
Support for building/installing without OCB things

### ISSUE THREAD

**Issue by ignatenkobrain** [Legrandin/pycryptodome#29]
Unfortunately that license is not fully free and we can't package it in Fedora (I guess, same for other distros like Debian).

Would be nice if we can get some option which will not build/install such code.

**Comment by Legrandin** [comment]
I certainly considered that because OCB is indeed controversial to many, but never found this to be a big enough problem myself - I may add this in the next version.

Can you point me to any Fedora policy that explains how OCB wouldn't be "fully free"?
I am a bit puzzled because OCB is also implemented in [mosh](https://mosh.org/), which Fedora is shipping today.

**Comment by ignatenkobrain** [comment]
> Can you point me to any Fedora policy that explains how OCB wouldn't be "fully free"?
As far as I understand OCB can't be used in military which means it's not completely "free".

> I am a bit puzzled because OCB is also implemented in mosh, which Fedora is shipping today.
That might be a problem (probably someone just didn't see it there). I will check more carefully what's going on there.

**Comment by ignatenkobrain** [comment]
raised thread at Fedora Project legal ML: https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/PPJTMAQITOAHHTAYXEWWMX6NHPLUZDFL/

**Comment by ignatenkobrain** [comment]
just checked openssl in Fedora, we strip OCB from there, so I think maintainer of mosh violates our guidelines.

@Legrandin so would be nice to add such option anyway.

**Comment by Legrandin** [comment]
> As far as I understand OCB can't be used in military which means it's not completely "free".

Maybe you refer to [license 2](http://web.cs.ucdavis.edu/~rogaway/ocb/license2.pdf), one of the three available for OCB. In [license 1](http://web.cs.ucdavis.edu/~rogaway/ocb/license1.pdf), any use is permitted (including related to military purposes), but only for an open source implementation, which I think is the applicable case here.

**Comment by ignatenkobrain** [comment]
@Legrandin most probably yes, so I suppose I was wrong.

**Comment by Legrandin** [comment]
Closing the issue, as license 1 of OCB seems to cover all intended usages.
