### ISSUE TITLE
Problem in documentation for Triple DES

### ISSUE THREAD

**Issue by jachymb** [Legrandin/pycryptodome#292]
There is the following example in documentation for DES3 https://pycryptodome.readthedocs.io/en/latest/src/cipher/des3.html

    >>> from Crypto.Cipher import DES3
    >>> from Crypto.Random import get_random_bytes
    >>>
    >>> # Avoid Option 3
    >>> while True:
    >>>     try:
    >>>         key = DES3.adjust_key_parity(get_random_bytes(24))
    >>>         break
    >>>     except ValueError:
    >>>         pass
    >>>
    >>> cipher = DES3.new(key, DES3.MODE_CFB)
    >>> plaintext = b'We are no longer the knights who say ni!'
    >>> msg = cipher.nonce + cipher.encrypt(plaintext)

However when I run this, I get the following error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'CfbMode' object has no attribute 'nonce'

Perhaps the documentation is outdated? I am using version `pycryptodome==3.8.1`

**Comment by Legrandin** [comment]
Thanks, it is fixed now.
