### ISSUE TITLE
Version 3.8.2 of pycryptodomex on pypi.org is missing windows wheels

### ISSUE THREAD

**Issue by TonyBeswick** [Legrandin/pycryptodome#293]
Version 3.8.2 of pycryptodomex on pypi.org is missing windows wheels: 
https://pypi.org/project/pycryptodomex/3.8.2/#files

Version 3.8.1 has them: https://pypi.org/project/pycryptodomex/3.8.1/#files

Also pycryptodome 3.8.2 has them: https://pypi.org/project/pycryptodome/3.8.2/#files

This causes the following error when trying to install pycrytodomex on windows without a compiler:

`distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27`

**Comment by Legrandin** [comment]
Thanks for reporting. Wheels for Windows are up too now.

**Comment by TonyBeswick** [comment]
Brilliant! Thanks @Legrandin
