### ISSUE TITLE
raise ValueError("Triple DES key degenerates to single DES")

### ISSUE THREAD

**Issue by leileigong** [Legrandin/pycryptodome#297]
when i create an 3DES instance, i got error `ValueError: Triple DES key degenerates to single DES`

Here is my code :
`cipher = DES3.new(MDK, DES3.MODE_ECB)`

`MDK` is 00000000000000000000000000000000 ( 0x00 of 16 bytes.)

I find some code in 3DES.py.
```
    if key_out[:8] == key_out[8:16] or key_out[-16:-8] == key_out[-8:]:
        raise ValueError("Triple DES key degenerates to single DES")
```

So I could use if the key is degenerated?
Thanks!

**Comment by leileigong** [comment]
i try this, it works:

```
        if MDK[:8] == MDK[8:16] and MDK[-8:] == MDK[8:16]:
            cipher = DES.new(MDK[:8], DES.MODE_ECB)
        elif MDK[:8] == MDK[8:16]:
            cipher = DES3.new(MDK[8:], DES3.MODE_ECB)
        elif MDK[-8:] == MDK[8:16]:
            cipher = DES3.new(MDK[:-8], DES3.MODE_ECB)
        else:
            cipher = DES3.new(MDK, DES3.MODE_ECB)
```

**Comment by Legrandin** [comment]
This is intended behaviour. Not all 3DES keys are strong: some degenerate into weak Single DES key, so that check exists to weed them out.

**Comment by jeremyherbert** [comment]
FWIW, this is problematic as some cryptographic devices (smartcards and NFC) ship in their blank state, for legacy reasons, with a default 3DES key of all zeros. You are supposed to use this key only once during initial provisioning and then use it upgrade the key to something like AES (and disable 3DES).

This is even true of some brand new (as of 2022) crypto devices that come from one of the largest crypto semiconductor manufacturers of the planet. It would be helpful if there was an argument (even a hidden one) which was something like "i_understand_the_risks_seriously_please_let_me_use_a_degenerate_key_this_one_time=True".
