### ISSUE TITLE
Unable to extend to Brainpool DP

### ISSUE THREAD

**Issue by l1980** [Legrandin/pycryptodome#301]
While working to extend the supported domain paramters to Brainpool curves, during the initialization of generator G ECCPoint I surprisingly have that "The EC point does not belong to the curve". WTF ??

[__init__.txt](https://github.com/Legrandin/pycryptodome/files/3301446/__init__.txt)

**Comment by Legrandin** [comment]
Currently, there is only support for curves defined by the equation  y^2 = x^3 + A*x + B, with A=-3 (that is, NIST curves).

Brainpool curves use other values for the A coefficient.
