### ISSUE TITLE
Docs inconsitency

### ISSUE THREAD

**Issue by Zwork101** [Legrandin/pycryptodome#302]
According to the docs, AES support keys with byte lengths 32, 48, and 64. https://github.com/Legrandin/pycryptodome/blob/master/Doc/src/cipher/aes.rst

However, the actual requirements are 
```py
# Size of a key (in bytes)
key_size = (16, 24, 32)
```
https://github.com/Legrandin/pycryptodome/blob/95ccce7ae82d3a36f1a8652dd2c645222d0128dd/lib/Crypto/Cipher/AES.py#L250

**Comment by Zwork101** [comment]
miss click sorry

**Comment by Legrandin** [comment]
Can you elaborate on where you see  byte lengths 32, 48, and 64?

**Comment by Zwork101** [comment]
Can I just say I've been working on this for too long? I apologise, I divided by 4 instead of 8. Sorry to bother you.
