### ISSUE TITLE
Compiling pycryptodome package without OCB support

### ISSUE THREAD

**Issue by ICKGeek** [Legrandin/pycryptodome#303]
Hi Team,

We want to use pycryptodome package without OCB cipher mode support. Is there anyway I can compile this package without this support. The reason for this is, we want to use this package without OCB license terms.

FYI, we are planning to use this pycryptodome package in our product which is not open source

Thanks

**Comment by Legrandin** [comment]
Are you aware that [one OCB license](https://web.cs.ucdavis.edu/~rogaway/ocb/license2.pdf) allows you to use OCB also in non-open source software (unless the closed source app is used for military purposes)?

**Comment by ICKGeek** [comment]
This will get packaged and shipped in our product. Our product can be used by military also. So I think we might see some complexities.
I am also looking at option of reverting the files that does OCB encryption from pycryptodomex package and use it in our product. Does this help in avoiding OCB license restrictions for us?

**Comment by Legrandin** [comment]
I am happy to take in patches - but I have no time to implement this and it is not going to help other open source projects. Closing.

**Comment by ICKGeek** [comment]
My idea was not ask you to apply patches. I am planning to do it myself and just wanted to check whether it is fine to do or not and by doing so (removing OCB usage), I can remove the OCB license restriction also, right?

**Comment by Legrandin** [comment]
Yes, if you do not distribute the files `src/raw_ocb.c`, `lib/Crypto/Cipher/_mode_ocb.py` and any compiled version, the OCB license stops being applicable.

**Comment by ICKGeek** [comment]
Ok. Thanks for the reply and confirmation. I will remove above two files and also the corresponding test file (lib/Crypto/SelfTest/Cipher/test_OCB.py) and distribute it in our software.
