### ISSUE TITLE
SelfTest

### ISSUE THREAD

**Issue by 1271** [Legrandin/pycryptodome#306]
https://github.com/Legrandin/pycryptodome/tree/master/lib/Crypto/SelfTest

Hi. Just wondering.
Is there a real need to publish a directory on the pip site?
SelfTest is 70% of the package size.
It looks weird to me.

Thank you

**Comment by frispete** [comment]
Given the complexity, topic and scope of this package, than I vigorously say: yes!

In fact, we're running the tests on **each and every** build for openSUSE and derivates:

https://build.opensuse.org/package/show/devel:languages:python/python-pycryptodome

If you want to split the package, why not do it in your own fork, and send pull requests?

**Comment by nedbat** [comment]
You could offer the SelfTest as an extra so that people who want it can get it, others wouldn't install it.

**Comment by ScottSturdivant** [comment]
If you're open to SelfTest as an extra, I can give this a try.

My use case is that I'm installing on an embedded device and the ~ 33.6MB that the self tests consume ~33% of the available space.

**Comment by 1271** [comment]
@ScottSturdivant 
SelfTest is used for tests only. You can remove it from the build by simply deleting the lines from packages https://github.com/Legrandin/pycryptodome/blob/649d981b84eeb1c1a7edb96ba796aad079a0de31/setup.py#L252-L261
But then you will no longer be able to run tests for the package at the client
