### ISSUE TITLE
No support for IV in AES.MODE_CTR... why?

### ISSUE THREAD

**Issue by cwebber** [Legrandin/pycryptodome#313]
In other applications in other languages, I'm passing in an initialization vector for aes+ctr... however pycryptodome doesn't allow this.  I can't figure out why.

It seems pretty well understood from other searches I can find online that support for an IV in aes+ctr is [expected](https://crypto.stackexchange.com/a/1570)

**Comment by Legrandin** [comment]
Yes, IV is supported, with the caveat that NIST does not use the term "IV" but "nonce", and we follow that reference.
These parts of the documentation can be helpful:

https://www.pycryptodome.org/en/latest/src/cipher/classic.html#ctr-mode
https://www.pycryptodome.org/en/latest/src/faq.html#is-ctr-cipher-mode-compatible-with-java

**Comment by cwebber** [comment]
Thanks!  I didn't realize it was a synonymn.

Closing!
