### ISSUE TITLE
Too much dependencies?

### ISSUE THREAD

**Issue by ghost** [Legrandin/pycryptodome#314]
I had a project which imported and used Pycryptodome. But I had to make executable for Windows and used PyInstaller to do so. PyInstaller generated a very  big .exe file (32MB) due to the fact that by importing Pycryptodome it also had to import numpy, scipy and a lot of big dependencies.

I switched from Pycryptodome to cryptography, which doesn't seem to use so much dependencies, and the resulting file is much smaller (8MB), while libraries such as numpy and scipy are not included.

Are those big dependencies absolutely necessary for Pycryptodome?

**Comment by Legrandin** [comment]
PyCryptodome doesn't have any dependency. The difference in size you see (7/8MB) is due to test vectors: the `pycryptodome` package includes them, whereas `cryptography` has them in a separate package.

**Comment by frispete** [comment]
> The difference in size you see (7/8MB) is due to test vectors: the pycryptodome package includes them

..which should be easy enough to get rid of during PyInstaller packaging.

To be fair, you should be aware, that the feature set of `cryptography` highly depend on the `openssl` version used, which in turn creates a three way dependency between `openssl` as used by `Python`, `openssl` and `cryptography`, whereas the feature set of pycryptodome is constant (depends on its own version only…).

Sure, you can link `cryptography` with your own `openssl` build, but that opens another can of worms, I'm afraid...

**Comment by frispete** [comment]
A PR with custom setup option --omit-testvectors would be cool.

**Comment by brezniczky** [comment]
Wish I had the time to have a go at that right now! I found this thread as I was also thinking about reducing the deployment size ... I am only using one encryption (AES), I *guess* I am not too unique in that, but not sure. 

Do you think there is any visible demand/obvious reason/etc. to suggest
a) that I am not alone with such customization needs (keeping support for only 1...a few cryptographic methods)
b) that such customization could contribute to a noticeable overall size reduction?

(Thank you! Absolutely no promises yet, but I might be able to give a hand later on.)

**Comment by Legrandin** [comment]
This is now fixed in version 3.10.1, most test vectors are in a separate package.
