### ISSUE TITLE
FFI implicit cast warning from SHA256

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Legrandin/pycryptodome#32]
Full warning message: 
"/venv/lib/python3.5/site-packages/Cryptodome/Hash/SHA256.py:116: 
UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
[18:27:59][Step 1/1]   bfr)"

**Comment by malina-kirn** [comment]
I get the same warning using the PKCS1_OAEP cipher to encrypt:
```
.../lib/python2.7/site-packages/Crypto/Util/strxor.py:60: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  _raw_strxor.strxor(term1, term2, result, c_size_t(len(term1)))
```

**Comment by Legrandin** [comment]
Thanks for reporting. The fix is on master and will soon end up in a point release.

**Comment by nueverest** [comment]
I'm still seeing this for py2.7, py3.5, and py3.6

> SHA256.py:116: UserWarning: implicit cast from 'char *' to a different p
> ointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
>     bfr)
