### ISSUE TITLE
AES Cipher digest raises a TypeError (Python 3.7)

### ISSUE THREAD

**Issue by matngo** [Legrandin/pycryptodome#321]
Hello,

The following code snippet: 

```python
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
data = b"123"
key = get_random_bytes(16)
cipher = AES.new(key, AES.MODE_EAX)
ciphertext, tag = cipher.encrypt_and_digest(data)
```

raises the following error:

```
Traceback (most recent call last):
  File "test_crypto.py", line 7, in <module>
    ciphertext, tag = cipher.encrypt_and_digest(data)
  File ".../Crypto/Cipher/_mode_eax.py", line 346, in encrypt_and_digest
    return self.encrypt(plaintext, output=output), self.digest()
  File ".../Crypto/Cipher/_mode_eax.py", line 261, in digest
    tag = strxor(tag, self._omac[i].digest())
  File ".../site-packages/Crypto/Hash/CMAC.py", line 210, in digest
    pt = strxor(strxor(self._last_ct, partial), self._k2)
TypeError: argument 2 must be bytes, not bytearray
```

with python 3.7.2 but works with python 3.6.7 ; with pycryptodome>3.7

Changing following snippet: 

https://github.com/Legrandin/pycryptodome/blob/c8bd2affb53d72aa41b6793608a7c4c35807d34d/lib/Crypto/Hash/CMAC.py#L210

to

```python
 pt = strxor(strxor(self._last_ct, bytes(partial)), self._k2)
```

seems to solve the issue for me.

Thanks!
Mathias

**Comment by Legrandin** [comment]
When you see this error, could you run `pip uninstall pycrypto` and then try again? 

The old PyCrypto shipped with a `strxor` module written as a native library (.so or .dll file). If you install both `pycrypto` and `pycryptodome`, the native module will take priority over the Python extension that comes in the latter. Unfortunately, there is no clear solution for this problem...

**Comment by matngo** [comment]
Thanks for your quick answer.

I installed pycryptodome on an empty virtual environment and still had the
same issue. I'm not sure if it is the same as un installing and
reinstalling and I'll be sure to try and come back to you.

Le jeu. 29 août 2019 à 17:27, Helder Eijs <notifications@github.com> a
écrit :

**Comment by Legrandin** [comment]
To see exactly what is being loaded (a `.py` or  `.so/.dll` file) you can do:

    from Crypto.Util.strxor import strxor
    print(strxor)

You should get something like (note it is a `.py` file):

    <module 'Crypto.Util.strxor' from '/home/he/pycryptodome/ve3/lib64/python3.7/site-packages/Crypto/Util/strxor.py'>

**Comment by matngo** [comment]
I tried uninstalling and reinstalling and everything works.

Thanks for the assistance!
