### ISSUE TITLE
Sign message with static nonce?

### ISSUE THREAD

**Issue by 766F6964** [Legrandin/pycryptodome#323]
To demonstrate a crypto attack/weakness I need to sign two messages with the same (static) nonce.
The documentation tells me there are two different modes one can supply during signing: `fips-186-3` and `deterministic-rfc6979`.
Furthermore one can supply a _randomfunc_ during signing. To quote from the docs:
```
A function that returns random byte strings, of a given length. 
If omitted, the internal RNG is used. Only applicable for the ‘fips-186-3’ mode.
```
For `fips-186-3` we can use our own random function, it seems.
So my idea was to use this to generate a static nonce:
```python
def bad_nonce(length):
    return "1337"

verifier = DSS.new(key, 'fips-186-3', randfunc=bad_nonce)
msg_hash = SHA256.new(message)
```
This results in an exception during signing:
```
  File "/usr/lib/python3.7/site-packages/Crypto/Signature/DSS.py", line 100, in sign
    nonce = self._compute_nonce(msg_hash)
  File "/usr/lib/python3.7/site-packages/Crypto/Signature/DSS.py", line 290, in _compute_nonce
    randfunc=self._randfunc)
  File "/usr/lib/python3.7/site-packages/Crypto/Math/_IntegerBase.py", line 389, in random_range
    randfunc=randfunc
  File "/usr/lib/python3.7/site-packages/Crypto/Math/_IntegerBase.py", line 341, in random
    msb &= (1 << significant_bits_msb) - 1
TypeError: unsupported operand type(s) for &=: 'str' and 'int'
```
How can I sign two messages with the same nonce?

**Comment by 766F6964** [comment]
I figured out a way to do it:
```python
def bad_nonce(N):
    return b"\x01\x02\x03\x04\x05"

sig_provider = DSS.new(key, 'fips-186-3', encoding='der', randfunc=lambda _: bad_nonce(5))
```
Please let me know if there is a better way to do this. But this, for now, yields the same `r` in my signature(s) which is exactly what I want.

**Comment by Legrandin** [comment]
You are definitely on the right track. I would use [SHAKE128](https://www.pycryptodome.org/en/latest/src/hash/shake128.html) to build a proper seedable PRNG:

    from Crypto.Hash import SHAKE128, SHA256
    from Crypto.Signature import DSS
    from Crypto.PublicKey import ECC

    class PRNG:
        def __init__(self, a=b''):
            self._s = SHAKE128.new(a)
        def __call__(self, n):
            return self._s.read(n)
    
    key = ECC.generate(curve='p256')
    signer = DSS.new(key, 'fips-186-3', randfunc=PRNG(b'seed'))
    msg_hash = SHA256.new(b'hello')
    sig = signer.sign(msg_hash)
    print(sig)
