### ISSUE TITLE
Alternative public-key ciphers to RSA?

### ISSUE THREAD

**Issue by pakal** [Legrandin/pycryptodome#339]
Hello,

I would like, for the hybrid encryption system of the Witness Angel (https://github.com/WitnessAngel), to protect the symmetric keys used with several layers of encryption, using different kinds of public key systems (based on different mathematical problems), not just RSA.

I've seen in the repo a (legacy) ElGamal public key system, but without public methods to encrypt/decrypt actual byte strings. And I can't seem to find "common" public key encryption systems, in Python and in other languages. Lots of different public key types exist, but all seem to be used only for signing or for key exchange.

What other public key encryptions would be available in Pycryptodome ? (Or in other libraries ?)
If possible having implementations in several languages (in case Java programs need to decrypt containers) ?

(Related ticket: https://github.com/Legrandin/pycryptodome/issues/139)

thanks in advance,
regards,
Pascal

**Comment by Legrandin** [comment]
Right now we only support RSA encryption. ElGamal is only included for legacy reasons and should not be used. Indeed EC encryption is still on the TODO list.

**Comment by pakal** [comment]
Is ElGamal insecure or juste "less secure" than RSA ? Since it's to be used as an additional layer (over already encrypted keys), I guess second-grade ciphers woudl still be good to add.

So far I've only found https://pypi.org/project/eciespy/ , however it requires a symmetric key specifically generated for it (not just random bytes), so I'd have to refactor my "layering" system.
