### ISSUE TITLE
Install without PIP

### ISSUE THREAD

**Issue by andrewcollier-com-au** [Legrandin/pycryptodome#344]
how can i install this without using pip? im sure everyone in the python world uses pip but Darwin is being an ass plus it restricts the ability for my code to be portable. any advice on how to get past the "
Traceback (most recent call last):
  File "/Users/andrew/Documents/GitHub/Libre/pycryptodome/setup.py", line 455, in <module>
    with open(os.path.join("lib", package_root, "__init__.py")) as init_root:
FileNotFoundError: [Errno 2] No such file or directory: 'lib/Crypto/__init__.py'
"
error when running as setup.py as sudo 

Thanks for your help

**Comment by frispete** [comment]
> im sure everyone in the python world uses pip

I beg to differ.

In most Linux distributions, we package python packages without pip for a couple of reasons:
 * use intrinsic packager
 * reproducible builds
 * easy install/uninstall/upgrade
 * run production systems *without* compiler (of course!)

> File "/Users/andrew/Documents/GitHub/Libre/pycryptodome/setup.py", line 455, in
with open(os.path.join("lib", package_root, "init.py")) as init_root:
FileNotFoundError: [Errno 2] No such file or directory: 'lib/Crypto/init.py'
"
error when running as setup.py as sudo

That's very much sounds like a permission problem. Unfortunately, you missed to provide the whole sequence of actions, but why do you want to run the build as root?

**Comment by andrewcollier-com-au** [comment]
Hi Frispete, i only tried it as root because i thought it needed to write something to the disk. I would ideally like to just drop the files into a directory and reference it... any ideas on how i can do what i want with this 'lib/Crypto' code base?

**Comment by frispete** [comment]
Start with:
```
git clone https://github.com/Legrandin/pycryptodome
cd pycryptodome
python3 setup.py build
```
Post commands and results.

**Comment by andrewcollier-com-au** [comment]
throws me the error at the top

**Comment by frispete** [comment]
I'm not sure, how

> you missed to provide the whole sequence of actions

or 

> Post commands and results.

is ambiguous in any way?

**Comment by andrewcollier-com-au** [comment]
i'v just decided to install pip (but when i distribute i will need to fork and include packages with the standalone patchs)

**Comment by frispete** [comment]
Good luck!

**Comment by Legrandin** [comment]
@andrewcollier-com-au [line 455 in `setup.py`](https://github.com/Legrandin/pycryptodome/blob/master/setup.py#L455) says:

    with open(os.path.join("lib", package_root, "__init__.py")) as init_root:

which is not what you have in the error message:

    with open(os.path.join("lib", package_root, "init.py")) as init_root:

Do you how why and how your `setup.py` changed in that way? As it is, it clearly won't work...

**Comment by frispete** [comment]
@Legrandin  That a formatting artifact. I noticed that, but the word `init` is written in __bold__.
He just didn't quote this phrase properly...

All attempts to elicit something reproducible from @andrewcollier-com-au failed so far.

Please to don't feel offended, @andrewcollier-com-au, but this looks very much like a PEBKAC to me.

**Comment by andrewcollier-com-au** [comment]
@Legrandin Thanks i will try setting that in the setup.py file
@frispete Funny guy... but to be fare all i did was did a git checkout and "python3 setup.py" so was well with-in the realm of noob... it would be nice though if i could just download the file, include and go...

**Comment by texadactyl** [comment]
@andrewcollier-com-au 
Have you investigated the Anaconda environment for Mac?
It tends to optimize your time and no root access is ever required.
I have used pycryptodome and its predecessor (pycrypto) there without issues.

**Comment by texadactyl** [comment]
In a Xubuntu environment,
1. pip3 uninstall pycryptodome
2. Downloaded zip file
3. Unzipped
4. cd'ed into the master
5. python3 setup.py install ---> no worries
6. Ran the following script which checks the Crypto version ---> 3.9.7
```
from Crypto import __version__
print("Crypto package version:", __version__)
```
Looks perfect to me.

**Comment by andrewcollier-com-au** [comment]
thanks people. i just ended up installing pip. but since then I have not even worked on Crypto pack. when i can be bothered going back i will have a look at your comments. thanks again.
