### ISSUE TITLE
Unexpected padding when length is a multiple of 16

### ISSUE THREAD

**Issue by pietjanssen** [Legrandin/pycryptodome#350]
For my program I am encrypting a random length of data ~(10 to 256 bytes) using ECB and CBC.
( I know ECB is not recommended, but I am only using it for scientific purposes)

For these mode of operations, you need to pad the data to a multiple of 16 bytes, but for some reason whenever I encrypt data that has a length of 16 itself, it will get a padding of 16 bytes too.

For example:
```python
data = b'12340006WE1CV020'
data = pad(data, AES.block_size)

# Data becomes b'12340006WE1CV020\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10' 
# New data length is 32 even though the data was already a multiple of 16.
```

I fixed it by changing the padding_len in the pad function to
**padding_len = (block_size-len(data_to_pad))%block_size**
```python
def pad(data_to_pad, block_size, style='pkcs7'):
    ...
    ...
    padding_len = block_size-len(data_to_pad)%block_size
    if style == 'pkcs7':
        padding = bchr(padding_len)*padding_len
    elif style == 'x923':
        padding = bchr(0)*(padding_len-1) + bchr(padding_len)
    elif style == 'iso7816':
        padding = bchr(128) + bchr(0)*(padding_len-1)
    else:
        raise ValueError("Unknown padding style")
    return data_to_pad + padding
```

Or is there a reason why the data still gets a padding of 16, even though it doesn't need it? Is it for extra obscurity of the data by padding every message?

**Comment by siccegge** [comment]
You have to encode how long the padding actually is (this is why the padding bytes in your eample are all `16`. You can't encode the length of `0` bytes with `0` bytes of space

**Comment by Legrandin** [comment]
Let's assume I send 16 bytes of data as it is (without adding any extra padding, because you say it doesn't need it), and let's also assume that the last byte of the data happens to be `01`.

As the receiver/reader, how do I know if I have to remove the last byte (because it looks like valid padding) or not (because it can be valid data)?

**Comment by pietjanssen** [comment]
> Let's assume I send 16 bytes of data as it is (without adding any extra padding, because you say it doesn't need it), and let's also assume that the last byte of the data happens to be `01`.
> 
> As the receiver/reader, how do I know if I have to remove the last byte (because it looks like valid padding) or not (because it can be valid data

**Comment by pietjanssen** [comment]
Oops accidentally closed the issue because I’m on my phone.

**Comment by pietjanssen** [comment]
> Let's assume I send 16 bytes of data as it is (without adding any extra padding, because you say it doesn't need it), and let's also assume that the last byte of the data happens to be `01`.
> 
> As the receiver/reader, how do I know if I have to remove the last byte (because it looks like valid padding) or not (because it can be valid data)?

You're absolutely right.
