### ISSUE TITLE
target does not support header

### ISSUE THREAD

**Issue by 0xFF1E071F** [Legrandin/pycryptodome#354]
Even though i have gcc-libs installed setup complains about these header files:
```
Testing support for clang
Target does not support clang
Testing support for gcc
Target does support gcc
Testing support for stdint.h header
Target does support stdint.h header
Testing support for 128-bit integer
Target does support 128-bit integer
Testing support for cpuid.h header
Target does support cpuid.h header
Testing support for intrin.h header
Target does not support intrin.h header
Testing support for posix_memalign
Target does support posix_memalign
Testing support for SSE2(intrin.h)
Target does not support SSE2(intrin.h)
Testing support for SSE2(x86intrin.h)
Target does support SSE2(x86intrin.h)
Testing support for AESNI intrinsics
Target does support AESNI intrinsics
Compiling support for AESNI instructions
Testing support for CLMUL intrinsics
Target does support CLMUL intrinsics
Compiling support for CLMUL instructions
running build
running build_py
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/Crypto
copying lib/Crypto/__init__.py -> build/lib.linux-x86_64-3.8/Crypto

```
BTW, i can successfully install pycryptodome on my system. i want to ask if this is a problem or not?

**Comment by frispete** [comment]
Apart from clang support complaint, which is to be expected, if not installed, where is your problem exactly? All those messages below clang are notes (no complaints)!

**Comment by 0xFF1E071F** [comment]
Hello
--sorry to not reply immediately--
actually there is no problem. i have compiled and installed the package.

i have asked the question, just to be sure if i am doing it right. I have clang installed with its development libraries but i get an warning. that was what i couldnt understand?
I have gcc with its development headers installed but; as you can see from the above output "Target does support SSE2(x86intrin.h)". But the header is installed on my system.

As i said before i have compiled and installed successfully.
Closing the issue
