### ISSUE TITLE
AES_CBC decrypt IV malfunction

### ISSUE THREAD

**Issue by Surya361** [Legrandin/pycryptodome#359]
import os
from Crypto.Cipher import AES
Key = os.urandom(16)
Iv = os.urandom(16)
encryption_suite = AES.new(Key, AES.MODE_CBC, Iv)
print(encryption_suite.decrypt(encryption_suite.encrypt("a"*32)))

The above code prints a garbage first block 
$ python3 /tmp/bug.py
b'\xbd/>\x02\xb6\xa7\xb2\x02\xf0A\xe2\xe4l\x8eL/aaaaaaaaaaaaaaaa'

i believe its because decrypt call is assuming the Initialization vector is not present and creating a new one resulting in a garbage first block

import os
from Crypto.Cipher import AES
Key = os.urandom(16)
Iv = os.urandom(16)
encryption_suite = AES.new(Key, AES.MODE_CBC, Iv)
decryption_suite =  AES.new(Key, AES.MODE_CBC, Iv)
print(decryption_suite.decrypt(encryption_suite.encrypt("a"*32)))

The second code prints the plain text properly

**Comment by Varbin** [comment]
When calling encrypt (or decrypt) again, the last block is used as next "IV". The same happens when "mixing" encryption and decryption.

The behaviour is there since the original PyCrypto.

**Comment by Surya361** [comment]
Need to document this behavior

**Comment by Varbin** [comment]
The behaviour is standardized in PEP-272.

**Comment by Legorooj** [comment]
@Surya361 @Varbin this isn't an issue with PyCryptoDome. This behaviour is expected. @Legrandin this needs closing.

**Comment by texadactyl** [comment]
@Legrandin 
This issue was founded on a misconception to begin with.  Suggest that you close it.

**Comment by Legrandin** [comment]
I think you wanted to report a PyCrypto problem. In PyCryptodome, the first example raises an exception to start with:

    TypeError: decrypt() cannot be called after encrypt()
