### ISSUE TITLE
Trying to serialize RSA Public keys raises a PicklingError

### ISSUE THREAD

**Issue by alehuo** [Legrandin/pycryptodome#365]
Hello!

I'm using the PYOIDC library which is used to handle OpenID Connect authorization workflow. It includes a special session state which stores RSA keys. By default, the library uses Python's native dictionary object to store the keys, but it's not persistent. Trying to serialzie the session state raises a PicklingException:

```
app  |     state = obj.__getstate__()
app  |   File "/usr/local/lib/python3.6/site-packages/Cryptodome/PublicKey/RSA.py", line 204, in __getstate__
app  |     raise PicklingError
app  | _pickle.PicklingError
```

Can you share some insight on why is the public key not serializable?

To my knowledge public keys are just plain bytearrays or Base64 encoded strings - in which case they could be serialized just fine.

**Comment by Legorooj** [comment]
You cannot serialise them because of the way the class is programmed. You need to serialise the result of `RsaKeyObj.export_key(options)`.

**Comment by alehuo** [comment]
I understand.

It seems that the correct way of proceeding is to create a custom handler for jsonpickle to handle objects of `RsaKey`. According to the jsonpickle source code, this block of code is executed before the actual state call is made: https://github.com/jsonpickle/jsonpickle/blob/38bd454f7fadfc1298bfb9694de34c2e174c4bb1/jsonpickle/pickler.py#L378

I have implemented the handler and everything is now working as excepted.

**Comment by frispete** [comment]
Mind sharing the custom handler with us?

**Comment by Legorooj** [comment]
@alehuo please share the handler. I know pickle doesn't support it, but we might be able to add something in the docs.

**Comment by alehuo** [comment]
Hello!

The handler, as requested:

```python
import jsonpickle
import base64
from jsonpickle.handlers import BaseHandler
from Crypto.PublicKey.RSA import RsaKey, import_key 
# If using pycryptodomex (the package that oic uses): 
# from Cryptodome.PublicKey.RSA import RsaKey, import_key 

class RSAKeyHandler(BaseHandler):
    def flatten(self, obj: RsaKey, data):
        data["rsa_key"] = base64.b64encode(obj.export_key()).decode("utf-8")
        return data

    def restore(self, obj):
        return import_key(base64.b64decode(obj["rsa_key"]))

jsonpickle.register(RsaKey, RSAKeyHandler)
```

I have written some tests for this case, you can find them the actual project repo: https://github.com/alehuo/pyoidc-redis-session-backend

Note, that I'm using Cryptodome library here, because `oic` uses `pycryptodomex` instead of `pycryptodome`. They are basically the same libraries, but with a different namespace.

**Comment by frispete** [comment]
Thanks a lot, @alehuo, much appreciated.

**Comment by Legorooj** [comment]
Yes thanks! We'll see about adding this to the docs/FAQ or similar @alehuo. Maybe even add this handler in the code... What do you think @frispete?

**Comment by frispete** [comment]
That's a good idea @Legorooj, but then, we would need a solution, that makes every Cryptodome object serializable (where it makes sense of course..)

**Comment by Legorooj** [comment]
Something to consider... Maybe a standalone package, that *does* have dependencies - PyCryptoDome one of them of course - and allows you to serialise objects? Oh and I'd say *don't* serialise private key objects unencrypted if we can manage that. I still personally think that private keys and public keys should have their own classes.
