### ISSUE TITLE
def derive(self) function is not working when I used mode_SIV

### ISSUE THREAD

**Issue by 20063209** [Legrandin/pycryptodome#366]
This is my code
`password = str(input("> "))
header = b"header"
data = "hi"
nonce = get_random_bytes(16)
key = hashlib.sha256(password.encode()).hexdigest()
cipher = AES.new(bytes(key,"UTF-8"), AES.MODE_SIV,nonce=nonce)
cipher.update(header)
ciphertext, tag = cipher.encrypt_and_digest(data)
json_k = [ 'nonce', 'header', 'ciphertext', 'tag' ]
json_v = [ b64encode(x).decode('utf-8') for x in (nonce, header, ciphertext, tag )]
result = json.dumps(dict(zip(json_k, json_v)))
print(ciphertext)`
This is the error message:
`Traceback (most recent call last):
  File "/Users/myusername/Desktop/script.py", line 17, in <module>
    ciphertext, tag = cipher.encrypt_and_digest(data)
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/Cryptodome/Cipher/_mode_siv.py", line 304, in encrypt_and_digest
    self._mac_tag = self._kdf.derive()
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/Cryptodome/Protocol/KDF.py", line 266, in derive
    padded = (self._last_string + b'\x80' + b'\x00' * 15)[:16]
TypeError: can only concatenate str (not "bytes") to str`
I tried to solve the problem by myself but it did not work
this is the code in KDF.py before I tried to solve the problem
`def derive(self):
        """"Derive a secret from the vector of components.

        :Return: a byte string, as long as the block length of the cipher.
        """

        if len(self._last_string) >= 16:
            # xorend
            final = self._last_string[:-16] + strxor(self._last_string[-16:], self._cache)
        else:
            # zero-pad & xor
            padded = (self._last_string + b'\x80' + b'\x00' * 15)[:16]
            final = strxor(padded, self._double(self._cache))
        mac = CMAC.new(self._key,
                       msg=final,
                       ciphermod=self._ciphermod,
                       cipher_params=self._cipher_params)
        return mac.digest()`
this is the code in KDF.py after I tried to solve the problem
`def derive(self):
        """"Derive a secret from the vector of components.

        :Return: a byte string, as long as the block length of the cipher.
        """

        if len(self._last_string) >= 16:
            # xorend
            final = self._last_string[:-16] + strxor(self._last_string[-16:], self._cache)
        else:
            # zero-pad & xor
            padded = (self._last_string + str(b'\x80') + str(b'\x00') * 15)[:16]
            final = strxor(bytes(padded,"UTF-8"), self._double(self._cache))
        mac = CMAC.new(self._key,
                       msg=final,
                       ciphermod=self._ciphermod,
                       cipher_params=self._cipher_params)
        return mac.digest()`
However the error message says there is an invalid syntax at line`mac = CMAC.new(self._key,`
The arrow was pointing at the m in mac
please fix this as soon as you can

**Comment by Legrandin** [comment]
Can you try to do `pip uninstall pycrypto` and then retry the original code?
It seems you have both installed at that won't work.

**Comment by 20063209** [comment]
I've uninstalled pycrypto and the error message is still the same when I ran the original file.

**Comment by Legrandin** [comment]
Please copy the output if you include this in the same code:

    from Crypto.Util import strxor
    print(strxor.__file__)

Which extension does the file have?

**Comment by 20063209** [comment]
This is the output 

> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Crypto/Util/strxor.py

**Comment by 20063209** [comment]
This is the output
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Crypto/Util/strxor.py
The file is a python file (.py)

**Comment by Varbin** [comment]
`data` was not encoded to `bytes`.

This code works: 

```python
import hashlib
import json

from base64 import b64encode

from Cryptodome.Cipher import AES
from Cryptodome.Random import get_random_bytes

password = input("> ")  # Always returns str
header = b"header"
data = "hi".encode()  # Problem was here, it was not type bytes
nonce = get_random_bytes(16) 
key = hashlib.sha256(password.encode()).hexdigest() 
cipher = AES.new(bytes(key,"UTF-8"), AES.MODE_SIV,nonce=nonce)
cipher.update(header)
ciphertext, tag = cipher.encrypt_and_digest(data)
json_k = [ 'nonce', 'header', 'ciphertext', 'tag' ]
json_v = [ b64encode(x).decode('utf-8') for x in (nonce, header, ciphertext, tag )]
result = json.dumps(dict(zip(json_k, json_v)))
print(ciphertext)
```

**Comment by 20063209** [comment]
Thank you sooooo much Varbin!!!
