### ISSUE TITLE
Type error in RSA.exportKey using python 3.6.8

### ISSUE THREAD

**Issue by KwisatzHaderach** [Legrandin/pycryptodome#373]
Using this code:

from Crypto.PublicKey import RSA
ssh_key = RSA.generate(bits=2048, randfunc=os.urandom)
ssh_key.publickey().exportKey('OpenSSH')

I'm getting TypeError in Crypto/PublicKey/RSA.py:315:
>   keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
E   TypeError: can't concat str to bytes

**Comment by frispete** [comment]
Just omit the randfunc as a workaround (and be assured, that PyCryptodome will do the right thing...)

**Comment by texadactyl** [comment]
@KwisatzHaderach 
```
import os

from Crypto.PublicKey import RSA
from Crypto import __version__ as version
ssh_key = RSA.generate(bits=2048, randfunc=os.urandom)
ssh_key2 = RSA.generate(bits=2048)
ssh_key.publickey().exportKey('OpenSSH')
ssh_key2.publickey().exportKey('OpenSSH')

print("TypeError seems to have disappeared in Crypto version {}".format(version))
```
Output:
```
TypeError seems to have disappeared in Crypto version 2.6.1
```
Suggest closing this issue.

**Comment by texadactyl** [comment]
@Legrandin
I would close this as the originator (@KwisatzHaderach) seems to have lost interest or is unable to follow up.

**Comment by KwisatzHaderach** [comment]
Sure, I don't remember what I did however this issue did not reproduce for me anymore.
