### ISSUE TITLE
[FEATURE] Incorporate Ulam's Spiral for faster generation of primes

### ISSUE THREAD

**Issue by prabhatsoni99** [Legrandin/pycryptodome#374]
Ulam's spiral is a pattern in mathematics. We know of a particular equation whose `y` value has approx 20X more chance of being a prime number (a high density distribution of numbers):  
`y = x^2 + x + 3399714628553118047`  
  
What are the thoughts on incorporating this to generate primes faster?
  
Resources for Ulam's Spiral:  
https://en.wikipedia.org/wiki/Ulam_spiral  
https://www.youtube.com/watch?v=iFuR97YcSLM

**Comment by Varbin** [comment]
If all generated primes would be on the spiral, wouldn't that reduce the keyspace when those primes are used for e.g. RSA?

I don't think it is worth the tradeoff, especially since key generation does not happen that often in a typical application.

**Comment by prabhatsoni99** [comment]
I guess you are correct. Key security >> Key generation time.
Thanks for your inputs!

**Comment by frispete** [comment]
This is probably another candidate for the experimental twig :wink:
