### ISSUE TITLE
Symbols conflict between different version of libgmp

### ISSUE THREAD

**Issue by emc2314** [Legrandin/pycryptodome#376]
# Problem
It starts from an astonishing result when I try to use the RSA module of pycryptodome in [SageMath](https://sagemath.org):

![image](https://user-images.githubusercontent.com/14357110/74120521-9d3cb800-4bfe-11ea-8c72-201b641839fc.png)

The above scenario can be easily reproduced when one uses the official **binary distribution** of Sage and pip install pycryptodome.

Sage is a great software for algebraic number theory which is pretty related to cryptography. **It would be a pity if Sage cannot work with pycryptodome. Furthermore,  there may be other python software distributions with their own libgmp suffering from this problem.**

# Details
After some investigation, it turns out that the problem is oriented from the ```IntegerGMP```. It always keeps only two decimal digits when converting to int:

![image](https://user-images.githubusercontent.com/14357110/74121077-eb52bb00-4c00-11ea-97ed-6986f2ea2416.png)

And the reason is that ``` _gmp.mpz_sizeinbase()``` always returns 1, so ```buf_len``` is always 3, corresponding to 2 decimal digits considering the ending '\0'.

https://github.com/Legrandin/pycryptodome/blob/282db2277986c52090d8dcf526846755ce420b09/lib/Crypto/Math/_IntegerGMP.py#L172-L180

After debugging the binary for a while, I find out the **REAL FIEND** behind this bug:

![image](https://user-images.githubusercontent.com/14357110/74121523-cfe8af80-4c02-11ea-91a7-6aca79a1f21c.png)

Two libgmp with different version are both loaded. The ```_gmp.mpz_sizeinbase()``` function is resolved by ```cffi``` and located in the system ```libgmp.so.10.3.2``` loaded by ```_IntegerGMP.py```:

https://github.com/Legrandin/pycryptodome/blob/282db2277986c52090d8dcf526846755ce420b09/lib/Crypto/Math/_IntegerGMP.py#L95

However, the sage version ```libgmp.so.23.0.3``` is already loaded. And **the ```__gmpn_bases``` symbol in ```libgmp.10.3.2``` is resolved to the address of the same symbol of  ```libgmp.so.23.0.3``` by ld.so**. So the code and data used are not compatible, which leads to the weird result that ```_gmpz_sizeinbase()``` returns 1.

![image](https://user-images.githubusercontent.com/14357110/74121534-dd059e80-4c02-11ea-805f-f2b0fc675549.png)

# Possible fix
## To include pycryptodome in Sage distribution
It seems that this has been a long existing issue since pycrypto became outdated and [removed by Sage](https://trac.sagemath.org/ticket/25844). One possible fix is to provide pycryptodome in Sage and force pycryptodome to use local libgmp. But they seem to have no intention to bring it back because of two reasons:
- They believe users can install pycryptodome easily with pip
- Sage itself does not depend on this package
## Build Sage yourself or use Sage from linux distribution repo
Sage is a REALLY ENORMOUS system. To build it will so long that people can hardly bear (except Gentoo fans). Besides, Sage depends on many many libraries, every time the system libgmp/libbalabala get some updates, one has to build it again. Also, those libraries may conflict with the version requirement of other softwares, so there are few linux distributions providing Sagemath in their repos.
## Use LD_LIBRARY_PATH or LD_PRELOAD to force one version of libgmp
The Sage version libgmp is imported by many other python modules/other .so libraries linked to this specific version and path of libgmp. Using system libgmp might result compatibility problems across linux distributions.
The pycryptodome loads libgmp by using ```cffi```, which calls ```ctype``` to [use ```ldconfig -p``` first to search libgmp](https://github.com/python/cpython/blob/3ed4d251587c36c3853daf42602eaad121b59bba/Lib/ctypes/util.py#L275). LD_LIBRARY_PATH and LD_PRELOAD does not affect ldconfig, so it does not work.
## The EASIEST FIX EVER
Since the main reason is symbol conflict, we just let the loaded library not use global symbols by changing one line of the source code:
https://github.com/Legrandin/pycryptodome/blob/282db2277986c52090d8dcf526846755ce420b09/lib/Crypto/Util/_raw_api.py#L101
to:

```lib = ffi.dlopen(name, ffi.RTLD_DEEPBIND)```

Then everything will work again.

Hope this suggestion would be adopted and make crypto great again( XD

**Comment by Legrandin** [comment]
Thanks for the great bug report, including solution(s) and apologies for the long silence.
The fix is now in master with https://github.com/Legrandin/pycryptodome/commit/7bc6d4d548596e5bfa3da0dd253a068b403b7c51

**Comment by kovidgoyal** [comment]
RTLD_DEEPBIND breaks sanitizers. Please dont use it. Or at the very least have some way to turn it off, say via an environment variable.

Reference: https://github.com/google/sanitizers/issues/611

**Comment by Legrandin** [comment]
Thanks @kovidgoyal - the next version will have an environment flag `PYCRYPTODOME_DISABLE_DEEPBIND`.
