### ISSUE TITLE
pycryptodome package for my board

### ISSUE THREAD

**Issue by shubham101096** [Legrandin/pycryptodome#377]
Hi

I need the pycryptodome package for the following architecture of my target board. The target board does not have internet access so I cannot directly install pycryptodome on it. I need a method to compile it on my ubuntu 64 bit pc and then transfer it on my board. Following describes the toolchain I am using and the architecture of the target board. I cant find a .whl file or anything else for this architecture. Please help me out.

PPC_e5500_CC_BASE_DIR   := /opt/fsl-qoriq/2.0/sysroots/x86_64-fslsdk-linux
ifeq (${TARGET_CPU}, PPC_e5500)
ifeq (${TARGET_CPU_BIT},)
$(info TARGET_CPU_BIT must be 32BIT/64BIT)
$(warning TARGET_CPU_BIT not specified, assuming 32BIT)
TARGET_CPU_BIT          = 32BIT
endif
TARGET_ARCH             = powerpc
COMPILER_TYPE           = gcc
ifeq (${TARGET_CPU_BIT}, 32BIT)
#TARGET_CPU_BIT          = 32BIT
CROSS_COMPILE_PATH      = ${PPC_e5500_CC_BASE_DIR}/usr/bin/powerpc-fsl-linux:${PPC_e5500_CC_BASE_DIR}/usr/bin
CROSS_COMPILE           = powerpc-fsl-linux-
HOST                    = powerpc-fsl-linux
CC_SYSROOT              = ${PPC_e5500_CC_BASE_DIR}/../ppce5500-fsl-linux
COMMON_CFLAGS          += -m32 -mhard-float -mcpu=e5500
COMMON_CFLAGS          += --sysroot=${CC_SYSROOT}

Regards
Shubham Mishra

**Comment by Legrandin** [comment]
I recommend you find a QEMU Linux image for PowerPC compatible to your board (maybe [one of these](https://people.debian.org/~aurel32/qemu/powerpc/)), install the right gcc and python packages, and create the binary wheel (with `python3 setup.py bdist_wheel`).
