### ISSUE TITLE
Python27: ChaCha20.new() takes exactly 0 arguments 

### ISSUE THREAD

**Issue by monopecez** [Legrandin/pycryptodome#38]
So I am following example like in the documentation/help:
```
from Crypto.Cipher import ChaCha20

key = b'*Thirty-two byte (256 bits) key*'
cipher = ChaCha20.new(key)
msg = cipher.nonce + cipher.encrypt(b'Attack at dawn')
```
and it returned:
`TypeError: new() takes exactly 0 arguments (1 given)`

Solution:
`cipher = ChaCha20.new(key)` should be changed to `cipher = ChaCha20.new(key = key)`

**Comment by Legrandin** [comment]
Right. I fixed the example with 191f1a820cc686cd71497eea1e682c0a03e480d4.
