### ISSUE TITLE
installation error with 64-bit Python3.8 on AIX

### ISSUE THREAD

**Issue by wudiwin728** [Legrandin/pycryptodome#384]
copying lib/Cryptodome/SelfTest/Signature/test_vectors/wycheproof/rsa_signature_test.json -> build/lib.AIX.7200.1543.64-3.8/Cryptodome/SelfTest/Signature/test_vectors/wycheproof
    running build_ext
    building 'Cryptodome.Hash._MD2' extension
    creating build/temp.AIX.7200.1543.64-3.8
    creating build/temp.AIX.7200.1543.64-3.8/src
    xlc_r -DNDEBUG -O -I/opt/include -O2 -qmaxmem=-1 -qarch=pwr5 -q64 -I/opt/include -O2 -qmaxmem=-1 -qarch=pwr5 -q64 -DHAVE_STDINT_H -DPYCRYPTO_BIG_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -DHAVE_POSIX_MEMALIGN -Isrc/ -I/opt/include/python3.8 -c src/MD2.c -o build/temp.AIX.7200.1543.64-3.8/src/MD2.o
    /opt/lib/python3.8/config-3.8/ld_so_aix xlc_r -bI:/opt/lib/python3.8/config-3.8/python.exp build/temp.AIX.7200.1543.64-3.8/src/MD2.o -o build/lib.AIX.7200.1543.64-3.8/Cryptodome/Hash/_MD2.so
    ld: 0711-736 ERROR: Input file build/temp.AIX.7200.1543.64-3.8/src/MD2.o:
        XCOFF64 object files are not allowed in 32-bit mode.
    error: command '/opt/lib/python3.8/config-3.8/ld_so_aix' failed with exit status 8
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r2xpp_3q/pycryptodomex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r2xpp_3q/pycryptodomex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vmuyayqg/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by Xhofe** [comment]
我也是 老哥解决了吗

**Comment by Legrandin** [comment]
You probably need to pass some additional parameters in the CFLAGS environment variable.
The IBM support team should be able to help you with that.
