### ISSUE TITLE
How to encrypt string with armored GPG key?

### ISSUE THREAD

**Issue by alex-yobota** [Legrandin/pycryptodome#387]
I did try posting this to the google group as the docs suggest, but I received a 'delivery failed' notification.

I have an armored (ASCII)  PGP public key, of the format:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

KEY
-----END PGP PUBLIC KEY BLOCK-----
```

and I would like to use it to PGP encrypt a string.

I am repeatedly getting the error that the format of the public key is
incorrect, when I run RSA.importkey. I have tried stripping the
---BEGIN/END PUBLIC KEY BLOCK--- lines, as well as base64 decoding the
key, but neither has helped.

Am I going about this the wrong way?

**Comment by Legrandin** [comment]
Import of PGP key is not supported.
