### ISSUE TITLE
RSA Signature Verification - Interoperability with Node.js Crypto

### ISSUE THREAD

**Issue by aaclayton** [Legrandin/pycryptodome#388]
**Situation:** I'm working on a project which needs RSA signature verification between Python and Node.js services. I'm hoping to use `pycryptodomex` in Python 3.8 and the built-in `crypto` package in Node.js `12.16.x`to sign and verify using an RSA keypair. In general, the Python process is responsible for signing while the Node.js process is responsible for verifying.

**Problem:** I am able to sign in Python and verify in Python. I am also able to sign in Node.js and verify in Node.js - but I am not able to sign in Python and verify in Node.js.

**Disclaimer:** This issue has the flavor of a support request - which I apologize for. I ran into trouble implementing what I expected to be fairly standard behavior across both platforms. If you're able to help me understand how to achieve interoperability between these libraries I would be happy to translate my learning into a documentation PR which shares this knowledge with other pycryptodome users (if you feel that would be valuable).

## Setup

Assume that both Node and Python services share the following globals: `PUBLIC_KEY` and `PRIVATE_KEY` in ascii string format which contain the keypair.

## Python Implementation

See: https://www.pycryptodome.org/en/latest/src/signature/signature.html

```python
import base64
from Cryptodome.PublicKey import RSA
from Cryptodome.Signature import pss
from Cryptodome.Hash import SHA256

def sign_python(message):
    """ Sign a message using a private key and return an string with the signature.
    """
    private_key = RSA.import_key(PRIVATE_KEY)
    signer = pss.new(private_key)
    hashed = SHA256.new(message.encode())
    signature = signer.sign(hashed)
    sig_str = base64.b64encode(signature).decode("ascii")
    return sig_str
    
def verify_python(message, sig_str):
    """ Verify a message using a public key and return whether the signature is valid.
    """
    public_key = RSA.import_key(PUBLIC_KEY)
    verifier = pss.new(public_key)
    hashed = SHA256.new(message.encode())
    signature = base64.b64decode(sig_str)
    verifier.verify(hashed, signature)
    return True

# Example usage
message = "Some test message"
sig_str = sign_python(message)
verify_python(message, sig_str) // True
```

## Node.js Implementation

See: https://nodejs.org/api/crypto.html#crypto_class_sign and https://nodejs.org/api/crypto.html#crypto_class_verify

```js
const crypto = require("crypto");

/**
 * Sign a message using a private key and return an string with the signature.
 */
function signJS(message) {
    const privateKey = crypto.createPrivateKey(PRIVATE_KEY);
    const signer = crypto.createSign("SHA256")
    signer.update(message);
    signer.end();
    const signature = signer.sign(privateKey, "base64");
    return signature;  
}

/**
 * Verify a message using a public key and return whether the signature is valid.
 */
function verifyJS(message, signature) {
    const publicKey = crypto.createPublicKey(PUBLIC_KEY);
    const verifier = crypto.createVerify("SHA256");
    verifier.write(message);
    verifier.end();
    const valid = verifier.verify(publicKey, signature, "base64");
    return valid;
}

// Example Usage
const message = "Some test message";
const sig_str = signJS(message);
verifyJS(message, sig_str); // true
```

## Interoperability

I'm not a cryptography expert - but I had expected these approaches to be interoperable - allowing me to sign content in one service and verify it in the other. I am, however, finding this not to be the case. Signatures generated in Python are not verified in Node.js (and vice-versa).

I'm confident this gap is due to me missing a configuration or parameter which does not share the same default value across libraries. I have some theories - but was not able to find an approach which worked through trial-and-error:

**Node.js**

* `sign.sign(privateKey)` supports configuring the `padding` parameter where the default behavior is  `crypto.constants.RSA_PKCS1_PADDING`. I suspect this may be the wrong choice or incompatible with the default behavior in Python. (https://nodejs.org/api/crypto.html#crypto_class_sign)
* The node signature also supports specifying a `saltLength` where the default behavior is to set `crypto.constants.RSA_PSS_SALTLEN_MAX_SIGN` but another option is `crypto.constants.RSA_PSS_SALTLEN_DIGEST` which sets the salt length to the digest size.

**Pycryptodome**

* `Crypto.Signature.pss.new(rsa_key, **kwargs)` accepts an optional argument for `salt_bytes` where the default is `hlen` which is the size of the digest. This seems to suggest that I should use `RSA_PSS_SALTLEN_DIGEST` on the Node.js side. Is that correct?
* I don't find anywhere in the `pss` documentation that describes configuration for the `padding` parameter. Is there a default value or configuration of that which would align behavior with Node.js?

Thank you very much for the helpful library and for any advice that you may have.
Andrew

**Comment by aaclayton** [comment]
An update: I've discovered that using `Signature.pkcs1_15` instead of `Signature.pss` does produce a verified result on the Node.js side (with no other code changes) - so there's something about my use of the PSS scheme which I'm using incorrectly. 

I was advised (and I am not enough of an expert to know the difference) to use PSS so I had gone that route - but I can move forward with the pkcs1_15 scheme. If you have any insight about what might need to change on the node.js side in order to verify the PSS signature I would be very interested to learn!

**Comment by Legrandin** [comment]
I agree that the issue is probably in the different defaults: Node.js maximizes the salt length (`crypto.constants.RSA_PSS_SALTLEN_MAX_SIGN`) whereas in PyCryptodome the salt is as long as the digest size.

If that is the case, you have two options:

1. At the JS side, add attribute `saltLength` to private and public keys using value `crypto.constants.RSA_PSS_SALTLEN_DIGEST`, or
2. At the Python side, maximize the salt size with something like this for both signing and verifcation:

```
    hashed = SHA256.new(message.encode())
    salt_bytes = private_key.size_in_bytes() - hashed.digest_size - 2
    signer = pss.new(private_key)
```

For this question:

> I don't find anywhere in the pss documentation that describes configuration for the padding parameter. Is there a default value or configuration of that which would align behavior with Node.js?

In PyCryptodome, RSA signature schemes (calling them "paddings" is not accurate) are implemented in two different modules:

* `Crypto.Signature.pss` implements `RSASSA-PSS` (PSS in short) which maps to `crypto.constants.RSA_PKCS1_PSS_PADDING` in NodeJS
* `Crypto.Signature.pkcs1_15` implement `RSAES-PKCS1-v1_5` (PKCS#1 v1.5 in short) which is called `crypto.constants.RSA_PKCS1_PADDING` in Node.JS (not a great name, they just exposed the OpenSSL name which is extremely dated)

PSS has many knobs, whereas PKCS#1 v1.5 is much more straightforward. In general, it better to use PKCS#1 v1.5 for signatures - it is not really less secure.

**Comment by aaclayton** [comment]
Thank you @Legrandin for the very helpful response - this helps me understand much better. I'm happy that I've gotten things working properly using PKCS#1 v1.5 and I'm glad to hear there are not any security concerns - so I think my own challenge is solved.

Thanks for the very helpful library, and it's been a useful learning experience for me to develop a better understanding of these concepts. 

o7
