### ISSUE TITLE
See this error 

### ISSUE THREAD

**Issue by pawarashish564** [Legrandin/pycryptodome#389]
https://stackoverflow.com/questions/60139976/right-way-to-decrypt-rsa-session-key @nicois Please help

**Comment by texadactyl** [comment]
Something is probably wrong in one or both of your files:
1. **encrypted_data.bin**, presumably (guessing):
- session key encrypted with the public key (usually embedded with private key)
- data encrypted with the session key
- a digital signature if the intention is to verify a signer (encryptor)
- an encrypted MAC if the message integrity is to be verified
2. **private.pem** - a PEM file? containing a private key + what else is embedded here when you created it?

Please do more research.
This does not seem to be a pycryptodome issue (bug or enhancement request).

**Comment by texadactyl** [comment]
@Legrandin
I would close this as the originator (@pawarashish564) seems to have lost interest or is unable to follow up.
