### ISSUE TITLE
SmartPointer destructor might fail

### ISSUE THREAD

**Issue by blakawk** [Legrandin/pycryptodome#39]
I have this issue when using PyCryptoDome from an apache WSGI:
`Exception ignored in: <bound method SmartPointer.__del__ of <Crypto.Util._raw_api.SmartPointer object at 0x7f79d4048e48>>`
`Traceback (most recent call last):`
`File "/usr/local/lib/python3.5/dist-packages/Crypto/Util/_raw_api.py", line 146, in __del__`
`NameError: name 'hasattr' is not defined`

It seems that using global functions (such as hasattr) during python interpreter destruction (as it might be the case here) lead to having builtin hasattr being undefined.

PyCryptoDome version is 3.4.3, Python version is 3.5.2, apache2 version is 2.4.18 and libapache2-mod-wsgi-py3 is 4.3.0-1.1build1, everything on ubuntu server 16.04.1.

**Comment by Legrandin** [comment]
Thanks for reporting. This is quite odd, but I have reworked `__del__` a little.
Would you have a chance to try again with `master`?

**Comment by blakawk** [comment]
I applied your correction and keep you in touch to see if it happens again.
I worry that AttributeError might be impacted as well as hasattr.

**Comment by blakawk** [comment]
Hello, this fix seems OK, ticket can be closed.

**Comment by Legrandin** [comment]
Thanks for following up.
