### ISSUE TITLE
RSA Invalid Condition

### ISSUE THREAD

**Issue by RapedTrap** [Legrandin/pycryptodome#392]
https://stackoverflow.com/questions/60460193/how-to-solve-problem-with-invalid-rsa-condition

**Comment by texadactyl** [comment]
What does this have to do with PyCryptodome?
Your source code from the stackoverflow page:
```
from mega import Mega
mega = Mega()
password = 'here is my password'
email = 'here is my email'
m = mega.login(email, password)
```

**Comment by texadactyl** [comment]
From what I can see, /mega/mega.py", line 131 is trying to login in someone and supplying a private/public key pair.  In the RSA.py consistency check, it detects the presence of a private key but it appears to be corrupted, the error raised as line 604.

What is "mega"?  Is this related to MEGAsync?  https://pypi.org/project/mega.py/

**Comment by texadactyl** [comment]
Clearly, 'here is my email' is an invalid email address.  

 On stackoverflow, you said "using a temporary anonymous account, and exit code was 0".  No error was raised, right? 

My guess is that mega.login is passing along an invalid request to RSA.  Shouldn't mega.login be diagnosing an invalid email address?

If you agree with me, please take this up with the Mega folks and close this issue.

**Comment by texadactyl** [comment]
I got curious.  Installed mega from Pypi.org and enhanced your stackoverflow program:
```
"""
https://pypi.org/project/mega.py/
"""
from mega import Mega

EMAIL = "donald.trump@whitehouse.gov"
PASSWORD = "Everybody says windmills cause cancer."

def tester(email, password):
    try:
        mega = Mega()
        m = mega.login(email, password)
        print("Successful login with {} and {}".format(email, password))
        details = m.get_user()
        print("m.get_usr() ok")
    except TypeError as err:
        print("*** Oops: TypeError\n{}".format(str(err)))
    except Exception as err:
        print("*** Oops:\n{}".format(str(err)))
    print("leaving tester\n")
    del mega

tester(EMAIL, PASSWORD)
tester('here is my email','here is my password')

mega = Mega()
m = mega.login()
print("Success with an anonymous user login")
del mega

```
I cannot reproduce your error.

My mega.login results:
- Anonymous login: ok
- Login with a good email address & password: ok
- Login with a valid email address which is not registered or an invalid password was supplied: fails with a reasonable explanation (could be clearer but nobody is perfect)
- Login with a malformed email address: throws "TypeError, 'int' object is not subscriptable"

Maybe you have an out of date ```mega``` or ```pycryptodome```?

Please check your repositories and retest.

**Comment by RapedTrap** [comment]
> I got curious. Installed mega from Pypi.org and enhanced your stackoverflow program:
> 
> ```
> """
> https://pypi.org/project/mega.py/
> """
> from mega import Mega
> 
> EMAIL = "donald.trump@whitehouse.gov"
> PASSWORD = "Everybody says windmills cause cancer."
> 
> def tester(email, password):
>     try:
>         mega = Mega()
>         m = mega.login(email, password)
>         print("Successful login with {} and {}".format(email, password))
>         details = m.get_user()
>         print("m.get_usr() ok")
>     except TypeError as err:
>         print("*** Oops: TypeError\n{}".format(str(err)))
>     except Exception as err:
>         print("*** Oops:\n{}".format(str(err)))
>     print("leaving tester\n")
>     del mega
> 
> tester(EMAIL, PASSWORD)
> tester('here is my email','here is my password')
> 
> mega = Mega()
> m = mega.login()
> print("Success with an anonymous user login")
> del mega
> ```
> 
> I cannot reproduce your error.
> 
> My mega.login results:
> 
> * Anonymous login: ok
> * Login with a good email address & password: ok
> * Login with a valid email address which is not registered or an invalid password was supplied: fails with a reasonable explanation (could be clearer but nobody is perfect)
> * Login with a malformed email address: throws "TypeError, 'int' object is not subscriptable"
> 
> Maybe you have an out of date `mega` or `pycryptodome`?
> 
> Please check your repositories and retest.
I don't know why, but everything is ok.
