### ISSUE TITLE
Hello, when I signed with pycryptodome 3.9.7, I also checked the success when I made a mistake

### ISSUE THREAD

**Issue by YXinAndy** [Legrandin/pycryptodome#395]
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
from Crypto.Hash import SHA256, MD5
import base64

def RSA_sign(data):
    privateKey = '''MIIEowIBAAKCAQEA08uOAJPiSyGK2kgWhgapEdPMXV1NiLDCZVtoNRsRygfiIh4Z7pDnJsY31K/ZPz1793Wi8wXJcwN4YK61ES6a1IBZ+/DT0ipXwpPyjrz1lSkEBC8j9LmayRT3HXvfZyV7Lgb6n3gc+MW+SZ8RAdvEnrSySl/nnjl4uOY0yWEhYQXHTqjPJKQ4D6v2N0tj6eIPYR78TFlrNx1oWN5XYlgo+ttAyWgQFe4oTcwRW57/oP2IfSBQwMq7e2E+/zLLr1GyETG22nzfrabpwT7YwFtIdp5d+8pcxur7EsO7CwRbjZcL6n4oblaXe4iEj2HFeweR7hZBxkHd5u/mnSce6FP3TQIDAQABAoIBAAVzrPEY3W9fqqpZxrKmgz2hPRZ+K1vEaQyg4LrVOoz/zPNh4PsCIeEeoxtHd4koNQO2tH4a/QeH5FZgyOprT7L+ptJUba9wRZgNpOXFuXCggKj26a8IBBL/BiltIeAO1+/kYBkwx1YkCPTuMkrg9Fu9fQVrGJQ7GH9x9ZPley17I5P4cuMPu1HXUzLk23z1lMxYU3FpwwUNUJw+XuWYCyo/GWdimWp9cOuiJWa9gfZAhQVXkOsk1DTuLxL0vcu+xVfmqijLD69e41rmGjkbQVsgAfd8lBHcKm2u4JmYuM29OlUAAnfK+7zsJF7hqqgch868Eb2AmYDHud4QvIzDWiECgYEA+rgfY6nB46RZNhNFgq4BVJzP+f/clYeCe7NPx22y5ceqn5wt3030EfmW9LUJ8t2vmAzyQ/h2vAZ/xgeRGRN8AFectzt2N9imx5zVaextLOGwZ03VxvlH5vesfj2wvaqxfUB9hsM/aR0Jld+b7wCQeJFPawYO8zV/o8ryuZcZ2RUCgYEA2EGNsMBxXvRn/UMfd6UHdlbhBfr3r3k6dqc6n74tRBEBo/yD+HgG7G9cQf+FUC0ADPzp4A+JXDYmNsieF+cq9qsqKIYbEa/jCgvpL9IJWjI82+WQf5TY59FyPmY9jW1wPqhu4bx5IVVB4osLQcxhkCQxcjTXkDF6yP+jOw4rQ1kCgYALambDeu9BFjKZq7b2hEW7PIibsXKxvEHMsBVp1yzWGYlDSzErgbkjOGIPMk8Jp95e5fgB8EY3uXQH6EBLDAARY+vWy/ZOBKdTX2i4MfOmn4AQtBKPxLnpYk2QUe7CNAtw0Ibmo+03NANDt7K55ySs2LDtBpGXsU/mfU8f9ClRIQKBgE7GalfFckbVnv/JsK/DpNk9wpCMICeCcIKCXj+MZi7SRxe2R1h+WH9N/XxpGOXgzpDsnEErR60YaIkyQSyR37ulFCFY4Ilr2bdyKUprJ0781+B+WkmvLegcCpKiaa+X+vhIIMQIBNPYm7xrS/l2+t8n3/8rMo7rB0Aqpwo/GhFZAoGBANR6PphQzV/jDgXy5FGOxQoXKBSHi8Cni0lHE10EjYW0xO+FQkQWf5jLXVsScsrzbuB3s2rcQ2XOw7qI7MtC4bs7aBTapnINa2lgj9MmFZB2uo5FmGFZ5gr17/do8S9h5CCgxX+9OXpGuNrfiiuo5Z7jF9bp+l5Z8XK1VR9leAvF'''

    private_keyBytes = base64.b64decode(privateKey)
    priKey = RSA.importKey(private_keyBytes)
    signer = PKCS1_v1_5.new(priKey)
    hash_obj = SHA256.new(data.encode('utf-8'))
    signature = base64.b64encode(signer.sign(hash_obj))
    return signature

def verify_sign(signature, data):
    print(signature)
    publicKey = """MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA08uOAJPiSyGK2kgWhgapEdPMXV1NiLDCZVtoNRsRygfiIh4Z7pDnJsY31K/ZPz1793Wi8wXJcwN4YK61ES6a1IBZ+/DT0ipXwpPyjrz1lSkEBC8j9LmayRT3HXvfZyV7Lgb6n3gc+MW+SZ8RAdvEnrSySl/nnjl4uOY0yWEhYQXHTqjPJKQ4D6v2N0tj6eIPYR78TFlrNx1oWN5XYlgo+ttAyWgQFe4oTcwRW57/oP2IfSBQwMq7e2E+/zLLr1GyETG22nzfrabpwT7YwFtIdp5d+8pcxur7EsO7CwRbjZcL6n4oblaXe4iEj2HFeweR7hZBxkHd5u/mnSce6FP3TQIDAQAB"""
    public_keyBytes = base64.b64decode(publicKey)
    pubKey = RSA.importKey(public_keyBytes)
    verifier = PKCS1_v1_5.new(pubKey)
    h = SHA256.new(data.encode('utf-8'))
    return verifier.verify(h, base64.b64decode(signature))

sign = RSA_sign('alipay_root_cert_sn=6bc29aa3b4d406c43483ffea81e08d22&app_cert_sn=50fa7bc5dc305a4fbdbe166689ddc827&app_id=2014072300007148&biz_content={"button":[{"actionParam":"ZFB_HFCZ","actionType":"out","name":"话费充值"},{"name":"查询","subButton":[{"actionParam":"ZFB_YECX","actionType":"out","name":"余额查询"},{"actionParam":"ZFB_LLCX","actionType":"out","name":"流量查询"},{"actionParam":"ZFB_HFCX","actionType":"out","name":"话费查询"}]},{"actionParam":"http://m.alipay.com","actionType":"link","name":"最新优惠"}]}&charset=GBK&method=alipay.mobile.public.menu.add&sign_type=RSA2')

print(verify_sign(sign.decode() + 'rtesggds', 'alipay_root_cert_sn=6bc29aa3b4d406c43483ffea81e08d22&app_cert_sn=50fa7bc5dc305a4fbdbe166689ddc827&app_id=2014072300007148&biz_content={"button":[{"actionParam":"ZFB_HFCZ","actionType":"out","name":"话费充值"},{"name":"查询","subButton":[{"actionParam":"ZFB_YECX","actionType":"out","name":"余额查询"},{"actionParam":"ZFB_LLCX","actionType":"out","name":"流量查询"},{"actionParam":"ZFB_HFCX","actionType":"out","name":"话费查询"}]},{"actionParam":"http://m.alipay.com","actionType":"link","name":"最新优惠"}]}&charset=GBK&method=alipay.mobile.public.menu.add&sign_type=RSA2'))

**Comment by texadactyl** [comment]
Sorry but its hard to tell why you created an issue.  Are you reporting a bug or requesting an enhancement?  Your program works as expected.

Attached is a simpler form of your source code (essai.py.txt).
My test message for sign/verify is not a certificate but it could be.
[essai.py.txt](https://github.com/Legrandin/pycryptodome/files/4382270/essai.py.txt)

**Comment by YXinAndy** [comment]
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
from Crypto.Hash import SHA256
import base64

def RSA_sign(data):
    privateKey = "MIIEowIBAAKCAQEA08uOAJPiSyGK2kgWhgapEdPMXV1NiLDCZVtoNRsRygfiIh4Z7pDnJsY31K/ZPz1793Wi8wXJcwN4YK61ES6a1IBZ+/DT0ipXwpPyjrz1lSkEBC8j9LmayRT3HXvfZyV7Lgb6n3gc+MW+SZ8RAdvEnrSySl/nnjl4uOY0yWEhYQXHTqjPJKQ4D6v2N0tj6eIPYR78TFlrNx1oWN5XYlgo+ttAyWgQFe4oTcwRW57/oP2IfSBQwMq7e2E+/zLLr1GyETG22nzfrabpwT7YwFtIdp5d+8pcxur7EsO7CwRbjZcL6n4oblaXe4iEj2HFeweR7hZBxkHd5u/mnSce6FP3TQIDAQABAoIBAAVzrPEY3W9fqqpZxrKmgz2hPRZ+K1vEaQyg4LrVOoz/zPNh4PsCIeEeoxtHd4koNQO2tH4a/QeH5FZgyOprT7L+ptJUba9wRZgNpOXFuXCggKj26a8IBBL/BiltIeAO1+/kYBkwx1YkCPTuMkrg9Fu9fQVrGJQ7GH9x9ZPley17I5P4cuMPu1HXUzLk23z1lMxYU3FpwwUNUJw+XuWYCyo/GWdimWp9cOuiJWa9gfZAhQVXkOsk1DTuLxL0vcu+xVfmqijLD69e41rmGjkbQVsgAfd8lBHcKm2u4JmYuM29OlUAAnfK+7zsJF7hqqgch868Eb2AmYDHud4QvIzDWiECgYEA+rgfY6nB46RZNhNFgq4BVJzP+f/clYeCe7NPx22y5ceqn5wt3030EfmW9LUJ8t2vmAzyQ/h2vAZ/xgeRGRN8AFectzt2N9imx5zVaextLOGwZ03VxvlH5vesfj2wvaqxfUB9hsM/aR0Jld+b7wCQeJFPawYO8zV/o8ryuZcZ2RUCgYEA2EGNsMBxXvRn/UMfd6UHdlbhBfr3r3k6dqc6n74tRBEBo/yD+HgG7G9cQf+FUC0ADPzp4A+JXDYmNsieF+cq9qsqKIYbEa/jCgvpL9IJWjI82+WQf5TY59FyPmY9jW1wPqhu4bx5IVVB4osLQcxhkCQxcjTXkDF6yP+jOw4rQ1kCgYALambDeu9BFjKZq7b2hEW7PIibsXKxvEHMsBVp1yzWGYlDSzErgbkjOGIPMk8Jp95e5fgB8EY3uXQH6EBLDAARY+vWy/ZOBKdTX2i4MfOmn4AQtBKPxLnpYk2QUe7CNAtw0Ibmo+03NANDt7K55ySs2LDtBpGXsU/mfU8f9ClRIQKBgE7GalfFckbVnv/JsK/DpNk9wpCMICeCcIKCXj+MZi7SRxe2R1h+WH9N/XxpGOXgzpDsnEErR60YaIkyQSyR37ulFCFY4Ilr2bdyKUprJ0781+B+WkmvLegcCpKiaa+X+vhIIMQIBNPYm7xrS/l2+t8n3/8rMo7rB0Aqpwo/GhFZAoGBANR6PphQzV/jDgXy5FGOxQoXKBSHi8Cni0lHE10EjYW0xO+FQkQWf5jLXVsScsrzbuB3s2rcQ2XOw7qI7MtC4bs7aBTapnINa2lgj9MmFZB2uo5FmGFZ5gr17/do8S9h5CCgxX+9OXpGuNrfiiuo5Z7jF9bp+l5Z8XK1VR9leAvF"
    private_keyBytes = base64.b64decode(privateKey)
    priKey = RSA.importKey(private_keyBytes)
    signer = PKCS1_v1_5.new(priKey)
    hash_obj = SHA256.new(data.encode('utf-8'))
    signature = base64.b64encode(signer.sign(hash_obj))
    return signature

def verify_signature(signature, data):
    #print(signature)
    publicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA08uOAJPiSyGK2kgWhgapEdPMXV1NiLDCZVtoNRsRygfiIh4Z7pDnJsY31K/ZPz1793Wi8wXJcwN4YK61ES6a1IBZ+/DT0ipXwpPyjrz1lSkEBC8j9LmayRT3HXvfZyV7Lgb6n3gc+MW+SZ8RAdvEnrSySl/nnjl4uOY0yWEhYQXHTqjPJKQ4D6v2N0tj6eIPYR78TFlrNx1oWN5XYlgo+ttAyWgQFe4oTcwRW57/oP2IfSBQwMq7e2E+/zLLr1GyETG22nzfrabpwT7YwFtIdp5d+8pcxur7EsO7CwRbjZcL6n4oblaXe4iEj2HFeweR7hZBxkHd5u/mnSce6FP3TQIDAQAB"
    public_keyBytes = base64.b64decode(publicKey)
    pubKey = RSA.importKey(public_keyBytes)
    verifier = PKCS1_v1_5.new(pubKey)
    h = SHA256.new(data.encode('utf-8'))
    return verifier.verify(h, base64.b64decode(signature)) # True or False

my_text = "Mary had a little lamb whose fleece was white as snow !@#$%^&*()_-+="
signature = RSA_sign(my_text)


if (verify_signature(signature.decode() + 'hhhh', my_text)):
    print("Test passed")
else:
    print("Test FAILED")
I added some strings to the generated signature. I expected the result to be a failed check, but it was actually a success. I should take this into consideration

> 在 2020年3月26日，上午12:53，Richard Elkins <notifications@github.com> 写道：
> 
> Sorry but its hard to tell why you created an issue. Are you reporting a bug or requesting an enhancement? Your program works as expected.
> 
> Attached is a simpler form of your source code (essai.py.txt).
> My test message for sign/verify is not a certificate but it could be.
> essai.py.txt <https://github.com/Legrandin/pycryptodome/files/4382270/essai.py.txt>

**Comment by YXinAndy** [comment]
I added something to the original generated signature and decoded it. I expected the result to be a failed verification, but now it is a success

**Comment by texadactyl** [comment]
This:
```
verify_signature(decoded_signature + 'hhhh', my_text)
```
and
```
verify_signature(decoded_signature, my_text)
```
are no different.  The reason is that when a signature is created, it is not a simple string of bytes.  The signature block has a structure with a length indicator inside.  The "hhhh" to the right of the signature block is simply ignored.

If you want to see a verification failure, do this:
```
signature = RSA_sign(my_text + "hhhh")
```

I suggest that you close this issue.

**Comment by YXinAndy** [comment]
ok thinks

**Comment by YXinAndy** [comment]
I see that your verify function does not return a value, but why does it return True when I call it，thanks

**Comment by texadactyl** [comment]
Use this program:
...
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
from Crypto.Hash import SHA256
import base64

MAKE_FAILURE = True

def RSA_sign(data):
    privateKey = "MIIEowIBAAKCAQEA08uOAJPiSyGK2kgWhgapEdPMXV1NiLDCZVtoNRsRygfiIh4Z7pDnJsY31K/ZPz1793Wi8wXJcwN4YK61ES6a1IBZ+/DT0ipXwpPyjrz1lSkEBC8j9LmayRT3HXvfZyV7Lgb6n3gc+MW+SZ8RAdvEnrSySl/nnjl4uOY0yWEhYQXHTqjPJKQ4D6v2N0tj6eIPYR78TFlrNx1oWN5XYlgo+ttAyWgQFe4oTcwRW57/oP2IfSBQwMq7e2E+/zLLr1GyETG22nzfrabpwT7YwFtIdp5d+8pcxur7EsO7CwRbjZcL6n4oblaXe4iEj2HFeweR7hZBxkHd5u/mnSce6FP3TQIDAQABAoIBAAVzrPEY3W9fqqpZxrKmgz2hPRZ+K1vEaQyg4LrVOoz/zPNh4PsCIeEeoxtHd4koNQO2tH4a/QeH5FZgyOprT7L+ptJUba9wRZgNpOXFuXCggKj26a8IBBL/BiltIeAO1+/kYBkwx1YkCPTuMkrg9Fu9fQVrGJQ7GH9x9ZPley17I5P4cuMPu1HXUzLk23z1lMxYU3FpwwUNUJw+XuWYCyo/GWdimWp9cOuiJWa9gfZAhQVXkOsk1DTuLxL0vcu+xVfmqijLD69e41rmGjkbQVsgAfd8lBHcKm2u4JmYuM29OlUAAnfK+7zsJF7hqqgch868Eb2AmYDHud4QvIzDWiECgYEA+rgfY6nB46RZNhNFgq4BVJzP+f/clYeCe7NPx22y5ceqn5wt3030EfmW9LUJ8t2vmAzyQ/h2vAZ/xgeRGRN8AFectzt2N9imx5zVaextLOGwZ03VxvlH5vesfj2wvaqxfUB9hsM/aR0Jld+b7wCQeJFPawYO8zV/o8ryuZcZ2RUCgYEA2EGNsMBxXvRn/UMfd6UHdlbhBfr3r3k6dqc6n74tRBEBo/yD+HgG7G9cQf+FUC0ADPzp4A+JXDYmNsieF+cq9qsqKIYbEa/jCgvpL9IJWjI82+WQf5TY59FyPmY9jW1wPqhu4bx5IVVB4osLQcxhkCQxcjTXkDF6yP+jOw4rQ1kCgYALambDeu9BFjKZq7b2hEW7PIibsXKxvEHMsBVp1yzWGYlDSzErgbkjOGIPMk8Jp95e5fgB8EY3uXQH6EBLDAARY+vWy/ZOBKdTX2i4MfOmn4AQtBKPxLnpYk2QUe7CNAtw0Ibmo+03NANDt7K55ySs2LDtBpGXsU/mfU8f9ClRIQKBgE7GalfFckbVnv/JsK/DpNk9wpCMICeCcIKCXj+MZi7SRxe2R1h+WH9N/XxpGOXgzpDsnEErR60YaIkyQSyR37ulFCFY4Ilr2bdyKUprJ0781+B+WkmvLegcCpKiaa+X+vhIIMQIBNPYm7xrS/l2+t8n3/8rMo7rB0Aqpwo/GhFZAoGBANR6PphQzV/jDgXy5FGOxQoXKBSHi8Cni0lHE10EjYW0xO+FQkQWf5jLXVsScsrzbuB3s2rcQ2XOw7qI7MtC4bs7aBTapnINa2lgj9MmFZB2uo5FmGFZ5gr17/do8S9h5CCgxX+9OXpGuNrfiiuo5Z7jF9bp+l5Z8XK1VR9leAvF"
    private_keyBytes = base64.b64decode(privateKey)
    priKey = RSA.importKey(private_keyBytes)
    signer = PKCS1_v1_5.new(priKey)
    hash_obj = SHA256.new(data.encode('utf-8'))
    signature = base64.b64encode(signer.sign(hash_obj))
    return signature

def verify_signature(signature, data):
    #print(signature)
    publicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA08uOAJPiSyGK2kgWhgapEdPMXV1NiLDCZVtoNRsRygfiIh4Z7pDnJsY31K/ZPz1793Wi8wXJcwN4YK61ES6a1IBZ+/DT0ipXwpPyjrz1lSkEBC8j9LmayRT3HXvfZyV7Lgb6n3gc+MW+SZ8RAdvEnrSySl/nnjl4uOY0yWEhYQXHTqjPJKQ4D6v2N0tj6eIPYR78TFlrNx1oWN5XYlgo+ttAyWgQFe4oTcwRW57/oP2IfSBQwMq7e2E+/zLLr1GyETG22nzfrabpwT7YwFtIdp5d+8pcxur7EsO7CwRbjZcL6n4oblaXe4iEj2HFeweR7hZBxkHd5u/mnSce6FP3TQIDAQAB"
    public_keyBytes = base64.b64decode(publicKey)
    pubKey = RSA.importKey(public_keyBytes)
    verifier = PKCS1_v1_5.new(pubKey)
    h = SHA256.new(data.encode('utf-8'))
    return verifier.verify(h, base64.b64decode(signature)) # True or False

my_text = "Mary had a little lamb whose fleece was white as snow !@#$%^&*()_-+="

if MAKE_FAILURE:
    signature = RSA_sign(my_text + 'hhhh')
else:
    signature = RSA_sign(my_text)

if (verify_signature(signature.decode() + 'hhhh', my_text)):
    print("Test passed")
else:
    print("Test FAILED")
...

When MAKE_FAILURE = True, ```verify_signature()``` returns False.
Otherwise, it returns True.

The first argument to ```verify_signature()``` can be ```signature.decode()``` or ```signature.decode() + 'hhhh'```.
As I said before, the signature is a structured block and anything outside the block is ignored.

Clear now?
