### ISSUE TITLE
Little mistake on counter_be.png

### ISSUE THREAD

**Issue by JohnDingeling** [Legrandin/pycryptodome#396]
Hello,
I think I found a little mistake on https://github.com/Legrandin/pycryptodome/blob/master/Doc/src/util/counter_be.png:

The green counter block on this figure is not incremented in the blocks from left to write. I think it should show an incremented counter value in big endian byte order (compare https://github.com/Legrandin/pycryptodome/blob/master/Doc/src/util/counter_le.png)

Best regards

**Comment by Legrandin** [comment]
Thanks. Fixed in 6fb4ca4c73d7e80f336c183dd8ed906d3c4320a2.
