### ISSUE TITLE
Byte string produced by AES cipher isn't usable

### ISSUE THREAD

**Issue by 0100101001010000** [Legrandin/pycryptodome#401]
Hello,

I'm trying to use the encrypted data that comes out of the cipher encryption and pass it to a REST service, unfortunately that data isn't readable and returns the following decode error:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte

For the sake of simplicity I'm using the [Encrypt Data with RSA](https://pycryptodome.readthedocs.io/en/latest/src/examples.html#encrypt-data-with-rsa) example from the Pycryptodome website, and just after the *Encrypt the data with the AES session key* step, I then try to pass it to my REST service:

Option 1:
```python
    [...]
    cipher_aes = AES.new(session_key, AES.MODE_EAX)
    ciphertext, tag = cipher_aes.encrypt_and_digest(document)
    file_out = open("test_encrypted_document_upload.bin", "wb")
    [file_out.write(x) for x in (enc_session_key, cipher_aes.nonce, tag, ciphertext)]

   key = str(uuid.uuid4())
   document = FileStorage(open('./test_encrypted_document_upload.bin'))

    doc_creation = app.test_client().post('/create_encrypted_document', data=dict(
        key=key,
        document=document
    ))
    [...]
```

Option 2:
```python
    [...]
    cipher_aes = AES.new(session_key, AES.MODE_EAX)
    ciphertext, tag = cipher_aes.encrypt_and_digest(document)
    encrypted_string = enc_session_key
    encrypted_string += cipher_aes.nonce
    encrypted_string += tag
    encrypted_string += ciphertext

    key = str(uuid.uuid4())
    doc_creation = app.test_client().post('/create_document', json={
        'key': key,
        'document': encrypted_string
    })
    [...]
```

In both cases I get the same error, however if I pass in an empty byte string then that accepts it without an issue, which pushed me to believe that it was an issue with what the cipher produced. 
So copied the string that was produced and tried playing around with it in the python terminal and as soon as I try to touch it I get that error.

Is this expected behavior?

Thanks

**Comment by texadactyl** [comment]
Things that could possibly be going wrong:

* ```receiver.pem``` from the REST service is okay?
* Is the PEM an RSA type of public key?
* REST service using RSA encryption protocol according to PKCS#1 OAEP?
* REST service using session (secret) key type AES?
* REST service using MODE_EAX?
* REST service session key length = 16?
* REST service expecting ciphertext and a MAC (encrypt_and_digest)?

Please provide your precise source code and the ```receiver.pem``` file.

Is this REST service on the Internet?

**Comment by texadactyl** [comment]
Looking at your code snippet, I think that your REST service is not expecting the raw byte array ```encrypted_string```.  It should be expecting encoding like Base 64, yes?

For example, using my own public key, I got this for an ```encrypted_string``` (309 raw bytes):
```
0000   13 48 2e 2a 43 44 06 28 5e bb c6 69 ef 80 2d 87   .H.*CD.(^..i..-.
0010   39 b6 c0 76 db 76 96 70 da e4 78 61 c8 79 32 8a   9..v.v.p..xa.y2.
0020   3f ab 73 e3 fa 8d f6 b8 6c c3 b5 30 37 02 05 0a   ?.s.....l..07...
0030   c0 59 ff e4 ed 40 6e 42 5b 67 b0 c4 30 21 3f 4e   .Y...@nB[g..0!?N
0040   d7 cc ea 5e 6e c4 fb 1c 0d da 89 f4 87 91 be b7   ...^n...........
0050   49 10 a9 ce 15 ae 0f 60 4f e0 46 aa 6e 6a 91 ac   I......`O.F.nj..
0060   38 4d 16 d0 b9 a4 15 d8 b1 ec ab d5 57 7a 14 85   8M..........Wz..
0070   14 d9 b2 14 3e 92 b2 7b 41 55 d4 99 a1 11 fa 06   ....>..{AU......
0080   d6 8e 4d 8f cc 38 ba ac ed a8 8a 17 7d 51 5e 45   ..M..8......}Q^E
0090   7e e5 78 0c 39 01 dd 0c 4c bf 51 fe 8c 37 46 24   ~.x.9...L.Q..7F$
00A0   6e 0a 9f ad 24 e7 45 93 43 99 31 fe d0 51 66 90   n...$.E.C.1..Qf.
00B0   5e aa f6 00 44 1a 98 a0 24 fc 92 6f 97 94 be 43   ^...D...$..o...C
00C0   7e e3 72 4b 92 1d 6d 4f 1e b3 5a e1 04 e8 a6 35   ~.rK..mO..Z....5
00D0   1b 8b c2 9b bc ba e0 0e 06 11 2d db 6d b4 11 e2   ..........-.m...
00E0   d1 63 d0 09 a7 99 d3 c9 5a d4 2a fb 5f 95 47 27   .c......Z.*._.G'
00F0   bb 13 45 52 58 4d 85 8e e0 f4 45 86 8a 97 26 4f   ..ERXM....E...&O
0100   45 e9 a4 35 c0 18 46 0d b0 ec 09 5d 57 b7 1b d4   E..5..F....]W...
0110   cb cd ea 52 f8 6d dc be 78 50 54 cb 54 70 21 c8   ...R.m..xPT.Tp!.
0120   23 fc 94 6e 01 a1 d7 4f c7 06 ee 98 de c3 de 8b   #..n...O........
0130   9e 35 9a 37 7f ae b5 d8 fd cb 03 78 da c5 36 d3   .5.7.......x..6.
0140   1f b8 68 da 6f                                    ..h.o            ```
```
When you Base 64 encode ```encrypted_string```, you get this as a String:
```
E0guKkNEBiheu8Zp74Athzm2wHbbdpZw2uR4Ych5Moo/q3Pj+o32uGzDtTA3AgUKwFn/5O1AbkJbZ7DEMCE/TtfM6l5uxPscDdqJ9IeRvrdJEKnOFa4PYE/gRqpuapGsOE0W0LmkFdix7KvVV3oUhRTZshQ+krJ7QVXUmaER+gbWjk2PzDi6rO2oihd9UV5FfuV4DDkB3QxMv1H+jDdGJG4Kn60k50WTQ5kx/tBRZpBeqvYARBqYoCT8km+XlL5DfuNyS5IdbU8es1rhBOimNRuLwpu8uuAOBhEt2220EeLRY9AJp5nTyVrUKvtflUcnuxNFUlhNhY7g9EWGipcmT0XppDXAGEYNsOwJXVe3G9TLzepS+G3cvnhQVMtUcCHII/yUbgGh10/HBu6Y3sPei541mjd/rrXY/csDeNrFNtMfuGjabw==
```
```
import base64
encoded = base64.b64encode(encrypted_string).decode("utf-8")
print("Base 64 encoded encrypted_string:", encoded)

```

**Comment by 0100101001010000** [comment]
You are entirely correct my code was expecting base 64 encoding, thank you very much for your help.
