### ISSUE TITLE
ValueError: RSA key format is not supported

### ISSUE THREAD

**Issue by BosnaZmaj** [Legrandin/pycryptodome#404]
I am trying to import an key "public.pem" with key= RSA.importKey(f.read()) and get this error

**Comment by texadactyl** [comment]
Show your complete source code and attach the external file that you are trying to use.

**Comment by texadactyl** [comment]
@BosnaZmaj
Free sample code:
```
from Crypto.PublicKey import RSA

#Generate RSA key pair
key = RSA.generate(4096)

#Write key pair to file in PEM format
f = open('keyfile.pem', 'wb')
f.write(key.exportKey('PEM'))
f.close()

#Read key pair from file formatted in PEM format
f = open('keyfile.pem', 'rb')

#Import key pairs for use
key = RSA.importKey(f.read())

```

Clearly, you don't normally do both generate and import in the same program.

Investigate:
- Maybe your ```public.pem``` is not what you think.
- Did you open the file ```f``` in binary mode (rb)?

**Comment by BosnaZmaj** [comment]
Thank you for reply and suggestions. So can only .pem files that have been created using RSA be imported or do any public/secret .pems be imported.

**Comment by texadactyl** [comment]
Think of RSA, Diffie-Hellman, ECC, and others as protocols or languages.  You cannot mix them.

When you generate an RSA key pair and store it for later use, it is expected that during the later use, you will retrieve and import it the same way.  In Cryptography, every little detail is important.

**Comment by BosnaZmaj** [comment]
Thank you for the information. I think it was more of an user error on my part.
