### ISSUE TITLE
Wrong code comment for ASN.1 ECDSA signature encoding (?)

### ISSUE THREAD

**Issue by sebastien-rosset** [Legrandin/pycryptodome#405]
The [code comments in DSS.py#L111](https://github.com/Legrandin/pycryptodome/blob/649d981b84eeb1c1a7edb96ba796aad079a0de31/lib/Crypto/Signature/DSS.py#L111) state the ASN.1 encoding of the (r, s) signature parameters are a sequence of OCTET STRING, but I think it is actually a sequence of INTEGER.

RFC 3279 states ECDSA signatures should be DER-encoded as shown below.
```
Ecdsa-Sig-Value  ::=  SEQUENCE  {
           r     INTEGER,
           s     INTEGER 
}
```
Also, while the default is raw binary, it would be worth mentioning that 'der' encoding is the encoding specified in RFC 3279 section 2.2.3 ECDSA Signature Algorithm, RFC 5480.

**Comment by Legrandin** [comment]
Thanks. Fixed in ede2ae08bf0eac7005be829e2a346b8fa6bc20e2 and 5eac14f8ccbee53b68289417683477436ede9c60.
