### ISSUE TITLE
Not able to install pycryptodome in Mac OS X

### ISSUE THREAD

**Issue by iqramali** [Legrandin/pycryptodome#412]
I installed `pycryptodome` in OS X and still python3 not able to find the module Crypto. Can someone tell me what package I need to install in order to use `pycryptodome` in OS X? Followed the instructions mentioned in this [pycryptodome page](https://pycryptodome.readthedocs.io/en/latest/src/installation.html#windows-from-sources-python-2-x-python-3-2) 

```pip list | grep crypto
$pycryptodome          3.9.7
$pycryptodomex         3.9.7
```
Here is the output from install

```
$pip install pycryptodome
$Requirement already satisfied: pycryptodome in /usr/local/lib/python3.7/site-packages (3.9.7)
```

```
$python3 -m Crypto.SelfTest
$/usr/local/opt/python/bin/python3.7: Error while finding module specification for 'Crypto.SelfTest' (ModuleNotFoundError: No module named 'Crypto')
```

EDIT:
I've added more details about my host environment.
```
Darwin xx-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
```

**Comment by texadactyl** [comment]
On my spouse's Macbookair:

```
uname -a
Darwin macbookair.local 17.7.0 Darwin Kernel Version 17.7.0: Tue Feb 18 22:51:29 PST 2020; root:xnu-4570.71.73~1/RELEASE_X86_64 x86_64

python3 --version
Python 3.8.2

pip3 list
Package      Version
------------ -------
numpy        1.17.4
pip          20.1
pycryptodome 3.9.7
scipy        1.3.2
setuptools   41.2.0
```

I cannot reproduce your symptoms with ```python3 -m Crypto.SelfTest```.

**Comment by texadactyl** [comment]
By the way, when you are finally able to run the self-test, you will see this:
```
Skipping GMP tests ([Error 126] The specified module could not be found) ............
```
No harm, no foul.

The O/S ```libgmp*``` packages support multiprecision arithmetic.  They are present on Linux and some Unixes but not the MacOS Unix for some reason.

On my Linux workstation, the AESNI tests are skipped probably because I have an old-ish AMD APU.

**Comment by iqramali** [comment]
OK. I managed to run the self-test after installing libgmp, this is the outpiut

```
----------------------------------------------------------------------
Ran 39553 tests in 81.115s

OK
```
