### ISSUE TITLE
Undocumented magic number in AES CTR mode overflow check

### ISSUE THREAD

**Issue by Dentosal** [Legrandin/pycryptodome#413]
In [`lib/Crypto/Cipher/_mode_ctr.py`, line 205](https://github.com/Legrandin/pycryptodome/blob/6fb4ca4c73d7e80f336c183dd8ed906d3c4320a2/lib/Crypto/Cipher/_mode_ctr.py#L205) there is code checking for counter overflows. However, the number `0x60002` seems arbitrary and I was not able to determine why the specific number was chosen. The overflow check was added in d61f253c54f59422551760b39b88965b71af280b by @Legrandin . I'd like to understand this code, and I would appreciate any help.

```python
if result:
    if result == 0x60002:
        raise OverflowError("The counter has wrapped around in"
                            " CTR mode")
    raise ValueError("Error %X while encrypting in CTR mode" % result)
```

**Comment by Legrandin** [comment]
`0x60002` is the error code `ERR_CTR_REPEATED_KEY_STREAM` defined in the C module:

https://github.com/Legrandin/pycryptodome/blob/master/src/raw_ctr.c#L39
