### ISSUE TITLE
3.9.8 not on pypi?

### ISSUE THREAD

**Issue by mgorny** [Legrandin/pycryptodome#430]
It seems that the 3.9.8 release is found on github but on pypi. Is this intentional? Is the release ready to be used?

**Comment by Legrandin** [comment]
It took some time to upload it into pypi, but now it's there.

**Comment by mgorny** [comment]
The sdist archive is still missing, only wheels are present.

**Comment by Legrandin** [comment]
Thanks for pointing out - they are there too now.
