### ISSUE TITLE
SelfTest consumes almost 90% space

### ISSUE THREAD

**Issue by vnitinv** [Legrandin/pycryptodome#431]
Around 90% which comes to 33 MB, is huge in this Library are from SelfTest.
Is there a way to skip this folder while installation.

```
(base) nitinkr-mbp:Downloads nitinkr$ du -h Cryptodome/
1.5M	Cryptodome//PublicKey
284K	Cryptodome//Util
 76K	Cryptodome//Signature
904K	Cryptodome//Hash
 52K	Cryptodome//IO
 33M	Cryptodome//SelfTest   <<<
1.1M	Cryptodome//Cipher
---
 37M	Cryptodome/
```

**Comment by Legrandin** [comment]
This is fixed in version 3.10.1, the largest test vectors are now in a separate package (`pycryptodome-test-vectors`)
