### ISSUE TITLE
Usage of HMAC

### ISSUE THREAD

**Issue by StevenLOL** [Legrandin/pycryptodome#432]
Hi, 

It is not clear how to use the HMAC in the following document:

https://github.com/Legrandin/pycryptodome/blob/master/Doc/src/hash/hmac.rst

eg:

Where is the "msg" and "mac" come from in the code block?

**Comment by texadactyl** [comment]
I suggest that you read the Pycryptodome documentation.  HMAC starts here:
[https://pycryptodome.readthedocs.io/en/latest/src/hash/hmac.html?highlight=HMAC](url)

I highly recommend reading the referenced document:
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.198-1.pdf

**Comment by StevenLOL** [comment]
Thanks
