### ISSUE TITLE
Decrypting textbook/no padding RSA values?

### ISSUE THREAD

**Issue by dstaley** [Legrandin/pycryptodome#434]
PyCrypto had the `RSA.decrypt` method to decrypt textbook RSA encoded values. I understand that PyCryptodome doesn't support encrypting or decrypting these values through the same method, but is there an alternative/hidden/private method that would achieve the same result? If not, is there a suggested alternative? I understand that it's not secure, but I'm just looking to decrypt some previously-encrypted values.

**Comment by texadactyl** [comment]
Ignore the APIs for the moment.  I suggest that you start with a description of what you are trying to accomplish.  What problem in the real world are you trying to solve?  Then, it would help to know why you are looking at RSA.  That might be the wrong tool.

**Comment by dstaley** [comment]
Yeah I totally realize this sounds like a terrible idea! I'm working on building a modern Python version of a tool that decrypts files stored in an old content management system. I have it working with Pycrypto, but would love to use Pycryptodome since it's much easier to install.

This is certainly not a feature request since this is something I doubt very many people really care about. I'm just trying to find an alternative to the original Pycrypto `RSA.decrypt` just so I can get the data for these files.

**Comment by texadactyl** [comment]
What works with the older pycrypto should also work with pycryptodome with possible minor API syntax changes.  My symmetric key projects have never needed major porting.

By "decrypts files", you are implying that the files are encrypted in storage.  Yes?  RSA for that?  

If the files are encrypted, then the protection is probably in some sort of file-system encryption or there is some sort of application-based storage key being used outside the file-system.  Either way, this is probably some sort of symmetric key based cryptography (DES3, RC2/4, AES, etc.), possibly based on a set of passwords.

**Comment by texadactyl** [comment]
Why don't you explain the detailed mechanics of what you say you are doing successfully with pycrpto.
Source code?

**Comment by dstaley** [comment]
Sure! Here's the working version using Pycrypto.

```python
from Crypto.PublicKey import RSA
import base64

# Private key in tuple form
key = [1, 1, 1]

bk = "zJuG60z9Iv..." # (obscured)

privatekey = RSA.construct(key)
result = privatekey.decrypt(base64.b64decode(bk))
```

**Comment by texadactyl** [comment]
That ```key``` value cannot be true.
The ```bk``` values is not true either.

**Comment by dstaley** [comment]
Oh yeah no, they're not the actual values. I figured posting the private key along with the actual value in a public forum probably wasn't a smart idea 😁

**Comment by texadactyl** [comment]
If you do not post the full data, how can somebody assist you?  I cannot try and reproduce your results without it.  Also, you never included a stack trace or stdout with symptoms.

Anyways, there is nothing wrong with your program using pycryptodome.  I suspect that you have some other problem  like using the wrong key part values (p, q, n).

**Comment by texadactyl** [comment]
By the way, RSA is primarily used for authentication and protecting symmetric keys.  It's the symmetric key (aka session key) that is used for encrypting data like a "book".  Using RSA for protecting data is very inefficient.

**Comment by dstaley** [comment]
Okay, I think I can use Pycrypto to generate a new private key and ciphertext, so I'll give that a shot so I can provide some actual values.

The issue I get with Pycryptodome is from [this line](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/PublicKey/RSA.py#L378). I tried using the suggested module, but I don't think it would work since my values don't use that particular scheme.

**Comment by texadactyl** [comment]
Use pycryptodome to generate a new private key and ciphertext

**Comment by texadactyl** [comment]
"Use module Crypto.Cipher.PKCS1_OAEP instead"
Did you follow that advice?

**Comment by texadactyl** [comment]
That is one of the changes you have to make in order to migrate to pycryptodome.

**Comment by texadactyl** [comment]
Either you figure it out (best!)
or Give me a sample and as you said and I'll demonstrate the code-change for you.

**Comment by dstaley** [comment]
Yes, I did try but I received errors indicating a decryption failure. I'll post the code from that attempt as well.

**Comment by texadactyl** [comment]
Post the stack trace too.
And the ciphertext.
And the privatekey.

**Comment by texadactyl** [comment]
Keep in mind that I am very bad at mind-reading!   (:

**Comment by texadactyl** [comment]
Free sample RSA pair of programs (sender, receiver) all in once source file.  Note the use of PKCS1_OAEP for creating the RSA key object and AES for the session key that encrypts/decrypts data.  Google "tls message flow" for an intro.

[rsa_tls_test.py.txt](https://github.com/Legrandin/pycryptodome/files/4942018/rsa_tls_test.py.txt)

**Comment by dstaley** [comment]
Alright, so to start, here's a script using PyCrypto that does what I'm attempting to do with PyCryptodome:

```python
from Crypto.PublicKey import RSA
import base64

key = [
    152322480989578381621850917617957686376737319478328911653794546208690021267852654819873296485322477316029479227290153402307319746966985180936578267825645172086617536376523023950114106709136700849371639432143504322747281332612100974654185491348946822042242620647388255432688650196561890884602582603966508523381,
    65537,
    137170883364251292042028128476686859859045777514564531607849711279803281736822374874640008117105787055211984146912587904502394019050269792766147004143215669122852343843533547088367527394487942037826248621222304654737555235502413755052453057515362263456021645913815113496347933509698289700519769657733896535169
]
bk = "aviJz9wJB6CiC6D7QGfEtdCopO+cDW7+UshgYnoRa7KqRW7RMKNAb+2bjN+HNETg1mKX82iEB2wDLBvLFcj4pAhiIjwA+C04s54LHeecsEiE9kErZHR39Dp8FD5gSNM6ys9BtOjuortCvy8phRQJ77o0Y8N/ZthA8uzJ1bsVWRA="

privatekey = RSA.construct(key)
result = privatekey.decrypt(base64.b64decode(bk))
print(result)
```

The result should be `b'hello world'`.

The values were generated using this PyCrypto script:

```python
from Crypto.PublicKey import RSA
import base64

key = RSA.generate(1024)
print([key.n, key.e, key.d]) # key

v = key.encrypt("hello world".encode("utf8"), 32)[0]
print(base64.b64encode(v)) # bk
```

I completely understand this is Not What You Should Do, but I'm not encrypting values as a part of my application. I'm only decrypting values that seem to have been encoded using textbook RSA. There's more steps in the process (involving AES), but I'm trying to focus just on this portion since it's small enough to understand where PyCrypto and PyCryptodome are different.

**Comment by texadactyl** [comment]
The output from the traceback tells you that RSA data encrypt() and decrypt() are not implemented in Pycryptodome (why bother? it is part of PKCS1_OAEP anyways):

```
Traceback (most recent call last):

  File "/mnt/elkdata/linux-home-folder/projects/crypto/rsa_construct.py", line 7, in <module>
    v = key.encrypt("hello world".encode("utf8"), 32)[0]

  File "/home/elkins/anaconda3/lib/python3.7/site-packages/Crypto/PublicKey/RSA.py", line 376, in encrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")

NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
```

The message gave you a hint as to how to proceed, right?  See the documentation 
i.e. https://pycryptodome.readthedocs.io/en/latest/src/cipher/oaep.html?highlight=PKCS1_OAEP#Crypto.Cipher.PKCS1_OAEP.PKCS1OAEP_Cipher

More free source code:
```
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from base64 import b64encode

key = [
    152322480989578381621850917617957686376737319478328911653794546208690021267852654819873296485322477316029479227290153402307319746966985180936578267825645172086617536376523023950114106709136700849371639432143504322747281332612100974654185491348946822042242620647388255432688650196561890884602582603966508523381,
    65537,
    137170883364251292042028128476686859859045777514564531607849711279803281736822374874640008117105787055211984146912587904502394019050269792766147004143215669122852343843533547088367527394487942037826248621222304654737555235502413755052453057515362263456021645913815113496347933509698289700519769657733896535169
]

cleartext1 = b"hello world"
print("cleartext1:\n", cleartext1)

privatekey = RSA.construct(key)
cipher = PKCS1_OAEP.new(privatekey)

ciphertext = cipher.encrypt(cleartext1)
print("\nciphertext:\n", b64encode(ciphertext))

cleartext2 = cipher.decrypt(ciphertext)
print("\ncleartext2:\n", cleartext2)
```

So, instead of decrypting with the RSA key, you do this (2 steps instead of one):
```
cipher = PKCS1_OAEP.new(privatekey)
hello_world = cipher.decrypt(ciphertext)
```
In Pycrypto, it was hidden away.  But, now, you have more control/options.

**Comment by texadactyl** [comment]
Stdout:

```
cleartext1:
 b'hello world'

ciphertext:
 b'G8Rg/7CnXrrHyGcmzhmC9l2nGVQce/I4gUiCk0z+cWXsD9vKbWA9f71QgCZl4deAgdXWwOhzN6zZ5X9MwACi/vCP6REdgOIIXFVuUB3i88kMglw7s+0ZvtRPotIbR/Z8HnnqqMyt6R+2zj3pZCaeG3tMfH0rla54I72GA41Ldyo='

cleartext2:
 b'hello world'
```

**Comment by dstaley** [comment]
Ah, I see! However when I run the following, I get the error "Incorrect decryption". Am I still doing something wrong?

```python
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
import base64

key = [
    152322480989578381621850917617957686376737319478328911653794546208690021267852654819873296485322477316029479227290153402307319746966985180936578267825645172086617536376523023950114106709136700849371639432143504322747281332612100974654185491348946822042242620647388255432688650196561890884602582603966508523381,
    65537,
    137170883364251292042028128476686859859045777514564531607849711279803281736822374874640008117105787055211984146912587904502394019050269792766147004143215669122852343843533547088367527394487942037826248621222304654737555235502413755052453057515362263456021645913815113496347933509698289700519769657733896535169
]

bk = "aviJz9wJB6CiC6D7QGfEtdCopO+cDW7+UshgYnoRa7KqRW7RMKNAb+2bjN+HNETg1mKX82iEB2wDLBvLFcj4pAhiIjwA+C04s54LHeecsEiE9kErZHR39Dp8FD5gSNM6ys9BtOjuortCvy8phRQJ77o0Y8N/ZthA8uzJ1bsVWRA="

privatekey = RSA.construct(key)
cipher = PKCS1_OAEP.new(privatekey)

text = cipher.decrypt(base64.b64decode(bk))
print(text)
```

**Comment by texadactyl** [comment]
```
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
import base64

key = [
    152322480989578381621850917617957686376737319478328911653794546208690021267852654819873296485322477316029479227290153402307319746966985180936578267825645172086617536376523023950114106709136700849371639432143504322747281332612100974654185491348946822042242620647388255432688650196561890884602582603966508523381,
    65537,
    137170883364251292042028128476686859859045777514564531607849711279803281736822374874640008117105787055211984146912587904502394019050269792766147004143215669122852343843533547088367527394487942037826248621222304654737555235502413755052453057515362263456021645913815113496347933509698289700519769657733896535169
]

bk = "aviJz9wJB6CiC6D7QGfEtdCopO+cDW7+UshgYnoRa7KqRW7RMKNAb+2bjN+HNETg1mKX82iEB2wDLBvLFcj4pAhiIjwA+C04s54LHeecsEiE9kErZHR39Dp8FD5gSNM6ys9BtOjuortCvy8phRQJ77o0Y8N/ZthA8uzJ1bsVWRA="

mary = b"Mary had a little lamb"

privatekey = RSA.construct(key)
cipher = PKCS1_OAEP.new(privatekey)

cg = cipher.encrypt(mary)
print(cipher.decrypt(cg))

```
That works fine.  So the private key is okay.
Maybe your bk is erroneous.

**Comment by texadactyl** [comment]
I do not know how the ciphertext in the file was produced.  
Can you decrypt successfully with the old Pycrypto package?
Is this a one-time job?

**Comment by texadactyl** [comment]
Okay, I was able to decrypt ```bk``` using Pycrypto 2.6.1:

```
import Crypto.PublicKey.RSA
from base64 import b64decode
from binascii import hexlify

import Crypto
print("Version:", Crypto.__version__)

key = [
    152322480989578381621850917617957686376737319478328911653794546208690021267852654819873296485322477316029479227290153402307319746966985180936578267825645172086617536376523023950114106709136700849371639432143504322747281332612100974654185491348946822042242620647388255432688650196561890884602582603966508523381,
    65537,
    137170883364251292042028128476686859859045777514564531607849711279803281736822374874640008117105787055211984146912587904502394019050269792766147004143215669122852343843533547088367527394487942037826248621222304654737555235502413755052453057515362263456021645913815113496347933509698289700519769657733896535169
]

bk = "aviJz9wJB6CiC6D7QGfEtdCopO+cDW7+UshgYnoRa7KqRW7RMKNAb+2bjN+HNETg1mKX82iEB2wDLBvLFcj4pAhiIjwA+C04s54LHeecsEiE9kErZHR39Dp8FD5gSNM6ys9BtOjuortCvy8phRQJ77o0Y8N/ZthA8uzJ1bsVWRA="

privatekey = Crypto.PublicKey.RSA.construct(key)

cg = b64decode(bk)
print("\ndecoded bk:", hexlify(cg))
print("\ndecrypted bk:", privatekey.decrypt(cg))
```
Stdout:
```
Version: 2.6.1

decoded bk: b'6af889cfdc0907a0a20ba0fb4067c4b5d0a8a4ef9c0d6efe52c860627a116bb2aa456ed130a3406fed9b8cdf873444e0d66297f36884076c032c1bcb15c8f8a40862223c00f82d38b39e0b1de79cb04884f6412b647477f43a7c143e6048d33acacf41b4e8eea2bb42bf2f29851409efba3463c37f66d840f2ecc9d5bb155910'

decrypted bk: b'hello world'
```

Bottom line:
* The PKCS1_OAEP technique is internally consistent (decrypt(encrypt(x) = x).
* However, PKCS1_OAEP misght not be able to recover what Pycrypto RSA encrypted.  Or maybe my approach was incorrect for your recovery purposes.

I hope that this is a one-time process i.e. you will be recovering the clear files and then doing something else with PKCS1_OAEP as needed.  So I would recommend recovering all of the files with Pycrypto 2.6.1.  After that, use Pycryptodome.

@Legrandin - Any thoughts on this?

**Comment by texadactyl** [comment]
@dstaley   Best wishes with your project.

**Comment by Legrandin** [comment]
Something like this should work (by doing decryption via modular exponentiation):

```python
from Crypto.PublicKey import RSA
import base64
           
key = [
    152322480989578381621850917617957686376737319478328911653794546208690021267852654819873296485322477316029479227290153402307319746966985180936578267825645172086617536376523023950114106709136700849371639432143504322747281332612100974654185491348946822042242620647388255432688650196561890884602582603966508523381,
    65537,
    137170883364251292042028128476686859859045777514564531607849711279803281736822374874640008117105787055211984146912587904502394019050269792766147004143215669122852343843533547088367527394487942037826248621222304654737555235502413755052453057515362263456021645913815113496347933509698289700519769657733896535169
]

bk = "aviJz9wJB6CiC6D7QGfEtdCopO+cDW7+UshgYnoRa7KqRW7RMKNAb+2bjN+HNETg1mKX82iEB2wDLBvLFcj4pAhiIjwA+C04s54LHeecsEiE9kErZHR39Dp8FD5gSNM6ys9BtOjuortCvy8phRQJ77o0Y8N/ZthA8uzJ1bsVWRA="

privatekey = RSA.construct(key)
ct = base64.b64decode(bk)
ct_int = int.from_bytes(ct, 'big')
pt_int = pow(ct_int, privatekey.d, privatekey.n)
pt = pt_int.to_bytes(privatekey.size_in_bytes(), 'big').lstrip(b'\x00')
print(pt)
```

**Comment by texadactyl** [comment]
@dstaley  I have verified this solution independently with Pycryptodome.  Please try it out yourself with real-world files and report back.

**Comment by dstaley** [comment]
@Legrandin Wow, I definitely did not expect that the solution was as easy as a single math operation! Thank you so much!

@texadactyl I really appreciate all the effort you put into helping me, even when it was unclear what I was asking. I'm sincerely grateful for your help over the past few days!

**Comment by julianogv** [comment]
> Something like this should work (by doing decryption via modular exponentiation):
....
 ```

@Legrandin Do you know how to do the reverse? Use pycryptodome to encrypt a text with plain RSA as we were used to do with Pycrypto + RSA.encrypt()?

I have a weird case here where I need to maintain backward compatibility and this kind of encryption is needed and It's kind of stopping me from updating to pycryptodome.

**Comment by Legrandin** [comment]
@julianogv you can do exactly the same, but use the `e` field instead of the `d` field. For instance (untested):

    publickey = RSA.construct(key).public_key()
    pt = b'data_to_encrypt_even_if_it_is_rsa_textbook_so_not_really_secure'
    pt_int = int.from_bytes(pt, 'big')
    ct_int = pow(pt_int, publickey.e, privatekey.n)
    ct = ct_int.to_bytes(publickey.size_in_bytes(), 'big')
    print(ct)
