### ISSUE TITLE
Python3.8 has an error in Chinese encryption

### ISSUE THREAD

**Issue by f-boss** [Legrandin/pycryptodome#439]
When I use AES encryption, I cannot encrypt Chinese, but English can
`  
def aes_encrypt(self, msg, key):
    pad = 16 - len(msg) % 16
    msg = msg + pad * chr(pad)
    encrypts = AES.new(str.encode(key), mode=AES.MODE_CBC, IV=str.encode(self.iv))
    a = str.encode(msg)
    result = encrypts.encrypt(a)
    result_str = base64.b64encode(result).decode('utf-8')
    return result_str
`
When the 'msg' into Chinese times wrong: ValueError: Data must be padded to 16 byte boundary in CBC mode

**Comment by texadactyl** [comment]
Show the whole program.  
Clearly, your "aes_encrypt" is a member function of a class definition.
Sample data?

Your key, msg, and iv should be byte arrays.  Your code is handling them as strings.  Maybe, that is where your code is going awry.

**Comment by f-boss** [comment]
That problem has been solved, thank you

**Comment by texadactyl** [comment]
@f-boss 
Then please close this issue.  Thank you.
