### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by rjotwani** [Legrandin/pycryptodome#441]
Greetings PyCryptodome developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz](https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects](https://github.com/google/oss-fuzz/tree/master/projects) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+).

We've already done the [heavy lifting](https://github.com/google/oss-fuzz/pull/4317), and all we need from you is a primary contact email address to which we can send bug reports. We've found the email `helderijs@gmail.com` in your repository, so please advise if it's alright to use this.

Please let me know if you have any questions about OSS-Fuzz, or if there's anything else I can help with.

Thanks!

Ravi
OSS-Fuzz Team

**Comment by Legrandin** [comment]
That sounds a great and very welcome idea.

Should any result come out of it, feel free to use `security@pycryptodome.org` (`helderijs@gmail.com` works too).

**Comment by rjotwani** [comment]
Thanks, @Legrandin! Closing this issue as our fuzzers have been merged. Please feel free to submit a PR to google/oss-fuzz if you'd like to make any changes.
