### ISSUE TITLE
Mypy stub file is outdated

### ISSUE THREAD

**Issue by Hanaasagi** [Legrandin/pycryptodome#442]
Hello, some Python stub files are outdated. For example `PKCS1_v1_5.new` 

https://github.com/Legrandin/pycryptodome/blob/4fbf0c3229e3b0257a552074ac8992930454af8c/lib/Crypto/Cipher/PKCS1_v1_5.py#L180-L194

It should receive a `Crypto.PublicKey.RSA` object as the `key` argument. But the annoation is still `buffer`.

https://github.com/Legrandin/pycryptodome/blob/4fbf0c3229e3b0257a552074ac8992930454af8c/lib/Crypto/Cipher/PKCS1_v1_5.pyi#L16-L17

**Comment by Legrandin** [comment]
Thanks, fixed with 2f3fdf5e825aa0a088c6fd1a5b14834a4ebfe321
