### ISSUE TITLE
Realize a CBC decrypt function in C++

### ISSUE THREAD

**Issue by zhangxinaaaa** [Legrandin/pycryptodome#443]
Hi,I want to realize a AES CBC decrypt function in C++ which can work with the function called 'cipher.encrypt' in pycryptodome,should I simply compile the source code into a dll? If you have time ,could you simply tell me the procedures to do this?Thank you very much!

**Comment by Legrandin** [comment]
Good reference here https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption
