### ISSUE TITLE
HMAC with SHA3 functions

### ISSUE THREAD

**Issue by Cryptanalyse** [Legrandin/pycryptodome#444]
The HMAC package does not allow to instantiate an object with SHA3 functions from `Crypto.Hash`.
The reason pertains to the absence of `block_size` for the SHA3 family in PyCryptodome ([exception raised here](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Hash/HMAC.py#L80)).
However, the [FIPS 202](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf) provides block sizes for these HMAC functions (Table 3, Page 22).

```python
from Crypto.Hash import HMAC, SHA1, SHA3_256
assert SHA1.new(b"").hexdigest() == "da39a3ee5e6b4b0d3255bfef95601890afd80709"
assert SHA3_256.new(b"").hexdigest() == "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a"
HMAC.new(key = b"", digestmod = SHA1).hexdigest()     # Works
HMAC.new(key = b"", digestmod = SHA3_256).hexdigest() # Fails
```

Is there a plan to incorporate those in PyCryptodome?
OpenSSL has test vectors for those cases [here](https://github.com/openssl/openssl/blob/master/test/recipes/30-test_evp_data/evpmac_common.txt#L136).

**Comment by Legrandin** [comment]
This is now supported in master.

**Comment by Cryptanalyse** [comment]
Thanks!
