### ISSUE TITLE
Crypto.Signature.pkcs1_15.PKCS115_SigScheme.verify behaves differently than specified

### ISSUE THREAD

**Issue by user163** [Legrandin/pycryptodome#445]
Issue:
------
According to the documentation `Crypto.Signature.pkcs1_15.PKCS115_SigScheme.verify` is supposed to throw a `ValueError ` in case of an invalid signature. This does not happen. Instead, the result is given as return value. This can be reproduced with the following code:

    from Crypto.PublicKey import RSA
    from Crypto.Signature import PKCS1_v1_5 as padding
    from Crypto.Hash import SHA256

    # Generate key pair
    privateKey = RSA.generate(1024)
    publicKey = privateKey.publickey()

    # Signing
    data = b'Some data'
    dataHash = SHA256.new(data)
    dataSignature = padding.new(privateKey).sign(dataHash)

    # Verifying
    otherData = b'Some other data'
    otherDataHash = SHA256.new(otherData)
    try:
        verified = padding.new(publicKey).verify(otherDataHash, dataSignature) 
        print(verified)
    except (ValueError):
        print('ValueError thrown')

Please note:
`Crypto.Signature.pss.PSS_SigScheme.verify` behaves according to the documentation and generates a `ValueError` in case of an invalid signature.

Possible solutions:
-------------------
Option 1: `Crypto.Signature.pkcs1_15.PKCS115_SigScheme.verify` should behave according to the documentation. 
Option 2: The documentation is revised so that the current behavior of the implementation is described.

Option 1 makes more sense with regard to a uniform behavior of PSS and PKCS#1 v1.5 padding.

**Comment by Legrandin** [comment]
In your example, you are importing the obsolete module `Crypto.Signature.PKCS1_v1_5` and not what the [documentation shows](https://www.pycryptodome.org/en/latest/src/signature/pkcs1_v1_5.html) `Crypto.Signature.pkcs1_15`.

The former is a relic from PyCrypto, and indeed it does not raise exceptions. It is there purely for backward compatibility only.

**Comment by user163** [comment]
Yes, as I have learned in the meantime and therefore wanted to update my post, but you were quicker. Thanks and sorry for the trouble.
