### ISSUE TITLE
PBKDF2 is calling `c+1` times the PRF instead of `c` times

### ISSUE THREAD

**Issue by vstoykovbg** [Legrandin/pycryptodome#447]
```
#!/usr/bin/python3

from Crypto.Protocol.KDF import PBKDF2
from Crypto.Hash import SHA512
from Crypto.Hash import HMAC
from Crypto.Util.strxor import strxor

from hashlib import sha512 as sha512_from_hashlib

import binascii

from importlib_metadata import version
print ("pycryptodome version:", version('pycryptodome'))


def print_digest(digest):
    print ("** print_digest: **")
    print ("Digest size: ", len(digest), "bytes")
    print ("Digest in hex format:", binascii.b2a_hex(digest).decode("utf-8"))
    print ("Digest in base64 format:", binascii.b2a_base64(digest).decode("utf-8"))

password = b'MyP@SSW0RD.c0rrect.horse.batt3ry.staple'
salt  = b'9c34a47ee5c81e76ab8e2c8f2937f155'
salt = binascii.a2b_hex(salt)

# making it 128 bytes to avoid padding with zeroes
password = sha512_from_hashlib(password).digest()
password = password + sha512_from_hashlib(password).digest()

#password = password + b'making it a little longer than 128 bytes'


def SHA512_digest(input):
    print("SHA512_digest("+ binascii.b2a_hex(input).decode("utf-8") + ")")
    return sha512_from_hashlib(input).digest()


def MyHMAC_SHA512(key, msg):
    print("MyHMAC_SHA512("+ binascii.b2a_hex(key).decode("utf-8") + ", " + binascii.b2a_hex(msg).decode("utf-8") + ")")
    # The size of the full SHA-512 hash in bytes.
    digest_size = 64 # 512 bits = 64 bytes
    # The internal block size of the hash algorithm in bytes.
    block_size = 128 # 1024 bits = 128 bytes
    if len(key) < block_size:
        print ("The key size is smaller than the block size")
        key_0 = key + b"\x00" * (block_size - len(key))
    elif len(key) > block_size:
        print ("The key size is bigger than the block size")
        hash_k = SHA512_digest(key)
        key_0 = hash_k + b"\x00" * (block_size - len(hash_k))
    else:
        print ("The key size is equal to the block size")
        key_0 = key
    key_0_ipad = strxor(key_0, b"\x36" * len(key_0))
    inner = SHA512_digest(key_0_ipad + msg)
    key_0_opad = strxor(key_0, b"\x5c" * len(key_0))
    outer = SHA512_digest(key_0_opad + inner)
    return outer



digest_PBKDF2 = PBKDF2(password, salt, 64, count=5, hmac_hash_module=SHA512)

#print_digest(digest_PBKDF2)
#print ("\n")

digest_test = PBKDF2(password, salt, 64, count=5, prf=MyHMAC_SHA512)

print ("\n")
print_digest(digest_test)

assert digest_PBKDF2 == digest_test
```

```
$ ./demo_PBKDF2.py | grep ^MyHMAC  | wc -l
6
```

Expected result: to get `5`.
What happens: I get `6`.

Maybe at some point the `PBKDF2` is calling the PRF one more time without using the output. But the [code](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Protocol/KDF.py) is difficult to read and I can't find exactly what happens.

According to the specification on Wikipedia the PRF should be called exactly `5` times when the specified iteration count is `5`.

I am reading other implementations and there are indeed 5 calls of the hash function where the iteration count is 5.
For example:

    for(var i=0; i<iterations; ++i)

This will count from 0 to 4 when the `iterations` is 5.

Source: http://anandam.name/pbkdf2/pbkdf2.js.txt

This Perl source code is more readable: https://metacpan.org/release/Crypt-PBKDF2/source/lib/Crypt/PBKDF2.pm

    sub PBKDF2 {
      my ($self, $salt, $password) = @_;
      my $iterations = $self->iterations;
      my $hasher = $self->hasher;
      my $output_len = $self->output_len || $hasher->hash_len;
     
      my $hLen = $hasher->hash_len;
      my $l = int($output_len / $hLen);
      my $r = $output_len % $hLen;
     
      if ($l > 0xffffffff or $l == 0xffffffff && $r > 0) {
        croak "output_len too large for PBKDF2";
      }
     
      my $output;
     
      for my $i (1 .. $l) {
        $output .= $self->_PBKDF2_F($hasher, $salt, $password, $iterations, $i);
      }
     
      if ($r) {
        $output .= substr( $self->_PBKDF2_F($hasher, $salt, $password, $iterations, $l + 1), 0, $r);
      }
     
      return $output;
    }
     
     

    sub _PBKDF2_F {
      my ($self, $hasher, $salt, $password, $iterations, $i) = @_;
      my $result = 
      my $hash = 
        $hasher->generate( $salt . pack("N", $i), $password );
     
      for my $iter (2 .. $iterations) {
        $hash = $hasher->generate( $hash, $password );
        $result ^= $hash;
      }
     
      return $result;
    }
     

First, it makes the initial hash, and then counts from `2` to `$iterations`. This means that if the `$iterations` is `5` it will make the initial hash, then count from `2 ` to `5`. And this way it will call the ` $hasher->generate(...)` `5` times total.

I think there is a bug in the Python implementation, but it's difficult to track.

I am not sure why it's calculating the correct test vectors. Maybe the result of the call is not used.

-----

Here is the full output:

    $ ./test.py 
    pycryptodome version: 3.9.8
    MyHMAC_SHA512(0385336cb20f042688e0ae0dcb31f28f3b4a3c687fab895455a72c3a28ae6e4ca8d7f542853eb0cfd4ceaabb332ee64b83daf676a2facb7a5a6bc471e0f4c0bd434e6424244844e9e290adf6a16f1b513a9001d7beeac44e4dc777acef027c8e0e7691802df2a6186f4b13cff9a781a81b9851385bc678034cfb98fd81ce5573, 9c34a47ee5c81e76ab8e2c8f2937f15500000001)
    The key size is equal to the block size
    SHA512_digest(35b3055a84393210bed6983bfd07c4b90d7c0a5e499dbf6263911a0c1e98587a9ee1c374b30886f9e2f89c8d0518d07db5ecc04094ccfd4c6c5df247d6c2f68b75785212127e72dfd4a69bc097592d670ca637e188dcf2787bf1419ad9344ab83840a7b61bc4902e597d25f9cf91b79e2dae670e6df04e357acdaecbb7f863459c34a47ee5c81e76ab8e2c8f2937f15500000001)
    SHA512_digest(5fd96f30ee53587ad4bcf251976daed36716603423f7d50809fb706674f23210f48ba91ed962ec938892f6e76f72ba17df86aa2afea697260637982dbca89ce11f123878781418b5beccf1aafd33470d66cc5d8be2b69812119b2bf0b35e20d2522acddc71aefa4433174f93a5fbddf447c40d64079a245f10a7c4a1dd92092f53ed1c38365481bc8bb6eca51c931451ed4f0eb5f9ba7605e4347ff5490ba553db05f53d58752d76f63e25a2e08d17225ca45d92b44e93706560b4611496c214)
    MyHMAC_SHA512(0385336cb20f042688e0ae0dcb31f28f3b4a3c687fab895455a72c3a28ae6e4ca8d7f542853eb0cfd4ceaabb332ee64b83daf676a2facb7a5a6bc471e0f4c0bd434e6424244844e9e290adf6a16f1b513a9001d7beeac44e4dc777acef027c8e0e7691802df2a6186f4b13cff9a781a81b9851385bc678034cfb98fd81ce5573, 00f139ab481a88b245276875f3853993153b22ce183c71eacc83b3f724d7bc24f265afd27adb397de2f53b4ff477145fada2b9e2263359905252772b4ca826c0)
    The key size is equal to the block size
    SHA512_digest(35b3055a84393210bed6983bfd07c4b90d7c0a5e499dbf6263911a0c1e98587a9ee1c374b30886f9e2f89c8d0518d07db5ecc04094ccfd4c6c5df247d6c2f68b75785212127e72dfd4a69bc097592d670ca637e188dcf2787bf1419ad9344ab83840a7b61bc4902e597d25f9cf91b79e2dae670e6df04e357acdaecbb7f8634500f139ab481a88b245276875f3853993153b22ce183c71eacc83b3f724d7bc24f265afd27adb397de2f53b4ff477145fada2b9e2263359905252772b4ca826c0)
    SHA512_digest(5fd96f30ee53587ad4bcf251976daed36716603423f7d50809fb706674f23210f48ba91ed962ec938892f6e76f72ba17df86aa2afea697260637982dbca89ce11f123878781418b5beccf1aafd33470d66cc5d8be2b69812119b2bf0b35e20d2522acddc71aefa4433174f93a5fbddf447c40d64079a245f10a7c4a1dd92092f9c3c94f82bd6c44ff4c8f1518b78df58725ba4a6946873e36c7c080dd52d4801b2db59ed038251af99cf32a06f5b756cca56724b24b92f8f9c50034127e2fb99)
    MyHMAC_SHA512(0385336cb20f042688e0ae0dcb31f28f3b4a3c687fab895455a72c3a28ae6e4ca8d7f542853eb0cfd4ceaabb332ee64b83daf676a2facb7a5a6bc471e0f4c0bd434e6424244844e9e290adf6a16f1b513a9001d7beeac44e4dc777acef027c8e0e7691802df2a6186f4b13cff9a781a81b9851385bc678034cfb98fd81ce5573, f969deb1a2b6139ca0e76c5dd4974ece94457c918b6962994e6d00c788b977835395ad305056b922bfc9b2f40f2b07f36eb6338f3c03aab5403030f72fdfd6be)
    The key size is equal to the block size
    SHA512_digest(35b3055a84393210bed6983bfd07c4b90d7c0a5e499dbf6263911a0c1e98587a9ee1c374b30886f9e2f89c8d0518d07db5ecc04094ccfd4c6c5df247d6c2f68b75785212127e72dfd4a69bc097592d670ca637e188dcf2787bf1419ad9344ab83840a7b61bc4902e597d25f9cf91b79e2dae670e6df04e357acdaecbb7f86345f969deb1a2b6139ca0e76c5dd4974ece94457c918b6962994e6d00c788b977835395ad305056b922bfc9b2f40f2b07f36eb6338f3c03aab5403030f72fdfd6be)
    SHA512_digest(5fd96f30ee53587ad4bcf251976daed36716603423f7d50809fb706674f23210f48ba91ed962ec938892f6e76f72ba17df86aa2afea697260637982dbca89ce11f123878781418b5beccf1aafd33470d66cc5d8be2b69812119b2bf0b35e20d2522acddc71aefa4433174f93a5fbddf447c40d64079a245f10a7c4a1dd92092f5bdb444e518caac5afdcd9cd000ddc4d41fb4f168cf37a9dd061c4287bb4569d6da817f351751e04850df43e6826584b2c51b9c6f1beee57131e504b4f1375f0)
    MyHMAC_SHA512(0385336cb20f042688e0ae0dcb31f28f3b4a3c687fab895455a72c3a28ae6e4ca8d7f542853eb0cfd4ceaabb332ee64b83daf676a2facb7a5a6bc471e0f4c0bd434e6424244844e9e290adf6a16f1b513a9001d7beeac44e4dc777acef027c8e0e7691802df2a6186f4b13cff9a781a81b9851385bc678034cfb98fd81ce5573, 9a658f406d6b2d1a88e0a054af3ff304e4d3aaf7e74b9ebee5ecb4f2c01329b3bf7b20dd72d55576ac30c3cf0b466ae1f688bd61cf23d76a6aed75f17ef9df10)
    The key size is equal to the block size
    SHA512_digest(35b3055a84393210bed6983bfd07c4b90d7c0a5e499dbf6263911a0c1e98587a9ee1c374b30886f9e2f89c8d0518d07db5ecc04094ccfd4c6c5df247d6c2f68b75785212127e72dfd4a69bc097592d670ca637e188dcf2787bf1419ad9344ab83840a7b61bc4902e597d25f9cf91b79e2dae670e6df04e357acdaecbb7f863459a658f406d6b2d1a88e0a054af3ff304e4d3aaf7e74b9ebee5ecb4f2c01329b3bf7b20dd72d55576ac30c3cf0b466ae1f688bd61cf23d76a6aed75f17ef9df10)
    SHA512_digest(5fd96f30ee53587ad4bcf251976daed36716603423f7d50809fb706674f23210f48ba91ed962ec938892f6e76f72ba17df86aa2afea697260637982dbca89ce11f123878781418b5beccf1aafd33470d66cc5d8be2b69812119b2bf0b35e20d2522acddc71aefa4433174f93a5fbddf447c40d64079a245f10a7c4a1dd92092fefc4cbf8e14b49be7c635f8386db45eb5ec8670eca99ff61ede322a27b18ae22c22ee7166a3639c7915e776b83ad161df44bdf40d19fc9ace8b7bd97fe92b194)
    MyHMAC_SHA512(0385336cb20f042688e0ae0dcb31f28f3b4a3c687fab895455a72c3a28ae6e4ca8d7f542853eb0cfd4ceaabb332ee64b83daf676a2facb7a5a6bc471e0f4c0bd434e6424244844e9e290adf6a16f1b513a9001d7beeac44e4dc777acef027c8e0e7691802df2a6186f4b13cff9a781a81b9851385bc678034cfb98fd81ce5573, b469f06034eeefadf67839a306c86b5600a1a5b30d78e7c73ce6fc1bb25f878e54c9440ada5f53234644ae3123ab5fafa45f3bcdde9063879da1375797d83230)
    The key size is equal to the block size
    SHA512_digest(35b3055a84393210bed6983bfd07c4b90d7c0a5e499dbf6263911a0c1e98587a9ee1c374b30886f9e2f89c8d0518d07db5ecc04094ccfd4c6c5df247d6c2f68b75785212127e72dfd4a69bc097592d670ca637e188dcf2787bf1419ad9344ab83840a7b61bc4902e597d25f9cf91b79e2dae670e6df04e357acdaecbb7f86345b469f06034eeefadf67839a306c86b5600a1a5b30d78e7c73ce6fc1bb25f878e54c9440ada5f53234644ae3123ab5fafa45f3bcdde9063879da1375797d83230)
    SHA512_digest(5fd96f30ee53587ad4bcf251976daed36716603423f7d50809fb706674f23210f48ba91ed962ec938892f6e76f72ba17df86aa2afea697260637982dbca89ce11f123878781418b5beccf1aafd33470d66cc5d8be2b69812119b2bf0b35e20d2522acddc71aefa4433174f93a5fbddf447c40d64079a245f10a7c4a1dd92092fa6c818d80b4b4237260782b1b232383b0980161b5bee34716a98eab6682b545eb7fe4ada25d70c95f34148045abffc370afe2514453cce7ca352d50dc53a0dc4)
    MyHMAC_SHA512(0385336cb20f042688e0ae0dcb31f28f3b4a3c687fab895455a72c3a28ae6e4ca8d7f542853eb0cfd4ceaabb332ee64b83daf676a2facb7a5a6bc471e0f4c0bd434e6424244844e9e290adf6a16f1b513a9001d7beeac44e4dc777acef027c8e0e7691802df2a6186f4b13cff9a781a81b9851385bc678034cfb98fd81ce5573, 201d15df6a0e40351e0c5fc24eaa498db832bf07626c21d8457a4c2a9a03e1c4d3a9480dacddb4ed770f1b93c40a60650df8129df76e2dcbf9d8292c3c9648a3)
    The key size is equal to the block size
    SHA512_digest(35b3055a84393210bed6983bfd07c4b90d7c0a5e499dbf6263911a0c1e98587a9ee1c374b30886f9e2f89c8d0518d07db5ecc04094ccfd4c6c5df247d6c2f68b75785212127e72dfd4a69bc097592d670ca637e188dcf2787bf1419ad9344ab83840a7b61bc4902e597d25f9cf91b79e2dae670e6df04e357acdaecbb7f86345201d15df6a0e40351e0c5fc24eaa498db832bf07626c21d8457a4c2a9a03e1c4d3a9480dacddb4ed770f1b93c40a60650df8129df76e2dcbf9d8292c3c9648a3)
    SHA512_digest(5fd96f30ee53587ad4bcf251976daed36716603423f7d50809fb706674f23210f48ba91ed962ec938892f6e76f72ba17df86aa2afea697260637982dbca89ce11f123878781418b5beccf1aafd33470d66cc5d8be2b69812119b2bf0b35e20d2522acddc71aefa4433174f93a5fbddf447c40d64079a245f10a7c4a1dd92092f6c4fc06650a5378d3b490e6e1e38f93a0721c783598ff3995528d34a150e2d93875095b56372b43022958ac7593182f58b5033bba5654f425161790f4a3c918c)

    ** print_digest: **
    Digest size:  64 bytes
    Digest in hex format: f7898de5d92719ac8554c21dc04fa682dd3eee1c1b0a4bd21e9eb7f34421845e99eb2e382eda32e7c047ffd617bb46879c3b1e5cfced6a031cf62c56b6c055fd
    Digest in base64 format: 94mN5dknGayFVMIdwE+mgt0+7hwbCkvSHp6380QhhF6Z6y44Ltoy58BH/9YXu0aHnDseXPztagMc9ixWtsBV/Q==

**Comment by Legrandin** [comment]
Your observation is correct: when you pass a custom PRF, the [pure Python implementation](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Protocol/KDF.py#L161) calls the PRF one time more than necessary. That allowed to significantly speed up computation when the count is very large. The output of the last PRF callis not used which indeed explains why the output of PBKDF2 is correct.
