### ISSUE TITLE
exported ECC DER key files incompatible with openssl

### ISSUE THREAD

**Issue by fr3aker** [Legrandin/pycryptodome#449]
When creating a DER-encoded ECC private key with pycryptodome the output file cannot be loaded with openssl. I do not know if this is a bug within pycryptodome, openssl, or simply an incompatibility.

My findings:
**works**:
Importing keys from openssl works (pub/priv).
Importing keys from pycryptodome works (pub/priv).
Exporting public keys and opening them with openssl works.

**works not**:
Exporting private keys and opening them with openssl does not work.

openssl error message:

```
read EC key
unable to load Key
error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1130:
error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:crypto/asn1/tasn_dec.c:694:
error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:627:Field=privateKey, Type=EC_PRIVATEKEY
error:10092010:elliptic curve routines:d2i_ECPrivateKey:EC lib:crypto/ec/ec_asn1.c:979:
```

code to reproduce:

    # create key with openssl
    openssl ecparam -name secp384r1 -genkey -noout -outform DER -out openssl.der
    # print private key information
    openssl ec -in openssl.der -inform DER -text -noout
    # export public key
    openssl ec -in openssl.der -inform DER -outform DER -pubout -out openssl.der.pub
    # print public key information
    openssl ec -pubin -in openssl.der.pub -inform DER -text -noout

pycd.py

```
from Crypto.PublicKey import ECC
with open('openssl.der', 'rb') as fh:
  key = ECC.import_key(fh.read())
# same error when doing
# key = ECC.generate(curve='NIST P-384')
with open('pycd.der', 'wb') as fh:
  fh.write(key.export_key(format='DER', compress=True))

```

then run `openssl ec -in pycd.der -inform DER -text -noout`

**Comment by Legrandin** [comment]
By default, `export_key()` will encode the private key in PKCS#8 format, which the `openssl ec` command does not accept.

You can output the key without PKCS#8 formatting with the `use_pkcs8=False` parameter to `export_key()`.
