### ISSUE TITLE
RSA not support python3.8

### ISSUE THREAD

**Issue by yangkai** [Legrandin/pycryptodome#450]
In _UserFriendlyRNG.py file,  there are codes  "t = time.clock()". "time" module remove "clock" in python 3.8.

**Comment by Legrandin** [comment]
That file is only in PyCrypto, not in PyCryptodome.
See this issue: https://github.com/pycrypto/pycrypto/issues/308

**Comment by yangkai** [comment]
Thanks! I have fixed my issue.
