### ISSUE TITLE
Contribute: Wheel for Python 3.9 under Windows 10 x64

### ISSUE THREAD

**Issue by evandrix** [Legrandin/pycryptodome#456]
for anyone else, like me, having to install this without admin rights: REDACTED

**Comment by Legrandin** [comment]
Sorry, I can't accept attachments and binary I can't verify directly.
BTW, in Windows, even if you do not have admin rights, you can always use `pip --user` or a `virtualenv` to install a package under your account.

**Comment by MrBrax** [comment]
I can't install this because I'd need to download the entire build tools for visual c++ 14, that seems a bit much
