### ISSUE TITLE
discrepency between documentation and implementation

### ISSUE THREAD

**Issue by keesj** [Legrandin/pycryptodome#457]
Hello, 

The [RSA signature verification documentation](https://pycryptodome.readthedocs.io/en/latest/src/signature/signature.html)  states that a ValueError will be raised on failure to verify the a signature. This is however not the case as the [method](https://github.com/Legrandin/pycryptodome/blob/28c3af46ad7bd525f981c1f7e2b68d744bb953f5/lib/Crypto/Signature/PKCS1_v1_5.py#L44) actually catches the exception.

For short currently only the return value of the verify can be used and in normal cases I would expect that indeed this might be a good strategy. The drawback is that when anything goes wrong (including for example passing an invalid sized signature, padding problems, hash size mismatch) the method simply return false and let the developer in the dark on what went wrong (here).

At fist I was thinking this was about the same reasoning [Crypto.Cipher.PKCS1_v1_5](https://pycryptodome.readthedocs.io/en/latest/src/cipher/pkcs1_v1_5.html) Forces somebody to provide a sentinel but the verification method is not time constant (hence will leak what went wrong to the attacker but not to the poor developers like me).

As developer It would be nice to have the primitives to perform the operations myself (to debug) e.g. RSA.encrypt/decrypt, control / debug PKCS paddings, be able to give the hash value myself instead of having to pass a hash object to a sign method. But at least I would like the documentation to match the code and the code to allow for some debugging

**Comment by Legrandin** [comment]
Could you please check the answer to this other issue: https://github.com/Legrandin/pycryptodome/issues/445 .
 
With respect to this:

> As developer It would be nice to have the primitives to perform the operations myself (to debug) e.g. RSA.encrypt/decrypt, control / debug PKCS paddings, be able to give the hash value myself instead of having to pass a hash object to a sign method.

The easiest approach is to monkey patch a temporary hash object, and make it return the hash value you want to sign directly.

**Comment by keesj** [comment]
Thanks I just saw the comment on the other issue.
