### ISSUE TITLE
Enhancement request: abi3 wheels

### ISSUE THREAD

**Issue by Varbin** [Legrandin/pycryptodome#458]
To support multiple Python versions in one wheel, those can be linked to a stable abi version. This would also solve the problem if the Python version changes (e.g. when upgrading a Linux distribution) or a new one is released for which no wheel was released yet. This would avoid issues such as #456 or #440 and even solve #69.

For Windows, the lowest supported Python for ABI3 wheels is 3.5, as earlier versions are compiled with a specific Visual Studio version. I'm not aware of such limitation on other platforms.

Theoretically, it should be enough to use `--py-limited-api cp35` when building wheels, but I have not tested it yet for PyCryptodome.

**Comment by Legrandin** [comment]
`abi3` wheels are now available with version 3.10.1
