### ISSUE TITLE
Unsupported ECC curve

### ISSUE THREAD

**Issue by RyanLiu6** [Legrandin/pycryptodome#459]
I ran into the following error when working on Apple's postback validation for iOS 14.

```
UnsupportedEccFeature: Unsupported ECC curve (OID: 1.2.840.10045.3.1.1)
```

Any chance you could support secp192r1 [NIST P-192, X9.62 prime192v1] (1.2.840.10045.3.1.1)?

Thanks!

**Comment by Legrandin** [comment]
Isn't it possible to use any other stronger curve, like P-256?

**Comment by jneb** [comment]
ECC is strong enough that a 192 bit curve can still be considered strong enough for all but the most paranoid among us.
I'll give it a shot to add a few more curves.

**Comment by Legrandin** [comment]
P-192 is supported in v3.14.0
