### ISSUE TITLE
Minor bug in util/unpad

### ISSUE THREAD

**Issue by Captainowie** [Legrandin/pycryptodome#467]
Hi there.

There is a minor bug in the unpad() function of Util/Padding.py.

If the function is called with zero-length data, and either `pkcs7` (the default) or `x923` are specified as the padding algorithm, then an IndexError is raised at line 88. This is inconsistent with the documentation, which only mentions the possibility of raising ValueErrors.

I wouldn't presume to prescribe the ideal fix, but something like the below ought to suffice:
```python
...
    pdata_len = len(padded_data)
    if not pdata_len:
        raise ValueError("Zero-length input cannot be unpadded")
    if pdata_len % block_size:
...
```
Kind regards
Owen.

**Comment by Legrandin** [comment]
Thanks. Fixed in badc4a942cbae016368e5f79dcbabc146df17a26
