### ISSUE TITLE
CMAC under Python 2.7

### ISSUE THREAD

**Issue by jneb** [Legrandin/pycryptodome#468]
There's a minor issue with CMAC under python 2.7:
If you CMAC a string that isn't a whole multiple of the cipher block size (AES in my case), you get:
  File "C:\Python27\lib\site-packages\Crypto\Hash\CMAC.py", line 210, in digest
    pt = strxor(strxor(self._last_ct, partial), self._k2)
TypeError: argument 2 must be string, not bytearray

The cause of that is that the string is appended with bytes, which are considered a bytearray under Python 2.7.
The easy fix is by adding in line 211:
            partial = type(self._last_ct)(partial)
but I must admit is a bit ugly.

**Comment by jneb** [comment]
Oh, I forgot to say: the file in question is Crypto/Hash/CMAC.py of coures

**Comment by texadactyl** [comment]
Have you tried the same code using Python 3.x?  Python 2.x, as you probably know, is no longer supported.
I cannot reproduce this anomaly using Python 3.8 with the attached source code.
```
from Crypto.Hash import CMAC
from Crypto.Cipher import AES


def try_cmac(arg_data, arg_key):
    print('Data: {} ({} bytes)'.format(arg_data, len(arg_data)))
    msgbytes = bytes(arg_data, 'utf-8')
    ref_mac = CMAC.new(arg_key, msg=msgbytes, ciphermod=AES).digest()

    # Break up message into chunks of different length.
    # The resulting MAC must always be the same.
    for chunk_length in 1, 2, 3, 7, 10, 13, 16, 17, 40, 80, 125, 128:
        chunks = [msgbytes[i : i + chunk_length] for i in range(0, len(msgbytes), chunk_length)]
        mac = CMAC.new(arg_key, ciphermod=AES)
        for chunk in chunks:
            mac.update(chunk)
        print('\tChunk length {}'.format(chunk_length))
        assert ref_mac == mac.digest()

key = b'1234567890123456'
try_cmac("Mary had a little lamb 1", key)
try_cmac("Mary had a little lamb 12", key)
try_cmac("Mary had a little lamb 123", key)
```

**Comment by jneb** [comment]
It works perfectly under python 3! I wasn't expecting otherwise; I use
pycryptodome
quite a lot (I am a cryptographer by profession, so it is sort of my thing
:-) ).
I was under the impression that is was supposed to be backward compatible.
I had to use some legacy code, and i didn't feel like upgrading (since it
was a throwaway project).
So basically, I just was lucky that the rest of pycryptodome did still work
for me (I actually also used AES and HMAC in the same file which worked
fine).
It's no big deal.
Regards, Jurjen.


Op di 10 nov. 2020 15:53 schreef Richard Elkins <notifications@github.com>:

**Comment by Legrandin** [comment]
As far as I can tell, also under Python 2 computing the CMAC of a byte string whose length is not multiple of 16 bytes works fine.

My guess is that you run into this problem: https://www.pycryptodome.org/en/latest/src/faq.html#why-does-strxor-raise-typeerror-argument-2-must-be-bytes-not-bytearray .

**Comment by jneb** [comment]
That's it!
Jurjen

Op zo 15 nov. 2020 21:54 schreef Helder Eijs <notifications@github.com>:
