### ISSUE TITLE
API feature match between RSA and ECC

### ISSUE THREAD

**Issue by cristi-neagu** [Legrandin/pycryptodome#469]
Hello,

That's a rather complicated title, but all i want to ask is this:
Why do RSA key pairs have a `publickey()` method, but ECC key pairs have a `public_key()` method? Shouldn't they be the same?

Thanks.

**Comment by Legrandin** [comment]
RSA key pairs (unlike ECC) came from the PyCrypto, so we have to keep backward compatibility on the API.
Having said that, RSA keys should also have `public_key` for consistency with ECC as you correctly point out.
I will make this change as it is largely overdue...

**Comment by Legrandin** [comment]
Fixed in 0b99f0dc5296b123696ee41478e7c4e943ff1fa8
