### ISSUE TITLE
How to decode a SHA256 object?

### ISSUE THREAD

**Issue by sshan0731** [Legrandin/pycryptodome#471]
Hello,
My task is to encrypt and decrypt strings. I encrypt a sting using SHA256. How can I decrypt it? And, how about sha224, sha256, sha384, sha512, blake2b, blake2s? 
Thanks a lot!

**Comment by Varbin** [comment]
You can't, as those are hash functions. Their purpose is to generate a deterministic - but unique for each input - fixed length string. Those strings cannot be reversed, and it is hard to find two different input string generating the same output string.

If you want to encrypt data, use blockciphers (AES, ...), stream ciphers (ChaCha20, ...) or asymetric ciphers (RSA, ...). Do not forget to protect your cipher texts (using AEAD constructs or MACs).
To avoid mistakes when implementing such things, try using a high-level library like NaCl (e.g. [https://pypi.org/project/PyNaCl/](PyNaCl) in your application which uses a list of secure algorithms and combinations by default. In contrast to NaCl, this library (PyCryptodome) is very low level.
