### ISSUE TITLE
PyCryptodome seems to use "latin1" encoding.

### ISSUE THREAD

**Issue by BeyondEvil** [Legrandin/pycryptodome#475]
Consider:

```py
from Crypto.Random import get_random_bytes

def main():
    nonce = get_random_bytes(12)
    nonce.decode()
```

Will fail with:

```bash
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 1: invalid start byte
```

passing in "latin1" to `decode` makes the code pass.

macOS 10.15.7
Python 3.7.7
pycryptodome==3.9.9
```bash
$ echo $LANG
en_US.UTF-8
```

What am I doing wrong? Is it possible to set the encoding used by PyCryptodome?

**Comment by Legrandin** [comment]
Can you explain what you are trying to achieve?
`nonce` is a random byte string, not a UTF-8 encoded string.

You get the same behavior with:

```
k = b'jdk\xF5'
k.decode()
```

**Comment by BeyondEvil** [comment]
There's something I obviously doesn't understand here. 😅 

While your example gives me the same error, this does not:

```
k = b'hello'
k.decode()
```

As for what I'm trying to achieve, I need to port the behaviour of [this node library](https://github.com/simonratner/node-encrypted-attr/blob/master/lib/encrypted-attr.js)

Basically I'm getting consuming a secret encrypted by that library and need to decrypt it in my python code.

**Comment by BeyondEvil** [comment]
Solved it by _not_ base64 encoding the `aad` 👍 😊 
 Will update the gist.
