### ISSUE TITLE
float usage with RSA.construct

### ISSUE THREAD

**Issue by paulolops** [Legrandin/pycryptodome#480]
Hello, 

I am trying to generate a private key using RSA.contruct() but the parameters that I need to fill in are floats (because they are longer than an int):

private_key = RSA.construct(pub_key.n, pub_key.e, d, p, q)

When I execute my code an error is raised :
"ValueError: A floating point type is not a natural number"

What should I do to be able to generate the private key ?

Thank you

**Comment by Varbin** [comment]
@paulolops Use an `int` (`long` for Python 2). In Python, the `int` type does not have any length restrictions.
