### ISSUE TITLE
AES in ECB mode test vectors

### ISSUE THREAD

**Issue by rdragos** [Legrandin/pycryptodome#486]
Hi,

I was trying to test ECB mode with AES on a zero key with a zero plaintext as the following:

```
from Crypto.Cipher import AES
key = b'0'*16
data = b'0'*16
cipher = AES.new(key, AES.MODE_ECB)
cipher.encrypt(data)
>>b'\xf9\\\x7fk\x19+"\xbf\xfe\xfd\x1bw\x993\xfb\xfc'
```
However the output does not correspond to the test vector suggested here: https://www.cosic.esat.kuleuven.be/nessie/testvectors/ (see Set 3, vector#  0) which should be `66E94BD4EF8A2C3B884CFA59CA342B2E`
The Rust package for AES matches the test vectors from the COSIC website and also the javascript tool here: https://www.hanewin.net/encrypt/aes/aes-test.htm

There has to be something wrong here as we cannot have multiple outputs for the same determinstic algorithm (AES-ECB).
I have tried to look at your test vectors but couldn't get an easy grasp as to where they taken http://www.iaik.tugraz.at/Research/krypto/AES/old/~rijmen/rijndael/testvalues.tar.gz because this file is not available anymore.

I've also tried to see whether this is a problem with the Big/Little Endian encoding but I don't see this being the issue.

**Comment by Varbin** [comment]
Pycryptodome does not use hexadecimal encoding. When converting from/to hex, it matches the NESSIE test vector:

```python3
from Crypto.Cipher import AES
from binascii import hexlify, unhexlify
key = data = unhexlify(32*'0')
print(hexlify(AES.new(key, AES.MODE_ECB).encrypt(data)).decode())
```

**Comment by rdragos** [comment]
Roger! Thanks for your reply, all good on my end now :+1:
