### ISSUE TITLE
Support for pkcs5

### ISSUE THREAD

**Issue by aress31** [Legrandin/pycryptodome#487]
I would like to know whether it could be possible to add support for `pkcs5` for the padding in `Crypto.Util.Padding`?

**Comment by Varbin** [comment]
I might be wrong, but isn't PKCS#5 padding equivalent to PKCS#7 padding (except PKCS#5 is always for 8 byte blocks)?

**Comment by Legrandin** [comment]
@Varbin is correct, PKCS#7 with block size of 8 bytes is equivalent to PKCS#5.
