### ISSUE TITLE
scrypt performance

### ISSUE THREAD

**Issue by frispete** [Legrandin/pycryptodome#49]
Hi, 

there's some deviation in performance from what is documented, and what I'm able to harvest here.
Using `pycryptodome 3.4.3` with `Python 3.4.5` on a `x86_64` linux machine with a `i7-4790K CPU @ 4.00GHz` and plenty of RAM, `scrypt(N, r, p)` with `(1048576, 8, 1)` is mentioned to take ~5 secs on common hardware from 2009, while it takes ~83 secs on my slightly(!) newer system here. 😟  

Watching the process with ps reveals, that just filling the table takes ~20 secs (time until memory peak load at ~2GB is reached). 

Any idea, why the difference is **that** big?

Here's something to play with::
```
import os
import time
from binascii import hexlify
from Crypto.Protocol.KDF import scrypt

password = os.urandom(8)
password_str = hexlify(password)
salt = os.urandom(16)
salt_str = hexlify(salt)
key_len = 32
N = 2**20
r = 8
p = 1

print('scrypt({password_str}, {salt_str}, key_len = {key_len}, '
      'N = {N}, r = {r}, p = {p}) started'.format(**locals()))
starttime = time.time()
key = scrypt(password, salt, key_len = 32, N = 2**20, r = 8, p = 1)
duration = time.time() - starttime
key_str = hexlify(key)
key_len = len(key)
print('scrypt finished in {duration:.2f} secs: [{key_len}]{key_str}'.format(**locals()))
```

**Comment by Legrandin** [comment]
Indeed the pure Python code was too slow for large values of N.
Fixed in e327c32111b0b90ab1a49c20c19207db51e625d1 by converting some of it to C.
