### ISSUE TITLE
how can i sign some data same as openssl rsautl -sign -pkcs ... way

### ISSUE THREAD

**Issue by quanliyuxin** [Legrandin/pycryptodome#492]
I write some code for create an signature for some image（part.bin）,  signature is not same as i create by openssl. How to have the same signature as openssl ？ thanks
`from Crypto.Hash import SHA256
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5, PKCS1_PSS

h = SHA256.new(open('images/part.bin', "rb").read())

key = RSA.importKey(open('rsa2048_pri.pem', "rb").read())
signer = PKCS1_PSS.new(key)
signatrue = signer.sign(h)

with open("images/part.py-pkcs.sign", "wb") as f:
    f.write(signatrue)`

$ hexdump images/part.py-pkcs.sign 
0000000 5764 d647 6134 9642 fdf3 8aa8 63ea 396d
0000010 1f42 a13e 0cd2 611f 67cb 3cdf 3304 a032
0000020 d630 d606 5352 43a7 364b eb45 9bd6 03a6
0000030 7b88 0605 f191 40b4 fd65 0dde bec6 c62d
0000040 4a1b 017f afe6 2a92 07b4 6e70 8461 8f9a
0000050 87d3 87c9 9b53 fbd7 1468 b768 f945 1e3d
0000060 aee8 5aeb 7398 97e2 5b0a 16a0 388b e7f9
0000070 b692 e978 b0f4 2bcf 3fbf e575 b4d1 bb2b
0000080 348d 5365 d8a3 cc5f 0bca fcd1 ea13 c31f
0000090 c670 e1d4 3675 c7e4 8f35 b1cb c3c6 1cc8
00000a0 c533 621e de0c 4f8b d22b bbfd d8ef f9d0
00000b0 75d8 a74f 8535 7d14 6dd9 1534 f7b7 d2c8
00000c0 ab62 25bd 2078 20d9 835c 205b bc8f 4648
00000d0 d8d8 1fd4 de09 5d76 ad80 5e2b 7f4f bba1
00000e0 12c6 8cfc 8227 8e58 c202 d801 0c2a 6e1a
00000f0 34ec c17a c17f 6ce9 2478 9e19 979f 3835
0000100

when i use openssl  as follow, i will get the result signature(part.pkcs.sign)
$openssl rsautl -sign -in images/part.bin -inkey rsa2048_pri.pem -out images/part.pkcs.sign -pkcs
$ hexdump images/part.pkcs.sign
0000000 9a16 fe13 1bed 8c06 0fd5 31dc 93cc 77c5
0000010 a03b 5395 eb0c 9cdc b208 c2f1 af25 c18f
0000020 a193 5231 2f1c f54f a651 65c6 f924 0285
0000030 5c2e 084a 59a8 b409 0ab0 d52f 837f 8c71
0000040 da49 b3d7 04ac 034b 5b23 7863 093a f851
0000050 c0db 147b e3bd ec8e 7716 b640 a376 a81c
0000060 0734 8a4e 6b30 65b4 d02f 395e 9191 d154
0000070 89e2 9a67 283d ca87 7900 07ca 2aed 0469
0000080 6a79 7458 1d97 3417 94c7 27b6 eb6b 3b0d
0000090 6e18 51d7 8b2c 238d 33b7 1bd9 cb00 6145
00000a0 63b2 439b c881 1370 06e8 286b fc71 107b
00000b0 ee37 1273 a0f4 8dbc 4db0 c862 e5af 876e
00000c0 c0fa a103 723b 0ce2 bc2d 7a19 e436 e86a
00000d0 5544 0594 2752 fb98 bda1 664e 7875 42c1
00000e0 8669 4a49 8d06 0a30 0929 09dc e565 0e18
00000f0 2ece 6d0d f654 d42b 7399 b3c6 91b4 4860
0000100

**Comment by quanliyuxin** [comment]
The signature process implemented in C language is as follows, which is the same as the result of Openssl tool.
if ((p_rsa = PEM_read_RSAPrivateKey(file, NULL, NULL, NULL)) == NULL) {
    ERR_print_errors_fp(stdout);
    return false;
}
RSA_private_encrypt(hashLen, hash_data, signature, p_rsa, RSA_PKCS1_PADDING);

**Comment by Legrandin** [comment]
First, you should use `PKCS1_v1_5` instead of `PKCS1_PSS`.
Second, I think that `openssl rsautl` only supports SHA-1 hashing, so you should use `openssl pkutl` or `openssl dgst` instead.
