### ISSUE TITLE
Cannot import 'XOR'

### ISSUE THREAD

**Issue by QAthulhu** [Legrandin/pycryptodome#495]
I have pycryptodome installed and the self test runs fine and returns OK. But when I try to import XOR using `from Crypto.Cipher import XOR` I get the error `ImportError: cannot import name 'XOR' from 'Crypto.Cipher'`

Installed pycryptodome using pip install.
Python global version: 3.9.1
Virtual env python: 3.9.1
pycryptodome version: 3.9.9
Running `python -m Crypto.SelfTest` returns a lot of dots and
`Ran 39559 tests in 80.623s

OK`

**Comment by Varbin** [comment]
[The XOR 'cipher' class has been removed](https://www.pycryptodome.org/en/latest/src/vs_pycrypto.html), but it is possible to xor strings with [Crypto.Util.strxor](https://www.pycryptodome.org/en/latest/src/util/util.html#module-Crypto.Util.strxor).
