### ISSUE TITLE
Validate associated data when decrypting AES GCM

### ISSUE THREAD

**Issue by j00ris** [Legrandin/pycryptodome#497]
The documentation shows an example of decrypting AES GCM, and it uses the associated data that came with the ciphertext, to update the cipher. Shouldn't this come from an external source, so that it can serve as an additional validation? 

https://github.com/Legrandin/pycryptodome/blame/master/Doc/src/cipher/modern.rst#L172
    >>>     cipher.update(jv['header'])

**Comment by Varbin** [comment]
The associated data is usually transfered/stored with the ciphertext and it is authenticated by the AEAD cipher, but not encrypted. Examples for such data are sequence numbers, headers, protocol or file format versions.

In the documented example a "header" field is used. To validate the header field was not tampered with, it is both included using encryption and decryption. It is included in the MAC tag generation ([line 150 in the same file](https://github.com/Legrandin/pycryptodome/blame/master/Doc/src/cipher/modern.rst#L150)), and in line 172 it is included to be verified later (line 172) together with the decryption and verification of the ciphertext. The `decrypt_and_verify()` invokation would fall if the authenticated data was not included by calling `.update(jv['header'])`.

Does this answer you question?

**Comment by j00ris** [comment]
Yes, sorry, I was only thinking of a use case where the associated data (e.g. database id) is used to ensure that the data cannot be decrypted in another context (e.g. database instance).
