### ISSUE TITLE
The imp module is deprecated

### ISSUE THREAD

**Issue by jolaf** [Legrandin/pycryptodome#498]
The following gets printed on every run on Python 3.6:

`/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py:41: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses`

It seems the fix for #58 was incomplete, see comment there.

**Comment by Legrandin** [comment]
I think you are using an old version of PyCryptodome: the problem you indicate was fixed in v3.7.0 (released in 2018).
The best option is to install the latest version.

**Comment by jolaf** [comment]
I use version 3.9.8.

Also I see the issue in the `master` branch.

Looks like the fix was incomplete.

**Comment by Legrandin** [comment]
I am puzzled, this is the code for v3.9.8:

https://github.com/Legrandin/pycryptodome/blob/4fbf0c3229e3b0257a552074ac8992930454af8c/lib/Crypto/Util/_raw_api.py#L39

and `import imp` cannot be reached with Python 3.

**Comment by jolaf** [comment]
Oh, now I see, I looked in the wrong place. Sorry for bothering.
