### ISSUE TITLE
AES.OCB default nonce length deviates from documentation

### ISSUE THREAD

**Issue by frispete** [Legrandin/pycryptodome#50]
Hi, 

sorry for being such a pest ATM, but I noticed another issue.
OCB mode is documented to use a nonce length of 15. This is also reflected in code:
`Module Crypto/Cipher/_mode_ocb.py: _create_ocb_cipher`, but:
```
--> from Crypto.Cipher import AES
--> plaintext = b'Attack at dawn'
--> key = b'Sixteen byte key'
--> cipher = AES.new(key, AES.MODE_CCM)
--> ciphertext = cipher.encrypt_and_digest(plaintext)
--> len(cipher.nonce)
11
```

I haven't found the code, that is responsible for this deviation.

**Comment by Legrandin** [comment]
I am not sure I follow.
OCB mode has a default nonce length of 15 bytes whereas CCM mode has one of 11 bytes.

**Comment by frispete** [comment]
Oh, man, silly me..
