### ISSUE TITLE
XChaCha nonce changes after calling new()

### ISSUE THREAD

**Issue by csm10495** [Legrandin/pycryptodome#500]
Hey folks, 

Here is an example of the nonce not matching the nonce I gave to new()

```
In [4]: from Crypto.Cipher import ChaCha20
...
In [7]: cipher = ChaCha20.new(key=b'a'*32, nonce=b'a'*24)

In [8]: cipher.nonce
Out[8]: b'\x00\x00\x00\x00aaaaaaaa'
```

The reason why I hit this was because I was using cipher.nonce to get the nonce since that was what was done in the encryption example on the docs: https://pycryptodome.readthedocs.io/en/latest/src/cipher/chacha20.html

Is this expected?

**Comment by Legrandin** [comment]
Thanks for reporting!
This is fixed in version 3.10.1
