### ISSUE TITLE
Probably bug in Blowfish and CFB mode

### ISSUE THREAD

**Issue by jaclas** [Legrandin/pycryptodome#507]
According to the examples created by Bruce Schneier, the author of the Blowfish algorithm:

https://www.schneier.com/wp-content/uploads/2015/12/vectors-2.txt

from ( https://www.schneier.com/academic/blowfish/ )

(see on end of document)

...in OFB mode pycryptodome returns an incorrect result. 

```
bytesdata = bytes.fromhex('37363534333231204E6F77206973207468652074696D6520666F722000')
key = bytes.fromhex('0123456789ABCDEFF0E1D2C3B4A59687')
iv = bytes.fromhex('FEDCBA9876543210')
cipher = Blowfish.new(key, Blowfish.MODE_CFB, iv)
ct = cipher.encrypt(bytesdata)
```

in result I get:

`E7BB1FC3073EB8314B378689FAB0B1160244415D4D017FCE0D9B4CB2FA`

which should be:

`E73214A2822139CAF26ECF6D2EB9E76E3DA3DE04D1517200519D57A6C3`

ps Other modes seem to be correct.

**Comment by Varbin** [comment]
What segment size is used in Schneier's CFB vectors?

**Comment by Legrandin** [comment]
Initializating `cipher` with a full segment size (64 bits for Blowfish) provides the same result:

    cipher = Blowfish.new(key, Blowfish.MODE_CFB, iv, segment_size=64)

By default, segment size is [8 bits](https://www.pycryptodome.org/en/latest/src/cipher/classic.html#cfb-mode).
