### ISSUE TITLE
After installing pycryptodome in arm architecture, python -m Crypto.SelfTest Segmentation fault (core damped)

### ISSUE THREAD

**Issue by yougnen** [Legrandin/pycryptodome#509]
CentOS Linux release 7.6.1810 (AltArch)
Python-3.8.5
pycryptodome-3.10.1-cp35-abi3-manylinux2014_aarch64.whl
I don't know how to solve it。

**Comment by yougnen** [comment]
I solved this problem by installing cffi==1.14.5 pycparser==2.20,and I don't know the specific reason.
Add: python-3.8.5 is installed through source code compilation

**Comment by Legrandin** [comment]
Can you share which platform/CPU you are running on?
And can you share the output of `pip freeze` when `python -m Crypto.SelfTest` gives the segfault?

**Comment by yougnen** [comment]
> 您可以共享正在运行的平台/ CPU吗？
> 并且您可以共享`pip freeze`何时`python -m Crypto.SelfTest`给段错误的输出吗？

![image](https://user-images.githubusercontent.com/56199042/110561615-f751d900-8182-11eb-9869-418adfe4d241.png)

**Comment by yougnen** [comment]
> 您可以共享正在运行的平台/ CPU吗？
> 并且您可以共享`pip freeze`何时`python -m Crypto.SelfT
[root@abc inspection_agent]# /home/yougnen/python38/bin/pip3 install pycryptodome-3.10.1-cp35-abi3-manylinux2014_aarch64.whl
Looking in indexes: http://cmc-cd-mirror.rnd.xxxx.com/pypi/simple/
Processing ./pycryptodome-3.10.1-cp35-abi3-manylinux2014_aarch64.whl
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.10.1
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the '/home/yougnen/python38/bin/python3.8 -m pip install --upgrade pip' command.
[root@abc inspection_agent]# /home/yougnen/python38/bin/pip3 list
Package      Version
------------ -------
pip          20.1.1
pycryptodome 3.10.1
setuptools   47.1.0
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the '/home/yougnen/python38/bin/python3.8 -m pip install --upgrade pip' command.
[root@abc inspection_agent]# /home/yougnen/python38/bin/python3 -m Crypto.SelfTest
Segmentation fault (core dumped)
[root@abc inspection_agent]# uname -a
Linux abc 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by aelgohar** [comment]
[relevant issue?](https://github.com/Legrandin/pycryptodome/issues/506)

**Comment by Legrandin** [comment]
@aelgohar I don't think CentOS runs on the Apple M1 (yet).

**Comment by aelgohar** [comment]
> @aelgohar I don't think CentOS runs on the Apple M1 (yet).

M1 is an ARM processor, so it seems like the common denominator is that it fails on ARM architecture.

**Comment by Legrandin** [comment]
@aelghor The ARM wheels were tested and they work both on the Apple M1 and on the Rasperry PI (64 bit).
It is still not clear to me on which ARM CPU @yougnen was having this problem.

**Comment by aelgohar** [comment]
FWIW, installing cffi==1.14.5 fixed the issue, and that's as far as my understanding goes.

**Comment by whymidnight** [comment]
> FWIW, installing cffi==1.14.5 fixed the issue, and that's as far as my understanding goes.

Another one for M1 8/7 CPU/GPU running Monterey - `pip3 install cffi==1.14.5` fixed it. The issue experienced was a segfault upon something.......`KAT SHA-512/256` when `python3 -m Crypto.SelfTest`. Python3.9 built from source for `arm64`. Still relevant after just doing `pip3 install pycryptodome` today.

**Comment by Legrandin** [comment]
Fixed in version 3.10.3.
