### ISSUE TITLE
in docker container aes encrypt / decrypt speed very slow

### ISSUE THREAD

**Issue by fiefdx** [Legrandin/pycryptodome#513]
host machine intel cpu support aes,
on host machine aes encrypt / decrypt 2M file use 5 seconds,
on the same host, use docker container, on container aes encrypt / decrypt the same 2M file use 60 seconds.

**Comment by Legrandin** [comment]
Can you post the output of `from Crypto.Util import _cpu_features; _cpu_features.have_aes_ni()` from inside the container?

**Comment by fiefdx** [comment]
> Can you post the output of `from Crypto.Util import _cpu_features; _cpu_features.have_aes_ni()` from inside the container?

from container and from host, I get the same result
>>> from Crypto.Util import _cpu_features
>>> _cpu_features.have_aes_ni()
1

**Comment by fiefdx** [comment]
I write a golang aes encrypt / decrypt program, and, the golang program performance on host or on container is the same, so, it should be some issue in this pycryptodome package

**Comment by Legrandin** [comment]
I am seeing a slowdown of "only" 3 times (2.5GB/s to 700MB/s) on an i5 with an Alpine-based image and for memory-only encryption, but so far I didn't pinpoint the cause. It doesn't seem to be due to seccomp related as running docker with `--privileged` doesn't make it much faster.

**Comment by Legrandin** [comment]
After switching from Alpine to Ubuntu for the base image OS, I see that the performance roughly goes back to the original values (outside a container). Therefore, I think the slowdown is due to `muslc`, which might not be the best choice to containerize a performance-sensitive Python app.
