### ISSUE TITLE
Error in sign

### ISSUE THREAD

**Issue by cjkzwe** [Legrandin/pycryptodome#515]
signer = PKCS1_PSS.new(prkey)
bizcontent['content'] = json.dumps(str(base64.b64encode(cipher.encrypt(bytes(ukey.encode(encoding='utf-8')))), encoding='utf-8').replace('+', '-').replace('/', '_'))
digest = SHA256.new()
digest.update(bytes(bizcontent['content'],encoding='utf-8'))
sign = signer.sign(digest)

The signer.sign() always says:'Expected type 'Hash', got 'SHA256Hash' instead'.

**Comment by Varbin** [comment]
I can't reproduce this, executing the below code works forme. Which version do you use?

```python3
from Cryptodome.Hash import SHA256
from Cryptodome.PublicKey import RSA
from Cryptodome.Signature import PKCS1_PSS

key = RSA.generate(1024)
s = PKCS1_PSS.new(key)
d = SHA256.new()
d.update(b''123')
s.sign(d)
```

**Comment by cjkzwe** [comment]
Still don't work......I have reinstallded.
I am using 3.10.1

**Comment by cjkzwe** [comment]
I think this error is like #505

**Comment by cjkzwe** [comment]
Using pip 21.0.1 from c:\users\cjfzw\pycharmprojects\cyrpted_helloword\venv\lib\site-packages\pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: C:\Users\cjfzw\AppData\Local\Temp\pip-ephem-wheel-cache-5egbrtzm
Created temporary directory: C:\Users\cjfzw\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Initialized build tracking at C:\Users\cjfzw\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Created build tracker: C:\Users\cjfzw\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Entered build tracker: C:\Users\cjfzw\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Created temporary directory: C:\Users\cjfzw\AppData\Local\Temp\pip-install-fzoe5smu
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pycryptodome in c:\users\cjfzw\pycharmprojects\cyrpted_helloword\venv\lib\site-packages (3.10.1)
Created temporary directory: C:\Users\cjfzw\AppData\Local\Temp\pip-unpack-sr_mtlir
Removed build tracker: 'C:\\Users\\cjfzw\\AppData\\Local\\Temp\\pip-req-tracker-l9tt5zoc'

**Comment by cjkzwe** [comment]
Using pip 21.0.1 from c:\users\.....\pycharmprojects\cyrpted_helloword\venv\lib\site-packages\pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: C:\Users\.....\AppData\Local\Temp\pip-ephem-wheel-cache-5egbrtzm
Created temporary directory: C:\Users\......\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Initialized build tracking at C:\Users\......\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Created build tracker: C:\Users\......\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Entered build tracker: C:\Users\......\AppData\Local\Temp\pip-req-tracker-l9tt5zoc
Created temporary directory: C:\Users\......\AppData\Local\Temp\pip-install-fzoe5smu
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pycryptodome in c:\users\......\pycharmprojects\cyrpted_helloword\venv\lib\site-packages (3.10.1)
Created temporary directory: C:\Users\......\AppData\Local\Temp\pip-unpack-sr_mtlir
Removed build tracker: 'C:\\Users\\......\\AppData\\Local\\Temp\\pip-req-tracker-l9tt5zoc'

**Comment by Varbin** [comment]
@cjkzwe 

Was Pycrypto installed? If yes, uninstall Pycrypto and Pycryptodome and reinstall Pycryptodome (only!) again.
What is the full traceback? It contains hints in which file of Pycryptodome the error might be.
Can you reproduce this with a fresh virtualenv and just Pycryptodome installed?
Does my example work in your fresh virtualenv? 
What is your _full_ code (including imports) or at least a minimal example that shows the same error?

**Comment by cjkzwe** [comment]
@Varbin In a flesh virtualenv , the pycharm still said 
![image](https://user-images.githubusercontent.com/15699794/115100615-4f44e200-9f70-11eb-880a-f2b259a844b6.png)
But it can run without any error..... May be I should just ignore it.
May be it's just the pycharm's problem...
