### ISSUE TITLE
Missing Python 3.3 Windows wheels

### ISSUE THREAD

**Issue by beardypig** [Legrandin/pycryptodome#52]
I don't know if it's intentional or by accident, but there are no Python 3.3 wheels for `pyCryptodome 3.4.5`. Has 3.3 support been dropped?

**Comment by Legrandin** [comment]
Wheels for 3.3 had been left behind on Appveyor. Now they are on pypi.

**Comment by beardypig** [comment]
Cool, thanks for sorting that @Legrandin :)
