### ISSUE TITLE
_raw*.cp38-win_amd64.pyd - what is it for?

### ISSUE THREAD

**Issue by DarkArcanine** [Legrandin/pycryptodome#521]
Hello, I am sorry if this is not the place but I can't find an answer on this.

What are all the files like _raw*.cp38-win_amd64.pyd in the Cipher folder?
Why do they change? 
(at one point I was messing with a project that used them like a few weeks ago... I tried to run it again and it was asking for the cp39 while it used to run with cp38)
do they change with each release?

**Comment by Varbin** [comment]
They are shared libraries ("DLLs") compiled from C of the [src folder](https://github.com/Legrandin/pycryptodome/tree/master/src). C language is used for performance reasons. As they are recompiled (and the underlying source may change) with each release, they will naturaly change.

With 3.10.1 the "cpXY-win_amd64" part has been dropped from the filename, as they are compatible with all Python versions 3.5 or later (see #458 for details behind this change).
