### ISSUE TITLE
PKCS1_v1_5.verify doesn't raise ValueError

### ISSUE THREAD

**Issue by sven-eliasen** [Legrandin/pycryptodome#522]
Hi !

Here's my spec:
- Windows 10
- Python: 3.8
- pycryptodome: 3.10.1

So my issue is about verifying a signature from a RSA private key with `PKCS1_v1_5`, no problem to sign but when I try to verify with a wrong hash, it doesn't raise any error.

I tried with `pss` and thankfully it raise the correct error but there might think be a bug with `PKCS1_v1_5`.

Here the code I used to test:
```Python
import binascii
import Crypto.Random
from Crypto.Hash import SHA256
from Crypto.PublicKey import RSA
from Crypto.Signature import pss
from Crypto.Signature import PKCS1_v1_5


class Client:
    def __init__(self):
        random = Crypto.Random.new().read
        self.private_key = RSA.generate(1024, random)
        self.public_key = self.private_key.publickey()
        self.signer = PKCS1_v1_5.new(self.private_key)


alice = Client()

msg = b'Message'
tmp1 = SHA256.new(msg)
print("Hash of msg : "+tmp1.hexdigest())

print("-------")

sig = alice.signer.sign(tmp1)
print("sig of hash of msg : "+binascii.hexlify(sig).decode('utf-8'))

print("-------")

msg2 = b'Wrong Message'
tmp2 = SHA256.new(msg2)
print("Hash of wrong msg : "+tmp2.hexdigest())

try:
    PKCS1_v1_5.new(alice.public_key).verify(tmp2, sig)
except (ValueError, TypeError):
    print("Not valid !")
```

**Comment by Varbin** [comment]
I think one is supposed to use [`pkcs1_15`](https://www.pycryptodome.org/en/latest/src/signature/pkcs1_v1_5.html) (lowercase!) for this behaviour.

The lowercase package raises errors, and the uppercase one returns `True`/`False`. If I had to guess, this is for compitability with PyCrypto, [which already had that API](https://www.dlitz.net/software/pycrypto/api/current/Crypto.Signature.PKCS1_v1_5-module.html).

**Comment by sven-eliasen** [comment]
> I think one is supposed to use [`pkcs1_15`](https://www.pycryptodome.org/en/latest/src/signature/pkcs1_v1_5.html) (lowercase!) for this behaviour.
> 
> The lowercase package raises errors, and the uppercase one returns `True`/`False`. If I had to guess, this is for compitability with PyCrypto, [which already had that API](https://www.dlitz.net/software/pycrypto/api/current/Crypto.Signature.PKCS1_v1_5-module.html).

I see, i'm learning with an old tutorial using pycrypto and it didn't even reading the new docs it didn't come in my mind to try in lowercase.

Thank for your answer @Varbin ! 🙂
