### ISSUE TITLE
Unable to match the digital sign with Java

### ISSUE THREAD

**Issue by vcidst** [Legrandin/pycryptodome#523]
I'm communicating with an API Server that verifies the AES encrypted digital signature via Java. However, with pycryptodome the digital sign generated does not match that of server.

Algorithm Specification:
1. BASE64(SHA-256(AESEncryption_HEX(request.body)))
2. Encryption algorithm details 
Algorithm – AES 
Key Size – 128 Bits
Padding – PKCS7Padding
Cyber Block – CBC
Encoding – UTF-8
Message Digest value: SHA-256
AES 128 bits key/ Initial vector

This is my python implementation of the above algorithm,
```py
def _encrypt(self, body):
    # encrypt, hash and encode
    # BASE64(SHA-256(AESEncryption_HEX(request.body)))
    
    # encrypt
    key = bytes.fromhex(self.aes_key)
    data = json.dumps(body).encode("utf-8")
    cipher = AES.new(key, AES.MODE_CBC, self.init_vector.encode("utf-8"))
    encrypted_body = cipher.encrypt(Padding.pad(data, 16, style='pkcs7'))
    
    # hash and encode
    m = hashlib.sha256()
    m.update(encrypted_body)
    sha256 = m.digest()
    return base64.b64encode(sha256).decode("utf-8")
```

However the hashes generated here do not match the Java counterpart. Am I making any strong assumptions in my implementation that I should clarify? Please share any pointers

**Comment by JamesTheAwesomeDude** [comment]
Are the keys being ordered differently in JSON serialization between Python and Java?

https://stackoverflow.com/a/23820416/1874170

**Comment by vcidst** [comment]
@JamesTheAwesomeDude There was indeed a whitespace! 😢 

Apart from that I also found the following differences, nothing wrong with AES but SHA256 and Base64 instead!

```diff
def _encrypt(self, body):
    # encrypt, hash and encode
    # BASE64(SHA-256(AESEncryption_HEX(request.body)))
    
    # encrypt
    key = bytes.fromhex(self.aes_key)
-    data = json.dumps(body).encode("utf-8")
+    data = json.dumps(body).replace(" ", "").encode("utf-8")
    cipher = AES.new(key, AES.MODE_CBC, self.init_vector.encode("utf-8"))
    encrypted_body = cipher.encrypt(Padding.pad(data, 16, style='pkcs7'))
    
    # hash and encode
    m = hashlib.sha256()
-    m.update(encrypted_body)
-    sha256 = m.digest()
-    return base64.b64encode(sha256).decode("utf-8")
+   m.update(encrypted_body.hex().encode("utf-8"))
+   sha256 = m.hexdigest()
+   return base64.b64encode(sha256.encode("utf-8")).decode("utf-8")
```

**Comment by JamesTheAwesomeDude** [comment]
For digitally-signed data, what you should be doing is transmitting the _signed serialization_ of the data. You should not be trying to reconstitute bytewise-exact data at each end of the network, on different libraries. (And, if you are doing so, troubleshooting such is certainly out-of-scope for either end's cryptographic library, unless it appears — which it does not here — to be functioning according-to-spec.)

Other possibilities for accomplishing what you're trying for include using an unambiguous serialization such as ASN.1 DER (which Pycryptodome has utility libraries for), or (if you really must use JSON as your transport) perhaps JWK or a derivative of it.
