### ISSUE TITLE
Requires Hash Object

### ISSUE THREAD

**Issue by Mr-Elysium** [Legrandin/pycryptodome#529]
I am trying to sign a message, so I create a hash of that message as so:
h = SHA256.new(message)

Then I want to sign is as so:
signer = DSS.new(key, 'fips-186-3')
signature = signer.sign(h)

But than it tells me an error that h is a SHA256Hash object while the sign function requires a Hash object

**Comment by Legrandin** [comment]
Can you please provide a full script to reproduce this? Because I can't.

**Comment by Varbin** [comment]
@Legrandin Maybe this is similar to #515 - a type warning in a linter / editor? Back then at least PyCharm did not evaluate correctly that `Hash` in the type stub is a subclass of `Protocol`.

**Comment by Mr-Elysium** [comment]
> Can you please provide a full script to reproduce this? Because I can't.

Will do when I get access to a computer
