### ISSUE TITLE
Cannot compile pycryptodome on Linux Mint 18

### ISSUE THREAD

**Issue by macdrai** [Legrandin/pycryptodome#53]
Hello,
When installing pycryptodome on Mint 18 with pip3, it seems that dependancies are missing:

`Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    warning: no support for Intel AESNI instructions
    building 'Crypto.Hash._MD2' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DLTC_NO_ASM -Isrc/ -I/usr/include/python3.5m -c src/MD2.c -o build/temp.linux-x86_64-3.5/src/MD2.o
    In file included from src/pycrypto_common.h:46:0,
                     from src/MD2.c:28:
    /usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h:9:26: fatal error: stdint.h: Aucun fichier ou dossier de ce type
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fkbn3483/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3tn2_4ub-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in `/tmp/pip-build-fkbn3483/pycryptodome/`

Should I install another lib on my Linux system ? Thank you.

**Comment by frispete** [comment]
You need to install a glibc development package

**Comment by Varbin** [comment]
This should be covered by `build-essential libgmp3-dev python3-dev`.
