### ISSUE TITLE
Provide Python 3.7-3.9 wheels for 3.10.1

### ISSUE THREAD

**Issue by nyuszika7h** [Legrandin/pycryptodome#537]
Could you provide Python 3.7-3.9 wheels for pycryptodomex 3.10.1? Python 3.5 is already EOL, and there are only 3.6 wheels for PyPy. I see that 3.9.9 has wheels for the newer Python versions but 3.10.1 does not.

**Comment by Varbin** [comment]
Those are "abi3" wheels which are compatible with all versions since 3.5.

See #458 for details.

**Comment by nyuszika7h** [comment]
My bad, I must be using an outdated version of pip, as it insisted on compiling it from source.
