### ISSUE TITLE
Cipher Padding Util not working as expected in Python3

### ISSUE THREAD

**Issue by mkumar1212** [Legrandin/pycryptodome#542]
Trying to decrypt a value using AES key in CBC mode with PKCS7 padding

key = PBKDF2('somePassword',b64decode(b'someSaltString'),16,65536)
cipher = AES.new(key, AES.MODE_CBS,b'someIVbytes')
unpad(cipher.decrypt(b64decode("pdxff2q5fwjnjls2pdlruw==")),8,style='pkcs7).decode('ASCII')

It throws value error: Padding is incorrect.
/local_disk0/.ephemeral_nfs/envs/pythonEnv-7dfdaa69-b526-49fc-af6d-d80db6a007f3/lib/python3.8/site-packages/Crypto/Util/Padding.py in unpad(padded_data, block_size, style)
     90         padding_len = bord(padded_data[-1])
     91         if padding_len<1 or padding_len>min(block_size, pdata_len):
---> 92             raise ValueError("Padding is incorrect.")
     93         if style == 'pkcs7':
     94             if padded_data[-padding_len:]!=bchr(padding_len)*padding_len:

ValueError: Padding is incorrect.

This used to work fine in Python2. Any help here is highly appreciated

**Comment by Varbin** [comment]
AES requires has 16 bytes blocks, and you used "8" for unpadding. Are you sure this code works on Python 2?

I can't reproduce this, as I do not have the salt for the PBKDF2 key derivation and other errors in it. If you could provide a fully working code snippet which I can run without modification, I might look into it.

P.S.: You can format your code in Github issues (and comments to it): https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by mkumar1212** [comment]
Thanks @Varbin  for your response. 

It is my understanding that only constraint on block size used during unpadding is that AES block size should be a multiple of it. Refer - https://pycryptodome.readthedocs.io/en/latest/src/util/util.html

That said, I did try it with block size as 16 and it still gives the same error. The only task I am performing is Decryption as encryption has been performed by a 3rd party. Given the sensitive nature of Salt string & IV, I was not able to share the exact code. I understand it is difficult to reproduce issues without actual code snippet and I am looking for any general guidance or help you can offer.

In fact to further simplify it, here is the output which I get from CIPHER DECRYPT process. Simply, unpadding this using PKCS7 style throws the same error even when length of output from decrypt process is 16 bytes. What am I missing here?

```
ct = b'\xd8e\x1a\xcf\xd3$<?\xdf\xf5\x89\x10\xa9\xafW\xa7'
len(ct)
unpad(ct,8,style='pkcs7')
```
3rd line will result in value error as reported before.

Any guidance here will help immensely. Also, I can confirm that this code worked before in Python2. As my last option, I am also working to get a python2 setup to test this again.

**Comment by Varbin** [comment]
@mkumar1212 
Well, it simply isn't valid padding. On Python 2 your new code will result in the same error message.

PKCS#7 works by adding n-bytes with the value of n until the size the blocksize is matched. If the blocksize is already matched, another whole block is added. The correctly padded string (for an 8 byte block, but as I previously mentioned, 8 byte blocks are wrong for AES) for your given example is `'\xd8e\x1a\xcf\xd3$<?\xdf\xf5\x89\x10\xa9\xafW\xa7\x08\x08\x08\x08\x08\x08\x08\x08'`. 

You may miss:

- _AES_ needs data with a multple of 16 in length for block cipher modes to work. As input may have a different length (e.g. 53 bytes), the input data is usually padded before encryption. How you ensure this, is your decision (or it was already decided for your).
- PKCS#7 padding always pads to the _next_ multiple of the block size (e.g. 53 is padded to 58, and **16 is padded to 32 bytes**; assuming a blocksize of 16).

> Given the sensitive nature of Salt string & IV, I was not able to share the exact code.

Regarding this: It does not matter if those values are the ones of your production. Just show values and code that show the same behavior. For anyone wanting to help, it is crucial to have enough information to reproduce the issue. Your last example *does have* enough information for this.

By the way: Salt and IV are _not_ sensitive by definition. Only the key is.

**Comment by mkumar1212** [comment]
Thanks @Varbin  for all the input. I have verified that the code I shared before works as expected without any change. It seems the value I using to decrypt had issues as someone converted it to lower case and then changed the ASCII encoding for actual characters behind the scene causing the corruption.

This will fail:
```
key = PBKDF2('somePassword',b64decode(b'someSaltString'),16,65536)
cipher = AES.new(key, AES.MODE_CBS,b'someIVbytes')
unpad(cipher.decrypt(b64decode("pdxff2q5fwjnjls2pdlruw==")),8,style='pkcs7).decode('ASCII')
```

This will complete successfully
```
key = PBKDF2('somePassword',b64decode(b'someSaltString'),16,65536)
cipher = AES.new(key, AES.MODE_CBS,b'someIVbytes')
unpad(cipher.decrypt(b64decode("PdXFF2q5fwjnjLS2pDLRUw==")),8,style='pkcs7).decode('ASCII')
```
