### ISSUE TITLE
can I make the module extensions statically linked?

### ISSUE THREAD

**Issue by sify21** [Legrandin/pycryptodome#547]
I have a project using pycrytodome, I want to ship dependencies with it. I'm using this approach: 
- build wheels of all deps
`pip wheel --wheel-dir=deps -r requirements.txt` 
- unzip all .whl files in the directory   

Then I can set PYTHONPATH to this directory and run my project without needing to install depencies.  
But I have a problem here, `Crypto/Cipher` contains module extensions, and they are dynamically linked. for example, this .so is built on alpine:
```
# ldd _raw_aes.abi3.so 
	/lib/ld-musl-x86_64.so.1 (0x7f228cb19000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f228cb19000)
```
can I make them statically linked for better portability?

**Comment by Legrandin** [comment]
That's what PyInstaller is for. I recommend to use that.
https://www.pyinstaller.org/
