### ISSUE TITLE
How to use PublicKey to decrypt message

### ISSUE THREAD

**Issue by pyAppman** [Legrandin/pycryptodome#548]
There is a implemention for Java code:
`public class RSAUtils {
    private static String ALGORITHM = "RSA/ECB/PKCS1Padding";

    public static String decrypt(String str, String str2) {
        try {
            PublicKey publicKey = getPublicKey(str2);
            Cipher instance = Cipher.getInstance(ALGORITHM);
            instance.init(2, publicKey);
            return HexUtils.bin2HexStr(instance.doFinal(HexUtils.hexStr2BinArr(str)));
        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
    }
}`

**Comment by Legrandin** [comment]
You cannot use a public key to decrypt.
