### ISSUE TITLE
Numerous test suite errors, mainly missing assets and problems with positional arguments

### ISSUE THREAD

**Issue by TheChymera** [Legrandin/pycryptodome#549]
I am having over 100 issues with the package test suite. This is the full build and test output: https://ppb.chymera.eu/7b64c4

mostly it seems to be missing `.so` and issues with positional arguments. Any idea what's wrong?

**Comment by Legrandin** [comment]
Did version 3.10.1 worked?

In a recent update, the library started using `os.path.isfile()` to check  if `.so` files exist.
As an example, from your log, the file `_raw_ecb.abi3.so` has been indeed created:

    x86_64-pc-linux-gnu-gcc -shared -Wl,-O1 -Wl,--as-needed -march=native -O2 -pipe /var/tmp/portage/dev-python/pycryptodomex-3.10.4/work/pycryptodomex-3.10.4-python3_9/temp.linux-x86_64-3.9/src/raw_ecb.o -L/usr/lib64 -o /var/tmp/portage/dev-python/pycryptodomex-3.10.4/work/pycryptodomex-3.10.4-python3_9/lib/Cryptodome/Cipher/_raw_ecb.abi3.so 

But then the same file is not found later. Is your build system somehow configure to reduce access to the filesytem?

**Comment by TheChymera** [comment]
@Legrandin 3.10.1 also fails: https://ppb.chymera.eu/83b6ec.log

> Is your build system somehow configure to reduce access to the filesytem?
For the system-wide install it's built in a sandbox for a separate user, but it should be perfectly able to read external libraries for the install process. And of course it can do anything it wants in the sandbox.

Here are the contents in the sandbox (the building of stuff happens under `.../work`):
https://ppb.chymera.eu/9cd7f5 (sorry if the formatting of the tree pipe characters is still off, trying to fix that)

**Comment by TheChymera** [comment]
Apparently I was running the tests incorrectly, they pass now
[build.log](https://github.com/Legrandin/pycryptodome/files/8356792/build.log).
