### ISSUE TITLE
load pycryptodome3.10.4 frozen using import 

### ISSUE THREAD

**Issue by KyleXBao** [Legrandin/pycryptodome#554]
We met a strange issue that the following scripts frozen forever:
from Crypto.Signature import DSS

The system is pycryptodome3.10.4 in a pypy3.6-7.3.3-linux64 virtual envirment.

Anybody met the same issue and give us an explanation?

**Comment by Varbin** [comment]
I can't reproduce it. :shrug: 

I downloaded a copy from [here](https://downloads.python.org/pypy/pypy3.6-v7.3.3-linux64.tar.bz2), installed pip and virtualenv, created a fresh virtualenv, activated it, installed PyCryptodome, imported DSS.

**Comment by Legrandin** [comment]
@KyleXBao Could you please provide more information about the OS (Linux distribution) you are running?

**Comment by Legrandin** [comment]
Closing for lack of feedback.
