### ISSUE TITLE
Getting Segmentation Fault at sha_compress with sha256

### ISSUE THREAD

**Issue by saiprasadreddy454** [Legrandin/pycryptodome#559]
### Getting Segmentation fault with the following program 

I am trying to generate SHA256Hash class object to get the SHA256 digest of the message. Facing this segmentation fault.
This crash is observed only when "msg" length is more than 64 characters. Less than 64 characters, crash is not seen. Also, the crash is observed only on our production device. If i run this on some VMs, or my dev machines, the crash is not seen even with huge 'msg' length.

@Legrandin 
My Sample program is below.

```
from Cryptodome.Hash import SHA256
msg = b'eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOTI5YzYzZmYxMDgyYmJiOGM5OWY59123' // some dummy message
h = SHA256.new(msg) // This line giving me crash, when i run this under gdb, crash is pointing at sha_compress.
 
```
Program received signal SIGSEGV, Segmentation fault.
sha_compress (hs=0x8126fe0) at src/hash_SHA2_template.c:183
183     src/hash_SHA2_template.c: No such file or directory.
        in src/hash_SHA2_template.c
(gdb) bt
#0  sha_compress (hs=0x8126fe0) at src/hash_SHA2_template.c:183
#1  0x009d177a in SHA256_update (hs=0x8126fe0, buf=<value optimized out>, len=64) at src/hash_SHA2_template.c:366
#2  SHA256_update (hs=0x8126fe0, buf=<value optimized out>, len=64) at src/hash_SHA2_template.c:347
#3  0x0072d44f in ffi_call_SYSV () at src/x86/sysv.S:61
#4  0x0072d280 in ffi_call (cif=0xf7eadec8, fn=0x9d16f0 <SHA256_update>, rvalue=0xf7e93e70, avalue=0xf7e93e60) at src/x86/ffi.c:213
#5  0x00719dca in cdata_call (cd=0xf7c52ae8, args=0xf7c6d504, kwds=0x0) at c/_cffi_backend.c:3025

**Comment by Legrandin** [comment]
Can you share more info about the production device?
Library version, OS version, Python version, pip list.
Also was the library installed with the wheel from pypi, or was it compiled?

**Comment by Legrandin** [comment]
Closing since no feedback
