### ISSUE TITLE
CTR mode support initial_value as bytes?

### ISSUE THREAD

**Issue by bdkearns** [Legrandin/pycryptodome#56]
In schemes such as CTR-ESSIV, the initial value for the counter in CTR mode is the output of an AES encrypt, naturally a series of bytes. However, the CTR mode only accepts initial_value as an integer (which it then converts internally back to bytes). If it could accept initial_value as bytes it would avoid the unnecessary conversions in this situation.

**Comment by Legrandin** [comment]
Added this with 97614ab9ada966b01c755d1c5b7769d75128d2dd
