### ISSUE TITLE
wrong byte order in _left_encode() from cSHAKE128.py

### ISSUE THREAD

**Issue by tebrost** [Legrandin/pycryptodome#566]
It seems that _left_encode() is generating the wrong byte order. In my fix, I also include a _right_encode() as it is needed by KMAC. Here is my code:

def _left_encode(x, left=True):
    """Left encode function as defined in NIST SP 800-185"""
    # Get number of bytes needed to represent x
    num = max(1, (x.bit_length() + 7) // 8)
    assert x >= 0 and num <= 0xFF
    # Convert x to big endian list of bytes
    enc = [(x>>(i<<3) & 0xFF) for i in reversed(range(num))]
    return bytes([num]+enc if left else enc+[num])

def _right_encode(x):
    """Right encode function as defined in NIST SP 800-185"""
    return _left_encode(x, False)

**Comment by Legrandin** [comment]
Thanks, this is fixed with cf64b7b40c19aef6af67ba135c6de6ea685ce6c0

**Comment by Legrandin** [comment]
Fixed in v3.12.0
