### ISSUE TITLE
Private key encryption and public key decryption?

### ISSUE THREAD

**Issue by sinall** [Legrandin/pycryptodome#567]
I have two applications:
C is a C++ application, acting as a http client,
S is a python http server (embeded).
I deliver both C and S to my customers, and I need to enforce they can only use S with C.
So,
1) I use pyarmor to obfuscate the code of S
2) I add an encrypted header with `exp time` for http call from **C--(with encrypted timestamp header)-->S**
3) Use private-key in S to decrypt the header and check the `exp time` to make sure the call is not a fake call

The problem here is that even I obfuscate the source code of S, one can still
1. hook pycryptodome code to get private-key, 
2. and once someone gets the private-key, 
3. they can generate corresponding public key and fake the call.

So if this library can provide a way to do private-key encryption & public-key decryption, then even user get the public key, they still can not reverse the private-key, so they can not fake a http call.

I know this is not a typical user case, do you have any suggestions?

**Comment by Legrandin** [comment]
I am not familiar with pyarmor and which protections it applies, but I expect you do not want to use a Python library with C extensions (like Pycryptodome is) but rather pure Python code.

**Comment by sinall** [comment]
> I am not familiar with pyarmor and which protections it applies, but I expect you do not want to use a Python library with C extensions (like Pycryptodome is) but rather pure Python code.

I switch to use private-key sign & public-key verify strategy now. Thanks.
