### ISSUE TITLE
DerBitString example incorrect

### ISSUE THREAD

**Issue by BradL-Msft** [Legrandin/pycryptodome#570]
https://github.com/Legrandin/pycryptodome/blob/776d77073ff3ca41b492a002b55b1b4f993dff07/lib/Crypto/Util/asn1.py#L712

BitStrings start with tag 0x03 rather than 0x04, so the sample doesn't run for me.  
However, it appears the code is correct.

**Comment by Legrandin** [comment]
Thanks, fixed with 2b2d75a26fd0bd2f9a0b44aaf8f7dc55b01ee42b

**Comment by Legrandin** [comment]
Fixed in v3.12.0
