### ISSUE TITLE
AES CBC NOPADDING equivalent in python?

### ISSUE THREAD

**Issue by keko950** [Legrandin/pycryptodome#580]
Hi, when im on Java i use AES_CBC_NOPADDING to encrypt my messages:

cipher = Cipher.getInstance("AES/CBC/NOPADDING")

How could i use cryptodome to decrypt them?

**Comment by Legrandin** [comment]
That's just plain CBC:

    input = b'Sixteen_ciphrtxt'
    key = b'Sixteen_byte_key'
    iv = b'IV_you_received!'
    cipher = AES.new(key, AES.MODE_CBC, iv)
    output = cipher.decrypt(input)
