### ISSUE TITLE
How to use Private key encryption and public key decryption?

### ISSUE THREAD

**Issue by hanwang-wish** [Legrandin/pycryptodome#581]
Some scenarios need private key encryption and public key decryption, such as when integrate some third party providers in your system, I have faced these problems. So if the library could provide a way to do private-key encryption & public-key decryption?

**Comment by Legrandin** [comment]
Maybe you should provide a more detailed description of your scenario.
Public keys are by definition not secret, which means that they are widely know - how can they be used for decryption then?

**Comment by hanwang-wish** [comment]
Yeah, I've integrate the third party charge provide in our system. They only support private key encryption and public key decryption, other language like Java and Javascript supported this method. I wonder whether pycryptodome could support these methods?

**Comment by Legrandin** [comment]
No, sorry, they can't be supported.
