### ISSUE TITLE
"Illegal instruction" on armv6l / RaspberryPI Zero

### ISSUE THREAD

**Issue by JsBergbau** [Legrandin/pycryptodome#585]
With https://www.piwheels.org/simple/pycryptodomex/pycryptodomex-3.12.0-cp35-abi3-linux_armv6l.whl 
open python3 and type
`from Cryptodome.Cipher import AES`
then it will crash with illegal instruction

![grafik](https://user-images.githubusercontent.com/37013344/146022009-74e77eb5-7682-4061-88b7-3f95f8994944.png)

Version 3.11 works, see https://github.com/JsBergbau/MiTemperature2/issues/104

**Comment by Legrandin** [comment]
The wheel is built on https://www.piwheels.org/. Unfortunately they don't publish the build log. I will need to get hold of a RPI0/1 to reproduce or possibly try with QEMU.

**Comment by JsBergbau** [comment]
I've never published to piwheels. Perhaps it is sufficient to republish the version 3.12 there, because the defective built was due to a temporary problem?

**Comment by Legrandin** [comment]
I mean, the team at https://www.piwheels.org builds the wheel. I have no interaction with them really, and I only publish on pypi.

**Comment by JsBergbau** [comment]
I write to piwheels.org and report back.

**Comment by steals** [comment]
Have the same issue on RaspberryPI 1 B+ (armv6h)

**Comment by JsBergbau** [comment]
Wrote a message to the email adress published at https://github.com/piwheels but no answer so far.

**Comment by JsBergbau** [comment]
New issue has been created https://github.com/piwheels/packages/issues/270

**Comment by Legrandin** [comment]
Issue is solved according to https://github.com/piwheels/packages/issues/270
