### ISSUE TITLE
Memory leak while decrypting data

### ISSUE THREAD

**Issue by ambuj750** [Legrandin/pycryptodome#586]
I am using pycryptodome module for encryption and decryption purposes but it is leading my code to a memory leak.

Version used: pycryptodome==3.12.0

**Comment by sagym** [comment]
I am experiencing the same, what's strange is that the leak is inconsistent in the number of bytes leaking. Process memory is rising steadily but not uniformly.

**Comment by Legrandin** [comment]
@ambuj750 are you using RSA or AES for encryption/decryption?
A memory leak for RSA was fixed in version 3.14.1.

**Comment by ambuj750** [comment]
Hi, @Legrandin  I was using RSA encryption and it was decryption that was causing a memory leak.

**Comment by Legrandin** [comment]
Thanks! I assume that the memory leak you saw is now fixed in v3.14.1 then.

**Comment by ambuj750** [comment]
I did not test with v3.14.1. I'll test it and confirm.
