### ISSUE TITLE
Conflict with PyCrypto: Both install files into the same namespace Crypto

### ISSUE THREAD

**Issue by yurivict** [Legrandin/pycryptodome#587]
[PyCrypto](https://github.com/pycrypto/pycrypto)

This causes conflicts like this between FreeBSD packages:
```
  - py38-pycrypto-2.6.1_3 conflicts with py38-pycryptodome-3.10.1 on /usr/local/lib/python3.8/site-packages/Crypto/Cipher/AES.py
Checking integrity... done (0 conflicting)
The following 5 package(s) will be affected (of 0 checked):

Installed packages to be REMOVED:
	mpv: 0.34.0_2,1
	py38-pycryptodome: 3.10.1
	yt-dlp: 2021.12.01

New packages to be INSTALLED:
	py38-pycrypto: 2.6.1_3
```

Please consider changing the namespace name to ```CryptoDome```.

**Comment by baseplate-admin** [comment]
Please read the docs. It says it's a drop in replacement for PyCrypto.

Also PyCrypto is outdated and filled with vulnerabilities.

**Comment by Varbin** [comment]
The package for the separate namespace [pycryptodomex](https://pypi.org/project/pycryptodomex/). 

If there are FreeBSD Ports packages explicitly requiring the old PyCrypto you should likely contact the respective maintainers.

**Comment by yurivict** [comment]
> If there are FreeBSD Ports packages explicitly requiring the old PyCrypto you should likely contact the respective maintainers.

I am doing exactly this: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260897

**Comment by Legrandin** [comment]
Closing because this behavior is intentional.
