### ISSUE TITLE
Custom number of rounds in AES processing

### ISSUE THREAD

**Issue by frispete** [Legrandin/pycryptodome#59]
Hi Elder,

don't know, if this is out of scope, but reading about AES [weaknesses](https://www.schneier.com/blog/archives/2009/07/another_new_aes.html) raised this question for my favourite crypto lib:

Would you consider an optional parameter to supply the custom number of AES rounds processing a sensible approach to tavkle this problem?

**Comment by Legrandin** [comment]
AES with a non-standard number of rounds wouldn't be AES anymore, with very negative consequences for interoperability. But beside that, I think there is consensus that AES128/192/256 still stand strong: the attack you point to is not very practical and it concerns a very hard to pull of case of [related keys](http://crypto.stackexchange.com/questions/1549/related-key-attacks-on-aes).

**Comment by frispete** [comment]
> AES with a non-standard number of rounds wouldn't be AES anymore, with very negative consequences for interoperability.

Sure, you're correct, but imagine a project, where interoperability isn't a concern, customizing the number of rounds is a nice and easy way to raise the safety margins of AES encryption schemes.

I've looked into the code already. The hard part would be the API of such an option, given other ciphers have no need of such parameters, and the interface must support all block sizes of course..

**Comment by Legrandin** [comment]
Closing this, as the use case is very narrow.
