### ISSUE TITLE
Undefined variable in Encrypt Data with AES example

### ISSUE THREAD

**Issue by Fey19** [Legrandin/pycryptodome#591]
The example [Encrypt Data with AES](https://github.com/Legrandin/pycryptodome/blob/master/Doc/src/examples.rst#encrypt-data-with-aes) has an undefined variable `data` which causes the example to fail. A possible fix could look like the following, where `data` is a string encoded as byte stream

```python3
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes

key = get_random_bytes(16)
cipher = AES.new(key, AES.MODE_EAX)
data = str.encode("secret data")
ciphertext, tag = cipher.encrypt_and_digest(data)

file_out = open("encrypted.bin", "wb")
[ file_out.write(x) for x in (cipher.nonce, tag, ciphertext) ]
file_out.close()
```

**Comment by Legrandin** [comment]
Fixed, thanks.
