### ISSUE TITLE
support import EC keys from raw format

### ISSUE THREAD

**Issue by trittsv** [Legrandin/pycryptodome#602]
It would be great to import a EC-Key from the raw format "r || s"
like described here https://tools.ietf.org/html/rfc4754 (see section 8.3 for example)

Dream-Usage:
```python
def base64_to_ecc_key(key_base64: str) -> EccKey:
    keyBase64Bytes: bytes = key_base64.encode("utf-8")
    keyDecoded = base64.decodebytes(keyBase64Bytes)
    key = ECC.import_key(keyDecoded, curve_name="secp521r1")
    return key

if __name__ == "__main__":

    privateKeyBase64: str = "AHrQjGp3C2n5do4PZnt+ga9HBAH4Q6jqWepgiM3bvevRW5HbmonBOls2BugwidLLEuQpo5Fg8GMu1VSzuAVD93Au"
    # 007ad08c 6a770b69 f9768e0f 667b7e81 af470401 f843a8ea 59ea6088 cddbbdeb d15b91db 9a89c13a 5b3606e8 3089d2cb 12e429a3 9160f063 2ed554b3 b80543f7 702e

    privateKey: EccKey = base64_to_ecc_key(privateKeyBase64)
```

Currently it results in:
```bash
python3 CryptoService.py

Traceback (most recent call last):
  File "CryptoService.py", line 40, in <module>
    privateKey: EccKey = base64_to_ecc_key(privateKeyBase64)
  File "CryptoService.py", line 27, in base64_to_ecc_key
    key = ECC.import_key(keyDecoded, curve_name="NIST P-521")
  File "/Users/sventrittler/Library/Python/3.8/lib/python/site-packages/Crypto/PublicKey/ECC.py", line 1301, in import_key
    raise ValueError("ECC key format is not supported")
ValueError: ECC key format is not supported
```

Please correct me if this is already possible, otherwise it would be awsome if pycryptodome could support this representation.

**Comment by Legrandin** [comment]
"r || s" is the ECDSA signature, it is not the ECC key.
If your goal is to verify an ECDSA signature which is encoded as "r || s", that is indeed already supported in the module `Crypto.Signature.DSS`.
The two examples shown here https://www.pycryptodome.org/en/latest/src/signature/dsa.html all work with "r || s" signatures (see also the `encoding` parameter to the `new()` function, and the default value `binary`).

**Comment by trittsv** [comment]
@Legrandin thank you for your response, may there is a missunderstanding.

My goal is to convert a rawRepresentation of a P521-PrivateKey to a `Crypto.PublicKey.ECC.EccKey` object.

What i mean with rawRepresentation:
```
      PrivateKeyInfo ::= SEQUENCE {
        version                   Version,
        privateKeyAlgorithm       PrivateKeyAlgorithmIdentifier,
        privateKey                PrivateKey,    <------------------------- rawRepresentation
        attributes           [0]  IMPLICIT Attributes OPTIONAL }
```

### Example

I have this private key (secp521r1) as [rawRepresentation](https://developer.apple.com/documentation/cryptokit/p521/signing/privatekey/3237782-rawrepresentation) (shown below as hex): 
**00aabaf31ecb761d2c8e17a93dcf42c372b07c3221dfe00bf5991923380634f5d63ea5793451624d555c567114a53d2b4b53255557550abfe886afba802f9bddacf4**

DER-Format would be:
3081ee020100301006072a8648ce3d020106052b810400230481d63081d30201010442**00aabaf31ecb761d2c8e17a93dcf42c372b07c3221dfe00bf5991923380634f5d63ea5793451624d555c567114a53d2b4b53255557550abfe886afba802f9bddacf4**a18189038186000401cb6eb020cc339e90daf8611d19a978e6e736bc08edeed515013f5f7445845893e2756f41b4b812da9c3de3eb5d6c7b821af1ca7080a654071a237b8d268c084b8800d35a8bf51682814ef4747fdafd46ad925b20003b026619871812de4979711d65f43501850f166223f43804a07ee3a440543e2fb587b5e401ac75d652f8614d9f2b

I want now to decrypt a message,
for that i have to import the key to get a `Crypto.PublicKey.ECC.EccKey` object
with my PrivateKey which i only have in RawRepresentation as shown above.

Is that somehow possible currently?

**Comment by Legrandin** [comment]
Thanks for clarifying. It seems that `construct()` is what you need actually:

```
from Crypto.PublicKey import ECC
from Crypto.PublicKey.ECC import EccKey
import base64

def base64_to_ecc_key(key_base64: str) -> EccKey:
    keyBase64Bytes: bytes = key_base64.encode("utf-8")
    keyDecoded = base64.decodebytes(keyBase64Bytes)
    key = ECC.construct(curve="secp521r1", d=int.from_bytes(keyDecoded, 'big'))
    return key

if __name__ == "__main__":

    privateKeyBase64: str = "AHrQjGp3C2n5do4PZnt+ga9HBAH4Q6jqWepgiM3bvevRW5HbmonBOls2BugwidLLEuQpo5Fg8GMu1VSzuAVD93Au"
    # 007ad08c 6a770b69 f9768e0f 667b7e81 af470401 f843a8ea 59ea6088 cddbbdeb d15b91db 9a89c13a 5b3606e8 3089d2cb 12e429a3 9160f063 2ed554b3 b80543f7 702e

    privateKey: EccKey = base64_to_ecc_key(privateKeyBase64)
```

Your `rawRepresentation` is just the integer in big endian format.
In [RFC5915](https://datatracker.ietf.org/doc/html/rfc5915), that is the content of the `privateKey` OCTET STRING.

**Comment by trittsv** [comment]
@Legrandin awsome, thank youm that worked.

I just realized that asymmetric en-/decryption with a `EccKey` and `eciesEncryptionStandardX963SHA512AESGCM` seems not possible with pycryptodome yet but will come in the future https://pycryptodome.readthedocs.io/en/latest/src/future.html

I am looking forward for these algorithms 🤓
