### ISSUE TITLE
Wired random numbers behaviour

### ISSUE THREAD

**Issue by catap** [Legrandin/pycryptodome#608]
I'm using `pycryptodomex==3.14.1` on
```
Python 3.9.10 (main, Jan 15 2022, 12:21:28) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

A naive test case:
```python
#!/usr/bin/env python3

from Cryptodome.Util import number

m = number.getRandomInteger(64)
print("[x] d: %d" % m)
print("[x] f: %f" % m)
```
works like this:
```
[x] d: 11038775639005585606
[x] f: 11038775639005585408.000000
```

I've expected that both number should be the same.  Am I wrong?

**Comment by Varbin** [comment]
Yes. This is a behaviour of floats - they (double precision floats) only have 52 bits precision (+ an 11 bit exponent and one bit for the sign). The generated number has 64 bits and therefore looses some bits when converted into a float. This does not only affect Python, but all programming languages with IEEE floats.

In case you need more precision see the [decimal](https://docs.python.org/3/library/decimal.html) library with adjustable precision:

```python3
from decimal import Decimal
print("%f" % 11038775639005585606) # 11038775639005585408.000000
print(d := Decimal(11038775639005585606), d == 11038775639005585606)  # 11038775639005585606 True
```
