### ISSUE TITLE
Support Kuznyechik & Kalyna

### ISSUE THREAD

**Issue by zaqas** [Legrandin/pycryptodome#610]
Hello,

I recently came upon these two ciphers which I find quite interesting. Kalyna is basically the encryption standard used in Ukraine and Kuznyechik is used in Russia. Can you add support for them? I think they would be great additions.

Thanks!

**Comment by Varbin** [comment]
For future reference, their specifications:

- Kuznyechik aka GOST R 34.12-2015: [RFC 7801](https://datatracker.ietf.org/doc/html/rfc7801)
- Kalyna: https://eprint.iacr.org/2015/650

**Comment by Legrandin** [comment]
Sorry, no plan to include these country-specific algorithms.
