### ISSUE TITLE
pycryptodome uses an incompatible blake2 implementation

### ISSUE THREAD

**Issue by georgthegreat** [Legrandin/pycryptodome#617]
I can not disclosure the details, but we link pycryptodome libraries statically, and pycryptodome goes in conflict with libarchive, which depends on blake2 implementation for some version of RAR compression format.

Is it possible to switch pycryptodome to https://github.com/BLAKE2/libb2?

**Comment by Legrandin** [comment]
No, sorry, that is not a change we can do.
If there is a conflict in symbols, I would recommend to look at the linking step: you might be able to address the problem there with the existing code.

**Comment by georgthegreat** [comment]
I have renamed these symbols locally, so this is not the problem at the time.
I just wanted to get a cleaner fix this.

No means no, thank you.
