### ISSUE TITLE
PKCS#1 signing without hashing

### ISSUE THREAD

**Issue by larcho** [Legrandin/pycryptodome#619]
Working with a vendor that expects data to be PKCS#1 signed but without hashing it. Is it possible to RSA sign a raw bytearray without hashing it first?

**Comment by Varbin** [comment]
The "raw" and rarely secure RSA signature can be performed with `key._decrypt(message)`, where `message` is an integer (convert from/to integer with `Crypto.Util.number.bytes_to_long` and `.long_to_bytes`).

AFAIK the [PKCS#1 standard](https://www.ietf.org/rfc/rfc2437.txt.pdf) does not have any signature scheme without hashing, so I am not sure what exactly your vendor wants.

**Comment by larcho** [comment]
It's possible that I'm miss-interpreting the rawness in the signing process. The vendor offers various examples from different frameworks where that signing is done without hashing first (some of these frameworks call this "private_encryption" and in the Go sample it seems the hashing value is passed as null).

The example for python they provide is piping it the through the openssl shell command like so:
`openssl rsautl -sign -inkey <private key>`
Seems a bit odd that using shell command is the best approach for signing.

**Comment by Varbin** [comment]
Okay. Found it out.

PKCS#1 has padding which consists of `\x00\x01\xff...\xff\x00` which is prepended to the message before it is signed. It is filled with enought `\xff` so the final message length equals to the keylength of the RSA key. Usually the message consists of a DER encoded message created from the hash and the hash algorithm.

https://github.com/Legrandin/pycryptodome/blob/db731bb3a7bc4ba7bf21ccd7ed3616b546f9468a/lib/Crypto/Signature/pkcs1_15.py#L197-L200

For whatever reason your vendor has decided to not hash his data, but instead pass the "raw" string directly. I guess this is the reason for "the hashing value is passed as null" in the Golang example.

Below is the code to do this signing.

```python3
"""
Do RSA signing/verification with PKCS#1 padding but an
arbitrary message string instead of the DER construct.

Test generated with `openssl rsautl -sign`.
"""
from hmac import compare_digest

from Cryptodome.PublicKey import RSA


def pad(message: bytes, key: RSA.RsaKey) -> bytes:
    if key.size_in_bytes() - len(message) < (3 + 8):
        raise ValueError("message too long")

    return b"\x00\x01" + b"\xff"*(key.size_in_bytes() - len(message) - 3) + b"\x00" + message
    

def sign(message: bytes, key: RSA.RsaKey) -> bytes:  
    padded = pad(message, key)
    signed = int(key._decrypt(int.from_bytes(padded, 'big')))
    return signed.to_bytes(key.size_in_bytes(), 'big')
    

def verify(signature: bytes, key: RSA.RsaKey, message: bytes) -> bool:
    padded = pad(message, key)
    unsigned = int(key._encrypt(int.from_bytes(signature, 'big')))

    return compare_digest(
        unsigned.to_bytes(key.size_in_bytes(), 'big'),
        padded
    )


if __name__ == "__main__":
    key = RSA.construct((
        28585282323270820944476623617706837988985167464751739503649190510846208421942723544116509481205078919399626292730640398116882397812434508502970012261637556420420078606974178055014921371322102167776216923798958042468480709342910542025847160972655341671171274494905998171710897170181144390905692150861972227923432328086985951984066416929819623100207074313136305375043161241104120814361129067079314631781752567265481452132086102520311609770617007004184025387471536816101350485313185311635512167767385096319558310882035605184901874009629407550253459225995218985098689482038761973706021983687165470671322271058375120670947,
        65537,
        21956804738597328628789130306778800133749078080711698225638955861818486228551760123454309585178810027962482072356995859456549123485633354563674114122569458324365576042160613444152938673304463480566012480645124858596873810341061029427363872062551992000347314617293558569417681058744202643364703036061944885387621573016246813335886689396475380451158702649500400372001238228643141059037769694645574198573249492242100263970481689795284532643836710077495379185068746577098428305596215946789026715492846923948491921264870949571985783305234404329851065295415182693468287082706406059506039611097486122709037957738958389291873
    ))

    test_message = b'Attack at dawn.'
    test_signature = b'+@-\x85\x1d?{l&\xebw\x8d\x0b@\xc1\xf2\x875\xe4\x07&\x10\xd2\xc8\xfe8n\xca\x01\x10\xc7\xd8"\xb7\x04\x8e\xc3\xd0<w\xbe\xfa\xbd\x95\x88\x02\xbeV>\xb1I\xdd\xe0\xb0Uj^\x7fg\xe6\xdc\xbf\x80Q\xea\xb6@>}\xe9\xc5b\x7f\xfb\x01YH\xe8\xe7\x17\xa6>\x8e5\xcf\xcc\xd8\xd8R\x9e=\xb5\\\xf1o\x122\xb7*?\x7f\x16\x8c\x99\x81}\xa67\x87\x00\xe4Hb\t\x95\x82\x1f\x90r\x11\xd1\xa3\xe0t\xd94.\x05V\x0eE}8h\xd92zji\xf4k\xbe\x150\x07\x1d\x98\x80\xe9<\xd0\x19\xca\xb6\xde\xd7\xcdx\xefQ\xcd\x0b\xf8\t\xa3\xd9\xbaq1\x84\x8e\x8ahq^2\xb1\'d"\xdf\x1b\x9b\x83q\xdd~\x95 \xfaN!B\x98\xf5\xda\x0e\xd9f\xc8\xb9\x85:Y\xcdj\xae\xaf\xbe\xbd\xd7\xa4\xc41\xe6u\xfb\x0b\xe9M\xca\x1d\xfd\xe9\xca\xd3\x0c,*~h\xaf\xed\xef\xf2\xc9\x86\x10\xb7\xf0\xe9\xe4\xa2\x1b=\x8da\xb5c\xa0^\x1fJ\xe1\xeb+'

    signature = sign(test_message, key)
    assert signature == test_signature
    assert verify(test_signature, key, test_message)
```

- - -

Regarding the "private_encryption" name: This is because the operations of **textbook** RSA decryption and signing are the same. In case you don't know how RSA internally works, below is a short explanation.

It consists of a bunch of numbers, for shortness I will only name the public exponent *e*, the modulus *N* and the private exponent *d*. (*e, N*) make the public key, (*d, N*) the private one. The exponentiation of any number with either *e* or *d* (modullo *N*) can only be reversed with the other one (at least if *e*, *d* and *N* were properly chosen). Therefore the primitive operations of RSA are (*m* is a message):

- Encryption: *m* ** *e* (mod *N*) 
- Decryption: *m* ** *d* (mod *N*)

For signing and verifying data the two operations are simply reversed:

- Sign: *m* ** *d* (mod *N*) 
- Verify: *m* ** *e* (mod *N*)

This leads to the issue that RSA signing is commonly called "private key encryption". For most real worlds applications (non textbook RSA) this does equivalency does not hold true: For many reasons (like the possibility to manipulate encrypted messages in textbook RSA or attacks like Bleichenbacher's) messages are wrapped with padding before applying the primitive operations above, and the padding formats for signatures and encryption are different.

**Comment by larcho** [comment]
> Okay. Found it out (I hope).
> 
> PKCS#1 has padding which consists of `\x00\x01\xff...\xff\x00` which is prepended to the message before it is signed. It is filled with enought `\xff` so the final message length equals to the keylength of the RSA key. Usually the message consists of a DER encoded message created from the hash and the hash algorithm.
> 
> https://github.com/Legrandin/pycryptodome/blob/db731bb3a7bc4ba7bf21ccd7ed3616b546f9468a/lib/Crypto/Signature/pkcs1_15.py#L197-L200
> 
> For whatever reason your vendor has decided to not hash his data, but instead pass the "raw" string directly. I guess this is the reason for "the hashing value is passed as null" in the Golang example.
> 
> Below is the code to do this signing.
> 
> ```python
> """
> Do RSA signing/verification with PKCS#1 padding but an
> arbitrary message string instead of the DER construct.
> 
> Test generated with `openssl rsautl -sign`.
> """
> from hmac import compare_digest
> 
> from Cryptodome.PublicKey import RSA
> 
> 
> def pad(message: bytes, key: RSA.RsaKey) -> bytes:
>     if key.size_in_bytes() - len(message) < (3 + 8):
>         raise ValueError("message too long")
> 
>     return b"\x00\x01" + b"\xff"*(key.size_in_bytes() - len(message) - 3) + b"\x00" + message
>     
> 
> def sign(message: bytes, key: RSA.RsaKey) -> bytes:  
>     padded = pad(message, key)
>     signed = int(key._decrypt(int.from_bytes(padded, 'big')))
>     return signed.to_bytes(key.size_in_bytes(), 'big')
>     
> 
> def verify(signature: bytes, key: RSA.RsaKey, message: bytes) -> bool:
>     padded = pad(message, key)
>     unsigned = int(key._encrypt(int.from_bytes(signature, 'big')))
> 
>     return compare_digest(
>         unsigned.to_bytes(key.size_in_bytes(), 'big'),
>         padded
>     )
> 
> 
> if __name__ == "__main__":
>     key = RSA.construct((
>         28585282323270820944476623617706837988985167464751739503649190510846208421942723544116509481205078919399626292730640398116882397812434508502970012261637556420420078606974178055014921371322102167776216923798958042468480709342910542025847160972655341671171274494905998171710897170181144390905692150861972227923432328086985951984066416929819623100207074313136305375043161241104120814361129067079314631781752567265481452132086102520311609770617007004184025387471536816101350485313185311635512167767385096319558310882035605184901874009629407550253459225995218985098689482038761973706021983687165470671322271058375120670947,
>         65537,
>         21956804738597328628789130306778800133749078080711698225638955861818486228551760123454309585178810027962482072356995859456549123485633354563674114122569458324365576042160613444152938673304463480566012480645124858596873810341061029427363872062551992000347314617293558569417681058744202643364703036061944885387621573016246813335886689396475380451158702649500400372001238228643141059037769694645574198573249492242100263970481689795284532643836710077495379185068746577098428305596215946789026715492846923948491921264870949571985783305234404329851065295415182693468287082706406059506039611097486122709037957738958389291873
>     ))
> 
>     test_message = b'Attack at dawn.'
>     test_signature = b'+@-\x85\x1d?{l&\xebw\x8d\x0b@\xc1\xf2\x875\xe4\x07&\x10\xd2\xc8\xfe8n\xca\x01\x10\xc7\xd8"\xb7\x04\x8e\xc3\xd0<w\xbe\xfa\xbd\x95\x88\x02\xbeV>\xb1I\xdd\xe0\xb0Uj^\x7fg\xe6\xdc\xbf\x80Q\xea\xb6@>}\xe9\xc5b\x7f\xfb\x01YH\xe8\xe7\x17\xa6>\x8e5\xcf\xcc\xd8\xd8R\x9e=\xb5\\\xf1o\x122\xb7*?\x7f\x16\x8c\x99\x81}\xa67\x87\x00\xe4Hb\t\x95\x82\x1f\x90r\x11\xd1\xa3\xe0t\xd94.\x05V\x0eE}8h\xd92zji\xf4k\xbe\x150\x07\x1d\x98\x80\xe9<\xd0\x19\xca\xb6\xde\xd7\xcdx\xefQ\xcd\x0b\xf8\t\xa3\xd9\xbaq1\x84\x8e\x8ahq^2\xb1\'d"\xdf\x1b\x9b\x83q\xdd~\x95 \xfaN!B\x98\xf5\xda\x0e\xd9f\xc8\xb9\x85:Y\xcdj\xae\xaf\xbe\xbd\xd7\xa4\xc41\xe6u\xfb\x0b\xe9M\xca\x1d\xfd\xe9\xca\xd3\x0c,*~h\xaf\xed\xef\xf2\xc9\x86\x10\xb7\xf0\xe9\xe4\xa2\x1b=\x8da\xb5c\xa0^\x1fJ\xe1\xeb+'
> 
>     signature = sign(test_message, key)
>     assert signature == test_signature
>     assert verify(test_signature, key, test_message)
>     assert not verify(test_signature, key, b'Attack at night.')
> ```
> 
> Regarding the "private_encryption" name: This is because the operations of **textbook** RSA decryption and signing are the same. In case you don't know how RSA internally works, below is a short explanation.
> 
> It consists of a bunch of numbers, for shortness I will only name the public exponent _e_, the modulus _N_ and the private exponent _d_. (_e, N_) make the public key, (_d, N_) the private one. The exponentiation of any number with either _e_ or _d_ (modullo _N_) can only be reversed with the other one (at least if _e_, _d_ and _N_ were properly chosen). Therefore the primitive operations of RSA are (_m_ is a message):
> 
> * Encryption: _m_ ** _e_ (mod _N_)
> * Decryption: _m_ ** _d_ (mod _N_)
> 
> For signing and verifying data the two operations are simply reversed:
> 
> * Sign: _m_ ** _d_ (mod _N_)
> * Verify: _m_ ** _e_ (mod _N_)
> 
> This leads to the issue that RSA signing is commonly called "private key encryption". For most real worlds applications (non textbook RSA) this does equivalency does not hold true: For many reasons (like the possibility to manipulate encrypted messages in textbook RSA or attacks like Bleichenbacher's) messages are wrapped with padding before applying the primitive operations above, and the padding formats for signatures and encryption are different.

You're the best. I'll close this issue, unless someone thinks this actually should be a feature considering it's not a great practice.
