### ISSUE TITLE
Build wheel for aarch64 as well

### ISSUE THREAD

**Issue by consideRatio** [Legrandin/pycryptodome#628]
Thank you for your work on this project!

I [see that](https://github.com/Legrandin/pycryptodome/blob/1be081a77234cd989f9180cab8921243e4f44171/.github/workflows/wheels.yml#L28-L87) wheels are built using cibuildwheel and github actions. Due to that, I think we can quite easily expand it to also build aarch64 wheels which is something I'd like to reduce the complexity of using this package in an arm64/aarch64 context.

There is documentation about this in https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation.

**Comment by Legrandin** [comment]
That approach is quite slow though. However, it seems that Azure is now making available real ARM machines (https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/), so there are good chances that Github will soon allow running Actions natively on Aarch64.

**Comment by Legrandin** [comment]
@consideRatio that's an interesting take. I will need to run some tests to get an idea of the slowdown.

I should have added that AArch64 wheels are **already** built and tested on a "real" ARM SoC (Raspberry PI3 with 64-bit Debian) but not with cibuildwheel. You can find them on PyPI:

https://pypi.org/project/pycryptodome/#files

Having this automated with GitHub  Actions would still be very nice. The other pain point is that I can't right now build wheel for Mac M1, but only for Linux Aarch64. And Win Arm64 is coming too.

**Comment by Legrandin** [comment]
Wheels are available have been available for aarch64 for a while now. Still, they are not built using github workers.
