### ISSUE TITLE
PKCS1_v1_5 cipher.decode() returns b''

### ISSUE THREAD

**Issue by reloverevolt** [Legrandin/pycryptodome#630]
Hi,

I am trying to implement decryption of encrypted response data from wapi platform.
I have an example code written on Java: https://github.com/HiCoinCom/WAPIDemo/blob/4825d744b15e6a6dd017ed01080fd472e8c272eb/java/RsaDemo/src/main/java/com.waas.wapi/utils/XRsa.java#L133

Trying to do the same in Python:

# needed creds are here: https://pastebin.com/zKmcktFk

`from Crypto.PublicKey import RSA
from base64 import b64decode
from Crypto.Cipher import PKCS1_v1_5

def get_rsa_key(key):
	key_bytes = b64decode(key)
	return RSA.importKey(key_bytes)

def decrypt(private_key, encrypted_data):

	rsa_priv_key = get_rsa_key(private_key)

	base64_decoded_data = b64decode(encrypted_data + '==')
	
	# adding zeros to match the 256 bytes block size
	data_bytes = base64_decoded_data + b'00000000' 
        
        cipher = PKCS1_v1_5.new(rsa_priv_key)

	result = cipher.decrypt(data_bytes, 'failure')
	print(result)
	# >> b''`

As you see function does't respond with 'failure', which means it was successful but returns empty byte string.
I have searched around didn't find what could be wrong in this case. 
Any support super appreciated!

**Comment by Legrandin** [comment]
The pastebin.com link does not work. Can you please paste here the sample data (key and ciphertext)?

**Comment by reloverevolt** [comment]
Hey @Legrandin  , sure:

DATA_TO_DECRYPT = "OL9kM_3V9TNSoQ-98-oagZ87eMRSsQGSFibmsy7gUTz0YMVMvGCoYD6ZoBTwFw4Cl-KNv-7o916RGjF8TkBBHgoPoTVHmxzXJRR4BIVwBrDRbrzP9Awz-K8PWEfd6VWqANiZ9jYuOs8w7uxPrgmNEvUEOurQBdnubraUQ32kSrA-cKn4sC0vFrYCaKV_f5HJPaMJTTTn6ryipvc3AU69d-m3zet4EadxFKfD5FbMvQI2DllG35Xsqveovn4xTJKjDy4TbDCz6a0tOF-zS3dvkfrHUlfNesuIao5lDXYSBWksFR4OE2bk_I0PaxSbvvc1Faa1Ua9Zv2GE102XE8OiwQ"

PRIVATE_KEY = "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXo/1KhisVunQMx8gg6iwH90ZNFRDTjpyYsHnkyoAZeVkf/yHeksPXLEbpGMRVC5cRC36kfI/S8nRm3tK1ZHbTO6jH/PeYi8EKitacpgUnNFErIIF098J2w8K+ZeyajMx+D2OgE9hEEJFUeqU2+8q87A2rpLlCEMhIrrRMeeeraEoAQ9QVYNVygkfOw//KdE8h71QBidBr1AT6WM+stK2PbYfj9WuZtZgf/eguJ7b69M8swQWLqv+lLtsz3+arl9iOmPTsVK5FUL9qwtunmSQGIC4idvuuNmdNO8qYlYQvHIlo1OPW7GBfF0Kf6VW/VN09GKIxTXE9wHybWkh14vlhAgMBAAECggEBAK1/YtaoFlg4GREDWJCq+Fw8ZpK0RUKBtprfOmOLTf+w87Vbt+t1GB6yoCcBZ02pspTjM7SyB6HIs0DlPJD3UOdpU8X8UVWp89pAlKWaqgC+BiR11dK/WPXnUXORXAmJCSrPxO9RqCozTkqzFuSjN55DKkiUkv2FtS9NaQEy/+OW3ctP+RZ4fTfccrRnGhfRjZNI3cLDiRzhudJsZOKZqaZP0VBpkA0qAYrv6ZAHKfdH2Bp1Bz64vIB6hrZEdSJAD2GTJGHzY66Ixnocs+iEFon1BJGI4f3703zcwgoHHvPWvONSueUdO/8NUyVpFsu+JjT97IjX2km2G2BTg02h3MECgYEA81LahocY9XaKMPHcSoDPZ9VB7dwfbfI3PNx50rf7zH85vQMCxc/utHdGUtBR4vTPwhHn+ltzfDpQzxfyHmnaXq0YiPRQp4if9DzY2FfHxUeUNGZziea5dDmfO4efS/MuKB6lTmI5pjXjmX5setElS1FRW8Mh45L0q9SXeukfUykCgYEA4t/vCYZyYw7mga3EyxjGepd59H83oYZrtWtXaQ2HVSCa6jAEZm+7Dx3WVmlwqNOoiuHaq+yrTKqalgHNnafNIWUphuTuiPLrO8DKvd/TyGOiSp3DuEeQcKroOsULDXip/l+abBPNGV3KLMGhEpWRSX+Cz+B9P4DqNlxQuLxXs3kCgYAE/mFPu3wOpZUmdgBAYy5egijtOcRHXF432IqDgZUgWEgWEfa/monamEwQLQhRMRcGc5mgMLpJBWVdKq+kYiXCJalIPkNdfNdTiuAkaIDIErT+8k9SuDJ8KSaUcS8avu3mkuJvnmJyf86g+tA9IQez6QJTcMjEQ+LTl/RX6GrlKQKBgB6QZoaU+0IHFtyviUyHKO4JDB/5J4h2MHp/XIZFkU7Rlq0oDN+z+7Jcpax8hfXoldMn/CqfNrCcZzkAQzATFBqEo2SN4OjIORKStX2A8uoTKiD9QgnIclgLXj/UndmRwO0I+ifHPyFEtmDzMPzs82bAa+IPbzAn8OWj6CgLD5GZAoGBAJ1QMSJxd2YVLg4wqAvoNhwD+b94lNBqBDskjRtSczrjBoUlg0e0dKOgd40VC7sbcmL1mDKALQlM1Eg0tNZCZ69N577mstjw5IPC6dh+3C6wCzrjFOWOmumKvEW0K6t0E/RSIPWwRebEXMIlLayMOd8rNYEknVXyYr7vuDXLwhpj"

**Comment by reloverevolt** [comment]
Just solved!

wrong
`base64_decoded_data = b64decode(encrypted_data + '==')`

works!
`base64_decoded_data = urlsafe_b64decode(encrypted_data + '==')`
