### ISSUE TITLE
Wrong typing specified for KDF

### ISSUE THREAD

**Issue by curtisforrester** [Legrandin/pycryptodome#634]
There is some incorrect typing and inconsistencies in the KDF.pyi.

The type for "RNG" should define two `bytes` (not `int`) parameters (rather than one) for consistency with HMAC (etc).
https://github.com/Legrandin/pycryptodome/blob/dfb16dd6e253d4e3e8df89f48824e90f307fc38f/lib/Crypto/Protocol/KDF.pyi#L4

Should be something like:
```
Buffer = Union[bytes, bytearray, memoryview]  # Like the HMAC.pyi
RNG = Callable[[Buffer, Buffer], bytes]
```

**Comment by Legrandin** [comment]
`RNG` is the type of the `prf` parameter to `Crypto.KDF.PBKDF`, which must be a function that takes an `int` as only parameter, so the current definition of `RNG` seems correct. I don't think it should be modified.
