### ISSUE TITLE
AES 256 CTR wrong output after 16 bytes of text

### ISSUE THREAD

**Issue by Enemias-Itzep** [Legrandin/pycryptodome#635]
I am using the AES 256 CTR and comparing it to the OpenSSL AES 256 CTR. When I see the encryption results they both match up until 16 bytes. The text after 16 bytes do not match.

This is what I am initializing:

KEY = '12345678901234567890123456789012'
`
cipher = AES.new(KEY, AES.MODE_CTR, counter=Counter.new(128, little_endian=True, initial_value=2)
ciphertext = cipher.encrypt('!E!E!E!E!E!E!E!E!E')

`
ciphertext from pycryptodome cipher: 
[181, 185, 46, 145, 229, 34, 171, 194, 50, 94, 133, 223, 226, 139, 73, 183, 104, 189]

ciphertext from OpenSSL:
[181, 185, 46, 145, 229, 34, 171, 194, 50, 94, 133, 223, 226, 139, 73, 183, 133, 72] 

As you can see bytes 17 and 18 are not equivalent.

When I test the pycryptodome using different IV for encrypting '!E' I get
Current IV: 3
[104, 189]                  This is the data past 16 bytes with IV=3 using pycryptodome 
Current IV: 2
[181, 185]                  This is the data past 16 bytes with IV=2 using pycryptodome 

So I am assuming pycryptodome increments the counter after a block (16 bytes). Is this correct?

**Comment by Legrandin** [comment]
OpenSSL uses a big endian counter, not a little endian counter.
See also here:

https://stackoverflow.com/questions/57486687/what-counter-increment-function-is-used-by-openssl-evp-aes-256-ctr

**Comment by Enemias-Itzep** [comment]
> OpenSSL uses a big endian counter, not a little endian counter. See also here:
> 
> https://stackoverflow.com/questions/57486687/what-counter-increment-function-is-used-by-openssl-evp-aes-256-ctr

So does this mean I cant use pycryptodome to check the encryption of OpenSSL? If I use big endian with pycryptodome counter, it doesnt output the correct encryption at all (1st block does not match)

**Comment by Varbin** [comment]
@Enemias-Itzep Here is working code for your problem:

```python3
from Crypto.Cipher import AES
START = 2
KEY = b'12345678901234567890123456789012'

# Counter will start at 2658455991569831745807614120560689152 (0x2000000000000000000000000000000)
cipher = AES.new(KEY, AES.MODE_CTR, counter=Counter.new(128, little_endian=False, initial_value=int.from_bytes(START.to_bytes(16, "little"), 'big')))
print(list(cipher.encrypt(b'!E!E!E!E!E!E!E!E!E')))
# [181, 185, 46, 145, 229, 34, 171, 194, 50, 94, 133, 223, 226, 139, 73, 183, 133, 72]
```

**Comment by Enemias-Itzep** [comment]
> @Enemias-Itzep Here is working code for your problem:
> 
> ```python
> from Crypto.Cipher import AES
> START = 2
> KEY = b'12345678901234567890123456789012'
> 
> # Counter will start at 2658455991569831745807614120560689152 (0x2000000000000000000000000000000)
> cipher = AES.new(KEY, AES.MODE_CTR, counter=Counter.new(128, little_endian=False, initial_value=int.from_bytes(START.to_bytes(16, "little"), 'big')))
> print(list(cipher.encrypt(b'!E!E!E!E!E!E!E!E!E')))
> # [181, 185, 46, 145, 229, 34, 171, 194, 50, 94, 133, 223, 226, 139, 73, 183, 133, 72]
> ```

Ah I see now, I was thinking the initial value was saved as big endian already. Thank you so much!
