### ISSUE TITLE
Issues with PKCS#7 padding implementation

### ISSUE THREAD

**Issue by phoewass** [Legrandin/pycryptodome#636]
I discovered some edge cases while trying to implement PKCS#7 padding and comparing it to this library's implementation.

The issue happens mainly when `len(data_to_pad) % block_size` is 0.

### Current behavior
When the length of `data_to_pad` can be devided by `block_size`, a padding of `block_size` is added .
```python
block_size = 16
data_to_pad = b'YELLOW SUBMARINE'
padded_data = pad(data_to_pad, block_size, style='pkcs7')
print(padded_data)
```
`b'YELLOW SUBMARINE\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10'`

### Expected behavior
According to the specification https://datatracker.ietf.org/doc/html/rfc5652#section-6.3
no padding should be added `if lth mod k = 0`

```python
block_size = 16
data_to_pad = b'YELLOW SUBMARINE'
padded_data = pad(data_to_pad, block_size, style='pkcs7')
print(padded_data)
```
`b'YELLOW SUBMARINE'`

**Comment by Legrandin** [comment]
I believe you are misreading the RFC.
When `lth mod k = 0`, the padding to add is (according to the RFC):

`k k ... k k`

That is what the library does today.

**Comment by phoewass** [comment]
Thanks a lot for the clarification, you are right.
We can close this issue.

And sorry again :)
