### ISSUE TITLE
Random e in Crypto.PublicKey.RSA.generate()

### ISSUE THREAD

**Issue by davejakenic** [Legrandin/pycryptodome#638]
Hi,

I would like to use point-symmetric public cryptography. That is, I want to have two keys k1 and k2 of which either decrypts the other,
but without one being able to guess one from the other. Now, if always one of the keys has the exponent 65337 then this just poses a risk to the naive user (say me).

Thus, I'd like an open for the use-case of securely publishing any one single key of k1 or k2.

Can this be made possible?
I am thankful for advice.
I will explicitly not care for any lecture on why I should use a specific e.

**Comment by Legrandin** [comment]
Probably something like this:

    from Crypto.PublicKey import RSA
    from Crypto.Random.random import randint

    k = RSA.generate(2048, e=randint(0, 2**2048)+1)

where the public key (e, n) is as random as the private (d, n).
