### ISSUE TITLE
Short, insecure ARC4 keys

### ISSUE THREAD

**Issue by mmaps** [Legrandin/pycryptodome#639]
Currently, the ARC4 cipher will [enforce a minimum key length of 5 bytes](https://github.com/Legrandin/pycryptodome/blob/99273ea596aa6fb4ae9f18f7efa17d6bb359f35b/lib/Crypto/Cipher/ARC4.py#L137).

This is better security, but there exist some scenarios where non-cryptographically-secure output is acceptable.

Would pycryptodome be open to changing this behavior by adding something like an "insecure" option to the ARC4 cipher constructor? That would enable a check [here](https://github.com/Legrandin/pycryptodome/blob/99273ea596aa6fb4ae9f18f7efa17d6bb359f35b/lib/Crypto/Cipher/ARC4.py#L55) like `if not insecure and len(key)...`

**Comment by stevemk14ebr** [comment]
To elaborate, the RC4 algorithm doesn't require any minimum key sizes, a 1 byte key is as valid as a 100 byte one. By having this limit in pycryptodome it prevents users from decrypting RC4 data that was encrypted with a short 'insecure' key.

**Comment by Legrandin** [comment]
Apart from the educational value, is there any practical application of these shorter lengths? Is there any system or protocol that uses a 1 byte "key"?

**Comment by stevemk14ebr** [comment]
Yes, there are. The algorithm doesn't have a limit, enforcing one breaks systems. It's not just a 1 byte key that is excluded, it's any key <=5 which excludes real systems. Malware for example, has used keys of this size. Writing decoders for those samples is problematic with this library.

**Comment by Legrandin** [comment]
Fixed with 7e59254350d4ca0dc6566a12d6c48154e8542926

**Comment by Legrandin** [comment]
Now in v3.16.0
