### ISSUE TITLE
pycryptodomex attempts to utilize MD5 on FIPS enabled machines, throws errors

### ISSUE THREAD

**Issue by dmurphy18** [Legrandin/pycryptodome#64]
Using pycryptodomex on FIPS enabled Redhat 6 & 7 systems is throwing ValueError or other UnboundedLocallError due to the use of MD5 which is now disabled on FIPS enabled systems.

see: 
https://github.com/saltstack/salt/issues/40890
https://github.com/saltstack/salt-pack/issues/261

The problem is use of the pattern:
try:
  from hashlib import md5
except ImportError:
 from md5 import md5

But on FIPS enabled systems MD5 is disabled.

Note this pattern is used in other Python files too, as shown in the comments of the salt-pack issue. 

Note the UnboundedLocalError in yacc.py due to MD5 instantiation failing  generated by use of : 
File "/usr/lib64/python2.7/site-packages/Cryptodome/Util/_raw_api.py", line 89, in 

results in MD5 instantiation failing

**Comment by Legrandin** [comment]
Master includes now native code for (the venerable) MD5 and SHA1 so `Crypto.Hash.MD5` and `Crypto.Hash.SHA1` are always available regardless of the OpenSSL library linked to Python.

**Comment by Legrandin** [comment]
Fixed in v3.5.1.
