### ISSUE TITLE
Can you publish a python 3.10 wheel?

### ISSUE THREAD

**Issue by augard** [Legrandin/pycryptodome#643]
I am running homeassistant os, where only pip is available, and no package manager or gcc.
(https://www.home-assistant.io/installation/raspberrypi)

**Comment by Legrandin** [comment]
Have you tried to install the wheel from piwheels (https://www.piwheels.org/project/pycryptodome)?
I see they have ABI3 wheels which might work for python 3.10.

**Comment by Lana-Deere** [comment]
I would second the request to have a python 3.10 wheel available on pypi.org.  Potential consumers won't know to go looking at other web sites.  If the 3.10 wheel isn't compatible with 3.11, then consider this a request for a 3.11 wheel as well.

**Comment by Varbin** [comment]
@Lana-Deere The published wheels are already compatible across Python versions. Please see the "abi3" in the filenames, effectively meaning they are compatible with any newer version in addition to the one in the filename.

**Comment by Lana-Deere** [comment]
Hmm, pip3 doesn't find the wheel.  I'm not sure why.

`$ pip3 --version`
`pip 22.3.1 from /home/tools/python/Python-3.10.8-install/lib/python3.10/site-packages/pip (python 3.10)`
`$ pip3 install cryptodomex`
`ERROR: Could not find a version that satisfies the requirement cryptodomex (from versions: none)`
`ERROR: No matching distribution found for cryptodomex`

**Comment by Lana-Deere** [comment]
pip3 does install it successfully from the source tar file.

**Comment by Akuli** [comment]
> `$ pip3 install cryptodomex`

The name of the library is `pycryptodome` or `pycryptodomex`, not `cryptodome`.
