### ISSUE TITLE
documentation of how to create an ECC generator

### ISSUE THREAD

**Issue by davejakenic** [Legrandin/pycryptodome#652]
Suppose I want to specify a curve ed25519 and fetch its generator ```G``` for subsequent computations.
How do I do this?
The documentation
https://pycryptodome.readthedocs.io/en/latest/src/public_key/ecc.html?highlight=ECC
shows how to create a key. But I would like to know how to get G such that I can make computations like ```H=k*G```.
Is there a more rigorous documentation that I am missing out on?
Kind regards.

**Comment by Legrandin** [comment]
At the moment, there is no public API to access domain parameters, such as the generator.
You can create G ffor Ed25519 by explicitly passing its affine, well-known coordinates:

    from Crypto.PublicKey.ECC import EccPoint
    G = EccPoint(EccPoint(0x216936d3cd6e53fec0a4e231fdd6dc5c692cc7609525a7b2c9562d608f25d51a, 0x6666666666666666666666666666666666666666666666666666666666666658, curve='ed25519')
