### ISSUE TITLE
About installation failure

### ISSUE THREAD

**Issue by zxctw** [Legrandin/pycryptodome#657]
Hi, I would like to know, how can I fix the problem I am having while installing pycryptodome

python3 3.9.12
wheel 0.37.1
pip 22.2.1

https://i.imgur.com/XJElfu1.png

**Comment by Varbin** [comment]
Please provide full, verbose logs (e.g. `pip install -v pycryptodome`). I would kindly ask you to just attach them as a file, not an image.

My first guess for the cause would be that you are likely missing development packages: As pycryptodome includes C extensions, it requires additional packages. I'm no expert on OpenWRT, but you likely at least need these three package: *python3-dev*, *libffi*, *gcc*. The packages *python3-dev* and *gcc* can be removed after the installation of pycryptodome.

**Comment by zxctw** [comment]
First, I would like to know how to upload the file?

**Comment by Varbin** [comment]
Either use drag and drop to move the file into the comment box, or click on the text below it ("Attach files by ...") and select the file you want to upload. 

This will create a link to the just uploaded file, like this one: [test.log](https://github.com/Legrandin/pycryptodome/files/9262988/test.log)

**Comment by zxctw** [comment]
Don't know if this is possible?

[putty.log](https://github.com/Legrandin/pycryptodome/files/9265960/putty.log)

**Comment by Varbin** [comment]
@zxctw While the attachment works, this is still the non-verbose log. Please run `pip install -v pycryptodome` (please mind the `-v` flag!) and attach the resulting log.

The "default" output of *pip* unfortunately does not include the underlying error, but only the unhelpful message that it did not work. With the `-v` flag, pip will additionally print the otherwise hidden underlying error.

**Comment by zxctw** [comment]
oh, i see what you mean！The attachment is to use the log with the -v installation command

[putty.log](https://github.com/Legrandin/pycryptodome/files/9274471/putty.log)

**Comment by Varbin** [comment]
Thanks.

Looking at this line: gcc: error: unrecognized command line option '-ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-aarch64_generic_musl/Python-3.9.12=Python-3.9.12'
It seems thus is a problem with the shipped GCC version. This particular argument (--file-prefix-map) is only supported with GCC 8.4 or so. The issue that OpenWRT seems to ship only an older GCC version together with Python occurred to others before (e.g. https://github.com/pandas-dev/pandas/issues/40997).

I guess you ultimately need a newer GCC version.


Am 6. August 2022 08:06:17 MESZ schrieb zxctw ***@***.***>:

**Comment by zxctw** [comment]
I just found out that "libgcc1" can be updated to version 8.4.0-3 if I update it will this fix the problem?  Or do I need to update the GCC ontology?

**Comment by zxctw** [comment]
@Varbin  I just found the GCC installation file of version 11.2.0-4 on the download page of openWRT version 22.03.  and successfully installed GCC of 11.2.0-4
