### ISSUE TITLE
Crypto.Protocol.KDF.PBKDF2 converts password to bytes but not salt

### ISSUE THREAD

**Issue by oyiptong** [Legrandin/pycryptodome#66]
The documentation mentions that the salt is expected to be a `str`.

This isn't accurate, the code expects it to be of type `bytes`.

https://github.com/Legrandin/pycryptodome/blob/2e0f288809bd68a46f881865b0a60f9c54c4751f/lib/Crypto/Protocol/KDF.py#L126

This is evidenced in the tests: https://github.com/Legrandin/pycryptodome/blob/2e0f288809bd68a46f881865b0a60f9c54c4751f/lib/Crypto/SelfTest/Protocol/test_KDF.py#L94

Either the documentation should be fixed or the function should be fixed to take a string, to be converted to bytes.

I would argue the latter to make more sense, i.e. salt to also be converted to bytes in the function

**Comment by oyiptong** [comment]
I can make a PR if that's the direction you'd like to take

**Comment by Legrandin** [comment]
Fixed in v3.5.1.
