### ISSUE TITLE
Result of AES encryption and then description is not same as original data file

### ISSUE THREAD

**Issue by snowuyl** [Legrandin/pycryptodome#665]
I try AES encryption then description. But result of AES encryption and then description is not same as original data file.

**Comment by snowuyl** [comment]
[data.dat.enc.dec.gz](https://github.com/Legrandin/pycryptodome/files/9474729/data.dat.enc.dec.gz)
[data.dat.enc.gz](https://github.com/Legrandin/pycryptodome/files/9474730/data.dat.enc.gz)
[data.dat.gz](https://github.com/Legrandin/pycryptodome/files/9474732/data.dat.gz)

**Comment by snowuyl** [comment]
[aes.py.gz](https://github.com/Legrandin/pycryptodome/files/9474735/aes.py.gz)

**Comment by Varbin** [comment]
You do use *cipher block chain mode of operation* (CBC). It works XORing the current plain text block with the previous ciphertext one. For the first block - where no previous one exists - an initialization vector is required. You can see this in the picture below.

[![Encryption in CBC mode of operation. The description is in the paragraph above](https://upload.wikimedia.org/wikipedia/commons/8/80/CBC_encryption.svg)](https://upload.wikimedia.org/wikipedia/commons/8/80/CBC_encryption.svg)

To prevent some security issues the IV needs to be unpredictable and should not be reused. The IV is not secret. It usually is chosen randomly and then stored with the ciphertext.

During decryption, the same happens in reverse. 

[![Decryption in CBC mode of operation](https://upload.wikimedia.org/wikipedia/commons/2/2a/CBC_decryption.svg)](https://upload.wikimedia.org/wikipedia/commons/2/2a/CBC_decryption.svg)

So what is wrong with your code? I copied the relevant portions from your linked file and marked the relevant line.

```python3

class Aes:
    def __init__(self):
        # ...
        self.cipher = AES.new(self.key, AES.MODE_CBC)  # <------------ A random IV is generated here!

# ...

    def encrypt(self, data):
        ciphered_data = self.cipher.encrypt(pad(data, AES.block_size))
        return ciphered_data

# ...

    def decrypt(self, data):
        decrypt_data = unpad(self.cipher.decrypt(data), AES.block_size)
        return decrypt_data
```

To prevent insecure code, a random IV is chosen whenever you call `AES.new()` without one. Now, when you create a new instance of your `Aes`-class, a new IV is generated. For decryption, the same IV needs to be used again.

The code below stores the IV with the cipher text and then uses this stored IV on decryption.

```python3

class Aes:
    def __init__(self):
        # ...

# ...

    def encrypt(self, data):
        cipher = AES.new(key, mode=AES.MODE_CBC)
        ciphered_data = cipher.IV + cipher.encrypt(pad(data, AES.block_size))
        return ciphered_data

# ...

    def decrypt(self, data):
        cipher = AES.new(key, mode=AES.MODE_CBC, iv=data[:16])
        decrypt_data = unpad(self.cipher.decrypt(data[16:]), AES.block_size)
        return decrypt_data
```

Please do not forget to authenticate your cipher texts!


See also #359, #342, ...

**Comment by snowuyl** [comment]
Thanks for your reply!
