### ISSUE TITLE
Where is the released source code for 3.16.0?

### ISSUE THREAD

**Issue by bdubbs** [Legrandin/pycryptodome#668]
Where am able to download version 3.16.0 similar to 
https://github.com/Legrandin/pycryptodome/archive/v3.15.0/pycryptodome-3.15.0.tar.gz with wget or similar.

A git clone is not really useful for the linuxfromscratch books.

**Comment by Akuli** [comment]
3.16 is not released yet, but you could download a zip file instead.
- Latest `master` (changes as pycryptodome is developed): https://github.com/Legrandin/pycryptodome/archive/refs/heads/master.zip
- The commit that is currently the latest commit on `master`: https://github.com/Legrandin/pycryptodome/archive/7e59254350d4ca0dc6566a12d6c48154e8542926.zip

To get these URLs, I clicked GitHub's green "Code" button, then right-clicked "Download ZIP", and selected "Copy link address".

If you are doing linuxfromscratch, you might not have `unzip` installed yet, but you probably have Python if you are trying to install pycryptodome. Python's `zipfile` module from the standard library can be called from command line to extract zip files:

```
$ wget https://github.com/Legrandin/pycryptodome/archive/refs/heads/master.zip
$ python3 -m zipfile -e master.zip .
$ ls pycryptodome-master/
AUTHORS.rst      FuturePlans.rst  pct-speedtest.py       src
bench_monty.py   INSTALL.rst      README.rst             test_vectors
Changelog.rst    lib              requirements-test.txt
compiler_opt.py  LICENSE.rst      setup.cfg
Doc              MANIFEST.in      setup.py
```

**Comment by bdubbs** [comment]
Thank you.  Is there a place where the latest stable release is listed?  Everything I see discusses pip and that does not specify a version, but we show users how to download the source and build/install from that.

**Comment by Akuli** [comment]
Like many other projects, pycryptodome marks the released versions with Git tags. You can see all tags by clicking the branch selector dropdown (at top left, it says "master" by default), then "Tags" and then "View all tags".

**Comment by Akuli** [comment]
Oh, I forgot to mention: Looking at Changelog.rst might be useful as well. It currently says "3.16.0 (xx xx 2022)" which is how I knew that 3.16 is not supposed to be released yet. There's no `v3.16.0` tag either, but that could also mean that the intention was to do a release but whoever did it forgot to create a tag.

**Comment by bdubbs** [comment]
OK, I see where the tags are.  My problem is that we have a set of scripts that check the latest stable version for over 1000 packages daily.  I don't see a good way to get to that tags dropdown via a script.

It would really help me if there was a line somewhere that said something like "The latest stable version is 3.15." that would be updated when a new version is released.  It doesn't need to be on github.  Someplace on https://www.pycryptodome.org/ would work also.

For most github projects I can have a script go to releases or tags and determine the latest release from that page.  For instance:

https://github.com/logrotate/logrotate/releases

But that does not seem to be available for this project.

**Comment by Akuli** [comment]
> I don't see a good way to get to that tags dropdown via a script.

```
$ git clone https://github.com/Legrandin/pycryptodome/
$ cd pycryptodome
$ git tag
```

> if there was a line somewhere that said something like "The latest stable version is 3.15."

You can use pypi (which is where `pip install` downloads packages from), even if you want to download the actual package from github: https://pypi.org/project/pycryptodome/

pypi also provides an API, which I found by googling for "pypi api":

```
$ curl -s -H "Accept: application/json" https://pypi.org/pypi/pycryptodome/json | grep -o '"version":"[^"]*"'
"version":"3.15.0"
```

This is probably the best way for most Python libraries.

**Comment by bdubbs** [comment]
That will work.  Thanks.
