### ISSUE TITLE
legacy-install-failure: invalid active developer path, missing xcrun

### ISSUE THREAD

**Issue by Openstreetmapler** [Legrandin/pycryptodome#671]
System: macOS Big Sur (11.6) on iMac (24", M1, 2021)

I am trying to install _pycryptodomex_ because it a dependency of _yt-dlp_ required to download anything from YouTube.

Problem: With both the commands `pip3 install pycryptodomex` and `pip3 install --upgrade yt-dlp` (installs _pycryptodomex_ in the process), installation quits with a _legacy-install-failure_.

If running the command `pip3 install --upgrade yt-dlp`, the very end of the output looks like this:

```
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -Isrc/ -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/MD2.c -o build/temp.macosx-10.9-universal2-cpython-310/src/MD2.o
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycryptodomex

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Full-length, verbose output (command `pip3 install --upgrade yt-dlp -v`) can be found here: https://pastebin.com/4wmJ3de7

**Comment by Varbin** [comment]
I'd guess your XCode command line tools are not properly installed, or at a different location.

**Comment by Jules-WinnfieldX** [comment]
Dealing with this as well, an easy fix without having to install the entirety of xcode can be found here: https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by Openstreetmapler** [comment]
Installed Xcode and successfully installed yt-dlp afterwards.
