### ISSUE TITLE
Bug or Question - Can't import key from npm `openpgp` generated key

### ISSUE THREAD

**Issue by Myzel394** [Legrandin/pycryptodome#674]
Okay so here's what I want to achieve:

1. Generate a new public / private key pair using the Javascript library `openpgp` (see https://www.npmjs.com/package/openpgp#generate-new-key-pair)
2. Import it in `pycroptodome`

No matter how I specify the configuration for the keys, I always get an error when I try to `RSA.import_key` the key. Sometimes I get this error:

```
ValueError: RSA key format is not supported
```

and other times I get this error:

```
ValueError: RSA key format is not supported
```

I'm sorry if this is an issue on my end, but maybe someone could help me out here? Been stuck on this for some days now :/

**Comment by Akuli** [comment]
pycryptodome doesn't support PGP keys: #663

**Comment by Myzel394** [comment]
@Akuli ohhh that's a pity. Do you by chance know a Python library that supports PGP keys?

**Comment by Akuli** [comment]
No, I have never had to work with PGP keys. Sorry :)

That said, if you only need to support specific a kinds of keys (e.g. private 4096-bit RSA key in PGP format with no passphrase), it might not be too difficult to find the relevant bytes from the key file (for a private RSA key these would be the `n` and `d`, most likely stored as big-endian). You could also look at how the javascript library does it.

**Comment by zachliu** [comment]
@Myzel394 try [python-gnupg](https://pypi.org/project/python-gnupg/). my understanding is that it's not needed for `pycryptodome` to support openpgp.

`pycryptodome` is the building blocks, `openpgp` is a building :grin:
