### ISSUE TITLE
Usage of `os.path.isfile` to load raw libs fails inside `zipimport`

### ISSUE THREAD

**Issue by mattfysh** [Legrandin/pycryptodome#676]
I need to deploy my python code in a zip and then add that zip to sys.path. The following code uses `os.path.isfile` which does not work when running via `zipimport`

https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Util/_raw_api.py#L303

Is there any way to resolve this? unfortunately I'm running in a cloud environment and cannot unzip the archive

**Comment by Legrandin** [comment]
I am afraid it is not possible. `pycryptodome` is based on dynamic modules and `zipimport` disallows importing them. That is a fundamental limitation, not related to `os.path.isfile`.
