### ISSUE TITLE
Musllinux wheels

### ISSUE THREAD

**Issue by nakata5321** [Legrandin/pycryptodome#678]
Hello!

I'm working with Home Assistant OS. Home Assistant OS is build on Alpine, which is `musllinux` system. And on HA OS i can not build your library without wheels.
But on PyPI our library has only `manylinux` system support. Can you provide wheels for `musllinux` system? Especially for `aarch64` and `x86_64` architectures.
I really need this wheels, because by default HomeAssistant OS doesn't install gcc, so i can not install my integration(which use your library) from the box. And HomeAssistant OS doesn't allow to install side packages.

**Comment by ben9923** [comment]
I've opened a PR to add `musllinux` wheels a month ago.
They sure would be useful :)

**Comment by nakata5321** [comment]
> I've opened a PR to add `musllinux` wheels a month ago. They sure would be useful :)

That is very good. I have not seen that PR.
But as I see in Pr, you provide `musllinux` wheels only for `x86` platform. Although, I need wheels for `aarch64` platform.

**Comment by ben9923** [comment]
I only added `x86_64 musllinux` to keep changes minimal for higher chance of approval, haha :P

@Legrandin what is your opinion on this matter?
Indeed it's super easy to also build `aarch64`. With parallelism tweaks it won't have a lot of impact on workflow execution time.
I'd be happy to add those changes as well.

**Comment by Legrandin** [comment]
I created the `musllinux` wheels for `aarch64` and uploaded on PyPI. I will soon make a small release and push also `musllinux`  wheels for `x86_64` using the great work that @ben9923 shared.

All wheels for `aarch64` are currently created on RPIs. I am curious to know how long it would take to do the same on GitHub using the QEMU approach... even now, for Linux `x86_64/i686` the job takes ~25 minutes, and that's already quite long.

**Comment by ben9923** [comment]
@Legrandin GitHub Actions should allow a couple more jobs running concurrently before hitting the limit (20?).
Linux wheels workflow could be parallelized on a per-arch basis, it might even make it a bit shorter.

**Comment by Legrandin** [comment]
All musl wheels available with v3.16.0.
