### ISSUE TITLE
TypeError: '_hashlib.HASH' object is not subscriptable

### ISSUE THREAD

**Issue by R-Rothrock** [Legrandin/pycryptodome#684]
I'm using Python 3.10, and I'm getting a strange error when trying to call a cipher.
```python
from Crypto.Cipher import AES
import hashlib

def sha256(plain_text: str):
    return hashlib.sha256(bytes(plain_text, "utf-8"))

def AES_encrypt(plain_text: str, password: str) -> list:
    plain_bytes = plain_text.encode("utf-8")
    key = sha256(password)    
    cipher = AES.new(key, AES.MODE_EAX)
    encrypted_text, tag = cipher.encrypt_and_digest(plain_bytes)

if __name__ == "__main__":
    password = "password"
    plain_text = "very important government data"
    print(AES_encrypt(plain_text, password)[0])

```
Here's the traceback I'm getting:
```
Traceback (most recent call last):
  File ".../test.py", line 16, in <module>
    print(AES_encrypt(plain_text, password)[0])
  File ".../test.py", line 10, in AES_encrypt
    cipher = AES.new(key, AES.MODE_EAX)
  File ".../env/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File ".../env/lib/python3.10/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File ".../env/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py", line 408, in _create_eax_cipher
    return EaxMode(factory, key, nonce, mac_len, kwargs)
  File ".../env/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py", line 107, in __init__
    self._omac = [
  File ".../env/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py", line 108, in <listcomp>
    CMAC.new(key,
  File ".../env/lib/python3.10/site-packages/Crypto/Hash/CMAC.py", line 301, in new
    return CMAC(key, msg, ciphermod, cipher_params, mac_len,
  File ".../env/lib/python3.10/site-packages/Crypto/Hash/CMAC.py", line 56, in __init__
    self._key = _copy_bytes(None, None, key)
  File ".../env/lib/python3.10/site-packages/Crypto/Util/py3compat.py", line 171, in _copy_bytes
    return seq[start:end]
TypeError: '_hashlib.HASH' object is not subscriptable                                                     
```
If it helps, I'm using a `virtualenv` virtual environment on Kali Linux

Any help is much appreciated.

**Comment by Akuli** [comment]
Your `sha256()` function does not return a string. It returns a hash object that has methods `.digest()` and `.hexdigest()` to get the hash as bytes or a hex string. Running a type checker would point this out to you.

**Comment by R-Rothrock** [comment]
You're right; I did some fidgeting with the code to put it on here and I didn't fix that. But this isn't a problem with `hashlib`; it's a problem with calling `Crypto.AES.new`, if you look at the traceback

**Comment by Akuli** [comment]
This is a bug in your code. You are passing an object of the wrong type to `Crypto.AES.new`. If you look at `lib/Crypto/Cipher/AES.pyi`, it expects a bytes-like object (`Union[bytes, bytearray, memoryview]`), but you are passing it a hash object from hashlib.

Python is a dynamically typed language (unless you use a type checker), so passing in an object of the wrong type typically gives an error that comes from somewhere in the library's internals. It doesn't mean that the library is somehow broken. It's just how Python works.

**Comment by R-Rothrock** [comment]
Oh!!! I see the problem. How foolish of me :-) I now see why it started throwing the TypeError as I continued programming. Sorry for the dumb question. Given that, the traceback makes decent sense.
