### ISSUE TITLE
AttributeError: module 'Crypto' has no attribute 'Hash'

### ISSUE THREAD

**Issue by R-Rothrock** [Legrandin/pycryptodome#686]
To start, I'm using Python 3.11, so I totally understand things like this happening. I can install pycryptodome for 3.11 just fine, but here's the actual problem:
```python
Python 3.11.0+ (main, Nov  4 2022, 09:23:33) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Crypto as c
>>> dir(c.Hash)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Crypto' has no attribute 'Hash'
>>> 
```
Again, I totally get it if you guys are getting bugs with the new version of Python.

**Comment by Legrandin** [comment]
This seems normal behavior for any version of Python.
`Hash` is not an attribute of `Crypto` but a submodule, so you can't access it as `Crypto.Hash` in a statement unless you do first:

    import Crypto.Hash

**Comment by R-Rothrock** [comment]
I could have **sworn** that I tried that... but I didn't, and it works fine. Sorry for the dumb question :)
