### ISSUE TITLE
Decrypt existing Fernet with pycryptodome

### ISSUE THREAD

**Issue by fhempy** [Legrandin/pycryptodome#691]
Hi,
I would like to switch from cryptography to pycryptodome. To make that switch possible for my users, I would need to support decryption of Fernet encrypted data via pycryptodome. Is that possible at all?
Thx!

**Comment by Legrandin** [comment]
A simple approach is (assuming the key can be trusted):

    from base64 import urlsafe_b64decode

    from Crypto.Cipher import AES
    from Crypto.Util.Padding import unpad
    from Crypto.Hash import HMAC, SHA256

    def decrypt_fernet(key_b64, token_b64):

        keys = urlsafe_b64decode(key_b64)
        token = urlsafe_b64decode(token_b64)

        try:
            hmac_key, dec_key = keys[:16], keys[16:]
            HMAC.new(hmac_key, token[:-32], digestmod=SHA256).verify(token[-32:])
            ts, iv, ct = token[1:9], token[9:9+16], token[9+16:-32]
            # Possibly check time-to-live here
            message = unpad(AES.new(dec_key, AES.MODE_CBC, iv=iv).decrypt(ct), 16)
        except ValueError:
            print("Invalid token")
            message = None

        return message

**Comment by fhempy** [comment]
Thank you very much, works as expected!
