### ISSUE TITLE
Raise ImportError along with OSError when .so files can't be imported

### ISSUE THREAD

**Issue by DUOLabs333** [Legrandin/pycryptodome#692]
Is it possible for Crypto to raise OSError as well as ImportError when an so file can't be loaded during importing?

**Comment by Legrandin** [comment]
What is the reason for doing so?

**Comment by DUOLabs333** [comment]
If you install PyCryptodome but remove the .so files, then try to use yt-dlp, it will fail because youtube-dl doesn't catch OSError when importing PyCryptodome. I tried to get them to also catch OSError, but they weren't receptive.

So, it's mostly to work around one program in one application.
