### ISSUE TITLE
33-bytes public key export for secp256r1

### ISSUE THREAD

**Issue by MaJerle** [Legrandin/pycryptodome#695]
Setup: ECC secp256r1 curve
Target: get 33-bytes public key from the private component

Does this library offer direct "export" of the 33-bytes public key (1bit padding + 256bits)?
https://cryptobook.nakov.com/asymmetric-key-ciphers/elliptic-curve-cryptography-ecc#ecc-keys

Public key is part of the private key, 32-bytes, that could be used for ECDSA verification purpose.

**Comment by Legrandin** [comment]
That's the compressed SEC1 format. You can get the 33 bytes (for secp256r1) with:

    key.public_key().export(format="SEC", compress=True)
