### ISSUE TITLE
SHA256 Support for python version 3.9?

### ISSUE THREAD

**Issue by SangeethaPH** [Legrandin/pycryptodome#696]
AttributeError: function/symbol 'SHA256_init' not found in library '/usr/local/lib/python3.9/site-packages/Crypto/Util/../Hash/_SHA256.cpython-39-x86_64-linux-gnu.so': /usr/local/lib/python3.9/site-packages/Crypto/Util/../Hash/_SHA256.cpython-39-x86_64-linux-gnu.so: undefined symbol: SHA256_init
/usr/local/lib/python3.9/site-packages/cffi/api.py:838: AttributeError

Undefined symbol: SHA256_init
/usr/local/lib/python3.9/site-packages/cffi/api.py:838: AttributeError

**Comment by Legrandin** [comment]
Please clarify OS and confirm that you don't have also `pycrypto` installed.
