### ISSUE TITLE
Build failure on Haiku (conflicting header guard regarding src/errors.h)

### ISSUE THREAD

**Issue by OscarL** [Legrandin/pycryptodome#698]
As reported in https://github.com/haikuports/haikuports/issues/4684, attempting to `pip install pycryptodome` (or `python3 setup.py build` it) on [Haiku](https://www.haiku-os.org/) fails due to PyCrytodome's `src/errors.h` header guard conflicting with the `support/Errors.h` one from the Haiku system headers. Both use:

```c
#ifndef _ERRORS_H
#define _ERRORS_H
```

Just changing the one on `src/errors.h` to, for example, `CRYPTODOME_ERRORS_H`, makes it build/nstall just fine.

We're patching it that way, in the meantime, for the upcoming pycryptodome/pycryptodomex packages for Haiku.

Starting the header guard with an underscore seems bad form in any case :-) https://stackoverflow.com/a/17307796

**Comment by Legrandin** [comment]
Thanks for the heads up. This is fixed with 2c61a7b94b3addf427fe786abad418a38f1c5e80.

**Comment by Legrandin** [comment]
Fixed in v3.17
