### ISSUE TITLE
pycryptodome has  a problem it doesnt generate RSA keys well

### ISSUE THREAD

**Issue by tomergahtan** [Legrandin/pycryptodome#699]
there is an issue that happens with RSA only in pycryptodome. on other libraries, RSA works fine.

the rule is
phi =(p-1)*(q-1)

 e*d % phi = 1
 
but result is not 1.

in addition many times: e*d % phi == (phi+3)//2 is True.

this was my code 

import Cryptodome.PublicKey.RSA
key = RSA.generate(2048)
e= key.e
d= key.d
p= key.p
q= key.q
n= key.n
phi = (p-1)*(q-1)
print(e*d % phi == 1) # returns false
print(e*d % phi == (phi+3)//2) # returns True

<img width="1007" alt="Screenshot 2023-01-03 181240" src="https://user-images.githubusercontent.com/121878273/210396283-dc12328c-127b-4459-96bf-a911b452fbfd.png">

**Comment by tomergahtan** [comment]
it happened many times. i think 50% of time that i tried to generate a key

**Comment by Legrandin** [comment]
> e*d % phi = 1
> but result is not 1

Yes, that's fine. That's a condition which is sufficient but not necessary.
See https://github.com/Legrandin/pycryptodome/issues/474.

**Comment by tomergahtan** [comment]
e*d % phi == (phi+3)//2 # returns True

'what about it? is that meaning something?

**Comment by Legrandin** [comment]
I think it simply means that, for that key, gcd(p-1,q-1) is 2.
