### ISSUE TITLE
Cipher operations should accept any type that supports buffer protocol

### ISSUE THREAD

**Issue by pkoning2** [Legrandin/pycryptodome#7]
In Python 3, if I ask for a cipher operation -- like encrypt () -- I get an error if the argument is not an instance of "bytes".  That is overly restrictive; it should accept anything that obeys the buffer protocol.  In particular, "bytearray" and "memoryview" types should be permitted.

**Comment by DRayX** [comment]
This appears to be true for all instances where bytes are passed into C code including the key initialization on an HMAC or Cipher, as well as all the update or encrypt calls.  This makes using this library very irritating in python2.7 (since it is non-trivial to construct a str from a memoryview), and less efficient across the board (as all data needs to be copied in order to be passed in).

**Comment by Legrandin** [comment]
I agree this is a problem and it is relatively high on my TODO list, but it didn't quite make it to the top.

@DRayX, the `tobytes` method can easily create a byte string out of a `memoryview` object (of course, this is still not efficient).

**Comment by pkoning2** [comment]
Is the issue simply the "isinstance" check, and the C code is ok?  If the C code uses the buffer machinery of Python 3, then it would be.  If so, the correct fix of course is a new Python built-in function "isbyteslike" or something like that, but a crude workaround would be simply to use "isinstance (foo, (bytes, bytearray, memoryview))".

**Comment by DRayX** [comment]
@Legrandin Oh, I had no idea memoryview had a tobytes method, that is really good to know.

**Comment by Legrandin** [comment]
@pkoning2 No, that wouldn't work because `cffi` will not accept memoryviews or bytearrays as `char *` when calling a C function. There are some [shenanigangs](http://www.gossamer-threads.com/lists/python/dev/1011232) possible with ctypes though.

**Comment by Legrandin** [comment]
As an update, starting from [version 1.8](http://cffi.readthedocs.io/en/latest/whatsnew.html#v1-8), `cffi` accepts bytearrays so this problem becomes solvable in a clean way.

**Comment by Legrandin** [comment]
Starting from PyCryptodome version 3.5.0, bytearrays can be passed to most methods. Still some work required for memoryviews...

**Comment by Legrandin** [comment]
And starting from PyCryptodome version, also memoryviews can be passed as well, though in this case a fairly recent version of `cffi` is needed (1.11). With this I think there is enough for closing this issue.
