### ISSUE TITLE
Storing encrypted data in 'RAM'

### ISSUE THREAD

**Issue by paulddrix** [Legrandin/pycryptodome#70]
Hello I am a bit new to python and I was wondering if one of you guys could show me how I can save the encrypted data into a string or any other datatype in python. In my case, it is not liable to write that to disk the way it is shown in the example. If you could write an example where a string is encrypted with a public key and the it is decrypted with the private key. Thank you for your time and support.

**Comment by Coal0** [comment]
This isn't an issue. You should probably [ask this on StackOverflow](https://stackoverflow.com/).
