### ISSUE TITLE
Typing of some ciphers doesn't allow None for nonce

### ISSUE THREAD

**Issue by sdoering01** [Legrandin/pycryptodome#705]
Passing a `None` as the nonce results in a typing error for some ciphers (tested with mypy for `AES.new` with mode GCM and `ChaCha20_Poly1305.new`). On further investigation I saw that the typings for these functions don't include `None` for the nonce:

https://github.com/Legrandin/pycryptodome/blob/2c61a7b94b3addf427fe786abad418a38f1c5e80/lib/Crypto/Cipher/ChaCha20_Poly1305.pyi#L25
https://github.com/Legrandin/pycryptodome/blob/2c61a7b94b3addf427fe786abad418a38f1c5e80/lib/Crypto/Cipher/AES.pyi#L127-L133

Even though both treat the nonce as an optional parameter:

https://github.com/Legrandin/pycryptodome/blob/2c61a7b94b3addf427fe786abad418a38f1c5e80/lib/Crypto/Cipher/ChaCha20_Poly1305.py#L314-L316
https://github.com/Legrandin/pycryptodome/blob/2c61a7b94b3addf427fe786abad418a38f1c5e80/lib/Crypto/Cipher/_mode_gcm.py#L608-L610

I believe this is an error in the typing, that could be solved by wrapping the nonce types in `Optional`. I guess the typing in the doc-strings would have to be corrected too in that case. For example here:

https://github.com/Legrandin/pycryptodome/blob/2c61a7b94b3addf427fe786abad418a38f1c5e80/lib/Crypto/Cipher/ChaCha20_Poly1305.py#L299

I could try to look through all the Ciphers and open a Pull Request to include `None` for the nonce where it is optional, if wanted.

**Comment by Legrandin** [comment]
Thanks. Fixed with https://github.com/Legrandin/pycryptodome/commit/454cf155d1eed75c07c86ce0c386f36735853559

**Comment by Legrandin** [comment]
Fixed in v3.17
