### ISSUE TITLE
Public Key for 0xDA6CEF8DE1169912

### ISSUE THREAD

**Issue by mans0954** [Legrandin/pycryptodome#72]
I see that the PyPy pycryptodome tarballs are PGP signed by 0xDA6CEF8DE1169912

Where can I find the public key, please? It doesn't appear to be on sks-keyservers.net.

Thanks.

Christopher Hoskin

**Comment by Legrandin** [comment]
The PGP key can be found here:

https://pycryptodome.readthedocs.io/en/latest/src/installation.html#pgp-verification
