### ISSUE TITLE
Can't use the module....

### ISSUE THREAD

**Issue by Xprogrammer777** [Legrandin/pycryptodome#721]
I'm trying to switch from Crypto to pycryptodome but I got no module named error even if I installed it (on Windows 10)
I did exactly: 
pip install pycryptodome
pip install pycryptodomex

But when I run "import pycryptodome" : No module named 'pycryptodome'
So is there anything I'm doing wrong? I'm using python 3.10.10 on Windows 10 normal installation.

**Comment by Varbin** [comment]
The import name is not called pycryptodome, but Crypto or Cryptodome. You [might want to look at the examples](https://www.pycryptodome.org/src/examples).

**Comment by Xprogrammer777** [comment]
> The import name is not called pycryptodome, but Crypto or Cryptodome. You [might want to look at the examples](https://www.pycryptodome.org/src/examples).

Sorry I don't remember exactly how I fixed but I remember that I removed all package such as Crypto, pycryptodomeex etc, and it worked
