### ISSUE TITLE
License information in setup.py is different from LICENSE.rst

### ISSUE THREAD

**Issue by mokajima-MRK** [Legrandin/pycryptodome#725]
classifiers in `setup.py` include the following

* Public Domain
* Apache Software License
* BSD License

However, `LICENSE.rst` does not include a description of the Apache Software License.

* BSD License
* Public Domain

I am not sure which is correct, could you please check?

**Comment by Legrandin** [comment]
Fixed with 303888da8881ab960db35e8c2e36d7c35b50f2f8
