### ISSUE TITLE
Try-and-Increment method of ECC generator creation

### ISSUE THREAD

**Issue by gi-david** [Legrandin/pycryptodome#734]
Hi all, apologies if this is the wrong place to post a question such as this.

I am using the Nist256 curve and would like to create a second generator, independent of the default generator i.e. not related to it by scalar multiplication. 

The common way to do this is by the try-and-increment method (if there is another method which works with pycryptodome then please tell) which involves basically:
1. Create some unique hash with context specific information and some padding. Treat this as the x coordinate of the generator.
2. Find the equivalent y coordinate of the point using the curve equation
3. If this point is on the curve, then bingo you've found a new generator.
    If this point is not on the curve, then increment the padding and go back to step 1.

The problem I have is that I cannot instantiate a pycryptodome EccPoint without knowledge of both the x and y coordinates. I cannot work out what the y coordinate is according to the curve equation because I cannot reproduce the curve equation with the parameters in the private EccCurve._curve attribute. 

The _curve attribute contains p, b, order, the default generator and some other information. I cannot see how to reconstruct the curve equation from this information, is there a way to do this?

Perhaps there is a better way to go about doing this that I'm missing?
Or maybe it just isn't possible to create a second independent generator using pycryptodome?

Many thanks in advance for any input.

**Comment by Legrandin** [comment]
First, I would not recommend to use `_curve` because it is a private attribute, and it will likely change or disappear in the future, breaking your code. However, you can take the constants and keep those in your code.

Second, for a short Weierstrass curve like P256, you can use the following expression to work out `y` from `x` (taken from https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/PublicKey/ECC.py#L1252, and of course assuming that `x` is a valid affine X coordinate):

    y = (x**3 - x*3 + curve.b).sqrt(curve.p)

Since this is a short Weierstrass curve, also `curve.p - y` will be a valid affine Y coordinate.

Is this the part you cannot reproduce?

Final note, if the "context specific information" is secret, your method will leak some of it.

**Comment by gi-david** [comment]
Thank you very much for the useful information!
Some further questions:
1. Sorry if this is an elementary question. What do you mean by a _valid_ affine x/y coordinate? Presumably not a coordinate for which there is a point on the curve, as that would defeat the purpose of the try-and-increment method
2. What is meant in the equation by the .sqrt method? Are we taking the square root of `(x**3 - x*3 + curve.b)` then adding `curve.p`? `curve.p` is a prime number so cannot be square-rooted no?
3. Is it worth trying to make use of the `import_public_key` function to construct the generator point? It seems as long as I pass in a single point encoded in the correct way, then all this will be taken care of for me. Again, all this is in the context of trying to create an independent generator point which can be used to generate public keys via scalar multiplication.

**Comment by Legrandin** [comment]
1. By "valid affine X coordinate" I meant to say that X must be a quadratic residue. In other words, not all possible values of `x` will make  `x**3 - x*3 + curve.b` a valid square modulo `curve.p` (actually, only half of them will be).
2. I was using the syntax of the library, where `x.square(p)` means "square root of x modulo p".
3. To me, the simplest approach is to take a random scalar, multiply by the P256 generator, and you obtain another equally valid generator over P256 (https://crypto.stackexchange.com/questions/35016/is-every-point-on-an-elliptic-curve-of-a-prime-order-group-a-generator).

**Comment by gi-david** [comment]
1, 2: I see, that makes sense, thanks! I can then use that equation to obtain a Y coordinate from an X, attempt to instantiate an EccPoint, and will get a ValueError if the point is not on the curve, which enables me to implement the try-and-increment method.

3. I agree, this is a much simpler way to do it. However, I cannot use this method because it must be publicly verifiable that no one knows the relationship between the first and second generator. We can do this by selecting some public context specific information, hashing it and following the try-and-increment process. Once we have the correct padding we publish this information alongside the two generators so that everyone can verify that the context specific information + the padding produces the second generator. If we then had some secret relating the two, we would have had to obtain it by breaking the hash function. For everyone, obtaining the relationship between the first and second is then equivalent to solving a discrete logarithm.

I'm saying this mostly for your own interest! Many thanks.

**Comment by gi-david** [comment]
1, 2: I see, that makes sense, thanks! I can then use that equation to obtain a Y coordinate from an X, attempt to instantiate an EccPoint, and will get a ValueError if the point is not on the curve, which enables me to implement the try-and-increment method.

3. I agree, this is a much simpler way to do it. However, I cannot use this method because it must be publicly verifiable that no one knows the relationship between the first and second generator. We can do this by selecting some public context specific information, hashing it and following the try-and-increment process. Once we have the correct padding we publish this information alongside the two generators so that everyone can verify that the context specific information + the padding produces the second generator. If we then had some secret relating the two, we would have had to obtain it by breaking the hash function. For everyone, obtaining the relationship between the first and second is then equivalent to solving a discrete logarithm.

I'm saying this mostly for your own interest! Many thanks.
