### ISSUE TITLE
cannot import name 'tostr' from 'Crypto.Util.py3compat'

### ISSUE THREAD

**Issue by nabilragab** [Legrandin/pycryptodome#745]
on python3.10 with version 3.18 i get this error, downgrade works

cannot import name 'tostr' from 'Crypto.Util.py3compat' (/path/venv/lib/python3.10/site-packages/Crypto/Util/py3co

**Comment by Legrandin** [comment]
I cannot reproduce this.
Can you share the full stack trace please?
