### ISSUE TITLE
Doc issue - Crypto.Util.Padding missing in docs for 3.4.6

### ISSUE THREAD

**Issue by stevejalim** [Legrandin/pycryptodome#75]
Minor niggle: the `Padding` module is present in the codebase, for sure, but the latest docs no longer reference it:

This exists: https://legrandin.github.io/pycryptodome/Doc/3.4/Crypto.Util.Padding-module.html

This 404s: https://legrandin.github.io/pycryptodome/Doc/3.4.6/Crypto.Util.Padding-module.html

**Comment by Legrandin** [comment]
It is fixed now.
Thanks for flagging this!
