### ISSUE TITLE
Add PGP signing key to releases

### ISSUE THREAD

**Issue by ileanadumitrescu95** [Legrandin/pycryptodome#750]
Would you please add the PGP signing key from `INSTALL.rst` to this release as `v3.18.0.tar.gz.asc`? This will allow for packaging future versions of pycryptodome for debian with proper signing key verification. Thanks!

**Comment by Legrandin** [comment]
Where would you like the PGP key to be added exactly?

**Comment by ileanadumitrescu95** [comment]
Could you edit the release and add it like in [here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)? This would be really helpful. Thank you!

**Comment by Legrandin** [comment]
Added the PGP signatures to the latest releases in GH.
