### ISSUE TITLE
When exporting the ECC secret key, a KeyError appears in the latest version

### ISSUE THREAD

**Issue by Fgaoxing** [Legrandin/pycryptodome#755]
As shown in the figure：
![image](https://github.com/Legrandin/pycryptodome/assets/92655031/085e1f84-f726-4022-8aa3-b59c41860eba)

**Comment by Fgaoxing** [comment]
@paxan

**Comment by Legrandin** [comment]
The `format` parameter has always been mandatory for the `export_key()` of an ECC key. No changes in that respect in the last version.
