### ISSUE TITLE
Python 3.12: ModuleNotFoundError: No module named 'setuptools' / 'distutils'

### ISSUE THREAD

**Issue by hugovk** [Legrandin/pycryptodome#764]
The [Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) is out! :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

Python 3.12.0 final will be released in 3 weeks: https://peps.python.org/pep-0693/

---

However, when adding 3.12 to the CI like https://github.com/hugovk/pycryptodome/commit/44152a46b11ee08690943667e747cfc0628ee139, it [fails](https://github.com/hugovk/pycryptodome/actions/runs/6139052059/job/16656556512#logs) with:

```pytb
> Run python setup.py test
Traceback (most recent call last):
  File "/home/runner/work/pycryptodome/pycryptodome/setup.py", line 26, in <module>
    from setuptools import Extension, Command, setup
ModuleNotFoundError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/pycryptodome/pycryptodome/setup.py", line 30, in <module>
    from distutils.core import Extension, Command, setup
ModuleNotFoundError: No module named 'distutils'
```

---

This will be due to the setuptools changes in Python 3.12:

> `easy_install`, `pkg_resources`, `setuptools` and `distutils` are no longer provided by default in environments created with `venv` or bootstrapped with `ensurepip`, since they are part of the setuptools package. For projects relying on these at runtime, the `setuptools` project should be declared as a dependency and installed separately (typically, using pip).

https://docs.python.org/3.12/whatsnew/3.12.html#removed

See also https://github.com/gitpython-developers/GitPython/issues/1640#issuecomment-1712918426 for more advice.

**Comment by Legrandin** [comment]
With the new release v3.19, pip will install `setuptools`
