### ISSUE TITLE
object of type 'DerOctetString' has no len()

### ISSUE THREAD

**Issue by qy527145** [Legrandin/pycryptodome#771]
这里digest是一个DerOctetString对象，应该修改成len(digestInfo)
https://github.com/Legrandin/pycryptodome/blob/eeffcf5cd35fe7d8688c9cbbc5d66a2293babdae/lib/Crypto/Signature/pkcs1_15.py#L205

**Comment by Legrandin** [comment]
Thanks, fixed with https://github.com/Legrandin/pycryptodome/commit/739558f4d6174c2870431fe081964613567ea1fc.
