### ISSUE TITLE
Tests cannot be run on non-x86 architectures

### ISSUE THREAD

**Issue by bdrung** [Legrandin/pycryptodome#774]
The Debian/Ubuntu packages runs the tests cases, but they fail on non-x86 architectures:

```
make[4]: Entering directory '/<<PKGBUILDDIR>>/src/test'
[ 1%] Building C object CMakeFiles/mont.dir/<<PKGBUILDDIR>>/src/mont.c.o
cc: error: unrecognized command-line option ‘-mssse3’
cc: error: unrecognized command-line option ‘-mpclmul’
cc: error: unrecognized command-line option ‘-maes’
make[4]: *** [CMakeFiles/mont.dir/build.make:76: CMakeFiles/mont.dir/<<PKGBUILDDIR>>/src/mont.c.o] Error 1
```

I tried to build the tests without SSE and AES disabled on ARM:

```shell
cd src/test/
export PYTHON=python3
cmake -DPYTHON=python3 -DSSE=OFF -DAESNI=OFF
make
```

It fails then:

```
[  1%] Building C object CMakeFiles/mont.dir/[...]/src/mont.c.o
cc: error: unrecognized command-line option '-mstackrealign'
make[2]: *** [CMakeFiles/mont.dir/build.make:76: CMakeFiles/mont.dir/[...]/src/mont.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:131: CMakeFiles/mont.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

I disabled `add_compile_options(-mstackrealign)` in `CMakeLists.txt` and then it failed with:

```
[ 97%] Building C object CMakeFiles/test_aesni.dir/test_aesni.c.o
[...]/src/test/test_aesni.c:2:10: fatal error: wmmintrin.h: No such file or directory
    2 | #include <wmmintrin.h>
      |          ^~~~~~~~~~~~~
```

The header `wmmintrin.h` seems to be x86-specific.

Please support building/running the tests on non-x86 architectures.

Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053328
Bug-Ubuntu: https://bugs.launchpad.net/ubuntu/+source/pycryptodome/+bug/2039968

**Comment by Bl4omArchie** [comment]
Hello, indeed, AES New Instructions are specific to x86 architectures: https://en.wikipedia.org/wiki/AES_instruction_set#Supporting_x86_CPUs
It is because instructions are implemented within your processor. If your request hasn't been fulfilled, I can look at the code and fix it for your architectures.

**Comment by Legrandin** [comment]
This is fixed in master

**Comment by bdrung** [comment]
Are you referring to those three commits?

* 1b8672a14f423c96702874b7b3098d1e6043e6a2
* 844a0d09df664ca06eee5e4048ca9afe900cefc2
* 544338e32cf1b8a44f1c8fdee12d28302949ddad

**Comment by Bl4omArchie** [comment]
yes, did it solved your issue ?

**Comment by bdrung** [comment]
I haven't tried yet, but I will next week.

**Comment by Legrandin** [comment]
This is fixed in v3.20.0.

**Comment by bdrung** [comment]
I just uploaded pycryptodome 3.20.0+dfsg-1 to Debian unstable. In the next hours we will see if the tests succeed on non-x86:

* https://buildd.debian.org/status/package.php?p=pycryptodome
* https://ci.debian.net/packages/p/pycryptodome/
* https://launchpad.net/ubuntu/+source/pycryptodome
* https://autopkgtest.ubuntu.com/packages/pycryptodome

**Comment by bdrung** [comment]
pycryptodome 3.20.0+dfsg-1 builds on most architectures now. So the SSE/AES config changes work. I filed two bug reports for the remaining failures:

* https://github.com/Legrandin/pycryptodome/issues/794
* https://github.com/Legrandin/pycryptodome/issues/795
