### ISSUE TITLE
Plans for KangarooTwelve?

### ISSUE THREAD

**Issue by cjpatton** [Legrandin/pycryptodome#780]
As far as I can tell, KangarooTwelve is not compatible with the CFRG draft version: https://datatracker.ietf.org/doc/draft-irtf-cfrg-kangarootwelve/

Am I correct? If so: The draft has reached RG last call, so I'm wondering if there are plans to align PyCryptodome with the (future) RFC.

**Comment by Legrandin** [comment]
I will add the test vectors from the RFC draft, but after a quick check & test, the KangarooTwelve implementation in this library is the already compatible with the draft. No change seems required, but I happy to learn if I missing something.

On the other hand, I intend to add TurboSHAKE128 (and 256).

**Comment by Legrandin** [comment]
Closing. I confirm that the current implementation of KangarooTwelve is compatible with the latest RFC draft.

**Comment by cjpatton** [comment]
Thanks so much! In which release can we expect TurboSHAKE?

**Comment by Legrandin** [comment]
It is available today in version 3.20.0: https://www.pycryptodome.org/src/hash/turboshake
