### ISSUE TITLE
Make PKCS8.wrap() parameters available when exporting keypair to PEM  (feature request)

### ISSUE THREAD

**Issue by pakal** [Legrandin/pycryptodome#791]
Accessing parameters like prot_params["iteration_count"] of PKCS8 would be useful to increase them (eg. 1 million rounds instead of 1000 by default for PBKDF2).

For now, helpers like RSA.export_key() do not allow to override the defaults of PKCS8.wrap() farther down the toolchain.

**Comment by Legrandin** [comment]
This was fixed in v3.20.0.

See for instance the example here:
https://www.pycryptodome.org/src/examples#generate-an-rsa-key
