### ISSUE TITLE
"AES" is unknown import symbolPylancereportGeneralTypeIssues (import) AES: Unknown

### ISSUE THREAD

**Issue by irajeshh** [Legrandin/pycryptodome#793]
"AES" is unknown import symbolPylance.
![image](https://github.com/Legrandin/pycryptodome/assets/85046336/3bd2a677-e10d-43a0-b07d-389c3f7a0c12)

I tried to import AES, but the below error is showing.
![image](https://github.com/Legrandin/pycryptodome/assets/85046336/df07b63b-2ea2-44c7-b997-d2832218546b)

I tried both Crypto & Cryptodome but none of them are having the definition _create_cipher.
Also I tried to test importing DES..etc each file shows the same _create_cipher file error.

I'm completely new for python and not sure abt to install any extra support dependencies are to be included! 

os: macOS 14.0
python: 3.12.0

**Comment by Varbin** [comment]
Does your code run or is this just a report by Pylance?

**Comment by irajeshh** [comment]
@Varbin No it doesnt allow to run the code
![image](https://github.com/Legrandin/pycryptodome/assets/85046336/e2fe9343-6701-4564-bd74-40b872838ced)
![image](https://github.com/Legrandin/pycryptodome/assets/85046336/29fb32ad-8d9d-4dc6-b563-5074d61df01f)

**Comment by Varbin** [comment]
The code should be:

from Cryptodome.Cipher import AES

and not

from Cryptodome.Cipher.AES import AES


Am 1. Januar 2024 12:31:17 MEZ schrieb Rajesh ***@***.***>:

**Comment by irajeshh** [comment]
🥲 Pardon! I didn't expected this to end like this, closing the issue.
