### ISSUE TITLE
ValueError (RSA key format not supported), pycryptodome documentation

### ISSUE THREAD

**Issue by Coal0** [Legrandin/pycryptodome#80]
As I was following the [pycryptodome documentation's examples](http://pycryptodome.readthedocs.io/en/latest/src/examples.html) and trying to execute them through a Python interactive session, I kept running into a `ValueError` when trying to read a private key. My exact setup is as follows:<br>

* `Bob`
    * `private.bin`
    * `public.bin`

* `Alice`
    * `private.bin`
    * `public.bin`

Both `private.bin` and `public.bin` were generated using the first [RSA example](http://pycryptodome.readthedocs.io/en/latest/src/examples.html#generate-an-rsa-key).

> key = RSA.generate(4096)
> key.exportKey(...)

Strangely, trying to import `Bob`'s `private.bin` *does* work. I only get an error when trying to import `Alice`'s `private.bin` (importing `public.bin` works).<br>

Anyone got an idea on how to solve this?<br>
Thanks.

**Comment by Legrandin** [comment]
Please provide a complete snippet of the code that does not work for you.
