### ISSUE TITLE
Windows Deferder Error

### ISSUE THREAD

**Issue by SchwebendeWolke** [Legrandin/pycryptodome#802]
Using Nuitka to pack project with pycryptodome
and Defender raise ERROR:Trojan:Win32/Wacatac.B!ml

**Comment by Bl4omArchie** [comment]
Hello, as you converts python code to assembly with cryptographic elements in it, Windows Defender will automatically interpret it as malware. 
Turn off Windows Defender so it can work.

**Comment by Varbin** [comment]
@SchwebendeWolke You can report false positives to Microsoft at https://www.microsoft.com/en-us/wdsi/filesubmission
