### ISSUE TITLE
how creat public key from n & e format base64 ?

### ISSUE THREAD

**Issue by cbogithub** [Legrandin/pycryptodome#81]
how creat public key from n & e format base64 ?

example.
n="omXjOQmHl77TtpwMXL9WPcd+Xcg1bh8CoLGOyX1Ug/CLtZJx/SvSo0bj5bEiVb8eCa5mXuc6sDg9/RRpCvKHHxZG6f9qh5r3ZNY+yr5hKQqeMafWa4b6UqouLSSwKsNe5FWD327BoyaEsMyCRheQg4wX86G/8zqynuvbT6KzQbQtp4iqQvMWGswovmflsk7zoZUESAFu6L5xlJUEFXMlDLPH13SsPKwvL4MgHa+Cx938B0FReUFtq7qEQHIPhGSTOeTS+v8Acp6VqkmcLB4kCIsk/Icr46VTEPv3WWDHcbSzp+RPR0lTa8WTdOd/E98U70jfAZJAKMDWr4sQkvfk7w=="

e= "AQAB"

thanks

**Comment by Legrandin** [comment]
Assuming Python3:

    import base64
    from Crypto.PublicKey import RSA

    pc = [int.from_bytes(base64.b64decode(x), byteorder='big') for x in n, e]
    key = RSA.construct(pc)

**Comment by cbogithub** [comment]
@Legrandin thanks

but:


```
    pc = [int.from_bytes(base64.b64decode(x), 'big') for x in n, e]
                                                                 ^
SyntaxError: invalid syntax
```

**Comment by Legrandin** [comment]
Indeed I forgot two parentheses:

    import base64
    from Crypto.PublicKey import RSA

    pc = [int.from_bytes(base64.b64decode(x), 'big') for x in (n, e)]
    key = RSA.construct(pc)
