### ISSUE TITLE
Import of rsa-pss public key failed

### ISSUE THREAD

**Issue by entarohydralisk** [Legrandin/pycryptodome#814]
openssl genpkey -algorithm RSA-PSS -out rsapsskey.pem -pkeyopt rsa_keygen_bits:2048
Failed to import rsa-pss public key after self issuing CA certificate using rsa-pss private key
![图片](https://github.com/Legrandin/pycryptodome/assets/165247070/199b1f62-3f24-47e8-ab14-714164e6efff)

**Comment by Legrandin** [comment]
Thanks for reporting.
This is fixed with 760cbd53b8cade7c7ed5a4f698d48cc5d508210f

**Comment by Legrandin** [comment]
Now in v3.21.0
