### ISSUE TITLE
Issue when creating RSA PEM format public key files?

### ISSUE THREAD

**Issue by AJPoulter-Soton** [Legrandin/pycryptodome#82]
Apologies if the error here is mine - but it looks like there's an issue when creating PEM format RSA public keys...

If I follow the documentation I can create the key as follows:

```
from Cryptodome.PublicKey import RSA
key = RSA.generate(2048)
pv_key_string = key.exportKey()
pb_key_string = key.publickey().exportKey()
```

And I can write these two keys to files very simply:

```
with open ("private.pem", "w") as prv_file:
    print("{}".format(pv_key_string.decode()), file=prv_file)


 with open ("public.pem", "w") as pub_file:
    print("{}".format(pb_key_string.decode()), file=pub_file)
```

Using OpenSSL the private key checks out okay...

```
$ openssl rsa -check -inform pem -noout -in private.pem 
RSA key ok
```

But if I try to use the public key I get an error...

 ```
$ openssl rsa -pubin -in ./public.pem                           
unable to load Public Key
62946:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/pem/pem_lib.c:648:Expecting: PUBLIC KEY
```

However if I manually edit they key file and change the header and footer from 
-----BEGIN RSA PUBLIC KEY----- & -----END RSA PUBLIC KEY----- to -----BEGIN PUBLIC KEY----- & -----END PUBLIC KEY----- it works just fine.

Is this a bug - or am I misunderstanding the differences between PKCS#1 & PKCS#8?

**Comment by Legrandin** [comment]
Yes, it is a bug (though I have the feeling that ``openssl`` used to generate RSA public keys with "RSA PUBLIC KEY" in some distant past).

I have put out a new bugfix release (3.4.7) for this.

**Comment by AJPoulter-Soton** [comment]
Thanks.
