### ISSUE TITLE
PyCryptoDome only installable through Pip and not APT?

### ISSUE THREAD

**Issue by EngineerHus** [Legrandin/pycryptodome#829]
Hi All,

I have a question in regards to installing the `pycryptodome` package. When I run the following command, `apt install python3-pycryptodome`, it installs the pip package `pycryptodomex` and not `pycryptodome`- My question is, is there a way to install the pip package `pycryptodome` through `apt`? Or is it setup in a way where the only way to install `pycryptodome` is through `pip`?

Many thanks

**Comment by Varbin** [comment]
Only the maintainers of your Linux distribution decide which packages are available for your `apt`. There is nothing inherent to Pycryptodome preventing your maintainers to packaging it. You may need to ask your maintainer, why they don't do it.

Looking at the project history, the following is my guess: It was impossible in the past, as long as PyCrypto in offered for installation (installing PyCrypto and pycryptodome at the same time is impossible). It is unnecessary now, as all Ubuntu/Debian code has migrated to pycryptodome**x**.

**Comment by Legrandin** [comment]
> is there a way to install the pip package pycryptodome through apt?

No, there is not as far as I know.

In Debian 10, the `Crypto` namespace was still used for the original pycrypto (python3-crypto Debian package), so maintainers created the python3-pycryptodome Debian package with pycryptodomex in it to avoid clashes (`Cryptodome` namespace).

Debian 11 removed the original pycrypto, so now they have the option of packaging pycryptodome into a Debian package (`Crypto` namespace, now unclaimed), but that has not happened.
