### ISSUE TITLE
pycryptodome-test-vectors 1.0.19 sdist contains `.x448_jwk_test.json.swp`

### ISSUE THREAD

**Issue by mtelka** [Legrandin/pycryptodome#837]
The `pycryptodome-test-vectors 1.0.19` sdist contains the `pycryptodome_test_vectors/Protocol/wycheproof/.x448_jwk_test.json.swp` file.  I believe the file should not be there.

**Comment by Legrandin** [comment]
Thanks for the heads-up, this is fixed now.
