### ISSUE TITLE
Feature request: Large file decryption and unpadding

### ISSUE THREAD

**Issue by Vellani** [Legrandin/pycryptodome#838]
I encountered a specific need to decrypt very large files. As such they had to be decrypted in chunks. 
To remove some abstraction and use exact examples...

```
# I have purposefully omitted good code practices (such as file open/close management) for brevity and simplicity
# The chunk size is chosen so that it can be divided by the block size of the chaining mode
def decrypt_chunks(input_file: BinaryIO, output_file: BinaryIO, chunk_size: int, block_size: int, cipher: Any):
    while True:
        chunk = input_file.read(chunk_size)
        if not chunk:
            break
        deciphered_text = cipher.decrypt(chunk)
        output_file.write(deciphered_text)

    # The important part would be the un-padding
    unpad_large_file(output_file, block_size)

def unpad_large_file(output_file: BinaryIO, block_size: int):
    # Go to end of file and move the pointer 1 block size back
    end_of_file_flag = 2
    output_file.seek(-block_size, end_of_file_flag)
    # Read the last chunk of the file
    last_chunk = output_file.read()
    # Unpad the last chunk
    unpadded_data = unpad(last_chunk, block_size)
    # Move the pointer back to where the actual file content ends and padding starts
    output_file.seek(-block_size + len(unpadded_data), end_of_file_flag)
    # Truncate the remaining file bytes
    output_file.truncate()
```

Since my use case involved the AES in CBC mode, to avoid loading the whole file into memory I would have to decrypt it a chunk at a time. After writing each decrypted chunk into a file, it would be necessary to unpad it by moving the pointer to the last important byte of the file and truncating the padding.

I figured this would be sufficient to start a conversation if such functionality is helpful to the community.

**Comment by Legrandin** [comment]
If you want to random access to an encrypt file, AES CTR is a better mode than CBC, because you set the counter to the offset within the file (in terms of blocks). Alternatively, you can use ChaCha20, where the object has an explicit `seek()` method (in terms of bytes). And in all cases, consideration should be given to authentication because none of the above gives you any guarantee that the ciphertext was not modified.

I close this as it is not really an issue.
