### ISSUE TITLE
NameError: name 'cipher' is not defined

### ISSUE THREAD

**Issue by LukeVideo** [Legrandin/pycryptodome#88]
When trying the example code to encrypt with a RSA public key the code fails.

```
cipher_aes = AES.new(session_key, AES.MODE_EAX)
ciphertext, tag = cipher_aes.encrypt_and_digest(data)
[ file_out.write(x) for x in (cipher.nonce, tag, ciphertext) ]
```

should MAYBE be 

```
cipher_aes = AES.new(session_key, AES.MODE_EAX)
ciphertext, tag = cipher_aes.encrypt_and_digest(data)
[ file_out.write(x) for x in (cipher_aes.nonce, tag, ciphertext) ]
```
this seems to work.
Please correct me if I'm wrong.

**Comment by Coal0** [comment]
[The first example](http://pycryptodome.readthedocs.io/en/latest/src/examples.html#encrypt-data-with-aes) declares `cipher`:

```python
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes

key = get_random_bytes(16)
cipher = AES.new(key, AES.MODE_EAX)
ciphertext, tag = cipher.encrypt_and_digest(data)

file_out = open("encrypted.bin", "wb")
[ file_out.write(x) for x in (cipher.nonce, tag, ciphertext) ]
```

**Comment by LukeVideo** [comment]
True. Only that's the AES example. In the RSA it is declared as cipher_aes so i assumed
`
from Crypto.PublicKey import RSA
from Crypto.Random import get_random_bytes
from Crypto.Cipher import AES, PKCS1_OAEP

file_out = open("encrypted_data.bin", "wb")

recipient_key = RSA.import_key(open("receiver.pem").read())
session_key = get_random_bytes(16)

# Encrypt the session key with the public RSA key
cipher_rsa = PKCS1_OAEP.new(recipient_key)
file_out.write(cipher_rsa.encrypt(session_key))

# Encrypt the data with the AES session key
cipher_aes = AES.new(session_key, AES.MODE_EAX)
ciphertext, tag = cipher_aes.encrypt_and_digest(data)
[ file_out.write(x) for x in (cipher.nonce, tag, ciphertext) ]
`

Might need to call the newly declared cipher_AES.

As the two cipher and cipher_AES are the same thing but not declared with the same name. It might be useful for better understanding to correct the typo or stick to one variable name ?

**Comment by Legrandin** [comment]
The RSA example is now fixed.
