### ISSUE TITLE
Release 3.4 on PyPI missing cp27-none-*.whl

### ISSUE THREAD

**Issue by CISC** [Legrandin/pycryptodome#9]
This causes pip install to compile it from the .tar.gz, and then either failing if you don't have a proper development environment set up, or compile with missing features (as f.ex. fast math).

**Comment by Legrandin** [comment]
Which version of `pip` are you using?
Could you try do first (in a *virtualenv*):

    pip install --upgrade pip

and then:

    pip install pycryptodome

**Comment by CISC** [comment]
Hmmm, indeed, I had an old (7.1.2) pip, the new one installs correctly.
