### ISSUE TITLE
Unable to use the installed keccak functions

### ISSUE THREAD

**Issue by dstreppa** [Legrandin/pycryptodome#91]
I need to use keccak functions on a machine (Ubuntu 16.04.3 LTS), but I don't realize to load them. Below the console output for an explanation:

<pre>
shiva@team-SEI-ML:/usr/local/bin$ pip list --format=legacy | grep dome
pycryptodome (3.4.7)
shiva@team-SEI-ML:/usr/local/bin$ ls -l /usr/local/lib/python2.7/dist-packages/Crypto/Hash/*ecc*
-rw-r--r-- 1 root staff  7096 Aug 26 13:20 /usr/local/lib/python2.7/dist-packages/Crypto/Hash/keccak.py
-rw-r--r-- 1 root staff  5788 Sep 27 18:02 /usr/local/lib/python2.7/dist-packages/Crypto/Hash/keccak.pyc
-rwxr-xr-x 1 root staff 28232 Sep 27 18:02 /usr/local/lib/python2.7/dist-packages/Crypto/Hash/_keccak.so
shiva@team-SEI-ML:/usr/local/bin$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from Crypto.Hash import keccak
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name keccak
>>> from Crypto.Hash import MD5
>>> 
</pre>

First strange thing: All the parts of `Crypto.Hash` can be correctly loaded, the unique not working is `keccak`. I reinstalled `pycryptodome` with no results. During the installation there are no warnings/errors. As you can see above the `keccak` files are present in the proper folder ` /usr/local/lib/python2.7/dist-packages/Crypto/Hash`.

Second (very) strange thing: in another machine (same OS, same python, same `pycryptodome` version) everything works...

I really don't understand which should be the possible cause of the problem.

**Comment by Varbin** [comment]
You may have PyCrypto (does not provide keccak) in installed in your user site-packages. Would you mind sending the result of following:

```
import Crypto
print(Crypto.__file__)
```

**Comment by Legrandin** [comment]
Closed due to no response from OP.
