### ISSUE TITLE
Simple (I hope) request for tagging

### ISSUE THREAD

**Issue by aixtools** [Legrandin/pycryptodome#93]
While I see I can get the latest "branded" pycryptodome using 'pip', I would appreciate the github area be 'tagged' so I can fork a master copy. Now, I will need to maintain two copies - at a minimum - where I make my own idea of the master (from what is currently the latest release) - and as releases come out - manually update that. (Copy #1).
To be comparing with the "real" master, I'll need to clone to my server and run a local diff. Far from ideal imho.

So, I hope this is 'simple' - and if it cannot be done - in hindsight - please tag the master when you have your next 'release'.

Regards,
Michael

**Comment by Legrandin** [comment]
Pycryptodome releases were actually already tagged (for instance, the last one has tag **v3.4.8**, you can find **v3.4.6** etc).

There have been two issues though:
* I forgot to tag release the recent 3.4.7 (my bad). I will try to find back and tag the right commit.
* Releases for the Cryptodome namespace were not tagged at all. I will start tagging those adding an "x" to the existing tag (i.e. now there is also a **v3.4.8x** tag).
