### ISSUE TITLE
openSUSE pip install error

### ISSUE THREAD

**Issue by insanerwayner** [Legrandin/pycryptodome#95]
**OS**: openSUSE Tumbleweed

When I try to install I keep getting this error where it can't find **lpython3.6m**.

```
    Compiling support for Intel AES instructions
    building 'Crypto.Hash._MD2' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -DLTC_NO_ASM -DHAVE_CPUID_H -Isrc/ -I/usr/include/python3.6m -c src/MD2.c -o build/temp.linux-x86_64-3.6/src/MD2.o
    gcc -pthread -shared build/temp.linux-x86_64-3.6/src/MD2.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/Crypto/Hash/_MD2.cpython-36m-x86_64-linux-gnu.so
    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lpython3.6m
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dia7_0hu/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h595s8zw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-dia7_0hu/pycryptodome/
```

**Comment by frispete** [comment]
On Sonntag, 8. Oktober 2017 04:33:38 Wayne Reeves wrote:
> **OS**: openSUSE Tumbleweed
> 
> When I try to install I keep getting this error where it can't find
> **lpython3.6m**.
> 
> ```
>     Compiling support for Intel AES instructions
>     building 'Crypto.Hash._MD2' extension
>     creating build/temp.linux-x86_64-3.6
>     creating build/temp.linux-x86_64-3.6/src
>     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG
> -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables
> -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fmessage-length=0
> -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
> -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables
> -fstack-clash-protection -g -fmessage-length=0 -grecord-gcc-switches -O2
> -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables
> -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -DLTC_NO_ASM
> -DHAVE_CPUID_H -Isrc/ -I/usr/include/python3.6m -c src/MD2.c -o
> build/temp.linux-x86_64-3.6/src/MD2.o gcc -pthread -shared
> build/temp.linux-x86_64-3.6/src/MD2.o -L/usr/lib64 -lpython3.6m -o
> build/lib.linux-x86_64-3.6/Crypto/Hash/_MD2.cpython-36m-x86_64-linux-gnu.so
> /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld:
> cannot find -lpython3.6m collect2: error: ld returned 1 exit status
>     error: command 'gcc' failed with exit status 1
> 
>     ----------------------------------------
> Command "/usr/bin/python3 -u -c "import setuptools,
> tokenize;__file__='/tmp/pip-build-dia7_0hu/pycryptodome/setup.py';f=getattr
> (tokenize, 'open', open)(__file__);code=f.read().replace('\r\n',
> '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
> /tmp/pip-h595s8zw-record/install-record.txt
> --single-version-externally-managed --compile" failed with error code 1 in
> /tmp/pip-build-dia7_0hu/pycryptodome/ ```

Did you installed python3-devel?

Why don't you use https://software.opensuse.org/package/python-pycryptodome?

Cheers,
Pete

**Comment by insanerwayner** [comment]
> Did you installed python3-devel?

That did it. Thanks!
