### ISSUE TITLE
cannot import name 'Salsa20'

### ISSUE THREAD

**Issue by hoang408** [Legrandin/pycryptodome#96]
I encountered this error while following the PDF of v.3.4.7, page 22/82:
from Crypto.Cipher import Salsa20 ---> cannot import name 'Salsa20'

I added this link to the environment variables of Windows 7:
C:\Program Files\Python36\Lib\site-packages\Cryptodome

Somehow, that still does not fix it.  Someone please help.

**Comment by hoang408** [comment]
Issue fixed.  Uninstalled, and re-installed using:
pip install pycryptodome

The new folder somehow changed to:
C:\Program Files\Python36\Lib\site-packages\pycryptodome-3.4.7-py3.6-win-amd64.egg\Crypto

And it worked.  Any explanation from expert would be appreciated.  Somehow, this folder still exists:
C:\Program Files\Python36\Lib\site-packages\Cryptodome

**Comment by Varbin** [comment]
Which version of pip do you have? You can find it out with `pip --version`.

**Comment by Legrandin** [comment]
Closing due to no response from OP.
