### ISSUE TITLE
Equations on page 27 (33/82) of v.3.4.7 PDF hard to see

### ISSUE THREAD

**Issue by hoang408** [Legrandin/pycryptodome#97]
The equations on page 27 (33/82) of the v.3.4.7 PDF are hard to see.  I had to find the corresponding page online to know what it was.  Attached is what it looks like.  Please see if there is a way to fix it.

![equations on p27](https://user-images.githubusercontent.com/22355177/31319859-8d155238-ac1f-11e7-843d-6e64ea76a042.png)

**Comment by Legrandin** [comment]
Closing this. There is only time to keep the HTML version readable.
