### ISSUE TITLE
ECC key export() error

### ISSUE THREAD

**Issue by hoang408** [Legrandin/pycryptodome#99]
I am following the PDF of v.3.4.7, on page 39/82. The code is encountered right on this line:
f.write(key.export_key('PEM'))

This is the error message:
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\BitBucket\cryptodome\Cryptodome tutorial 4 - Key type, ECC.py", line 5, in <module>
    f.write(key.export_key('PEM'))
TypeError: export_key() takes 1 positional argument but 2 were given

Any help would be appreciated. Thanks.

**Comment by Varbin** [comment]
Instead of 
`key.export_key('PEM')`
it should be
`key.export_key(format='PEM')`.

The "signature" of the function *export_key* is 
`export_key(**kwargs)`
where the arguments `format`, `passphrase`, `use_pkcs8` and `protection` are allowed as positional arguments.

**Comment by Legrandin** [comment]
See also the relevant documentation:

https://www.pycryptodome.org/en/latest/src/public_key/ecc.html#Crypto.PublicKey.ECC.EccKey.export_key
